Repository glpi-project/glpi, pull requests merged in 2018-05, with the labels that each got.

#3922 Add warning message about internal backup
  front/backup.php
Labels: need_cherrypick

#3947 Typos, refs #3945
  inc/config.php
  inc/notificationeventmailing.class.php
  inc/notificationmailing.class.php
Labels: need_cherrypick

#3952 Fix undefined method
  ajax/getKbRevision.php
Labels: bug, need_cherrypick

#3946 Fix dependency version; closes #3931
  composer.json
  composer.lock
Labels: need_cherrypick

#3948 Typo, refs #3945
  inc/rack.class.php
Labels: need_cherrypick

#3934 Add language selector on login page
  inc/auth.class.php
  inc/session.class.php
  inc/user.class.php
  index.php
  js/common.js
Labels: enhancement, need_cherrypick

#3954 Wrong variable used; fixes #3953
  inc/knowbaseitem.class.php
Labels: need_cherrypick

#3779 fix assign group from a user - see #3778
  inc/group_user.class.php
Labels: need_cherrypick

#3963 Check rigth for submenu
  inc/datacenter.class.php
Labels: need_cherrypick

#3958 Drop countlogin
  inc/event.class.php
  index.php
  tools/checkfunction.php
Labels: need_cherrypick

#3960 Fix escaping quote issue; closes #1264
  inc/toolbox.class.php
  tests/functionnal/Ticket.php
Labels: need_cherrypick

#3966 Improve regexp; refs #3932
  inc/notificationeventmailing.class.php
Labels: need_cherrypick

#3972 remove height attribute from inline displayed image to avoid stretching
  inc/html.class.php
Labels: need_cherrypick

#3973 don't display problems search options in ticket when no right for; fi…
  inc/ticket.class.php
Labels: need_cherrypick

#3971 add Line to global search
  inc/define.php
Labels: need_cherrypick

#3967 Fix undefined index
  inc/location.class.php
Labels: need_cherrypick

#3969 Fix old format search options retrieval
  inc/commondbtm.class.php
Labels: bug, need_cherrypick

#3989 Fix display of README
  README.md
Labels: need_cherrypick

#3987 Fix path calculation for windows (slash and reverse slash mixed)
  front/backup.php
Labels: need_cherrypick

#3974 fix splitted button in timeline forms; fix #3938
  css/styles.css
  inc/commonitilobject.class.php
  inc/ticket.class.php
  js/common.js
Labels: need_cherrypick

#3979 Fix 'nodisplay' specificities in item devices list; closes #3247
  inc/item_devices.class.php
Labels: need_cherrypick

#4000 Upgrade Zend dependencies to get official PHP 7.2 support
  composer.json
  composer.lock
  tools/zend-cache-php7.2.patch
Labels: need_cherrypick

#4002 Fix variable override in rights matrix display
  inc/profile.class.php
Labels: bug

#4009 Use getSearchURL() instead of hardcoded URL
  inc/control.class.php
  inc/slm.class.php
Labels: enhancement, need_cherrypick

#4012 Make defaut cache namespace unique to prvent multi instances issues
  inc/config.class.php
Labels: bug, need_cherrypick

#4030 ipv6 field needs to be NULL instead of empty string
  inc/apiclient.class.php
Labels: bug

#4022 Enlarge default size for task template content field; closes #4021
  inc/tasktemplate.class.php
Labels: need_cherrypick

#4029 Fix warning when display IPv4 range in history; fixes #4018
  inc/apiclient.class.php
Labels: need_cherrypick

#4017 Deprecated method called
  inc/notificationtargetsavedsearch_alert.class.php
Labels: need_cherrypick

#4020 Undefined variables; closes #4014
  inc/savedsearch.class.php
Labels: need_cherrypick

#4028 Fix warning when fail to established DB connection; fixes #4027
  inc/dbmysql.class.php
Labels: need_cherrypick

#4010 Another bunch of hardcoded paths replacement
  inc/auth.class.php
  inc/config.class.php
  inc/notification.class.php
  inc/ticket.class.php
Labels: enhancement, need_cherrypick

#4041 Fix undefined index
  inc/dcroom.class.php
  inc/rack.class.php
Labels: need_cherrypick

#4040 Add Select2 upgrade entry in changelog
  CHANGELOG.md
Labels: need_cherrypick

#4042 Fix extraline in dc room; closes #3988 (thanks to @orthagh)
  css/styles.css
Labels: need_cherrypick

#4048 Fix regexps; refs #3932
  inc/notificationeventmailing.class.php
Labels: bug, need_cherrypick

#4011 Fix menu
  front/control.php
  inc/control.class.php
  inc/html.class.php
  tests/units/Html.php
Labels: need_cherrypick

#4046 programmaticaly set value for ajax dropdown
  inc/commonitiltask.class.php
  inc/dropdown.class.php
  inc/html.class.php
  inc/projecttask.class.php
  inc/projecttasktemplate.class.php
  tests/units/Html.php
Labels: need_cherrypick

#4050 softwarelicences are recursive
  inc/commondbtm.class.php
  inc/softwarelicense.class.php
Labels: bug, need_cherrypick

#4052 Fix remaning ComputerDisks references; closes #4036
  inc/define.php
  inc/plugin.class.php
  inc/transfer.class.php
  scripts/add_creation_date.php
Labels: need_cherrypick

#4057 Prevent script to ba called directly
  install/update.php
  install/update_content.php
Labels: need_cherrypick, security

#4045 Add Item_Device* searchable lists
  CHANGELOG.md
  front/item_device.common.form.php
  front/item_device.php
  inc/commondevice.class.php
  inc/item_devices.class.php
  install/update_92_93.php
Labels: enhancement

#4061 Change htaccess for Apache 2.4
  files/.htaccess
  install/mysql/.htaccess
  locales/.htaccess
  scripts/.htaccess
Labels: need_cherrypick

#4063 fix display planning for change task - see #4062
  inc/planning.class.php
Labels: need_cherrypick

#4066 Better way to restrict content_update.pp direct access
  install/update.php
  install/update_content.php
Labels: need_cherrypick

#4070 Non positionned racks were considered in; fixes #4068
  inc/rack.class.php
Labels: need_cherrypick

#4072 fix network label
  inc/computer.class.php
  inc/networkequipment.class.php
  inc/printer.class.php
Labels: need_cherrypick

#4073 fix(menu) remove old control part for fieldunicity breadcrumb
  front/fieldunicity.php
Labels: RC feedback

#4067 review slightly readme (add some badges, text, and screenshots)
  README.md
  pics/screenshots/components.png
  pics/screenshots/dcim_racks_draganddrop.gif
  pics/screenshots/dcim_racks_toggleimages.gif
  pics/screenshots/timeline.png
Labels: need_cherrypick

#4078 Fix deprecated msg for NotificationTargetProjectTask::getTeamSuppliers()
  inc/notificationtargetprojecttask.class.php
Labels: need_cherrypick

#4081 Remove condition that seems useless
  inc/commonitilactor.class.php
Labels: need_cherrypick

#4083 Add missing conf; make mass actions on components check config
  inc/define.php
  inc/item_devices.class.php
Labels: need_cherrypick

#4084 Fix SQL date query; closes #3994
  inc/consumableitem.class.php
Labels: need_cherrypick

#4093 Deprecate showPrivatePublicSwitch
  CHANGELOG.md
  inc/dropdown.class.php
Labels: need_cherrypick

#4039 Fix postform in simplified interface not have the options of the crea…
  inc/ticket.class.php
Labels: bug

#4091 Remove GLPI version on source code
  inc/html.class.php
  tests/units/Html.php
Labels: need_cherrypick

#4098 Take care of not for priority and impact; fixes #4095
  inc/search.class.php
Labels: need_cherrypick

#4097 Do not check library if not present; fixes #4096
  inc/config.class.php
Labels: need_cherrypick
