Repository glpi-project/glpi, pull requests merged in 2018-09, with the labels that each got.

#4492 rule for ticket's supplier now set use_notification = 1, fix #4467
  inc/commonitilobject.class.php
  inc/ruleticket.class.php
  install/mysql/glpi-empty.sql
  install/update_930_931.php
Labels: need_cherrypick

#4541 Don't use getFromIter for one result
  inc/olalevel_ticket.class.php
Labels: need_cherrypick

#4564 Fix firmware manufacturer update on manufacturer deletion
  inc/relation.constant.php
Labels: bug, need_cherrypick

#4512 display/hide (new config variable) source on login page; fix 4406
  inc/config.class.php
  index.php
  install/mysql/glpi-empty.sql
  install/update_930_931.php
Labels: need_cherrypick

#4565 Fix availability of expert mode of LDAP import
  inc/authldap.class.php
Labels: bug, need_cherrypick

#4566 Variable may not be set; fixes #4546
  inc/search.class.php
Labels: need_cherrypick

#4567 Reset user; fixes #4557
  inc/ticket.class.php
Labels: need_cherrypick

#4576 Fix undefined index; closes #4573
  inc/problem_ticket.class.php
Labels: need_cherrypick

#4577 Get correct field; fix #4572
  inc/commonitilobject.class.php
Labels: need_cherrypick

#4579 Wrong iterator usage; fixes #4578
  inc/transfer.class.php
Labels: need_cherrypick

#4582 Do not use verbatim HTTP_X_FORWARDED_FOR header
  inc/auth.class.php
  inc/toolbox.class.php
Labels: need_cherrypick

#4583 Switch to commondbchild; fix logs
  inc/itilsolution.class.php
Labels: need_cherrypick

#4588 Fix disk clone on computer clone
  inc/item_disk.class.php
Labels: bug, need_cherrypick

#4431 Use Event from Glpi namespace; see #1175
  front/knowbaseitem_comment.form.php
  front/knowbaseitem_item.form.php
  front/savedsearch_alert.form.php
  inc/autoload.function.php
  inc/event.class.php
  inc/knowbaseitemtranslation.class.php
  tests/functionnal/Search.php
Labels: need_cherrypick

#4600 force api to have commonDBTM messages send after redirect
  inc/api.class.php
Labels: need_cherrypick

#4598 Fix project and project task visibility in ticket; fixes #4596
  inc/projecttask_ticket.class.php
Labels: need_cherrypick

#4602 Fix fetching of user's groups from LDAP
  inc/user.class.php
Labels: need_cherrypick

#4603 Fix fetching of user's items
  inc/user.class.php
Labels: need_cherrypick

#4618 Fix project task in modal context
  front/projecttask.form.php
Labels: need_cherrypick

#4614 Clean ajax files
  ajax/comments.php
  ajax/dropdownConnectNetworkPort.php
  ajax/dropdownMassiveActionAddValidator.php
  ajax/dropdownProjectTaskTicket.php
  ajax/dropdownSoftwareLicense.php
  ajax/dropdownValidator.php
  ajax/getFileTag.php
  ajax/searchmetarow.php
  ajax/searchrow.php
  ajax/ticketassigninformation.php
  ajax/updatecurrenttab.php
Labels: need_cherrypick

#4604 Cleanup user class
  inc/user.class.php
Labels: need_cherrypick

#4611 Fix massive unlock action; fixes #4585
  inc/lock.class.php
Labels: need_cherrypick

#4619 Clean front files
  front/commonitilcost.form.php
  front/commonitiltask.form.php
  front/commonitilvalidation.form.php
  front/document.form.php
  front/dropdown.common.form.php
  front/dropdown.common.php
  front/item_device.common.form.php
  front/lock.form.php
  front/report.contract.list.php
  front/report.infocom.conso.php
  front/report.infocom.php
  front/report.year.list.php
  front/reservation.form.php
  front/rule.common.form.php
  front/rule.common.php
  front/rule.test.php
  front/rulesengine.test.php
  front/savedsearch_alert.form.php
  front/stat.global.php
  front/tracking.injector.php
  front/user.form.php
Labels: need_cherrypick

#4625 Prevent truncation of links in followups and solutions
  inc/itilsolution.class.php
  inc/ticketfollowup.class.php
Labels: bug

#4626 api: detect parent in PUT query (avoid warnings and provide logs)
  inc/api.class.php
Labels: api, need_cherrypick

#4630 Remove ability to use password recovery when using ext auth
  inc/auth.class.php
Labels: bug, need_cherrypick

#4631 Replace raw SQL with dbiterator
  inc/displaypreference.class.php
Labels: need_cherrypick

#4633 Fix missing return status in cartridge cron
  inc/cartridgeitem.class.php
Labels: need_cherrypick

#4634 Clean some classes code
  inc/ajax.class.php
  inc/api.class.php
  inc/apirest.class.php
  inc/apixmlrpc.class.php
  inc/auth.class.php
  inc/authldap.class.php
  inc/authmail.class.php
  inc/budget.class.php
  inc/calendar.class.php
  inc/calendar_holiday.class.php
  inc/calendarsegment.class.php
  inc/cartridgeitem.class.php
  inc/cartridgeitem_printermodel.class.php
  inc/central.class.php
  inc/certificate.class.php
  inc/certificate_item.class.php
  inc/change.class.php
  inc/change_item.class.php
  inc/change_problem.class.php
  inc/change_project.class.php
  inc/change_ticket.class.php
  inc/changetask.class.php
  inc/commondbchild.class.php
  inc/commondbconnexity.class.php
  inc/commondbrelation.class.php
  inc/commondbtm.class.php
  inc/computer_item.class.php
  inc/transfer.class.php
Labels: need_cherrypick

#4637 Fix/4636
  inc/rule.class.php
  inc/ruleimportentity.class.php
Labels: need_cherrypick

#4638 show map without displaypref rights
  inc/search.class.php
Labels: need_cherrypick

#4641 Fix TinyMCE languages file existence check; fixes #4640
  inc/html.class.php
Labels: need_cherrypick

#4629 Prevent taking into account if changes made by requester
  inc/ticket.class.php
  tests/functionnal/Ticket.php
Labels: need_cherrypick

#4632 Clean cartridge class
  inc/cartridge.class.php
Labels: need_cherrypick

#4642 Document exact query required to add missing index on id_search_option
  install/update_91_92.php
Labels: need_cherrypick

#4649 Fix can connexity item on invalid items
  inc/commondbconnexity.class.php
Labels: need_cherrypick

#4650 Cannot create PDU template; closes #4647
  front/pdu.form.php
Labels: need_cherrypick

#4651 Fix missing checks when adding items on DC elements; fixes #4648
  inc/define.php
  inc/item_enclosure.class.php
  inc/item_rack.class.php
  inc/update.class.php
  install/update_931_932.php
  scripts/cliupdate.php
Labels: need_cherrypick

#4672 Make CS fails block CI; fix CS
  .circleci/config.yml
  inc/config.class.php
  inc/document.class.php
  inc/itilsolution.class.php
  inc/notificationtemplate.class.php
  inc/planning.class.php
  inc/ruleimportentity.class.php
  install/update_931_932.php
  tests/functionnal/Document.php
Labels: need_cherrypick

#4665 API: add ITILSolution hateoas to itilobject
  inc/api.class.php
Labels: api, need_cherrypick

#4669 fix(css): manage bottom in vsplit layout
  css/styles.css
Labels: need_cherrypick

#4659 Replace composer calls with raw commands to prevent timeouts
  .circleci/config.yml
  composer.json
Labels: need_cherrypick

#4693 Clean some classes code
  inc/ajax.class.php
  inc/authldap.class.php
  inc/commondbtm.class.php
  inc/commondbvisible.class.php
  inc/commondevice.class.php
  inc/commondropdown.class.php
  inc/commonglpi.class.php
  inc/commonimplicittreedropdown.class.php
  inc/commonitilactor.class.php
  inc/commonitilcost.class.php
  inc/commonitilobject.class.php
  inc/commonitiltask.class.php
  inc/commonitilvalidation.class.php
  inc/consumableitem.class.php
  inc/devicenetworkcard.class.php
  inc/html.class.php
  inc/networkequipment.class.php
  inc/printer.class.php
  inc/problem.class.php
  inc/reservationitem.class.php
  inc/ticket.class.php
Labels: need_cherrypick

#4696 Fix personnal display preferences list
  inc/displaypreference.class.php
Labels: bug, need_cherrypick

#4697 Replace RAW SQL by new querying syntax
  ajax/selectUnaffectedOrNewItem_Device.php
  inc/calendar_holiday.class.php
  inc/calendarsegment.class.php
  inc/cartridgeitem.class.php
  inc/certificate.class.php
  inc/change_project.class.php
  inc/commondbtm.class.php
  inc/commondevice.class.php
  inc/commonitilcost.class.php
  inc/commonitilobject.class.php
  inc/commontreedropdown.class.php
  inc/computer.class.php
  inc/computer_item.class.php
  inc/computer_softwareversion.class.php
  inc/computerantivirus.class.php
  inc/consumableitem.class.php
  inc/contract.class.php
  inc/contract_item.class.php
Labels: need_cherrypick

#4699 Error PHP in front/dropdown.php fix #4698
  front/dropdown.php
Labels: need_cherrypick

#4700 Fix typo in Ticket class
  inc/ticket.class.php
Labels: bug

#4702 Add ORDERBY and GROUP capabilities
  inc/dbmysqliterator.class.php
  tests/units/DBmysqlIterator.php
Labels: enhancement

#4706 decode entities in completion field
  ajax/autocompletion.php
Labels: bug

#4708 Fix doc; closes #3334
  apirest.md
Labels: need_cherrypick

#4719 Add viewport plugin in qtip2 build to fix positionning
  lib/jqueryplugins/qtip2/jquery.qtip.css
  lib/jqueryplugins/qtip2/jquery.qtip.js
  lib/jqueryplugins/qtip2/jquery.qtip.min.js
Labels: bug
