Repository glpi-project/glpi, pull requests merged in 2018-10, with the labels that each got.

#4721 remove relative positioning of the body, fix sticky toolbar dropdowns…
  css/styles.css
Labels: need_cherrypick

#4722 fix bottom positioning in split layout
  css/styles.css
Labels: need_cherrypick

#4725 Bug fix for Using solution in Change log ERROR
  inc/commonitilobject.class.php
Labels: need_cherrypick

#4726 Handle item rakc name; closes #4704
  inc/item_rack.class.php
Labels: need_cherrypick

#4727 Display user in reservation item; closes #4671
  inc/reservation.class.php
Labels: need_cherrypick

#4729 Business rules for ticket with SLA criteria fix #4680
  inc/levelagreement.class.php
Labels: need_cherrypick

#4690 Drop type prefix, t's added automatically when needed
  inc/commonitiltask.class.php
  inc/computer.class.php
  inc/computerantivirus.class.php
  inc/contract.class.php
  inc/html.class.php
  inc/item_operatingsystem.class.php
  inc/notepad.class.php
  inc/software.class.php
  inc/softwarelicense.class.php
Labels: need_cherrypick

#4733 Add major option in priority dropdown criteria
  inc/rule.class.php
Labels: enhancement

#4731 add minutes option to time search option
  inc/html.class.php
Labels: enhancement

#4336 feat(rule): add input to execute action
  CHANGELOG.md
  inc/olalevel_ticket.class.php
  inc/rule.class.php
  inc/ruleimportcomputer.class.php
  inc/ruleimportentity.class.php
  inc/rulemailcollector.class.php
  inc/ruleright.class.php
  inc/ruleticket.class.php
  inc/slalevel_ticket.class.php
Labels: enhancement, need_cherrypick

#4744 fix pager url in public faq
  inc/knowbaseitem.class.php
Labels: bug

#4112 Adding new method update or insert in dbmysql class
  inc/dbmysql.class.php
  tests/functionnal/CommonDBTM.php
Labels: enhancement

#4747 Fixed select2 matcher for options without optgroup
  inc/html.class.php
Labels: bug, need_cherrypick

#4748 Fixed user icon in planning page
  css/styles.css
  inc/planning.class.php
Labels: bug

#4749 display softwares in computer only for the current entity
  inc/computer_softwareversion.class.php
Labels: bug, need_cherrypick

#4751 fix breadcrumb sub item and force menu regeneration in debug mode
  inc/datacenter.class.php
  inc/html.class.php
  inc/project.class.php
Labels: bug, enhancement

#4752 in split layout, adding an item to enclosure failed to get enclosure id
  inc/enclosure.class.php
  inc/item_enclosure.class.php
Labels: bug, need_cherrypick

#4753 Fix display of KB creation from Change or Problem solution
  front/change.form.php
  front/problem.form.php
Labels: bug, need_cherrypick

#4754 add 'my devices' label on items tab of tab
  inc/item_ticket.class.php
Labels: bug

#4756 limit visibility of states for enclosures
  inc/enclosure.class.php
  install/mysql/glpi-empty.sql
  install/update_931_932.php
Labels: need_cherrypick

#4741 Fix update of configuration when referenced item is deleted
  inc/documentcategory.class.php
  inc/relation.constant.php
  inc/requesttype.class.php
  inc/softwarecategory.class.php
  inc/ssovariable.class.php
  inc/transfer.class.php
  tests/functionnal/Config.php
Labels: bug, need_cherrypick

#4743 Fix update of consumable when deleting group or user
  inc/group.class.php
  inc/relation.constant.php
  inc/user.class.php
  tests/functionnal/Consumable.php
Labels: bug, need_cherrypick

#4765 Fix truncated data with emojis on mail
  composer.json
  composer.lock
  inc/mailcollector.class.php
Labels: need_cherrypick

#4746 Fix relation constraints and cleaning
  CHANGELOG.md
  inc/calendar.class.php
  inc/cartridgeitem.class.php
  inc/certificate.class.php
  inc/change.class.php
  inc/commondbtm.class.php
  inc/commonitilobject.class.php
  inc/commonitiltask.class.php
  inc/computer.class.php
  inc/consumable.class.php
  inc/consumableitem.class.php
  inc/contact.class.php
  inc/contract.class.php
  inc/crontask.class.php
  inc/dcroom.class.php
  inc/document.class.php
  inc/enclosure.class.php
  inc/entity.class.php
  inc/group.class.php
  inc/ipaddress.class.php
  inc/ipnetwork.class.php
  inc/itilsolution.class.php
  inc/knowbaseitem.class.php
  inc/link.class.php
  inc/monitor.class.php
  inc/networkequipment.class.php
  inc/networkname.class.php
  inc/networkport.class.php
  inc/notification.class.php
  inc/notificationtemplate.class.php
  inc/olalevel.class.php
  inc/pdu.class.php
  inc/peripheral.class.php
  inc/phone.class.php
  inc/plug.class.php
  inc/printer.class.php
  inc/printermodel.class.php
  inc/problem.class.php
  inc/profile.class.php
  inc/project.class.php
  inc/projecttask.class.php
  inc/rack.class.php
  inc/relation.constant.php
  inc/reminder.class.php
  inc/reservationitem.class.php
  inc/rssfeed.class.php
  inc/rule.class.php
  inc/savedsearch.class.php
  inc/slalevel.class.php
  inc/slm.class.php
  inc/software.class.php
  inc/softwarelicense.class.php
  inc/softwareversion.class.php
  inc/supplier.class.php
  inc/ticket.class.php
  inc/user.class.php
  inc/vlan.class.php
  tests/functionnal/DbUtils.php
Labels: bug, need_cherrypick

#4768 Yet another typo
  scripts/migrations/racks_plugin.php
Labels: need_cherrypick

#4791 Drop direct usage of SESSION['glpi_plugins']
  CHANGELOG.md
  inc/autoload.function.php
  inc/config.class.php
  inc/crontask.class.php
  inc/includes.php
  inc/plugin.class.php
  inc/search.class.php
  inc/session.class.php
Labels: enhancement

#4793 Display cache entries in debug panel
  inc/html.class.php
Labels: enhancement

#4767 ldap connection: try to find user by its login+auth_id before trying …
  inc/auth.class.php
  inc/authldap.class.php
  tests/LDAP/AuthLdap.php
Labels: bug, need_cherrypick

#4796 limit visibility os states in pdu (+fix visibility in enclosure
  inc/define.php
  inc/pdu.class.php
  inc/state.class.php
  install/mysql/glpi-empty.sql
  install/update_931_932.php
Labels: need_cherrypick

#4797 fix loading on plugins
  inc/includes.php
Labels: need_cherrypick

#4775 Fix list of unaffected devices in computer components form
  ajax/selectUnaffectedOrNewItem_Device.php
Labels: bug, need_cherrypick

#4810 fix comments of a reservation - see #4809
  inc/search.class.php
Labels: need_cherrypick

#4662 Fix associated elements label on helpdesk ticket form; see #4660
  inc/item_ticket.class.php
  inc/ticket.class.php
Labels: need_cherrypick

#4805 Prevent filtering while choosing mailbox folders
  inc/mailcollector.class.php
Labels: enhancement, need_cherrypick

#4807 Fix missing EOL after 'composer install' requirement warning
  inc/autoload.function.php
Labels: need_cherrypick

#4821 review icons in kb list, faq should display only if published in multientities mode
  inc/knowbaseitem.class.php
Labels: bug

#4803 Fix handling of ticket/followup content handling in collector
  inc/mailcollector.class.php
  inc/ticket.class.php
Labels: bug

#4703 Check ticket/followup rights on mail collector
  inc/commonitilactor.class.php
  inc/mailcollector.class.php
  inc/notimportedemail.class.php
  inc/profile.class.php
  inc/ticket.class.php
  tests/functionnal/Profile.php
  tests/functionnal/Ticket.php
Labels: bug, need_cherrypick

#4826 fix retrieving of profiles under current one
  inc/profile.class.php
  tests/functionnal/Profile.php
Labels: need_cherrypick

#4830 Adding a solution for problem or changes should not close them
  inc/itilsolution.class.php
  tests/functionnal/ITILSolution.php
Labels: bug

#4831 avoid overflow of pictures in timeline when followup collected
  css/styles.css
Labels: need_cherrypick

#4833 Fix Entity_Reminder::getEntities
  inc/entity_reminder.class.php
  inc/group_reminder.class.php
  inc/profile_reminder.class.php
  inc/reminder_user.class.php
Labels: bug, need_cherrypick

#4834 Fix embedded image cid format; fixes #4421
  inc/notificationeventmailing.class.php
Labels: Need feedback, need_cherrypick

#4829 Rework limits for commontreedrodown with entities; fixes #4828
  inc/dropdown.class.php
  tests/functionnal/Dropdown.php
Labels: need_cherrypick
