Repository glpi-project/glpi, pull requests merged in 2018-04, with the labels that each got.

#3783 Do not rely on contract_types from year reports; fixes #3781
  front/report.year.list.php
  inc/define.php
Labels: need_cherrypick

#3782 Check is array; fixes #3780
  inc/user.class.php
Labels: need_cherrypick

#3790 Drop and ignore bad tinymce language file; fixes #3788
  .gitignore
  lib/tiny_mce/langs/ru_RU.js
Labels: need_cherrypick

#3772 Extract en_GB verbatim from pot file
  tools/locale/extract_template.sh
Labels: need_cherrypick

#3793 Not closed html element; fixes #3531
  inc/dropdown.class.php
Labels: need_cherrypick

#3796 Drop demo/example files from 3rd party libs
  lib/jqueryplugins/fullcalendar/demos/agenda-views.html
  lib/jqueryplugins/fullcalendar/demos/background-events.html
  lib/jqueryplugins/fullcalendar/demos/basic-views.html
  lib/jqueryplugins/fullcalendar/demos/default.html
  lib/jqueryplugins/fullcalendar/demos/external-dragging.html
  lib/jqueryplugins/fullcalendar/demos/gcal.html
  lib/jqueryplugins/fullcalendar/demos/json.html
  lib/jqueryplugins/fullcalendar/demos/json/events.json
  lib/jqueryplugins/fullcalendar/demos/list-views.html
  lib/jqueryplugins/fullcalendar/demos/locales.html
  lib/jqueryplugins/fullcalendar/demos/php/get-events.php
  lib/jqueryplugins/fullcalendar/demos/php/get-timezones.php
  lib/jqueryplugins/fullcalendar/demos/php/utils.php
  lib/jqueryplugins/fullcalendar/demos/selectable.html
  lib/jqueryplugins/fullcalendar/demos/theme.html
  lib/jqueryplugins/fullcalendar/demos/timezones.html
  lib/jqueryplugins/fullcalendar/demos/week-numbers.html
  lib/jqueryplugins/jquery-gantt/index.html
  lib/jqueryplugins/jquery-ui-scrollable-tabs/index.html
  lib/jqueryplugins/jquery-ui-timepicker-addon/index.html
Labels: need_cherrypick

#3797 Check for the right field
  install/update_92_921.php
Labels: need_cherrypick

#3799 fix computer template - see #3798
  inc/computer.class.php
Labels: need_cherrypick

#3803 display an error when ldap connection fails
  inc/auth.class.php
Labels: bug, need_cherrypick

#3805 Make sure id is unique; fixes #3198
  ajax/dropdownTrackingDeviceType.php
  inc/item_ticket.class.php
Labels: need_cherrypick

#3807 Restore rely on delete right, not purge; fixes #3165
  inc/massiveaction.class.php
  inc/ticket.class.php
Labels: need_cherrypick

#3808 Fix task checkbox title on change; closes #3160
  ajax/timeline.php
  inc/ticket.class.php
Labels: need_cherrypick

#3812 Replace deprecated each()
  inc/networkequipment.class.php
Labels: need_cherrypick

#3818 Improve isCron check; fixes #3817
  inc/session.class.php
Labels: need_cherrypick

#3828 Add ticket position on change the same as add problem/project
  inc/change_ticket.class.php
Labels: need_cherrypick

#3831 Add email in user perso informations; fixes #2346
  inc/user.class.php
Labels: need_cherrypick

#3806 Drop extra column; refs #3161
  inc/item_ticket.class.php
Labels: need_cherrypick

#3829 Load entity from itemtype on ticket creation; fxes #2173
  inc/ticket.class.php
Labels: need_cherrypick

#3833 Display comment in SLA tooltip; fxes #3321
  inc/levelagreement.class.php
Labels: need_cherrypick

#3835 Take care of copy/pasted images in KB; fixes #3343
  inc/document.class.php
Labels: need_cherrypick

#3837 Fix task creation from simplified interface; closes #2283
  inc/ticket.class.php
Labels: need_cherrypick

#3839 Fix prerequisites and install/update docs
  README.md
Labels: need_cherrypick

#3851 Factorize, log message if file has not been found; fixes #3843
  inc/html.class.php
Labels: need_cherrypick

#3847 Fix 3841
  inc/user.class.php
Labels: need_cherrypick

#3852 Check entities recursively; fixes #3848
  inc/project.class.php
Labels: need_cherrypick

#3856 Fix bad search option
  inc/search.class.php
Labels: need_cherrypick

#3853 Fix 3769
  inc/commonitilobject.class.php
  inc/ticket.class.php
Labels: need_cherrypick

#3854 Fix display; closes #3737
  css/styles.css
  inc/ticket.class.php
Labels: need_cherrypick

#3858 Add comment in search options; fixes #3846
  inc/slm.class.php
Labels: need_cherrypick

#3870 Add history for consumable items; fixes #3034
  inc/consumableitem.class.php
Labels: need_cherrypick

#3871 Fix wrong path of test install script
  tests/README.md
  tests/bootstrap.php
Labels: need_cherrypick

#3872 Fix errors on last step of install wizard
  inc/dbmysqliterator.class.php
  install/install.php
Labels: need_cherrypick

#3876 fix typo
  inc/config.php
Labels: need_cherrypick

#3884 Drop old class references; fixes #3882
  inc/purgelogs.class.php
Labels: need_cherrypick

#3885 Object has been renamed
  tools/generate_bigdump.function.php
Labels: need_cherrypick

#3886 use correct dates in stats > tickets (graph mode)
  front/stat.graph.php
Labels: bug

#3904 Add apt upgrade to avoid issues...
  .circleci/config.yml
Labels: need_cherrypick

#3881 Add check for db engine version
  .circleci/config.yml
  inc/config.class.php
  inc/dbmysql.class.php
  inc/toolbox.class.php
  inc/update.class.php
  tests/functionnal/Config.php
Labels: need_cherrypick

#3899 rewrite isInfocomOption, follows #3898
  inc/search.class.php
  tests/units/Search.php
Labels: need_cherrypick

#3913 Check comment ACL on the right object; fixes #3901
  inc/knowbaseitem_comment.class.php
Labels: need_cherrypick

#3914 fix #1776 planning in central
  inc/commonitiltask.class.php
Labels: need_cherrypick

#3912 Fix database checks display on upgrade screen
  inc/config.class.php
Labels: need_cherrypick

#3915 Remove user picture along with user; fixes #3905
  inc/user.class.php
Labels: need_cherrypick

#3921 Multiple Problem with the cronSavedSearchesAlerts fix #3920
  inc/savedsearch_alert.class.php
Labels: need_cherrypick

#3925 Add Kannada lang
  inc/define.php
  locales/kn.mo
  locales/kn.po
Labels: need_cherrypick

#3916 use DB::delete() instead of raw queries
  inc/user.class.php
  tests/functionnal/KnowbaseItem_Revision.php
Labels: need_cherrypick

#3917 Allow to pass user and password calling script; closes #3911
  tools/generate_bigdump.php
Labels: need_cherrypick

#3927 Fix display on command line
  inc/config.class.php
Labels: need_cherrypick

#3924 Fix notification templates issues from 9.2 migration
  install/update_922_923.php
Labels: need_cherrypick
