Repository glpi-project/glpi, pull requests merged in 2018-08, with the labels that each got.

#4392 Add ability to search on solutions statuses
  inc/commonitilobject.class.php
  inc/itilsolution.class.php
Labels: need_cherrypick

#4401 Fix images in changes, problems and tickets notifications; fixes #4345
  inc/html.class.php
  inc/itilsolution.class.php
  inc/notificationeventmailing.class.php
  inc/notificationtargetchange.class.php
  inc/notificationtargetcommonitilobject.class.php
  inc/notificationtargetproblem.class.php
  inc/notificationtargetticket.class.php
  inc/notificationtemplate.class.php
Labels: need_cherrypick

#4425 Mark unused constants as deprecated
  CHANGELOG.md
  inc/commondbtm.class.php
Labels: need_cherrypick

#4416 Fix collector reject solution
  inc/commonitilobject.class.php
  inc/ticket.class.php
Labels: need_cherrypick

#4450 Fix visibility of validation request notification status
  inc/commonitilvalidation.class.php
Labels: need_cherrypick

#4451 Wrong value in empty SQL
  install/mysql/glpi-empty.sql
Labels: need_cherrypick

#4452 Factorize CommonITILObkect::countActiveObjects*
  inc/commonitilobject.class.php
Labels: need_cherrypick

#4457 don't show tasks from project template in 'my tasks' view
  inc/search.class.php
Labels: need_cherrypick

#4409 Rewrite PHPDoc for CommonDBTM properties
  inc/commondbtm.class.php
  inc/commonglpi.class.php
Labels: need_cherrypick

#4448 Add array init and fix 'Variable '$foo' is undefined IDE warnings
  inc/commondbconnexity.class.php
  inc/commondbrelation.class.php
  inc/commondbtm.class.php
  inc/commondropdown.class.php
  inc/commonglpi.class.php
  inc/commonitilobject.class.php
  inc/commonitiltask.class.php
  inc/commonitilvalidation.class.php
  inc/commontreedropdown.class.php
  inc/computer_item.class.php
  inc/config.class.php
  inc/consumableitem.class.php
  inc/contract.class.php
Labels: need_cherrypick

#4449 Deprecated Config::getSQLMode() method (and fix it)
  CHANGELOG.md
  inc/config.class.php
Labels: need_cherrypick

#4460 Deprecate isAllPluginsCSRFCompliant
  CHANGELOG.md
  inc/includes.php
  inc/plugin.class.php
Labels: need_cherrypick

#4461 fix display of assets in planning items
  inc/commonitiltask.class.php
Labels: need_cherrypick

#4462 Fix Computer_Item php error
  inc/computer_item.class.php
Labels: need_cherrypick

#4463 Fix DeviceFirmware Import #4438
  inc/devicefirmware.class.php
Labels: need_cherrypick

#4471 fix raw SQL query convertion to query builder
  inc/transfer.class.php
Labels: bug

#4466 Fix/planning issues
  css/styles.css
  inc/planning.class.php
  js/log_filters.js
Labels: need_cherrypick

#4469 Fix missing entry in changelog and rename 9.3 to 9.3.0
  CHANGELOG.md
Labels: need_cherrypick

#4477 Fix wrong queries; closes #4475
  inc/computer_softwareversion.class.php
Labels: need_cherrypick

#4473 Fix transfer again
  inc/transfer.class.php
Labels: bug, need_cherrypick

#4479 Add support for extra condition in foreign key
  inc/dbmysqliterator.class.php
  tests/units/DBmysqlIterator.php
Labels: need_cherrypick

#4489 replace groups_id in glpi_consumables when group is purged
  inc/define.php
  inc/group.class.php
  inc/relation.constant.php
Labels: need_cherrypick

#4488 Fix revision author and creation date in KB; fixes #4485
  front/knowbaseitemtranslation.form.php
  inc/knowbaseitem_revision.class.php
Labels: need_cherrypick

#4480 self-service users should not be able to display revisions/comments tabs in faq
  inc/knowbaseitem.class.php
  inc/knowbaseitem_comment.class.php
  inc/knowbaseitem_revision.class.php
  install/mysql/glpi-empty.sql
  tests/functionnal/KnowbaseItem_Comment.php
  tests/functionnal/KnowbaseItem_Revision.php
Labels: bug, need_cherrypick

#4398 Fix color cell covering for project state; fixes #4380
  inc/project.class.php
  inc/search.class.php
Labels: need_cherrypick

#4501 Allow anonymous assignation of ITIl objects; closes #4447
  inc/commonitilactor.class.php
  inc/commonitilobject.class.php
Labels: need_cherrypick

#4502 Fix error on infocom items list of supplier page
  inc/supplier.class.php
Labels: iterator, need_cherrypick

#4499 Fix software category filter in Software tab of computers
  inc/computer_softwareversion.class.php
Labels: need_cherrypick

#4503 KB: visibility concatenate and append the same string
  inc/commondbvisible.class.php
Labels: bug, need_cherrypick

#4483 Fix document rights check; fixes #4236
  inc/document.class.php
  inc/knowbaseitem.class.php
  tests/functionnal/Document.php
Labels: need_cherrypick

#4507 clean unreachable code
  inc/search.class.php
Labels: need_cherrypick

#4505 Fix deprecated call to countElementsInTable using string as condition
  inc/group.class.php
  inc/infocom.class.php
Labels: iterator, need_cherrypick

#4513 Fix updated version on forced 'cli update'
  scripts/cliupdate.php
Labels: need_cherrypick

#4491 Upgrade Font Awesome to version 5.2.0
  css/styles.css
  inc/commonglpi.class.php
  inc/commonitilobject.class.php
  inc/dropdown.class.php
  inc/html.class.php
  inc/item_devices.class.php
  inc/item_rack.class.php
  inc/itilsolution.class.php
  inc/knowbaseitemcategory.class.php
  inc/levelagreement.class.php
  inc/pdu_rack.class.php
  inc/planning.class.php
  inc/search.class.php
  inc/stat.class.php
  inc/ticket.class.php
  inc/user.class.php
  index.php
  js/fuzzysearch.js
  lib/font-awesome-4.7.0/css/font-awesome.css
  lib/font-awesome-4.7.0/css/font-awesome.min.css
  lib/font-awesome-4.7.0/fonts/FontAwesome.otf
  lib/font-awesome-4.7.0/fonts/fontawesome-webfont.eot
  lib/font-awesome-4.7.0/fonts/fontawesome-webfont.svg
  lib/font-awesome-4.7.0/fonts/fontawesome-webfont.ttf
  lib/font-awesome-4.7.0/fonts/fontawesome-webfont.woff
  lib/font-awesome-4.7.0/fonts/fontawesome-webfont.woff2
  lib/font-awesome-5.2.0/LICENSE.txt
  lib/font-awesome-5.2.0/css/all.css
  lib/font-awesome-5.2.0/css/all.min.css
  lib/font-awesome-5.2.0/webfonts/fa-brands-400.eot
  lib/font-awesome-5.2.0/webfonts/fa-brands-400.svg
  lib/font-awesome-5.2.0/webfonts/fa-brands-400.ttf
  lib/font-awesome-5.2.0/webfonts/fa-brands-400.woff
  lib/font-awesome-5.2.0/webfonts/fa-brands-400.woff2
  lib/font-awesome-5.2.0/webfonts/fa-regular-400.eot
  lib/font-awesome-5.2.0/webfonts/fa-regular-400.svg
  lib/font-awesome-5.2.0/webfonts/fa-regular-400.ttf
  lib/font-awesome-5.2.0/webfonts/fa-regular-400.woff
  lib/font-awesome-5.2.0/webfonts/fa-regular-400.woff2
  lib/font-awesome-5.2.0/webfonts/fa-solid-900.eot
  lib/font-awesome-5.2.0/webfonts/fa-solid-900.svg
  lib/font-awesome-5.2.0/webfonts/fa-solid-900.ttf
  lib/font-awesome-5.2.0/webfonts/fa-solid-900.woff
  lib/font-awesome-5.2.0/webfonts/fa-solid-900.woff2
Labels: ux

#4518 replace also &#39 char
  inc/toolbox.class.php
  tests/functionnal/Ticket.php
Labels: need_cherrypick

#4527 prevent multiple solution to be posted on the same item
  inc/itilsolution.class.php
  tests/functionnal/ITILSolution.php
Labels: need_cherrypick

#4525 Do not show map option for itemtypes with no items and cannot be located
  inc/search.class.php
Labels: need_cherrypick

#4493 Update rules for OCS adding actions "Child entities" & "groups_id_tech"
  inc/ruleimportentity.class.php
Labels: Need feedback

#4526 Fix drag and drop upload
  js/fileupload.js
Labels: need_cherrypick

#4538 Fix undefined index for PDU consumption
  inc/item_rack.class.php
Labels: need_cherrypick

#4536 Fix datacenter items deletion
  css/styles.css
  inc/commondbtm.class.php
  inc/dcbreadcrumb.class.php
  inc/pdu.class.php
  inc/plug.class.php
  inc/rack.class.php
  inc/relation.constant.php
Labels: need_cherrypick

#4533 Fix cases where rack position is not set
  inc/rack.class.php
Labels: need_cherrypick
