Repository glpi-project/glpi, pull requests merged in 2018-11, with the labels that each got.

#4845 PSR16 cache key must be 64 chars long maximum; fixes #4838
  inc/dbutils.class.php
  tests/functionnal/DbUtils.php
Labels: need_cherrypick

#4871 fix reservation tab of an item - fixed #4870
  inc/reservation.class.php
Labels: need_cherrypick

#4868 ticket rules: itilcategory criterion now permits to target completename
  inc/ruleticket.class.php
  install/mysql/glpi-empty.sql
  install/update_93_94.php
Labels: enhancement

#4812 Subqueries in JOIN
  inc/dbmysqliterator.class.php
  tests/units/DBmysqlIterator.php
Labels: feature suggestion

#4886 Fix presence of signature in ajax notifications
  inc/notificationevent.class.php
Labels: bug

#4885 Fix stripping of initial mail in collector; fixes #4864
  inc/mailcollector.class.php
Labels: need_cherrypick

#4896 Change max DC equipment weight
  inc/commondcmodeldropdown.class.php
Labels: enhancement, need_cherrypick

#4897 Do not add less than 1 plug in PDU; closes #4848
  inc/pdu_plug.class.php
Labels: need_cherrypick

#4898 Auto detect recursivity; closes #4795
  inc/commondbrelation.class.php
Labels: need_cherrypick

#4899 Fix typo; closes #4755
  inc/ruleaction.class.php
Labels: need_cherrypick

#4953 Add hooks on notification recipient add
  CHANGELOG.md
  inc/notificationtarget.class.php
Labels: enhancement, need_doc_improvement

#4968 missing icon for edit a kb's comment
  inc/knowbaseitem_comment.class.php
  tests/functionnal/KnowbaseItem_Comment.php
Labels: bug, need_cherrypick

#4956 Fix select2 matcher; closes #4952
  inc/html.class.php
Labels: need_cherrypick

#4906 Fix import of rejected mail; fixes #4892
  inc/mailcollector.class.php
Labels: Need feedback, need_cherrypick

#4904 Disable checks on collector if anonymous ticket/fup enabled; fixes #4889
  inc/mailcollector.class.php
Labels: Need feedback, need_cherrypick

#4884 Fix SLA/OLA values in ticket rules export; fixes #4865
  inc/rulecollection.class.php
Labels: Need feedback

#4969 Fix ticket last editor in mailcollector context; fixes #4924
  inc/ticket.class.php
  tests/functionnal/Ticket.php
Labels: need_cherrypick

#4976 Add 9.3.3 changelog
  CHANGELOG.md
Labels: need_cherrypick

#4978 add new rule criteria to check creation date is a working hour in a c…
  inc/ruleticket.class.php
  inc/ticket.class.php
Labels: enhancement

#4992 Fix string; closes #4990
  inc/knowbaseitem.class.php
  inc/knowbaseitemtranslation.class.php
Labels: need_cherrypick

#4994 fix link in item ticket - #4900 and PR #4907
  inc/item_ticket.class.php
Labels: need_cherrypick
