Repository glpi-project/glpi, pull requests merged in 2018-06, with the labels that each got.

#4100 Display link for associated items in certificates; fixes #4044
  inc/certificate.class.php
  inc/search.class.php
Labels: need_cherrypick

#4105 Fix 4104
  inc/event.class.php
Labels: need_cherrypick

#4103 Fixes #4099
  inc/ticket.class.php
  tests/functionnal/Ticket.php
Labels: need_cherrypick

#4117 Add new unit tests
  tests/units/DB.php
  tests/units/Migration.php
Labels: need_cherrypick

#4127 Fix focused style on form elements; fixes #4118
  css/styles.css
Labels: need_cherrypick

#4119 Both 'Web Link' and 'Web link' does exists, use same everywhere
  inc/document.class.php
  inc/notificationtargetcommonitilobject.class.php
  inc/notificationtargetproject.class.php
  inc/notificationtargetprojecttask.class.php
Labels: need_cherrypick

#4121 Fix js
  inc/ajax.class.php
Labels: need_cherrypick

#4132 Work on popups in sarch list
  css/styles.css
  inc/html.class.php
  inc/search.class.php
Labels: enhancement

#4004 Fix redirections when object url contains params
  inc/toolbox.class.php
Labels: need_cherrypick

#3087 Added an option (inactive_deleted) to get also inactive or deleted users from getSqlSearchResult()
  ajax/getDropdownUsers.php
  ajax/searchoptionvalue.php
  inc/user.class.php
Labels: need_cherrypick

#4129 Fix solutions migration
  install/update_92_93.php
Labels: need_cherrypick

#4139 Ensure quotes are escaped in link title; drop unused code
  inc/commondbtm.class.php
  inc/group_user.class.php
Labels: bug, need_cherrypick, security

#4137 Use autolink on non converted html; closes #3907
  inc/ticket.class.php
Labels: need_cherrypick

#4142 Ensure data are escaped; fixes #4141
  front/ticket.form.php
Labels: need_cherrypick

#4152 Rework solutions migration; closes #4146
  install/update_92_93.php
Labels: need_cherrypick

#4164 PHP Notice: Undefined index: itemtype to the creation of a ticket from a user fix #4163
  inc/ticket.class.php
Labels: need_cherrypick

#4194 Logger was not initialized; closes #4169
  scripts/checkdb.php
Labels: need_cherrypick

#4193 Fix mode SQL query
  inc/dbmysqliterator.class.php
  tests/units/DBmysqlIterator.php
Labels: need_cherrypick

#4191 Fix solutions; closes #4173
  inc/itilsolution.class.php
  inc/ticket_ticket.class.php
  tests/functionnal/ITILSolution.php
Labels: need_cherrypick

#4198 Update apirest.md : Capitalize spelling of API
  apirest.md
Labels: need_cherrypick

#4196 Fix potential undefined index
  ajax/savedsearch.php
  inc/search.class.php
Labels: need_cherrypick

#4199 Make Html::getPrefixedUrl public and final; closes #4149
  inc/html.class.php
Labels: need_cherrypick

#4200 Check if link oprator is in list
  inc/search.class.php
Labels: need_cherrypick

#4201 Fix search URL; closes #4166
  inc/ticket.class.php
Labels: need_cherrypick

#4204 Check db version on cli scripts; closes #4167
  inc/dbmysql.class.php
  scripts/cliinstall.php
  scripts/cliupdate.php
Labels: need_cherrypick

#4211 Check for DB version after connection has been checked (and session s…
  scripts/cliupdate.php
Labels: need_cherrypick

#4216 Break update on unknown version
  inc/update.class.php
Labels: need_cherrypick

#4218 permits to view itil solutions with api
  inc/itilsolution.class.php
Labels: need_cherrypick

#4228 Fix large image paste; fixes #3949
  inc/toolbox.class.php
Labels: need_cherrypick

#4240 we can update takeintoacccountstat without update on some cases
  inc/ticket.class.php
Labels: need_cherrypick

#4241 Explicit integer querying is_deleted
  inc/commonitilobject.class.php
  inc/commonitiltask.class.php
  inc/search.class.php
  inc/stat.class.php
  inc/ticket.class.php
Labels: need_cherrypick

#4245 Fix map on tickets
  ajax/map.php
  inc/search.class.php
Labels: need_cherrypick

#4246 Do not display map control on items that cannot be located
  inc/commondbtm.class.php
  inc/search.class.php
Labels: need_cherrypick

#4250 Ensure HTML entities are decoded; fixes #4248
  inc/rulecollection.class.php
Labels: need_cherrypick

#4253 Ensure return higher error code
  inc/config.class.php
Labels: need_cherrypick

#4254 Run CS checks on PHP 7.2 only
  .circleci/config.yml
Labels: need_cherrypick

#4257 datacenter => data center
  inc/datacenter.class.php
  inc/dcbreadcrumb.class.php
  inc/dcroom.class.php
Labels: need_cherrypick

#4203 Add missing getTypeName() methods; closes #4202
  inc/olalevel_ticket.class.php
  inc/purgelogs.class.php
  inc/slalevel_ticket.class.php
  inc/telemetry.class.php
Labels: need_cherrypick, wip

#4217 Add error messages on software installations
  front/computer_softwareversion.form.php
Labels: need_cherrypick, wip

#4219 Select distinct itemtype.id; fixes #4154
  inc/search.class.php
Labels: need_cherrypick, wip
