Repository glpi-project/glpi, pull requests merged in 2018-12, with the labels that each got.

#5010 Move LDAP sync command to console
  CHANGELOG.md
  inc/authldap.class.php
  inc/console/ldap/synchronizeuserscommand.class.php
  inc/user.class.php
  scripts/ldap_mass_sync.php
Labels: need_doc_improvement

#5018 Reload SCSS compilation if one of the source files has changed
  inc/html.class.php
Labels: bug, enhancement

#4996 autoclose cron now based on calendar open days
  inc/calendar.class.php
  inc/ticket.class.php
  tests/functionnal/Calendar.php
  tests/functionnal/Ticket.php
Labels: enhancement

#4967 compute take into account stat on date creation
  inc/levelagreement.class.php
  inc/ticket.class.php
Labels: enhancement

#4919 Prevent duplicated checks on plugins while displaying plugin page
  front/plugin.php
  inc/plugin.class.php
  tests/functionnal/Plugin.php
Labels: enhancement

#4965 Display list of related notifications in notification templates
  inc/notification_notificationtemplate.class.php
  inc/notificationtemplate.class.php
  inc/relation.constant.php
Labels: enhancement

#5044 fix count typo
  inc/entity.class.php
Labels: beta

#5045 Fix progress bar display on sync error
  inc/console/abstractcommand.class.php
  inc/console/ldap/synchronizeuserscommand.class.php
Labels: beta, need_cherrypick

#5064 Fix dropdown conditions
  inc/cartridgeitem.class.php
  inc/certificate.class.php
  inc/computer.class.php
  inc/consumableitem.class.php
  inc/enclosure.class.php
  inc/line.class.php
  inc/monitor.class.php
  inc/networkequipment.class.php
  inc/pdu.class.php
  inc/peripheral.class.php
  inc/phone.class.php
  inc/printer.class.php
  inc/project.class.php
  inc/rack.class.php
  inc/software.class.php
  inc/softwarelicense.class.php
  inc/softwareversion.class.php
Labels: beta

#5065 Fix SQL in item_ticket fixes #5055 fixes #5056 fixes #5057
  inc/item_ticket.class.php
Labels: beta

#5067 Fix undefined index in document_item for users fixes #5054
  inc/document_item.class.php
Labels: beta

#5076 Fix db:install params in tests readme file
  tests/README.md
Labels: beta

#5074 Fix cache usage and clear cache in update process; fixes #5050
  inc/config.class.php
  install/update.php
Labels: beta, need_cherrypick

#5061 Fix PDF title fixes #5060
  inc/search.class.php
Labels: beta

#5089 Remove deprecated log on KB item
  inc/knowbaseitem.class.php
Labels: beta

#5090 Fix rejected followup import
  inc/mailcollector.class.php
Labels: beta

#5077 Fix/5058
  inc/search.class.php
  tests/functionnal/Search.php
Labels: need_cherrypick

#5110 Add elapsed time and memory usage in console output
  inc/console/application.class.php
Labels: beta

#5105 Prevent plugins loading for install and update commands
  inc/console/application.class.php
  inc/console/command/forcenopluginsoptioncommandinterface.class.php
  inc/console/commandloader.class.php
  inc/console/database/installcommand.class.php
  inc/console/database/updatecommand.class.php
  tests/units/Glpi/Console/CommandLoader.php
Labels: beta

#5096 Add confirmation on LDAP sync command
  inc/console/ldap/synchronizeuserscommand.class.php
Labels: beta, enhancement

#5097 Drop support of PHP 5.6
  .circleci/config.yml
  .travis.yml
  README.md
  composer.json
  composer.lock
  inc/define.php
  index.php
Labels: need_doc_improvement

#5021 Move racks plugin migration to command console
  CHANGELOG.md
  inc/console/migration/racksplugintocorecommand.class.php
  inc/item_rack.class.php
  scripts/migrations/racks_plugin.php
Labels: need_cherrypick

#5111 Avoid double compiling SCSS files
  inc/html.class.php
Labels: beta

#5118 Prevent proxy timeout on installation; fixes #5114
  inc/dbmysql.class.php
Labels: Need feedback

#5135 fix adding itil object from items
  inc/change.class.php
  inc/problem.class.php
  tests/functionnal/Change.php
  tests/functionnal/Problem.php
Labels: need_cherrypick
