Repository glpi-project/glpi, pull requests merged in 2018-03, with the labels that each got.

#3645 KB restrict user - #3644
  inc/knowbaseitem.class.php
Labels: need_cherrypick

#3643 fix search engine - #3642
  inc/search.class.php
Labels: need_cherrypick

#3647 Escape get keys to prevent possible xss
  inc/html.class.php
Labels: need_cherrypick

#3635 default values for Search now merge Search-Itemtype-User defaults; se…
  inc/search.class.php
Labels: need_cherrypick

#3658 Add some tests
  inc/toolbox.class.php
  tests/units/Toolbox.php
Labels: need_cherrypick

#3648 Plural for "private" and "public"; see #3641 comments
  inc/savedsearch.class.php
Labels: need_cherrypick

#3660 Add atoum patch for code coverage wrong CSS path
  composer.json
  tools/atoum-coverage.patch
Labels: need_cherrypick

#3668 Display original user in timeline; fixes #3514
  inc/ticket.class.php
Labels: need_cherrypick

#3669 start and limit should be OK; fixes #3487
  ajax/getDropdownValue.php
Labels: need_cherrypick

#3676 Fix images links from system cron; fixes #3653
  inc/html.class.php
Labels: need_cherrypick

#3678 There is no users_id fields; fixes #3677
  inc/savedsearch_alert.class.php
Labels: need_cherrypick

#3690 add sso tests
  tests/LDAP/AuthLdap.php
Labels: need_cherrypick

#3693 Add aliases support on queries; closes #2327
  inc/dbmysql.class.php
  inc/dbmysqliterator.class.php
  tests/units/DB.php
  tests/units/DBmysqlIterator.php
Labels: need_doc_improvement

#3585 [wip] Manage accounts on sources, so can have same 'login' for different so…
  css/styles.css
  front/login.php
  inc/api.class.php
  inc/auth.class.php
  inc/authldap.class.php
  inc/central.class.php
  inc/dropdown.class.php
  inc/user.class.php
  index.php
  install/mysql/glpi-empty.sql
  install/update_92_93.php
  pics/login_password.png
  pics/login_user.png
  scripts/ldap_mass_sync.php
  tests/LDAP/AuthLdap.php
  tests/functionnal/AuthLdap.php
  tests/functionnal/AuthLdapReplicate.php
  tests/functionnal/Computer_SoftwareLicense.php
  tests/functionnal/Computer_SoftwareVersion.php
  tests/functionnal/Config.php
  tests/functionnal/DbUtils.php
  tests/functionnal/KnowbaseItem_Comment.php
  tests/functionnal/KnowbaseItem_Item.php
  tests/functionnal/Monitor.php
  tests/functionnal/Networkport.php
  tests/functionnal/NotificationAjax.php
  tests/functionnal/NotificationMailing.php
  tests/functionnal/Printer.php
  tests/functionnal/RuleCriteria.php
  tests/functionnal/RuleDictionnarySoftwareCollection.php
  tests/functionnal/RuleSoftwareCategoryCollection.php
  tests/functionnal/Search.php
  tests/functionnal/Software.php
  tests/functionnal/Ticket.php
  tools/generate_bigdump.php
Labels: enhancement

#3691 Added cache suffix for TinyMCE
  inc/html.class.php
Labels: need_cherrypick

#3704 Fixed tiny_mce load (Close #3663)
  inc/define.php
Labels: need_cherrypick

#3703 Update user
  inc/user.class.php
Labels: need_cherrypick

#3710 Fixed author from mail on cron CLI (Close #2498)
  inc/mailcollector.class.php
Labels: need_cherrypick

#3682 Edit - changed grammar in a comment
  tools/cleanhistory.php
Labels: need_cherrypick

#3721 Do not consider aborted loads as errors
  inc/ajax.class.php
Labels: bug, need_cherrypick

#3687 Fixed line break display for content of ticket
  inc/ticket.class.php
Labels: bug, need_cherrypick

#3734 Fixed date displayed in timeline (Close #3722)
  inc/ticket.class.php
Labels: need_cherrypick

#3754 Item type must be specified; handle posted itemtype
  front/device.form.php
  inc/commondropdown.class.php
Labels: need_cherrypick

#3756 No array tag expected in fordebug; fixes #3701
  inc/config.class.php
Labels: need_cherrypick

#3753 Use iterator; escape value to fix #3750
  inc/search.class.php
Labels: need_cherrypick

#3740 Load analytics script if present
  inc/html.class.php
Labels: enhancement, need_cherrypick

#3755 Do not chek unicity if unicity fields did not change; fixes #3699
  inc/state.class.php
Labels: need_cherrypick

#3757 Category not replaced in closed tickets #3368
  inc/ticket.class.php
  tests/functionnal/Ticket.php
Labels: need_cherrypick

#3742 Add document for helpdesk
  inc/ticket.class.php
Labels: need_cherrypick

#3764 Reword; fixes #3730
  inc/html.class.php
  inc/search.class.php
Labels: need_cherrypick

#3713 fix warnings in generate_bigdump
  composer.json
  composer.lock
  inc/ipaddress.class.php
  inc/state.class.php
  tools/generate_bigdump.function.php
  tools/generate_bigdump.php
Labels: need_cherrypick

#3775 Keep files infos; fixes #3741
  inc/ticket.class.php
Labels: need_cherrypick
