Repository glpi-project/glpi, pull requests merged in 2019-12, with the labels that each got.

#6599 Date exceptions for recurrent events
  inc/caldav/traits/vobjectconvertertrait.class.php
  inc/html.class.php
  inc/objectlock.class.php
  inc/planning.class.php
  inc/planningevent.class.php
  js/common.js
  lib/bundles/base.js
  package-lock.json
  package.json
  tests/abstracts/AbstractPlanningEvent.php
  tests/functionnal/Planning.php
  webpack.config.js
Labels: enhancement

#6615 Add new option to mail collector
  inc/mailcollector.class.php
  install/mysql/glpi-empty.sql
  install/update_94_95.php
  tests/emails-tests/08-tech-and-cc.eml
  tests/imap/MailCollector.php
Labels: enhancement

#6668 Time (only) field
  inc/html.class.php
Labels: feature suggestion

#6670 Add geolocation to entities
  ajax/map.php
  inc/entity.class.php
  inc/location.class.php
  inc/mapgeolocation.class.php
  inc/search.class.php
  install/mysql/glpi-empty.sql
  install/update_94_95.php
Labels: enhancement

#6706 Fix search when using options based on composite keys
  inc/search.class.php
  tests/functionnal/Search.php
Labels: bug

#6711 Fix cache automatic namespace when using multiple DB hosts
  inc/config.class.php
Labels: bug

#6718 fix(rule): count from all actions not actions added by user; fixes #6491
  inc/rule.class.php
  tests/functionnal/Rule.php
Labels: bug

#6676 Fix recurrent tickets having periodicity > 1 day
  inc/ticketrecurrent.class.php
  tests/functionnal/TicketRecurrent.php
Labels: bug
