Repository glpi-project/glpi, pull requests merged in 2019-06, with the labels that each got.

#5976 faster load of groups in session
  inc/session.class.php
Labels: need_cherrypick

#5986 Fix console commands exit code
  inc/console/application.class.php
Labels: bug

#5985 Compile all CSS during release build
  .circleci/config.yml
  tools/compilescsscommand.class.php
Labels: performance

#5862 Add install/activate/unactivate plugin console commands
  inc/autoload.function.php
  inc/climigration.class.php
  inc/console/abstractcommand.class.php
  inc/console/application.class.php
  inc/console/database/updatecommand.class.php
  inc/console/plugin/abstractplugincommand.class.php
  inc/console/plugin/activatecommand.class.php
  inc/console/plugin/deactivatecommand.class.php
  inc/console/plugin/installcommand.class.php
  inc/migration.class.php
  inc/plugin.class.php
Labels: enhancement

#5988 Fix SCSS compilation output path in release process
  tools/make_release.sh
Labels: performance

#5932 Add a ticket business rule action to prevent take into account
  inc/commonitilactor.class.php
  inc/commonitilobject.class.php
  inc/ruleaction.class.php
  inc/ruleticket.class.php
  inc/ticket.class.php
  tests/functionnal/Rule.php
  tests/functionnal/Ticket.php
Labels: enhancement

#5977 check task right when adding change/problem task
  inc/changetask.class.php
  inc/problemtask.class.php
  install/mysql/glpi-empty.sql
  install/update_942_943.php
Labels: need_cherrypick

#5918 Add 'status' criterion on tickets business rules
  inc/ruleticket.class.php
  tests/functionnal/RuleTicket.php
Labels: enhancement

#5915 Fix overwrite of status set by business rules
  inc/commonitilobject.class.php
  inc/ruleticket.class.php
  inc/ticket.class.php
  tests/functionnal/RuleTicket.php
  tests/functionnal/Ticket.php
Labels: bug

#5972 Fix location business rule when an array of requesters is given
  inc/ticket.class.php
  tests/functionnal/Ticket.php
Labels: Need unit tests, bug

#6011 Exclude deleted and template certificates from cron
  inc/certificate.class.php
Labels: bug

#6021 add another html char for apostrophe (saw it in gmail mail)
  inc/toolbox.class.php
Labels: need_cherrypick

#6034 Fix missing cleanup of Change_Item/Item_Problem when deleting assets
  inc/certificate.class.php
  inc/commondbtm.class.php
  inc/computer.class.php
  inc/dcroom.class.php
  inc/enclosure.class.php
  inc/monitor.class.php
  inc/networkequipment.class.php
  inc/pdu.class.php
  inc/peripheral.class.php
  inc/phone.class.php
  inc/printer.class.php
  inc/rack.class.php
  inc/software.class.php
  inc/softwarelicense.class.php
Labels: bug

#6012 fix php warning on too small files
  inc/document.class.php
Labels: bug

#6038 Display requester identity in ITIL timeline; fixes #4015
  inc/commonitilobject.class.php
Labels: bug, enhancement

#6036 Fix duration statistics CSV export; fixes #6035
  inc/html.class.php
  inc/stat.class.php
Labels: Need feedback

#6031 Allow to disable stats computation after a followup is added
  inc/itilfollowup.class.php
  tests/functionnal/ITILFollowup.php
Labels: enhancement

#6052 Forbid javascript scheme
  inc/html.class.php
Labels: bug, security

#5853 Fix search on notification event
  inc/notification.class.php
  inc/search.class.php
Labels: bug

#6054 Backport security fix from 9.4.3 to 9.3
  inc/html.class.php
  inc/user.class.php
Labels: security

#6059 Missing translation
  inc/glpinetwork.class.php
Labels: bug
