Repository glpi-project/glpi, pull requests merged in 2019-04, with the labels that each got.

#5736 Prevent timezone set to null in session
  inc/auth.class.php
  inc/user.class.php
Labels: bug

#5729 scss compiler doesn't support hex8
  css/styles.scss
Labels: bug, need_cherrypick

#5713 Change default tab on ITIL objects, racks and dc rooms
  inc/ajax.class.php
  inc/change.class.php
  inc/commonitilobject.class.php
  inc/dcroom.class.php
  inc/problem.class.php
  inc/rack.class.php
  inc/ticket.class.php
Labels: enhancement

#5727 Move racks plugin migration to command console
  CHANGELOG.md
  inc/console/migration/racksplugintocorecommand.class.php
  inc/item_rack.class.php
  scripts/migrations/racks_plugin.php
Labels: task

#5719 Display timezone config only if available and add warnings
  inc/central.class.php
  inc/config.class.php
  inc/dbmysql.class.php
  inc/toolbox.class.php
  inc/user.class.php
  tests/functionnal/CommonDBTM.php
Labels: enhancement

#5772 fix user pictures
  front/document.send.php
  inc/user.class.php
Labels: need_cherrypick

#5776 Fixed output not working in rule actions
  inc/rule.class.php
Labels: bug

#5818 feat(core): ability to configure more CSRF options in local_define
  inc/define.php
Labels: enhancement

#5840 Fix software regroupment; see #5833
  inc/software.class.php
Labels: bug

#5846 Replace isIndex
  inc/db.function.php
  inc/dbutils.class.php
  inc/migration.class.php
  install/update_91_92.php
  install/update_92_921.php
  install/update_92_93.php
  src/Glpi/Database/AbstractDatabase.php
  tests/functionnal/DbUtils.php
  tests/units/Glpi/Database/MySql.php
Labels: enhancement
