Repository glpi-project/glpi, pull requests merged in 2019-05, with the labels that each got.

#5855 Rename getAllDatasFromTable and deprecate raw order
  CHANGELOG.md
  inc/api.class.php
  inc/auth.class.php
  inc/authldap.class.php
  inc/blacklist.class.php
  inc/budget.class.php
  inc/calendarsegment.class.php
  inc/commondbtm.class.php
  inc/commonitilobject.class.php
  inc/commonitilvalidation.class.php
  inc/computervirtualmachine.class.php
  inc/db.function.php
  inc/dbutils.class.php
  inc/entity.class.php
  inc/item_ticket.class.php
  inc/mailcollector.class.php
  inc/notificationeventabstract.class.php
  inc/notificationtarget.class.php
  inc/notificationtargetchange.class.php
  inc/notificationtargetcommonitilobject.class.php
  inc/notificationtargetproblem.class.php
  inc/notificationtargetproject.class.php
  inc/notificationtargetprojecttask.class.php
  inc/notificationtargetticket.class.php
  inc/notificationtemplatetranslation.class.php
  inc/objectlock.class.php
  inc/plugin.class.php
  inc/profile_user.class.php
  inc/ruleaction.class.php
  inc/ruledictionnaryprintercollection.class.php
  inc/ruleright.class.php
  inc/stat.class.php
  inc/tickettemplate.class.php
  install/update_0723_078.php
  install/update_0782_080.php
  install/update_078_0781.php
  install/update_080_0801.php
  status.php
  tests/functionnal/DbUtils.php
  tests/functionnal/Networkport.php
  tests/functionnal/NotificationEventAjax.php
  tests/functionnal/NotificationMailing.php
  tests/functionnal/RuleSoftwareCategoryCollection.php
  tests/functionnal/Search.php
Labels: iterator

#5858 Fix filtering of used items in tickets items
  inc/item_ticket.class.php
Labels: bug

#5808 Fix creation of recurrent tickets outside calendar hours
  inc/calendar.class.php
  inc/ticketrecurrent.class.php
  tests/functionnal/TicketRecurrent.php
Labels: bug

#5867 Hide DB password input on install command
  inc/console/database/installcommand.class.php
Labels: enhancement

#5881 Fix undefined action in LDAP sync command; see #5860
  inc/authldap.class.php
Labels: bug

#5876 Fix '_date_creation_calendars_id' criteria on ticket update rules
  inc/ticket.class.php
Labels: bug

#5875 Fix search when using NOT notcontains in HAVING
  inc/search.class.php
Labels: bug

#5872 Make CSS cacheable by browsers and proxies
  front/css.php
  front/find_num.php
  inc/html.class.php
  index.php
  tools/compilescsscommand.class.php
Labels: enhancement

#5895 apply not operator for search groups
  inc/search.class.php
Labels: bug

#5883 Add a ticket business rule action to prevent take into account
  inc/commonitilactor.class.php
  inc/commonitilobject.class.php
  inc/ruleaction.class.php
  inc/ruleticket.class.php
  inc/ticket.class.php
  tests/functionnal/Rule.php
  tests/functionnal/Ticket.php
Labels: enhancement

#5874 Add a 'next escalation level' search option on tickets
  inc/search.class.php
  inc/ticket.class.php
Labels: enhancement

#5893 Fix visibility of problems/tickets in problem/ticket
  inc/problem_ticket.class.php
Labels: bug

#5889 use closure to inspect criteria in api search item
  inc/api.class.php
Labels: need_cherrypick

#5902 fix(dicosoft): escape software name
  inc/ruledictionnarysoftwarecollection.class.php
Labels: bug

#5828 Make items unlocking async; fixes #5799
  inc/objectlock.class.php
Labels: Need feedback

#5894 Fix invalid is_private condition for change/problem tasks
  inc/commonitilobject.class.php
  inc/commonitiltask.class.php
Labels: bug

#5906 Fix ancestors and sons cache invalidation
  inc/commontreedropdown.class.php
  inc/entity.class.php
Labels: bug

#5908 API: changeActiveEntities on root entity without is_recursive shouldn…
  inc/session.class.php
Labels: bug, need_cherrypick

#5911 display private icon on timeline also without edit right
  inc/commonitilobject.class.php
Labels: bug

#5937 Observer group condition (9.4)
  inc/commonitilobject.class.php
  inc/ruleticket.class.php
Labels: bug

#5949 Fix undefined index in reservations search; fixes #5929
  inc/search.class.php
Labels: bug

#5933 MailCollector : option to mark supplier followup as private
  CHANGELOG.md
  inc/entity.class.php
  inc/mailcollector.class.php
  inc/supplier.class.php
  install/mysql/glpi-empty.sql
  install/update_94_95.php
  tests/imap/MailCollector.php
Labels: enhancement

#5948 Add ability to reset translation cache
  front/config.form.php
  inc/config.class.php
Labels: enhancement

#5938 Add ability to customize CSS into entity configuration
  CHANGELOG.md
  ajax/entityCustomCssCode.php
  css/styles.scss
  inc/entity.class.php
  inc/html.class.php
  install/mysql/glpi-empty.sql
  install/update_94_95.php
  package-lock.json
  package.json
  webpack.config.js
Labels: enhancement

#5892 Add ssl connect option to mysql/mariadb databases
  inc/dbmysql.class.php
Labels: enhancement

#5953 Add ability to defines custom options for PDO connection
  src/Glpi/Database/AbstractDatabase.php
  src/Glpi/Database/MySql.php
  src/Glpi/DatabaseFactory.php
Labels: enhancement, need_doc_improvement

#5973 Fix default COLLATE used by MySQL connection
  inc/dbmysql.class.php
Labels: performance
