Repository glpi-project/glpi, pull requests merged in 2019-03, with the labels that each got.

#5498 Fix name of function
  inc/transfer.class.php
Labels: need_cherrypick

#5510 visibility tab for reminder should be displayed only on CREATE right
  inc/reminder.class.php
Labels: bug

#5520 Strict check
  inc/auth.class.php
Labels: bug, security

#5523 All tables must use InnoDB
  .circleci/config.yml
  inc/central.class.php
  inc/config.class.php
  inc/console/database/updatecommand.class.php
  inc/toolbox.class.php
  install/update.php
  install/update_0803_083.php
  install/update_0831_084.php
  install/update_084_085.php
  install/update_085_0853.php
  install/update_0905_91.php
  install/update_91_92.php
  install/update_92_921.php
Labels: enhancement

#5561 fix regex used to match ticket's id in mail headers
  inc/mailcollector.class.php
Labels: bug

#5544 Prevent failure on itemtype migration
  inc/plugin.class.php
Labels: Need feedback

#5577 Password token date was not removed
  inc/user.class.php
Labels: bug, security

#5588 https more secure and with HTTP/2
  js/common.js
Labels: enhancement

#5661 fix synchronization - fixed #5660
  inc/commondbrelation.class.php
Labels: need_cherrypick

#5699 Add encrypted file ssytems support
  CHANGELOG.md
  inc/item_disk.class.php
  install/mysql/glpi-empty.sql
  install/update_94_95.php
Labels: enhancement

#5707 Fix missing filepath on transfered documents
  inc/document.class.php
  tests/functionnal/Document.php
Labels: bug

#5701 Add active status on suppliers
  inc/supplier.class.php
  install/mysql/glpi-empty.sql
  install/update_94_95.php
Labels: enhancement
