Repository glpi-project/glpi, pull requests merged in 2019-02, with the labels that each got.

#5315 Fix translation contexts; closes #5291
  inc/contact.class.php
  inc/location.class.php
Labels: need_cherrypick

#5316 Wrong approval user ID on solutions; fixes #5301
  inc/commonitilobject.class.php
Labels: need_cherrypick

#5223 Add missing rights
  install/mysql/glpi-empty.sql
Labels: need_cherrypick

#5342 fix cut param and display of forcegroupby items in search (incorrect …
  inc/config.class.php
  inc/html.class.php
  inc/search.class.php
Labels: beta, bug, need_cherrypick

#5349 Fix item relation - see #4850
  inc/commondbconnexity.class.php
Labels: need_cherrypick

#5364 fix rendering of timeline (ticket recall and document item)
  css/styles.scss
  inc/commonitilobject.class.php
Labels: need_cherrypick

#5367 Manage UNIQUE keys separately; closes #5359
  inc/migration.class.php
Labels: need_cherrypick

#5369 don't display search controls when _in_modal param provided and no re…
  inc/search.class.php
Labels: need_cherrypick

#5378 Get entity from ticket/problem when creating a change/problem
  inc/change.class.php
  inc/problem.class.php
Labels: enhancement

#5396 Bad variable, fixes #5394
  inc/search.class.php
Labels: need_cherrypick

#5397 Fix update from dev version, see #5362
  inc/update.class.php
Labels: need_cherrypick

#5380 Fix CSRF and DB function in install.php
  install/install.php
Labels: bug

#5401 add search option for profile
  inc/define.php
  inc/profile.class.php
  inc/update.class.php
  install/update_940_941.php
Labels: need_cherrypick

#5408 Fix form title for Item_Devices
  inc/item_devices.class.php
Labels: need_cherrypick

#5399 Take care to migrate solutions wichc contains only a type; closes #5312
  install/update_92_93.php
Labels: need_cherrypick

#5416 Polyfill for String.prototype.normalize()
  inc/html.class.php
  index.php
  install/install.php
  js/common.js
  lib/unorm/unorm.js
Labels: bug

#5417 clear some deprecated warnings (dropdown and itilactor searchoptions)
  inc/ticket.class.php
Labels: bug, need_cherrypick

#5337 Encrypted volumes
  inc/item_disk.class.php
  install/mysql/glpi-empty.sql
  install/update_94_100.php
Labels: enhancement

#5433 add new display hook timeline_actions
  CHANGELOG.md
  inc/commonitilobject.class.php
Labels: enhancement

#5431 fiw project team - see #5430
  inc/projectteam.class.php
Labels: need_cherrypick
