Repository glpi-project/glpi, pull requests merged in 2020-10, with the labels that each got.

#8055 Add search option on saved searches privacy; closes #7936
  inc/savedsearch.class.php
Labels: enhancement

#8059 error and complete callback support for ajaxform
  inc/html.class.php
Labels: enhancement

#8072 Fix associated elements in ticket template
  front/tickettemplatepredefinedfield.form.php
Labels: bug

#8080 Plugin::isInstalled() not always returning a bool
  inc/plugin.class.php
Labels: bug

#8084 Use entity id if present; to avoid difficult to undesrtand cases
  inc/commondbtm.class.php
Labels: bug

#8071 Fix mandatory fields for recurrent ticket
  inc/commonitilobject.class.php
Labels: bug

#8099 avoid loading non existent class
  inc/search.class.php
Labels: bug

#8085 Fix some PHP 8 issues
  composer.lock
  inc/application/errorhandler.class.php
  inc/autoload.function.php
  inc/commondbtm.class.php
  inc/entity.class.php
  inc/html.class.php
  inc/profile.class.php
  inc/project.class.php
  inc/system/requirement/protectedwebaccess.class.php
  tests/functionnal/CommonDropdown.php
  tests/functionnal/Group_User.php
  tests/functionnal/Search.php
  tests/units/Glpi/Application/ErrorHandler.php
Labels: bug

#8062 Battery wear support
  inc/html.class.php
  inc/item_devicebattery.class.php
  inc/item_devices.class.php
  install/mysql/glpi-empty.sql
  install/update_95_xx.php
  install/update_95_xx/devicebattery.php
Labels: feature suggestion

#8118 History: fix display for deletion of a subitem
  inc/log.class.php
Labels: bug

#7659 Inherit geolocation data
  inc/entity.class.php
  inc/location.class.php
  tests/functionnal/Entity.php
  tests/functionnal/Location.php
Labels: enhancement

#8135 Load plugin commands from all plugins directories
  inc/console/commandloader.class.php
  tests/units/Glpi/Console/CommandLoader.php
Labels: bug

#8115 Fix itemcount in Ticket
  inc/commonitilobject.class.php
  inc/impact.class.php
  inc/ticket.class.php
Labels: bug

#8142 Add config:set command
  inc/config.class.php
  inc/console/config/setcommand.class.php
Labels: enhancement

#8156 fix(transfer): prevent PHP notice
  inc/commonitilvalidation.class.php
Labels: bug, php

#8010 feat(sla): add month duration
  inc/levelagreement.class.php
  tests/functionnal/SLM.php
Labels: enhancement

#8155 Reduce query count on home page and fix full list display; see #6765
  inc/commonitiltask.class.php
  inc/problem.class.php
  inc/ticket.class.php
Labels: bug

#8178 Check plugins prerequisites on marketplace view
  inc/marketplace/view.class.php
Labels: bug

#8182 Fix disk 'Free percentage' search option
  inc/search.class.php
Labels: bug

#8186 fix(translate): ticket has been registered but not yet processed
  inc/ticket.class.php
  tests/functionnal/ProjectTask.php
  tests/functionnal/TicketTask.php
Labels: enhancement

#8187 Always display max_closedate for surveys
  ajax/ticketsatisfaction.php
Labels: enhancement
