Repository glpi-project/glpi, pull requests merged in 2020-06, with the labels that each got.

#7314 Fix template entity
  inc/commondbtm.class.php
  inc/contract.class.php
  inc/projectcost.class.php
  inc/projecttask.class.php
  tests/functionnal/CommonDBTM.php
Labels: bug

#7362 remove reverseData params as its behaviors is very strange, fix #7354
  inc/dashboard/widget.class.php
Labels: beta

#7372 Fix behavior of --force param in install command
  inc/console/database/installcommand.class.php
  inc/toolbox.class.php
Labels: bug

#7305 Add rich text to itsm and project's tasks (and their templates)
  inc/commonitiltask.class.php
  inc/define.php
  inc/itilfollowup.class.php
  inc/planningexternalevent.class.php
  inc/projecttask.class.php
  inc/projecttasktemplate.class.php
  inc/tasktemplate.class.php
  install/update_94_95.php
Labels: enhancement

#7413 Call to non existing translation domain
  inc/marketplace/view.class.php
Labels: RC feedback

#7306 Notifications: Fix Yes/No condition on non english languages
  inc/notificationtemplate.class.php
Labels: bug

#7464 ITILTemplate is abstract, use static to access called class
  inc/itiltemplate.class.php
Labels: RC feedback, bug

#7463 Use composer to fetch scrutinizer/ocular
  .circleci/config.yml
  composer.json
  composer.lock
Labels: dependencies

#7465 Remove useless patchwork/jsqueeze lib
  composer.json
  composer.lock
Labels: dependencies

#7466 Upgrade wapmorgan/unified-archive to version 1.0.0
  composer.json
  composer.lock
Labels: dependencies

#7474 Prevent usage of calendars having no working days
  inc/calendar.class.php
  inc/commonitilobject.class.php
  inc/levelagreement.class.php
  inc/ticket.class.php
Labels: bug

#7492 Prevent blocking of telemetry cron on cURL failure
  inc/telemetry.class.php
Labels: bug

#7491 Fix download of plugins archive from GLPI Network
  front/marketplace.download.php
  inc/marketplace/api/plugins.class.php
  inc/marketplace/controller.class.php
  inc/marketplace/view.class.php
Labels: RC feedback, bug

#7493 Check mandatory core requirements on all commands
  inc/console/abstractcommand.class.php
  inc/console/application.class.php
  inc/console/command/glpicommandinterface.class.php
  inc/console/database/installcommand.class.php
  inc/console/database/updatecommand.class.php
  inc/console/system/checkrequirementscommand.class.php
Labels: enhancement

#7500 Fix exit code on exception/fatal error
  inc/application/errorhandler.class.php
Labels: RC feedback, bug
