Repository glpi-project/glpi, pull requests merged in 2020-05, with the labels that each got.

#7230 Fix not clickable buttons on installed plugins page
  css/marketplace.scss
Labels: beta, bug

#7175 Make release process compatible with GPLI 9.5
  bin/console
  package.json
  tools/build_glpi.sh
  tools/make_release.sh
  webpack.config.js
Labels: task

#7188 Feature/contract new field states
  inc/contract.class.php
  inc/define.php
  inc/notificationtargetcontract.class.php
  inc/state.class.php
  install/mysql/glpi-empty.sql
  install/update_94_95.php
Labels: enhancement

#7247 Improve filter wording for numeric values and correct the behaviour of "not contains"
  inc/search.class.php
Labels: enhancement

#7208 add default dashboards
  css/dashboard.scss
  inc/certificatetype.class.php
  inc/commondcmodeldropdown.class.php
  inc/commonglpi.class.php
  inc/computertype.class.php
  inc/dashboard/grid.class.php
  inc/dashboard/widget.class.php
  inc/monitortype.class.php
  inc/networkequipmenttype.class.php
  inc/peripheraltype.class.php
  inc/phonemodel.class.php
  inc/phonetype.class.php
  inc/printermodel.class.php
  inc/printertype.class.php
  inc/softwarelicensetype.class.php
  inc/state.class.php
  install/empty_data.php
  install/update_94_95.php
  install/update_94_95/dashboards.php
  js/dashboard.js
  tests/functionnal/Glpi/Dashboard/Dashboard.php
Labels: task

#6991 API support for deprecated itemtypes
  .gitignore
  apirest.php
  apixmlrpc.php
  inc/api/api.class.php
  inc/api/apirest.class.php
  inc/api/apixmlrpc.class.php
  inc/api/deprecated/commondeprecatedtrait.class.php
  inc/api/deprecated/computer_softwarelicense.class.php
  inc/api/deprecated/computer_softwareversion.class.php
  inc/api/deprecated/deprecatedinterface.class.php
  inc/api/deprecated/ticketfollowup.class.php
  inc/autoload.function.php
  inc/item_softwarelicense.class.php
  inc/item_softwareversion.class.php
  inc/itilfollowup.class.php
  inc/search.class.php
  inc/toolbox.class.php
  tests/APIBaseClass.php
  tests/bootstrap.php
  tests/deprecated-searchoptions/Computer_SoftwareLicense.json
  tests/deprecated-searchoptions/Computer_SoftwareVersion.json
  tests/deprecated-searchoptions/TicketFollowup.json
  tests/functionnal/CommonDBTM.php
  tests/functionnal/Item_SoftwareLicense.php
  tests/router.php
  tests/units/Toolbox.php
  tests/web/APIRest.php
  tests/web/APIXmlrpc.php
  tests/web/deprecated/Computer_SoftwareLicense.class.php
  tests/web/deprecated/Computer_SoftwareVersion.class.php
  tests/web/deprecated/DeprecatedInterface.class.php
  tests/web/deprecated/TicketFollowup.class.php
Labels: api
