Repository glpi-project/glpi, pull requests merged in 2020-07, with the labels that each got.

#7546 Change branches in dependabot strategies
  .dependabot/config.yml
Labels: dependencies

#7584 Fix SQL errors on search solution into KB from ticket
  inc/knowbaseitem.class.php
Labels: RC feedback, bug

#7598 Encrypt GLPI Network registration key
  inc/config.class.php
  inc/glpinetwork.class.php
  install/update_94_95.php
Labels: RC feedback, enhancement

#7599 Fix form refresh after problem actor email update
  front/problem_user.form.php
Labels: bug

#7654 Update registration key on security key change; see #7645
  inc/glpikey.class.php
Labels: bug

#7667 Fix erronous mail collector rejected email reason
  inc/mailcollector.class.php
Labels: bug

#7602 Add domains to global search
  inc/define.php
Labels: enhancement

#7637 Do not expose registration key in API config endpoint
  inc/config.class.php
Labels: api

#7687 Fix reopen check
  inc/itilfollowup.class.php
Labels: bug

#7694 Handle missing 'to' email header
  inc/mailcollector.class.php
  tests/emails-tests/12-missing-to.eml
  tests/imap/MailCollector.php
Labels: bug

#7698 Prevent exception on maillcollector connection
  inc/mailcollector.class.php
Labels: bug

#7745 Fix right error when using 'with_document' in API
  inc/api/api.class.php
Labels: bug

#7762 Do not show impersonate button for new user
  inc/session.class.php
  inc/user.class.php
Labels: bug

#7775 Fix 'display' param of yes/no checkboxes
  inc/dropdown.class.php
Labels: bug

#7784 Display Historical tab on items templates
  inc/log.class.php
Labels: enhancement

#7792 New icons for impact UI
  inc/impact.class.php
Labels: enhancement
