Repository glpi-project/glpi, pull requests merged in 2020-12, with the labels that each got.

#8381 Update paragonie/sodium_compat to get better PHP 8 compatibility
  composer.json
  composer.lock
  tools/sodium_compat-php8-compat.patch
Labels: dependencies

#8401 Remove vendor cleaning in release process
  tools/build_glpi.sh
Labels: dependencies

#8403 Load JSTree CSS directly from library
  css/jstree-glpi.css
  inc/entity.class.php
  inc/html.class.php
  inc/knowbase.class.php
  lib/bundles/jstree.js
  lib/jstree/themes/glpi/32px.png
  lib/jstree/themes/glpi/40px.png
  lib/jstree/themes/glpi/throbber.gif
  webpack.config.js
Labels: dependencies

#8289 Log SQL warnings
  inc/application/errorhandler.class.php
  inc/dbmysql.class.php
  inc/toolbox.class.php
  tests/functionnal/MassiveAction.php
Labels: enhancement

#8404 Fix <emails> in notifications 2
  inc/notificationeventmailing.class.php
  inc/notificationtargetticket.class.php
  inc/toolbox.class.php
Labels: bug

#8427 Prevent secured configs to be altered by sanitize logic; see #8283
  front/config.form.php
Labels: bug

#8431 Fix KB item assocated documents list
  inc/knowbaseitem.class.php
Labels: bug

#8318 Hide plugins with no installable version
  inc/marketplace/api/plugins.class.php
Labels: bug

#8441 Fix/missingso
  inc/appliance.class.php
  inc/search.class.php
Labels: enhancement
