Repository glpi-project/glpi, pull requests merged in 2020-11, with the labels that each got.

#8213 Fix locale string
  inc/marketplace/view.class.php
Labels: bug

#8215 Upgrade to webpack 5.0
  package-lock.json
  package.json
  webpack.config.js
Labels: dependencies

#7917 Massive actions on Plugins
  inc/plugin.class.php
Labels: enhancement

#7866 feat(rule): add action for RuleTicket engine
  inc/rule.class.php
  inc/ruleticket.class.php
  tests/functionnal/RuleTicket.php
Labels: enhancement

#8222 Enhance configuration history
  inc/config.class.php
  inc/glpikey.class.php
  inc/log.class.php
  tests/functionnal/Config.php
  tests/units/Migration.php
Labels: enhancement

#8224 Fix pasted rich text
  css/styles.scss
Labels: bug

#8239 fix autogrow on textarea
  inc/html.class.php
Labels: bug

#7896 Add plugin lifecycle hooks
  inc/plugin.class.php
Labels: enhancement

#8251 Fix bad comparison in log
  inc/log.class.php
Labels: bug

#8255 Fix dropdown display when selected value is part of toadd
  inc/html.class.php
Labels: bug

#8264 TinyMCE: Fix paste with context menu
  inc/html.class.php
Labels: bug

#8258 Increase max items per contract
  inc/contract.class.php
Labels: bug

#8245 add relations between certificates, domains and appliances.
  inc/appliance.class.php
  inc/certificate.class.php
  inc/define.php
Labels: enhancement

#8280 Handle definition of xxx_types config handled by a plugin
  inc/item_devices.class.php
  inc/plugin.class.php
Labels: Need unit tests, enhancement

#8269 Fix ticket rules for itilcategories_id_code
  inc/ticket.class.php
  tests/functionnal/RuleTicket.php
Labels: bug

#8283 Prevent passwords to be altered by sanitize logic; fixes #8188
  ajax/mailcollector.php
  front/authldap.form.php
  front/config.form.php
  front/mailcollector.form.php
  inc/authldap.class.php
  inc/mailcollector.class.php
  tests/functionnal/AuthLdap.php
Labels: bug

#8051 Enhance PHP 8 compatibility
  .composer-require-checker.config.json
  .github/workflows/ci.yml
  composer.json
  composer.lock
  tests/functionnal/Auth.php
  tests/functionnal/Calendar.php
  tests/functionnal/Document.php
  tests/functionnal/NotificationTargetUser.php
  tests/functionnal/Plugin.php
  tests/functionnal/Profile.php
  tests/functionnal/Search.php
  tests/functionnal/Session.php
  tests/functionnal/Ticket.php
  tests/functionnal/User.php
  tests/units/Toolbox.php
  tests/web/APIXmlrpc.php
  tools/tcpdf-php8-compat.patch
Labels: enhancement

#8292 Fix ticket template change on helpdesk form
  inc/ticket.class.php
Labels: bug

#8300 Fix higher version fetching in plugins marketplace
  inc/marketplace/api/plugins.class.php
Labels: bug

#8301 Handle registration key validation message returned by Services API
  inc/glpinetwork.class.php
Labels: enhancement

#8307 Switch to atoum/atoum stable 4.x releases
  .atoum.php
  composer.json
  composer.lock
  tests/APIBaseClass.php
  tests/GLPITestCase.php
  tests/functionnal/Computer.php
  tests/functionnal/Domain.php
  tests/functionnal/MassiveAction.php
  tests/functionnal/Transfer.php
  tests/imap/MailCollector.php
  tests/web/Telemetry.php
  tools/genphpcov.sh
Labels: dependencies

#8310 Strip unusable sourcemaps from bundled libs; fixes #8302
  package-lock.json
  package.json
  webpack.config.js
Labels: bug

#8315 fix(search): use no sort for virtual field
  inc/datacenter.class.php
Labels: bug

#8311 Fix AND NOT meta search
  inc/search.class.php
  tests/functionnal/Search.php
Labels: bug

#8316 split 'not' criteria
  inc/stat.class.php
Labels: bug
