Repository glpi-project/glpi, pull requests merged in 2020-03, with the labels that each got.

#7013 Upgrade Fullcalendar from 4.3.x to 4.4.0
  package-lock.json
  package.json
Labels: dependencies

#6984 API/initSession: add get_full_session option
  apirest.md
  inc/api.class.php
  inc/session.class.php
  tests/web/APIRest.php
  tests/web/APIXmlrpc.php
Labels: api

#7010 Use caret operator for atoum/atoum compatibility
  composer.json
  composer.lock
Labels: dependencies

#7026 Fix warning with objects in session
  inc/abstractquery.class.php
  inc/html.class.php
  inc/queryexpression.class.php
  inc/queryparam.class.php
Labels: bug

#7015 Anonymous support agents on helpdesk
  inc/commondbtm.class.php
  inc/commonitilobject.class.php
  inc/entity.class.php
  inc/html.class.php
  inc/itilfollowup.class.php
  inc/migration.class.php
  inc/notificationtargetcommonitilobject.class.php
  inc/search.class.php
  inc/session.class.php
  install/empty_data.php
  install/mysql/glpi-empty.sql
  install/update_94_95.php
  tests/functionnal/ITILFollowup.php
  tests/units/Migration.php
Labels: enhancement

#7043 Optimize footprint checks on getMultiple operations
  inc/cache/simplecache.class.php
Labels: beta

#7064 Fix additionnal buttons value
  inc/commondbtm.class.php
Labels: beta, bug

#7061 Fix display of documents associated items
  inc/document_item.class.php
Labels: beta, bug

#7072 Fix ability to retrieve ITIL items document on API
  inc/api.class.php
Labels: api, bug

#7073 Use new official repository for PHP Parallel Lint dev dependency
  composer.json
  composer.lock
Labels: dependencies

#6993 Define GLPI_ constants using server env variables
  .gitignore
  CHANGELOG.md
  inc/based_config.php
  inc/caldav/traits/vobjectconvertertrait.class.php
  inc/config.class.php
  inc/define.php
  inc/xhprof.class.php
Labels: enhancement

#7088 Fix missing history for TicketTask
  inc/commonitiltask.class.php
Labels: api

#7086 add action 'copy default from user' for group requester
  inc/rule.class.php
  inc/ruleaction.class.php
  inc/ruleticket.class.php
  inc/ticket.class.php
  tests/functionnal/RuleTicket.php
Labels: enhancement
