Repository glpi-project/glpi, pull requests merged in 2020-09, with the labels that each got.

#7764 Add an helper form for domain record data
  ajax/domainrecord_data_form.php
  inc/domainrecord.class.php
  inc/domainrecordtype.class.php
  install/mysql/glpi-empty.sql
  install/update_94_95.php
  install/update_95_xx/domains.php
Labels: enhancement

#7875 Fix migration of encrypted data; see #7848
  inc/glpikey.class.php
Labels: bug

#7856 Fix status update of tasks served as VEVENT on CalDAV
  inc/caldav/traits/vobjectconvertertrait.class.php
  inc/commonitiltask.class.php
  inc/planningexternalevent.class.php
  inc/projecttask.class.php
  inc/reminder.class.php
Labels: bug

#7926 Prevent mail import failure to break collector
  inc/mailcollector.class.php
  tests/emails-tests/17-malformed-email.eml
  tests/imap/MailCollector.php
Labels: enhancement

#7931 fix(ui): fix mini dashboard CSS
  css/dashboard.scss
Labels: bug

#7938 Add check for invalid address or netmask
  inc/ipnetwork.class.php
Labels: bug

#7660 Add title, timezone, and plugin hook for vCards
  inc/contact.class.php
  inc/user.class.php
Labels: enhancement

#7940 Prevent failure of "glpi:security:change_key" command
  inc/glpikey.class.php
  inc/toolbox.class.php
  tests/units/Toolbox.php
Labels: bug

#7887 Do not import mail already seen
  inc/mailcollector.class.php
  install/mysql/glpi-empty.sql
  install/update_951_952.php
  tests/imap/MailCollector.php
Labels: enhancement

#7973 Fix scrollbar from softwares list on computer
  inc/ajax.class.php
Labels: bug

#7978 Fix plugin unloading
  inc/plugin.class.php
Labels: bug

#7994 Fix SLA/OLA progress bar; see #5272 and #4960
  inc/search.class.php
Labels: bug

#8000 Handle missing read rights on cache footprint file
  inc/cache/simplecache.class.php
  tests/units/Glpi/Cache/SimpleCache.php
Labels: bug

#8006 Fix RSS feeds duplicates
  inc/rssfeed.class.php
Labels: bug

#8012 Override canDelete, canPurge and canPurgeItem on DomainRecord
  inc/domainrecord.class.php
Labels: bug

#7992 Fix #7980 Bug : Notification template block post_addItem of ticket
  inc/notificationtargetcommonitilobject.class.php
Labels: Need unit tests
