Repository glpi-project/glpi, pull requests merged in 2020-04, with the labels that each got.

#7060 Fix handling of ITIL documents
  front/change.form.php
  front/problem.form.php
  front/ticket.form.php
  inc/api.class.php
  inc/commonitilobject.class.php
  inc/document.class.php
  inc/notificationeventmailing.class.php
  inc/notificationtargetcommonitilobject.class.php
  inc/transfer.class.php
  tests/functionnal/Ticket.php
Labels: beta, bug, help wanted

#7127 Rework massiveactions for add or delete template from notification
  inc/notification.class.php
  inc/notification_notificationtemplate.class.php
Labels: bug

#6561 Improve install script
  inc/dbmysql.class.php
  tests/units/DB.php
Labels: enhancement

#7147 replace date[time|multiple] picker by flatpickr
  css/styles.scss
  inc/authldap.class.php
  inc/change.class.php
  inc/commonitiltask.class.php
  inc/html.class.php
  inc/knowbaseitem.class.php
  inc/levelagreement.class.php
  inc/planning.class.php
  inc/problem.class.php
  inc/project.class.php
  inc/reminder.class.php
  inc/reservation.class.php
  inc/ticket.class.php
  inc/toolbox.class.php
  inc/user.class.php
  js/common.js
  js/planning.js
  lib/bundles/base.js
  lib/bundles/flatpickr.js
  package-lock.json
  package.json
  tests/functionnal/Ticket.php
  webpack.config.js
Labels: task

#7162 Fix markup diplay when term match with html entity
  js/common.js
Labels: bug

#7206 Fix inconsistency in requires and prevent install of useless polyfills
  composer.json
  composer.lock
  inc/system/requirementsmanager.class.php
Labels: dependencies, enhancement
