Repository glpi-project/glpi, pull requests merged in 2021-04, with the labels that each got.

#8921 Update tecnickcom/tcpdf to get PHP 8.0 official support
  composer.json
  composer.lock
  tools/tcpdf-php8-compat.patch
Labels: dependencies

#8878 Handle errors on crontasks
  inc/crontask.class.php
  inc/crontasklog.class.php
  inc/notificationtargetcrontask.class.php
Labels: bug

#8872 Prevent 'on update current_timestamp' to be auto set on timestamps
  inc/console/database/updatecommand.class.php
  inc/console/migration/timestampscommand.class.php
  inc/define.php
  inc/update.class.php
  install/mysql/glpi-empty.sql
  install/update_954_955.php
Labels: bug

#8881 Fix handling of plugins namespaces on crontask
  inc/crontask.class.php
  tests/functionnal/CronTask.php
Labels: bug

#8938 HtmLawed: allow "notes" scheme
  inc/toolbox.class.php
Labels: enhancement

#8943 Fix user mentions feature on helpdesk followup form
  inc/itilfollowup.class.php
Labels: bug

#8946 Ensure plugin state is up to date before activate/install it
  inc/console/plugin/activatecommand.class.php
  inc/console/plugin/deactivatecommand.class.php
  inc/console/plugin/installcommand.class.php
Labels: bug

#8939 feat(crontask): improve clean temp crontask
  inc/crontask.class.php
  tests/units/CronTask.php
Labels: bug, enhancement

#8875 Partial inventory
  composer.lock
  inc/inventory/asset/antivirus.class.php
  inc/inventory/asset/bios.class.php
  inc/inventory/asset/cartridge.class.php
  inc/inventory/asset/device.class.php
  inc/inventory/asset/inventoryasset.class.php
  inc/inventory/asset/inventorynetworkport.class.php
  inc/inventory/asset/mainasset.class.php
  inc/inventory/asset/monitor.class.php
  inc/inventory/asset/networkport.class.php
  inc/inventory/asset/operatingsystem.class.php
  inc/inventory/asset/peripheral.class.php
  inc/inventory/asset/remotemanagement.class.php
  inc/inventory/asset/software.class.php
  inc/inventory/asset/virtualmachine.class.php
  inc/inventory/asset/volume.class.php
  inc/inventory/inventory.class.php
  inc/ruleimportasset.class.php
  tests/fixtures/inventory/computer_1.json
  tests/fixtures/inventory/computer_1_partial_batteries.json
  tests/fixtures/inventory/computer_1_partial_softs.json
  tests/fixtures/inventory/computer_1_partial_volumes.json
  tests/functionnal/Glpi/Inventory/Assets/Antivirus.php
  tests/functionnal/Glpi/Inventory/Inventory.php
  tests/functionnal/RuleImportAsset.php
Labels: enhancement

#8941 Ability to disallow marketplace overrides and manual download links
  .composer-require-checker.config.json
  inc/based_config.php
  inc/marketplace/controller.class.php
  inc/marketplace/view.class.php
Labels: enhancement

#8849 Fix external links
  inc/link.class.php
  inc/search.class.php
Labels: bug

#8964 Allow usage of specific display without a name
  inc/search.class.php
Labels: bug

#8965 Add clean massive action for plugins
  inc/plugin.class.php
Labels: enhancement

#8990 Add missing encoding for savedsearch notif name
  inc/savedsearch.class.php
Labels: bug

#8982 a search uses DISTINCT, counting its results shall contain it as well
  inc/search.class.php
Labels: bug

#8991 Fix followups rights checks
  inc/commonitilobject.class.php
  inc/ticket.class.php
  tests/functionnal/Ticket.php
Labels: bug

#8985 Search / Future dates
  inc/certificate.class.php
  inc/commonitiltask.class.php
  inc/contract.class.php
  inc/infocom.class.php
Labels: bug, enhancement

#8997 feat(auth): add option to define timeout
  inc/auth.class.php
  inc/authldap.class.php
  inc/authldapreplicate.class.php
  install/migrations/update_9.5.x_to_10.0.0/ldaps.php
  install/mysql/glpi-empty.sql
  tests/LDAP/AuthLdap.php
Labels: enhancement

#8992 Give ability to tickets observers to add followups
  inc/commonitilobject.class.php
  inc/itilfollowup.class.php
  inc/ticket.class.php
  tests/functionnal/Ticket.php
Labels: enhancement

#9001 Fix handling of illegal chars in collected emails; see #8986
  inc/mailcollector.class.php
  tests/emails-tests/26-illegal-char-in-body.eml
  tests/imap/MailCollector.php
Labels: bug

#9009 Drop phpCAS extension check on install
  inc/system/requirementsmanager.class.php
Labels: task

#9018 Do not update tickets date on inline images fixing
  inc/document_item.class.php
  install/update_951_952.php
  tests/functionnal/Document_Item.php
Labels: bug

#9020 Fix two typos (an an -> an)
  inc/notificationtargetchange.class.php
  inc/notificationtargetticket.class.php
Labels: bug

#9005 Escape software name in rules; fixes #9004
  inc/ruledictionnarysoftwarecollection.class.php
Labels: bug
