Repository glpi-project/glpi, pull requests merged in 2021-11, with the labels that each got.

#9832 Fix getLegacyTimelineActionsHTML for plugins
  inc/commonitilobject.class.php
Labels: bug

#9833 Fix modal size
  inc/ajax.class.php
Labels: bug

#9838 Add appliances to global search
  inc/define.php
Labels: enhancement

#9784 FAQ: Fix full text search with illegal chars
  inc/knowbaseitem.class.php
  tests/functionnal/KnowbaseItem.php
Labels: bug

#9834 add timeline hook for plugins
  inc/commonitilobject.class.php
  inc/plugin/hooks.class.php
Labels: enhancement, need_doc_improvement

#9851 fix date picker UI
  inc/html.class.php
Labels: bug

#9879 Add SNMP inventory hook
  inc/agent/communication/abstractrequest.class.php
  inc/inventory/request.class.php
  inc/plugin/hooks.class.php
  tests/units/Glpi/Inventory/Request.php
Labels: need_doc_improvement

#9890 Fix old migration warning on PHP 8.1
  install/migrations/update_0.84.x_to_0.85.0.php
Labels: bug

#9692 Kanban Filters
  css/includes/components/_kanban.scss
  inc/commonitilobject.class.php
  inc/html.class.php
  inc/project.class.php
  js/modules/Kanban/Kanban.js
  js/modules/SearchTokenizer/SearchToken.js
  js/modules/SearchTokenizer/SearchTokenizer.js
  js/modules/SearchTokenizer/SearchTokenizerResult.js
  templates/components/kanban/kanban.html.twig
  tests/js/SearchTokenizer/SearchTokenizer.test.js
Labels: enhancement

#9933 Fix recursive documents in knowbase
  inc/knowbaseitem.class.php
Labels: bug

#9934 Fix plugin locales loading from files/_locales
  inc/plugin.class.php
Labels: bug

#9929 ensure notifications are send with data for the correct user's timezone
  inc/dbmysql.class.php
  inc/notificationeventabstract.class.php
  inc/notificationtarget.class.php
Labels: bug

#9894 Supplier and contact add administrative number
  inc/contact.class.php
  inc/supplier.class.php
  install/migrations/update_9.5.x_to_10.0.0/contact.php
  install/migrations/update_9.5.x_to_10.0.0/supplier.php
  install/mysql/glpi-empty.sql
  templates/generic_show_form.html.twig
Labels: enhancement

#9928 Use global cache namespace prefix
  inc/cache/cachemanager.class.php
  inc/console/cache/configurecommand.class.php
  inc/console/cache/setnamespaceprefixcommand.class.php
  tests/units/Glpi/Cache/CacheManager.php
Labels: enhancement, need_doc_improvement

#9945 fix(planning): refresh button
  js/planning.js
Labels: bug

#9935 Fix missing breaks in switches
  inc/cable.class.php
  inc/commondbtm.class.php
  inc/console/ldap/synchronizeuserscommand.class.php
  inc/contract_item.class.php
  inc/dashboard/provider.class.php
  inc/html.class.php
  inc/pdu_rack.class.php
  inc/projecttasktemplate.class.php
  inc/ruleticket.class.php
  inc/search.class.php
  inc/toolbox.class.php
  inc/transfer.class.php
  inc/user.class.php
Labels: bug

#9964 Fix project clone
  inc/features/clonable.class.php
  tests/functionnal/Project.php
Labels: bug

#9967 Fix FAQ anchors
  inc/knowbaseitem.class.php
  tests/functionnal/KnowbaseItem.php
Labels: bug

#9971 Update minimal supported lib versions in composer.json
  composer.json
  composer.lock
Labels: dependencies
