Repository glpi-project/glpi, pull requests merged in 2021-09, with the labels that each got.

#9486 Fix empty value for user dropdown
  inc/user.class.php
Labels: bug

#9485 Content templates: Add extra variables for users
  inc/contenttemplates/parameters/usercategoryparameters.class.php
  inc/contenttemplates/parameters/userparameters.class.php
  inc/contenttemplates/parameters/usertitleparameters.class.php
  tests/functionnal/Glpi/ContentTemplates/Parameters/ChangeParameters.php
  tests/functionnal/Glpi/ContentTemplates/Parameters/ProblemParameters.php
  tests/functionnal/Glpi/ContentTemplates/Parameters/TicketParameters.php
  tests/functionnal/Glpi/ContentTemplates/Parameters/UserParameters.php
  tests/functionnal/Glpi/ContentTemplates/Parameters/UsercategoryParameters.php
  tests/functionnal/Glpi/ContentTemplates/Parameters/UsertitleParameters.php
Labels: enhancement

#9494 avoid duplicate id usage in dom for entity selector
  inc/entity.class.php
Labels: bug

#9488 add generic showForm function to CommonDBTM
  CHANGELOG.md
  front/setup.notification.php
  inc/appliance.class.php
  inc/cartridgeitem.class.php
  inc/certificate.class.php
  inc/cluster.class.php
  inc/commondbtm.class.php
  inc/computer.class.php
  inc/consumableitem.class.php
  inc/contact.class.php
  inc/contract.class.php
  inc/datacenter.class.php
  inc/domain.class.php
  inc/enclosure.class.php
  inc/line.class.php
  inc/monitor.class.php
  inc/networkequipment.class.php
  inc/notificationsettingconfig.class.php
  inc/notificationtemplatetranslation.class.php
  inc/passivedcequipment.class.php
  inc/pdu.class.php
  inc/peripheral.class.php
  inc/phone.class.php
  inc/printer.class.php
  inc/rack.class.php
  inc/rulematchedlog.class.php
  inc/software.class.php
  inc/softwarelicense.class.php
  inc/supplier.class.php
  inc/ticket.class.php
  inc/ticketsatisfaction.class.php
  inc/unmanaged.class.php
  templates/generic_show_form.html.twig
  tests/functionnal/NotificationSettingConfig.php
Labels: enhancement

#9496 fix overlap of template name field with header's ribbon
  templates/components/form/header.html.twig
Labels: bug

#9499 explicit multiple selection mode for ajax dropdowns
  inc/abstractrightsdropdown.class.php
  inc/html.class.php
  inc/netpoint.class.php
Labels: bug

#9509 Preserve npm lockfile version during dependencies install
  bin/console
Labels: dependencies

#9378 Fix meta JOIN
  inc/search.class.php
  tests/functionnal/Search.php
Labels: bug

#9530 Add ability to (en|dis)able Telemetry during install/update process
  inc/console/database/installcommand.class.php
  inc/console/database/updatecommand.class.php
  inc/console/traits/telemetryactivationtrait.class.php
  inc/telemetry.class.php
Labels: enhancement

#9451 Added missing 'group in charge of the task'
  inc/notificationtargetplanningrecall.class.php
Labels: enhancement

#9560 Search engine: Fix group criteria after meta criteria
  inc/search.class.php
  tests/functionnal/Search.php
Labels: bug

#9572 Change action_type for itilfollowup_template and task_template
  inc/ruleticket.class.php
  install/migrations/update_9.5.x_to_10.0.0/ruleticketaction.php
  tests/functionnal/RuleTicket.php
Labels: enhancement

#9540 First try on known LDAP server(s) to speed-up login
  inc/authldap.class.php
Labels: enhancement

#9576 Add search option on softwareversion architecture
  inc/software.class.php
  tests/functionnal/Software.php
Labels: enhancement

#9579 add possibility to search user by registration_number in user dropdown
  inc/user.class.php
Labels: enhancement

#9545 feat(change): use change template from create form
  css/styles.scss
  inc/change.class.php
Labels: bug

#9586 Check if _locales exist
  inc/plugin.class.php
  inc/session.class.php
Labels: bug

#9584 fix(doc): no recusivity for upload doc from richtext
  inc/commondbtm.class.php
Labels: bug, Need feedback

#9607 Compress CSS using csso
  composer.json
  composer.lock
  css/chartists-glpi.css
  css/jquery-glpi.css
  css/print.css
  css/style_install.css
  css/tab-scroller-menu.css
  package-lock.json
  package.json
  tools/RoboFile.php
  tools/build_glpi.sh
Labels: dependencies
