Repository glpi-project/glpi, pull requests merged in 2021-02, with the labels that each got.

#8597 feat(searchoption): add software date install to metacriteria
  inc/software.class.php
  tests/functionnal/Software.php
Labels: enhancement

#7816 Complete Clonable trait
  CHANGELOG.md
  inc/calendar.class.php
  inc/commondbconnexity.class.php
  inc/commondbtm.class.php
  inc/commonitilobject.class.php
  inc/features/clonable.class.php
  inc/massiveaction.class.php
  inc/networkport.class.php
  inc/projecttask.class.php
  inc/rule.class.php
  inc/toolbox.class.php
  inc/user.class.php
  tests/functionnal/Calendar.php
  tests/functionnal/Ticket.php
  tests/units/Glpi/Features/Clonable.php
  tests/units/Toolbox.php
Labels: enhancement

#8625 Enhance db:check command
  .github/actions/test_update_from_9.5.sh
  .github/actions/test_update_from_older_version.sh
  .github/workflows/ci.yml
  CHANGELOG.md
  inc/console/database/checkcommand.class.php
  inc/console/migration/dynamicrowformatcommand.class.php
  inc/console/migration/utf8mb4command.class.php
  inc/dbmysql.class.php
  inc/system/diagnostic/databasechecker.class.php
  inc/system/requirement/dbconfiguration.class.php
  install/update_95_xx.php
  install/update_95_xx/date_fields_defaults.php
  install/update_95_xx/native_inventory.php
  install/update_95_xx/recurrentchange.php
  install/update_95_xx/schema_fixes.php
  tests/database/DBmysql.php
  tests/glpi-9.5.3-empty.sql
  tests/units/DB.php
  tests/units/Glpi/System/Diagnostic/DatabaseChecker.php
Labels: enhancement

#8619 fix(event): fix get event for savedsearch
  inc/notificationtargetsavedsearch_alert.class.php
Labels: bug

#8633 fix(apppliance): prevent duplicated infocom creation
  inc/console/migration/appliancesplugintocorecommand.class.php
Labels: bug

#8650 Promote glpi:build:compile_scss as an official command
  inc/console/build/compilescsscommand.class.php
Labels: need_doc_improvement

#8623 fix(api): manage mainitems_id foreignkey
  inc/api/api.class.php
Labels: api, bug

#8659 Allow iframes in rich text only when allowed by config
  .composer-require-checker.config.json
  inc/based_config.php
  inc/html.class.php
  inc/toolbox.class.php
  tests/units/Html.php
  tests/units/Toolbox.php
Labels: enhancement

#8629 Populate meta criteria in a generic way
  CHANGELOG.md
  inc/commonitilcost.class.php
  inc/contract.class.php
  inc/project.class.php
  inc/search.class.php
  tests/functionnal/Search.php
Labels: enhancement

#8639 Add a check on database keys
  .github/actions/test_install.sh
  .github/actions/test_update-from-9.5.sh
  .github/actions/test_update-from-older-version.sh
  inc/console/database/checkschemacommand.class.php
  inc/system/diagnostic/databasekeyschecker.class.php
  inc/system/diagnostic/databaseschemachecker.class.php
  install/mysql/glpi-empty.sql
  install/update_95_xx/native_inventory.php
  install/update_95_xx/schema_fixes.php
  tests/units/Glpi/System/Diagnostic/DatabaseKeysChecker.php
  tests/units/Glpi/System/Diagnostic/DatabaseSchemaChecker.php
  tools/checkkeyscommand.class.php
Labels: task

#8667 Drop PHP 7.2 support
  .github/workflows/ci.yml
  README.md
  composer.json
  composer.lock
  inc/define.php
  index.php
Labels: need_doc_improvement

#8655 Add location from user and default group from user and first group fromuser for rule asset
  inc/commondbtm.class.php
  inc/rule.class.php
  inc/ruleaction.class.php
  inc/ruleasset.class.php
  tests/units/RuleAsset.php
Labels: enhancement

#8678 fix adding new user planning due to a bad idor check
  inc/session.class.php
Labels: bug

#8668 fix(lifecycle): check if reopening is allowed through lifecycle rights
  inc/itilfollowup.class.php
Labels: bug, wip

#8682 Fix dropdown using 0 as a concrete value; see #8681
  inc/dashboard/filter.class.php
  inc/dropdown.class.php
  inc/html.class.php
Labels: bug

#8666 Do no delete default profiles if no rules were applied
  inc/profile_user.class.php
  inc/user.class.php
  install/mysql/glpi-empty.sql
  install/update_953_954.php
  tests/units/RuleRight.php
Labels: Need unit tests

#8690 fix(appliance): add location and manufacturer searchOptions
  inc/appliance.class.php
Labels: enhancement

#8691 fix(ldap_sync): check if link already exist before add
  inc/user.class.php
Labels: bug

#8694 Fix image pasting in rich text
  css/styles.scss
  inc/html.class.php
Labels: bug

#8695 Upgrade TinyMCE from 4.9.x to 5.7.x
  .gitignore
  css/palettes/_darker.scss
  css/styles.scss
  css/tiny_mce/dark_content.css
  css/tiny_mce/skins/light/content.inline.min.css
  css/tiny_mce/skins/light/content.min.css
  css/tiny_mce/skins/light/fonts/tinymce-small.eot
  css/tiny_mce/skins/light/fonts/tinymce-small.svg
  css/tiny_mce/skins/light/fonts/tinymce-small.ttf
  css/tiny_mce/skins/light/fonts/tinymce-small.woff
  css/tiny_mce/skins/light/fonts/tinymce.eot
  css/tiny_mce/skins/light/fonts/tinymce.svg
  css/tiny_mce/skins/light/fonts/tinymce.ttf
  css/tiny_mce/skins/light/fonts/tinymce.woff
  css/tiny_mce/skins/light/img/anchor.gif
  css/tiny_mce/skins/light/img/loader.gif
  css/tiny_mce/skins/light/img/object.gif
  css/tiny_mce/skins/light/img/trans.gif
  css/tiny_mce/skins/light/skin.min.css
  css/tiny_mce_custom.css
  inc/html.class.php
  js/fileupload.js
  lib/bundles/tinymce.js
  lib/tiny_mce/custom_plugins/stickytoolbar/plugin.js
  package-lock.json
  package.json
  webpack.config.js
Labels: dependencies, enhancement
