Repository glpi-project/glpi, pull requests merged in 2021-01, with the labels that each got.

#8265 Handle RFC5987 format in Content-Disposition header (single line)
  tests/emails-tests/20-attachement-rfc5987-singleline.eml
  tests/imap/MailCollector.php
Labels: bug

#8491 Fix entity tree expand
  ajax/entitytreesons.php
Labels: bug

#8492 Fix email attachement decoding logic
  inc/mailcollector.class.php
Labels: bug

#8498 Fix IMAP auth without login source dropdown
  inc/auth.class.php
Labels: bug

#8503 Prevent console commands to be executed if DB is not up-to-date
  inc/console/abstractcommand.class.php
  inc/console/application.class.php
  inc/console/command/glpicommandinterface.class.php
  inc/console/database/abstractconfigurecommand.class.php
  inc/console/database/updatecommand.class.php
  inc/console/maintenance/disablemaintenancemodecommand.class.php
  inc/console/maintenance/enablemaintenancemodecommand.class.php
  inc/console/system/clearcachecommand.class.php
Labels: enhancement

#8509 Init active tab on display
  inc/commonglpi.class.php
Labels: bug

#8538 Fix default entity in CommonDBRelation
  inc/commondbrelation.class.php
  inc/session.class.php
Labels: bug

#8540 Remove sensiolabs/security-checker
  .github/workflows/ci.yml
  composer.json
  composer.lock
Labels: dependencies

#8539 keep only a subsert of ticket's rights when swithcing profile to selfservice
  inc/profile.class.php
  tests/functionnal/Profile.php
Labels: bug

#8452 Added add_default_join plugin hook
  inc/search.class.php
Labels: need_doc_improvement

#8546 Dashboards: fix graph counts
  inc/dashboard/dashboard.class.php
  inc/dashboard/filter.class.php
  inc/dashboard/provider.class.php
  inc/stat.class.php
Labels: bug

#8559 make notification email/name from entity inheritables
  css/styles.scss
  inc/entity.class.php
  inc/notification.class.php
  inc/notificationtarget.class.php
  tests/bootstrap.php
  tests/functionnal/Entity.php
  tests/functionnal/Notification.php
  tests/functionnal/NotificationTarget.php
Labels: enhancement

#8569 Fixed custom css from entity inheritables
  inc/entity.class.php
  tests/functionnal/Entity.php
Labels: bug

#8496 Async sending of ITIL objects notifications
  CHANGELOG.md
  inc/commondbtm.class.php
  inc/commonitilobject.class.php
  inc/queuednotification.class.php
  tests/functionnal/NotificationEventAjax.php
  tests/functionnal/QueuedNotification.php
Labels: enhancement

#8582 Fix tickets ID fetching from email headers
  inc/mailcollector.class.php
  inc/notificationtarget.class.php
  tests/bootstrap.php
  tests/emails-tests/04-ticket-followup.eml
  tests/emails-tests/04.1-ticket-followup-from-inreplyto.eml
  tests/emails-tests/04.2-ticket-followup-from-references.eml
  tests/emails-tests/04.3-ticket-followup-from-subject.eml
  tests/emails-tests/22-notification-from-glpi.eml
  tests/imap/MailCollector.php
Labels: bug

#3957 Ensure In-Reply-To mail header is unique accross instances
  CHANGELOG.md
  inc/mailcollector.class.php
  inc/notificationeventmailing.class.php
  inc/notificationtarget.class.php
  inc/notificationtargetticket.class.php
  tests/emails-tests/04.1-ticket-followup-from-oldformat-inreplyto.eml
  tests/emails-tests/04.2-ticket-followup-from-oldformat-references.eml
  tests/emails-tests/04.4-ticket-followup-from-newformat-inreplyto.eml
  tests/emails-tests/04.5-ticket-followup-from-newformat-references.eml
  tests/emails-tests/22.1-notification-from-glpi-old-messageid-format.eml
  tests/emails-tests/22.2-notification-from-glpi-new-messageid-format.eml
  tests/emails-tests/23-uuid-from-another-glpi.eml
  tests/imap/MailCollector.php
Labels: help wanted

#8583 Add appliances search options from item
  inc/appliance.class.php
  inc/search.class.php
Labels: enhancement
