Repository glpi-project/glpi, pull requests merged in 2021-05, with the labels that each got.

#8763 Fix XSS clean/unclean process
  inc/mailcollector.class.php
  inc/toolbox.class.php
  tests/functionnal/ITILFollowup.php
  tests/functionnal/ITILSolution.php
  tests/functionnal/KnowbaseItem.php
  tests/functionnal/Ticket.php
  tests/imap/MailCollector.php
  tests/units/Toolbox.php
Labels: bug

#9047 Use correct infocom data for softwares searchoptions
  inc/infocom.class.php
Labels: bug

#9052 Add new 'validation' criteria to tickets rules
  inc/rule.class.php
  inc/ruleticket.class.php
  tests/functionnal/RuleTicket.php
Labels: enhancement

#9022 Copy names to clipboard
  css/styles.scss
  inc/dropdown.class.php
  inc/html.class.php
  inc/search.class.php
  js/common.js
  tests/functionnal/Search.php
Labels: enhancement

#9053 Prevent console error when a plugin is installed twice
  inc/console/commandloader.class.php
Labels: bug

#9057 Remove useless laminas cache adapters
  composer.json
  composer.lock
Labels: dependencies

#9060 Anonymized helpdesk: add nicknames
  inc/commonitilobject.class.php
  inc/entity.class.php
  inc/group.class.php
  inc/notificationtargetcommonitilobject.class.php
  inc/search.class.php
  inc/ticket.class.php
  inc/user.class.php
  install/migrations/update_9.5.x_to_10.0.0/nicknames.php
  install/mysql/glpi-empty.sql
  tests/functionnal/Entity.php
Labels: enhancement

#9077 Drop deprecated code
  inc/commonitilobject.class.php
  inc/commonitiltask.class.php
  inc/itilfollowup.class.php
Labels: task

#9071 Ticket rules: add 'global_valdiation' action
  inc/rule.class.php
  inc/ruleaction.class.php
  inc/ruleticket.class.php
  tests/functionnal/Rule.php
  tests/functionnal/RuleTicket.php
Labels: enhancement

#9085 Fix images handling in dropdown and massive actions
  inc/commondbtm.class.php
  inc/commondropdown.class.php
  inc/html.class.php
  inc/itilfollowuptemplate.class.php
  inc/solutiontemplate.class.php
  inc/ticket.class.php
Labels: bug

#9066 Add infocom search options to DC assets
  inc/define.php
  inc/enclosure.class.php
  inc/migration.class.php
  inc/passivedcequipment.class.php
  inc/pdu.class.php
  inc/rack.class.php
  inc/update.class.php
  install/update_955_956.php
  tests/units/Migration.php
Labels: enhancement

#9067 fix(stat): get real web dir for plugin stats
  inc/stat.class.php
Labels: bug

#9088 Fix planning timezone
  inc/planning.class.php
Labels: bug

#9096 Add WiFi ac and ax versions
  inc/wifinetwork.class.php
Labels: enhancement

#9097 fix(core): always restore default language
  inc/notificationtemplate.class.php
  inc/notificationtemplatetranslation.class.php
Labels: bug

#8947 Add link between Contrat and Tickets
  front/ticket_contract.form.php
  inc/commonitilobject.class.php
  inc/commonitilobject_item.class.php
  inc/contract.class.php
  inc/dropdown.class.php
  inc/entity.class.php
  inc/ruleticket.class.php
  inc/ticket.class.php
  inc/ticket_contract.class.php
  inc/tickettemplate.class.php
  install/empty_data.php
  install/migrations/update_9.5.x_to_10.0.0/ticket_contract.php
  install/mysql/glpi-empty.sql
  tests/functionnal/Entity.php
  tests/functionnal/ITILTemplate.php
  tests/functionnal/MassiveAction.php
  tests/functionnal/RuleTicket.php
Labels: enhancement
