Repository glpi-project/glpi, pull requests merged in 2021-06, with the labels that each got.

#9065 Try fix BC for external links with domains
  inc/link.class.php
Labels: bug

#9129 Replace deprecated usages from wapmorgan\UnifiedArchive
  inc/marketplace/controller.class.php
Labels: dependencies

#9130 feat(dashboard): add missing solved state
  inc/dashboard/provider.class.php
Labels: enhancement

#8706 Pending reasons
  ajax/pendingreason.php
  css/styles.scss
  front/pendingreason.form.php
  front/pendingreason.php
  inc/change.class.php
  inc/commondbtm.class.php
  inc/commonitilobject.class.php
  inc/commonitiltask.class.php
  inc/dropdown.class.php
  inc/itilfollowup.class.php
  inc/itilsolution.class.php
  inc/pendingreason.class.php
  inc/pendingreason_item.class.php
  inc/pendingreasoncron.class.php
  inc/problem.class.php
  inc/profile.class.php
  inc/ticket.class.php
  inc/user.class.php
  install/empty_data.php
  install/migrations/update_9.5.x_to_10.0.0/pendingreason.php
  install/mysql/glpi-empty.sql
  tests/functionnal/PendingReason.class.php
  tests/functionnal/Search.php
  tests/functionnal/Ticket.php
  tests/functionnal/Transfer.php
Labels: enhancement

#9132 Fix dbversion when migration from < 9.2 fails
  install/update_91_92.php
Labels: bug

#9135 Do not filter unavailable plugins in marketplace
  css/marketplace.scss
  inc/marketplace/api/plugins.class.php
  inc/marketplace/controller.class.php
  inc/marketplace/view.class.php
Labels: enhancement

#9140 correct typo
  inc/commonitilobject.class.php
  inc/ticket.class.php
Labels: bug

#9155 Don't redirect to AJAX URLs
  inc/html.class.php
Labels: bug

#9145 Anonymize observers if they have at least one 'central' profile
  inc/itilfollowup.class.php
  tests/functionnal/ITILFollowup.php
Labels: bug

#9163 Use correct entity when splitting tickets
  inc/ticket.class.php
Labels: bug

#9154 Support larger impact graphs
  CHANGELOG.md
  inc/migration.class.php
  inc/system/diagnostic/databaseschemachecker.class.php
  install/migrations/update_9.5.x_to_10.0.0/impact.php
  install/mysql/glpi-empty.sql
  tests/units/Glpi/System/Diagnostic/DatabaseSchemaChecker.php
  tests/units/Migration.php
Labels: enhancement

#9164 add action button in user synchronization tab to clear ldap sync field
  front/user.form.php
  inc/auth.class.php
  inc/authldap.class.php
  inc/user.class.php
  tests/LDAP/AuthLdap.php
Labels: enhancement

#9171 Add ITILObject actor HATEOAS classes
  inc/api/api.class.php
Labels: enhancement

#9131 fix(display): fix display number of days
  inc/commondbtm.class.php
  inc/dropdown.class.php
  inc/search.class.php
  tests/functionnal/Dropdown.php
Labels: bug

#9063 Rule action appliance
  inc/ruleticket.class.php
  inc/ticket.class.php
  tests/functionnal/Rule.php
  tests/functionnal/RuleTicket.php
Labels: enhancement

#9170 Add 'Myself' search criteria
  ajax/searchoptionvalue.php
  inc/dashboard/filter.class.php
  inc/dashboard/provider.class.php
  inc/dbutils.class.php
  inc/dropdown.class.php
  inc/search.class.php
  inc/user.class.php
  tests/functionnal/Search.php
Labels: enhancement

#9181 Filter service and change format in HTTP Status endpoint
  status.php
Labels: enhancement

#9209 Transfer: fix 'keep_software' option
  inc/transfer.class.php
  tests/functionnal/Computer.php
  tests/functionnal/Transfer.php
Labels: bug

#9210 Fix fields consistency on add/update
  inc/commondbtm.class.php
  inc/computer.class.php
  tests/functionnal/CommonDBTM.php
  tests/functionnal/ITILSolution.php
  tests/functionnal/ProjectTask.php
  tests/functionnal/TicketTask.php
  tests/units/Migration.php
Labels: bug

#9200 Fix inconsistency on date fields and add index on name fields
  .github/actions/test_install.sh
  .github/actions/test_update-from-9.5.sh
  .github/actions/test_update-from-older-version.sh
  CHANGELOG.md
  inc/console/database/checkschemaintegritycommand.class.php
  inc/inventory/asset/printer.class.php
  inc/knowbaseitem.class.php
  inc/knowbaseitem_revision.class.php
  inc/networkport.class.php
  inc/networkport_networkport.class.php
  inc/networkportconnectionlog.class.php
  inc/networkportmetrics.class.php
  inc/notepad.class.php
  inc/notificationtargetobjectlock.class.php
  inc/objectlock.class.php
  inc/printerlog.class.php
  inc/project.class.php
  inc/projecttask.class.php
  inc/system/diagnostic/abstractdatabasechecker.class.php
  inc/system/diagnostic/databasekeyschecker.class.php
  inc/system/diagnostic/databaseschemaconsistencychecker.class.php
  inc/system/diagnostic/databaseschemaintegritychecker.class.php
  inc/transfer.class.php
  install/migrations/update_9.5.x_to_10.0.0/native_inventory.php
  install/migrations/update_9.5.x_to_10.0.0/schema_fixes.php
  install/mysql/glpi-empty.sql
  tests/functionnal/DbUtils.php
  tests/functionnal/Glpi/CalDAV/Server.php
  tests/functionnal/Glpi/Inventory/Assets/Printer.php
  tests/functionnal/NetworkPortMetrics.php
  tests/functionnal/PrinterLog.php
  tests/units/Glpi/System/Diagnostic/DatabaseKeysChecker.php
  tests/units/Glpi/System/Diagnostic/DatabaseSchemaConsistencyChecker.php
  tests/units/Glpi/System/Diagnostic/DatabaseSchemaDiffChecker.php
  tools/checkdatabasekeyscommand.class.php
  tools/checkdatabaseschemaconsistencycommand.class.php
  tools/fake_metrics.php
Labels: task
