Repository glpi-project/glpi, pull requests merged in 2022-06, with the labels that each got.

#11738 Hide empty cards on self-service homepage
  templates/components/masonry_grid.html.twig
  templates/pages/self-service/home.html.twig
Labels: bug

#11731 Force api init endpoint
  src/Api/API.php
  src/Api/APIRest.php
  src/Api/APIXmlrpc.php
Labels: api

#11777 Do not set assigned status on invalid itemtypes
  src/CommonITILObject.php
  tests/functionnal/Change.php
  tests/functionnal/ITILSolution.php
Labels: bug

#11784 Handle translator exceptions
  front/locale.php
  inc/autoload.function.php
Labels: bug

#11789 delete ticket button may show when no right to delete
  templates/components/itilobject/footer.html.twig
Labels: bug

#11790 Add plugin activate and deactivate hooks handling
  src/Plugin.php
Labels: enhancement

#11729 Fix config:set command for inventory context
  src/Console/Config/SetCommand.php
  src/Inventory/Conf.php
Labels: bug

#11781 Paginate cartridge lists
  src/Cartridge.php
Labels: enhancement, performance

#11825 Move post_item hook before self service buttons
  templates/components/itilobject/selfservice.html.twig
Labels: bug

#11806 fix(ldap): force delete policy to be applied
  src/User.php
Labels: bug

#11815 Fix add column button tag and role
  js/modules/Kanban/Kanban.js
Labels: bug

#11848 Dictionaries: fix assign category action
  src/Inventory/Asset/Software.php
Labels: bug

#11832 Ability to choose TLS version in LDAP transactions
  install/migrations/update_10.0.x_to_10.1.0/tls_version.php
  install/mysql/glpi-10.1.0-empty.sql
  src/Auth.php
  src/AuthLDAP.php
Labels: enhancement

#11817 Fix HTML head when bypassing updates
  inc/config.php
  templates/layout/parts/page_header.html.twig
  templates/layout/parts/page_header_empty.html.twig
Labels: bug

#11829 fix(check all): on footer not work
  js/common.js
  src/Html.php
  templates/components/search/table.html.twig
Labels: bug

#11850 check existence of field before acessing it
  src/NotificationTarget.php
Labels: bug

#11854 Cleanup ITIL Object Kanban closed column warning
  css/includes/components/_kanban.scss
  js/modules/Kanban/Kanban.js
Labels: ux

#11831 [GLPI 10.0 Bugfixes] Fix load Templates for Plugins
  src/ContentTemplates/Parameters/TicketParameters.php
Labels: bug

#11650 Add more control over Marketplace availability
  .composer-require-checker.config.json
  front/marketplace.download.php
  front/marketplace.php
  inc/based_config.php
  src/Console/Marketplace/DownloadCommand.php
  src/Console/Marketplace/InfoCommand.php
  src/Console/Marketplace/SearchCommand.php
  src/Marketplace/Controller.php
  src/Marketplace/View.php
  src/Plugin.php
Labels: enhancement

#11841 Fix multiple issues with Inventory code and PHPDoc
  src/Inventory/Asset/Antivirus.php
  src/Inventory/Asset/Camera.php
  src/Inventory/Asset/Cartridge.php
  src/Inventory/Asset/Device.php
  src/Inventory/Asset/Drive.php
  src/Inventory/Asset/InventoryAsset.php
  src/Inventory/Asset/InventoryNetworkPort.php
  src/Inventory/Asset/MainAsset.php
  src/Inventory/Asset/Monitor.php
  src/Inventory/Asset/NetworkEquipment.php
  src/Inventory/Asset/NetworkPort.php
  src/Inventory/Asset/Peripheral.php
  src/Inventory/Asset/Printer.php
  src/Inventory/Asset/RemoteManagement.php
  src/Inventory/Asset/Software.php
  src/Inventory/Asset/VirtualMachine.php
  src/Inventory/Asset/Volume.php
  src/Inventory/Conf.php
  src/Inventory/Inventory.php
  src/Inventory/Request.php
Labels: bug

#11855 Add Time to resolve to Change Template
  src/ChangeTemplate.php
  tests/functionnal/ITILTemplate.php
Labels: enhancement

#11837 get the correct entity in conf when populating softwares
  src/Inventory/Asset/InventoryAsset.php
  src/Inventory/Asset/Software.php
  tests/functionnal/Glpi/Inventory/Assets/Software.php
Labels: bug

#11880 Handle bad return for timeline_answer_actions hook
  src/CommonITILObject.php
Labels: bug, need_doc_improvement

#11872 Templates: Fix name display
  templates/components/form/header.html.twig
Labels: ux

#11887 Fix 'Entity for software creation' field handling
  src/Entity.php
Labels: bug

#11808 fix(ticket task): availability not displayed
  ajax/planningcheck.php
  src/Planning.php
  templates/components/itilobject/timeline/form_task.html.twig
Labels: bug

#11894 Self-service: load tinymce on ticket page
  inc/define.php
Labels: bug

#11906 Self-service: add missing breadcrumbs
  front/helpdesk.faq.php
  front/helpdesk.public.php
  front/reservationitem.php
  inc/define.php
Labels: bug

#11912 API: fix default ranges
  apirest.md
  src/Api/API.php
Labels: bug

#11715 Asset rules: add last inventory update criteria
  src/CommonDBTM.php
  src/Rule.php
  src/RuleAsset.php
  src/RuleCriteria.php
  tests/functionnal/RuleAsset.php
  tests/functionnal/RuleCriteria.php
Labels: bug, enhancement

#11892 Faq: fix categories form
  src/Dropdown.php
  src/KnowbaseItem.php
  src/KnowbaseItem_KnowbaseItemCategory.php
  tests/DbTestCase.php
  tests/functionnal/KnowbaseItem.php
Labels: bug

#11932 Fix RSS URL handling
  src/RSSFeed.php
Labels: bug

#11931 Fix alarm threshold value in notifications
  src/Cartridge.php
  src/Consumable.php
Labels: bug

#11910 Fix saving cards with transparency
  src/Dashboard/Grid.php
  templates/components/form/fields_macros.html.twig
Labels: bug

#11939 Surround number input attributes values by quotes
  templates/components/form/fields_macros.html.twig
Labels: bug

#11813 Add missing default recurring change rights
  install/empty_data.php
  install/migrations/update_9.5.x_to_10.0.0/recurrentchange.php
Labels: bug

#11943 feat(rule): add itemtype to RuleImportEntity
  src/RuleImportEntity.php
Labels: enhancement

#11946 fix warning null value when call dropdown of computers
  src/Dropdown.php
Labels: bug

#11926 Feature/global
  install/empty_data.php
  install/migrations/update_10.0.1_to_10.0.2/.gitkeep
  install/migrations/update_10.0.1_to_10.0.2/configs.php
  src/CommonDBTM.php
  src/Computer_Item.php
  src/Config.php
  src/Inventory/Asset/InventoryAsset.php
  src/Inventory/Asset/Monitor.php
  src/Inventory/Asset/Peripheral.php
  src/Inventory/Asset/Printer.php
  src/Inventory/Conf.php
  tests/functionnal/Glpi/Inventory/Assets/Monitor.php
  tests/functionnal/Glpi/Inventory/Assets/Peripheral.php
  tests/functionnal/Glpi/Inventory/Assets/Printer.php
Labels: enhancement

#11960 fix(search): correctly display linked item
  install/empty_data.php
  install/migrations/update_10.0.1_to_10.0.2/agent.php
  src/Agent.php
Labels: bug

#11964 Set inventory isDiscovery status before calling hook
  src/Inventory/Request.php
Labels: bug

#11651 Associate Users from Profile form
  src/Profile_User.php
Labels: enhancement

#11989 Rely on mserial if serial is wrong
  src/Blacklist.php
  src/Inventory/Asset/MainAsset.php
  tests/functionnal/Glpi/Inventory/Assets/Computer.php
Labels: Need unit tests

#11991 fix(change): invalid status when reopening change
  src/ITILFollowup.php
Labels: bug

#11997 fix(so): add missing SO
  src/NetworkEquipment.php
  src/Phone.php
  src/Printer.php
Labels: enhancement

#12001 Improve Kanban performance
  src/CommonITILObject.php
  src/Project.php
Labels: performance

#11996 Add access error log
  src/CommonDBTM.php
  src/Html.php
  src/Session.php
Labels: enhancement

#11698 Add massive actions for reservations
  src/MassiveAction.php
  src/Reservation.php
  src/ReservationItem.php
  tests/functionnal/MassiveAction.php
  tests/web/APIRest.php
Labels: enhancement

#11984 allow plugins to check their DB integrity
  src/Console/Database/CheckSchemaIntegrityCommand.php
Labels: enhancement

#12013 fix(inventory): reload updated item anyway
  src/Inventory/Asset/MainAsset.php
Labels: bug, enhancement

#11928 Groups: fix user list (no entities restrictions)
  src/Group_User.php
Labels: bug

#11978 add processes list
  css/includes/components/_datatable.scss
  css/legacy/includes/_styles.scss
  install/migrations/update_10.0.x_to_10.1.0/processes.php
  install/mysql/glpi-10.1.0-empty.sql
  js/log_filters.js
  src/Computer.php
  src/Inventory/Asset/Process.php
  src/Inventory/Conf.php
  src/Inventory/Inventory.php
  src/Item_Process.php
  src/Item_SoftwareVersion.php
  src/Phone.php
  templates/components/datatable.html.twig
  templates/components/logs.html.twig
  tests/functionnal/Glpi/Inventory/Assets/Process.php
Labels: enhancement

#12030 DisplayPrefs: Fix fixed columns
  src/DisplayPreference.php
Labels: bug
