Repository glpi-project/glpi, pull requests merged in 2022-02, with the labels that each got.

#10460 Fix decimal dropdown
  inc/dropdown.class.php
  inc/toolbox.class.php
  tests/functionnal/Dropdown.php
  tests/units/Toolbox.php
Labels: bug

#10519 Fix antivirus creation
  src/ComputerAntivirus.php
Labels: bug

#10163 Browse items by category
  ajax/search.php
  ajax/treebrowse.php
  css/includes/_includes.scss
  css/includes/components/_browser_tree.scss
  css/legacy/includes/_styles.scss
  lib/bundles/base.js
  src/Document.php
  src/Features/TreeBrowse.php
  src/Knowbase.php
  src/Search.php
  src/Software.php
  src/User.php
  templates/components/search/controls.html.twig
  templates/components/search/display_data.html.twig
  tests/functionnal/Search.php
Labels: enhancement

#10457 feat(database): add missing SO
  src/Database.php
Labels: wip

#10527 Fix commondropdown headers
  front/dropdown.common.form.php
Labels: bug

#10584 Show only ongoing problems for "Link to a problem" massive action
  src/Ticket.php
Labels: bug

#10607 Fix edit saved search icon color
  css/legacy/includes/_styles.scss
Labels: bug

#10606 fix(UI): get timeline position from parent
  src/CommonDBTM.php
Labels: bug

#10623 Allow usage of npm v7
  package-lock.json
  package.json
Labels: dependencies

#10660 Fix default visibility value in group creation form; see #10582
  src/Group.php
Labels: bug

#10724 Fix spelling error (private dashboards)
  src/Dashboard/Grid.php
Labels: bug

#10725 Automatically check for Github Actions dependencies updates
  .github/dependabot.yml
Labels: dependencies

#10668 Fix "Undefined array key" when attribute does not exist in LDAP
  src/AuthLDAP.php
Labels: bug

#10692 Add prefix to tickets number
  src/CommonITILObject.php
Labels: ux

#10717 Use direct query for createLinkTable
  src/Migration.php
Labels: bug

#10723 Fix/Improve AbstractRightsDropdown
  src/AbstractRightsDropdown.php
  src/Dashboard/Grid.php
Labels: bug

#10703 Replace outdated leaflet-osm-geocoder by leaflet-control-geocoder
  css/legacy/includes/_styles.scss
  lib/bundles/leaflet.js
  lib/leaflet/plugins/leaflet-control-osm-geocoder/Control.OSMGeocoder.css
  lib/leaflet/plugins/leaflet-control-osm-geocoder/Control.OSMGeocoder.js
  lib/leaflet/plugins/leaflet-control-osm-geocoder/LICENSE
  lib/leaflet/plugins/leaflet-control-osm-geocoder/images/geocoder.png
  package-lock.json
  package.json
  src/MapGeolocation.php
Labels: dependencies

#10764 self-service cannot switch entity anymore
  front/central.php
Labels: bug

#10762 Fix domains entity filtering on domains alerts
  inc/domain.class.php
  tests/functionnal/Domain.php
Labels: bug

#10554 Add Database Plugin Migration Script
  src/Console/AbstractCommand.php
  src/Console/Migration/AbstractPluginToCoreCommand.php
  src/Console/Migration/DatabasesPluginToCoreCommand.php
Labels: enhancement

#10707 Fix clone name uniqueness
  inc/commondbtm.class.php
  inc/massiveaction.class.php
  inc/rule.class.php
  inc/user.class.php
  tests/functionnal/Appliance.php
  tests/functionnal/Certificate.php
  tests/functionnal/Computer.php
  tests/functionnal/Entity.php
  tests/functionnal/Monitor.php
  tests/functionnal/NetworkPort.php
  tests/functionnal/Project.php
  tests/functionnal/Rule.php
  tests/functionnal/RuleSoftwareCategory.php
  tests/functionnal/Software.php
  tests/functionnal/Ticket.php
  tests/functionnal/User.php
Labels: bug

#10782 AbstractRightDropdown value parsing in front files
  src/AbstractRightsDropdown.php
  tests/units/AbstractRightsDropdown.php
Labels: enhancement

#10791 Decrease Kanban team member padding
  templates/components/kanban/item_panels/default_panel.html.twig
Labels: ux
