Repository glpi-project/glpi, pull requests merged in 2022-04, with the labels that each got.

#11151 Prevent memory issues on archives handling in marketplace
  src/Marketplace/Controller.php
Labels: bug

#11169 add some hidden features to network ports display
  css/includes/_includes.scss
  css/includes/components/_networkport.scss
  css/legacy/includes/_styles.scss
  src/NetworkPort.php
  src/Plugin/Hooks.php
Labels: enhancement

#11172 Fix SearchInput overflow
  js/modules/SearchTokenizer/SearchInput.js
Labels: bug, ux

#11189 Hide add button when ticket link started
  templates/components/itilobject/linked_tickets.html.twig
Labels: ux

#11179 fix(search): do not compute link (and / or) if statement is having
  src/Search.php
Labels: bug

#11180 Marketplace CLI commands
  src/Console/Marketplace/DownloadCommand.php
  src/Console/Marketplace/InfoCommand.php
  src/Console/Marketplace/SearchCommand.php
  src/Marketplace/Controller.php
Labels: enhancement

#11209 Fix encoding of completename in logs
  inc/dropdown.class.php
  inc/log.class.php
Labels: bug

#11211 Fix some buggy/useless usages of stripslashes
  ajax/dropdownNotificationEvent.php
  ajax/dropdownValidator.php
  ajax/impact.php
  ajax/ruleactionvalue.php
  front/knowbaseitem.php
  src/Auth.php
  src/Event.php
  src/Item_Ticket.php
  src/Log.php
  src/Search.php
  src/Toolbox.php
  tests/DbTestCase.php
  tests/functionnal/Toolbox.php
Labels: bug

#11194 Add supplier on add_actor massive action & is_active to post_getEmpty
  ajax/dropdownMassiveActionAddActor.php
  src/Supplier.php
Labels: enhancement

#11227 Drop unmaintained webmozart/path-util dev dependency
  composer.lock
Labels: dependencies

#11234 Add Writer to RuleTicket Criteria
  src/RuleTicket.php
Labels: enhancement

#11230 Fix completename encoding issues
  src/CommonTreeDropdown.php
  src/DbUtils.php
  src/Dropdown.php
  src/Log.php
  tests/functionnal/CommonTreeDropdown.php
Labels: bug

#11006 Group approval requests
  CHANGELOG.md
  ajax/dropdownMassiveActionAddValidator.php
  ajax/dropdownValidator.php
  front/commonitilvalidation.form.php
  install/empty_data.php
  install/migrations/update_10.0.x_to_10.1.0/validations.php
  install/mysql/glpi-empty.sql
  src/Ajax.php
  src/Change.php
  src/CommonITILObject.php
  src/CommonITILValidation.php
  src/Dashboard/Provider.php
  src/Notification.php
  src/NotificationTargetChange.php
  src/NotificationTargetCommonITILObject.php
  src/NotificationTargetTicket.php
  src/Problem.php
  src/RuleTicket.php
  src/Search.php
  src/Ticket.php
  templates/components/itilobject/fields/global_validation.html.twig
  templates/components/itilobject/timeline/form_validation.html.twig
  templates/components/itilobject/timeline/timeline_item_header.html.twig
  templates/components/itilobject/timeline/timeline_item_header_badges.html.twig
  tests/functionnal/ChangeValidation.php
  tests/functionnal/CommonITILValidation.php
  tests/functionnal/Glpi/RichText/UserMention.php
  tests/functionnal/Rule.php
  tests/functionnal/Ticket.php
  tests/functionnal/TicketValidation.php
  tests/src/CommonITILValidation.php
Labels: enhancement, need_doc_improvement

#11277 fix(certificate/domain): delete alert after date_expiration update
  src/Certificate.php
  src/CommonDBTM.php
  src/Domain.php
Labels: bug

#11291 Enhance errors handling on update
  config/_config_db.php
  install/install.php
  src/Console/Database/UpdateCommand.php
  src/DBConnection.php
  src/Update.php
  templates/install/update.invalid_database.html.twig
Labels: bug

#11276 Fix approval request handling in Change creation form
  src/Application/View/Extension/PhpExtension.php
  src/CommonITILObject.php
  src/Ticket.php
  templates/components/itilobject/fields/global_validation.html.twig
Labels: bug

#11307 Hide versions in front-end assets URL
  src/Application/View/Extension/FrontEndAssetsExtension.php
  src/Html.php
  src/Toolbox/FrontEnd.php
  tests/units/Glpi/Toolbox/FrontEnd.php
  tests/units/Html.php
Labels: enhancement

#11225 Replace usage of negative values in SLM/SLA/OLA calendars_id fields
  CHANGELOG.md
  install/migrations/update_9.5.x_to_10.0.0/slm.php
  install/mysql/glpi-empty.sql
  src/LevelAgreement.php
  src/SLM.php
  src/Ticket.php
Labels: bug

#11263 Fix menu links from helpdesk_menu_entry hook
  src/Html.php
Labels: bug

#11313 Fix dashboard animated number ending with wrong values
  js/dashboard.js
Labels: bug

#11321 fix display of user's responsible column
  src/Search.php
  src/User.php
Labels: bug

#11328 no requester when a ticket created by self-service
  templates/components/itilobject/selfservice.html.twig
Labels: bug

#11330 Fix truncated DOUBLE warning for new LDAP server
  src/AuthLDAP.php
Labels: bug

#11333 Add missing glpi_slas.calendars_id field
  install/migrations/update_9.5.x_to_10.0.0/slm.php
Labels: bug

#11335 Fix group central view
  ajax/central.php
  src/Central.php
Labels: bug

#11327 requester cannot reopen ticket with followup anymore
  src/CommonITILObject.php
  templates/components/itilobject/footer.html.twig
  templates/components/itilobject/timeline/form_followup.html.twig
  tests/functionnal/Ticket.php
Labels: bug

#11336 Dashboard filters: under category
  src/Dashboard/Provider.php
Labels: bug

#11337 Fix plugin commands result codes on failure
  src/Console/Plugin/ActivateCommand.php
  src/Console/Plugin/DeactivateCommand.php
  src/Console/Plugin/InstallCommand.php
Labels: bug

#11352 Prevent incompatibility with ext-psr
  composer.json
  composer.lock
Labels: bug, dependencies

#11364 Hide 'Add document' button in timeline
  src/CommonITILObject.php
Labels: bug

#11353 Move symfony/css-selector in production dependencies
  composer.json
  composer.lock
  src/Config.php
Labels: bug, dependencies

#11354 in followup form, content is not marked as required when needed
  templates/components/itilobject/timeline/form_followup.html.twig
Labels: bug

#11372 Re-add category dropdown to new KB item form
  src/KnowbaseItem.php
  tests/functionnal/KnowbaseItem.php
Labels: bug

#11138 Allow limiting available statuses in ITIL Templates
  inc/relation.constant.php
  install/migrations/update_10.0.x_to_10.1.0/itilobject_templates.php
  install/mysql/glpi-empty.sql
  src/CommonITILObject.php
  src/ITILTemplate.php
  templates/components/itilobject/fields/status.html.twig
  templates/components/itilobject/itiltemplate.html.twig
  templates/dropdown_form.html.twig
Labels: enhancement, need_doc_improvement

#11388 Fix lockedfields display
  css/legacy/includes/_styles.scss
  src/CommonGLPI.php
Labels: bug, enhancement

#11363 Do not send 'new actor' notifications on ticket creation
  src/CommonITILObject.php
Labels: bug

#10824 Add new right for assigning service levels
  install/empty_data.php
  install/migrations/update_10.0.x_to_10.1.0/slm.php
  src/SLM.php
  src/Ticket.php
  templates/components/itilobject/service_levels.html.twig
  tests/functionnal/Ticket.php
Labels: enhancement, need_doc_improvement

#11412 fix some firefox mobile issues with timeline
  css/includes/components/itilobject/_footer.scss
  css/includes/components/itilobject/_layout.scss
  templates/components/itilobject/fields_panel.html.twig
  templates/components/itilobject/timeline/timeline.html.twig
Labels: bug

#11394 Fix status update on actors assign
  src/CommonITILObject.php
Labels: bug

#11430 Upgrade TinyMCE to 6.x
  lib/bundles/tinymce.js
  package-lock.json
  package.json
  src/Html.php
Labels: dependencies
