Repository glpi-project/glpi, pull requests merged in 2022-07, with the labels that each got.

#12057 Fix magic MassiveAction::__set() method
  src/MassiveAction.php
Labels: bug

#12047 9.5.7 migration: Remove duplicated items_os before adding unicity
  install/migrations/update_9.5.6_to_9.5.7.php
Labels: bug

#12069 Preserve in_modal tracking in form submissions
  templates/components/form/header.html.twig
Labels: bug

#12052 Fix global search
  src/Search.php
Labels: bug, ux

#12049 fix: is_recursive
  templates/components/form/header.html.twig
Labels: bug

#12073 fix(itiltask): empty date
  src/CommonITILTask.php
Labels: bug

#12072 fix(ux): fix combox empty choice width
  src/Dropdown.php
Labels: bug, ux

#11423 Replace phpmailer with Symfony/Mailer (Swiftmailer)
  CHANGELOG.md
  composer.json
  composer.lock
  inc/define.php
  install/migrations/update_10.0.x_to_10.1.0/mailer.php
  src/Config.php
  src/GLPIMailer.php
  src/MailCollector.php
  src/NotificationEventMailing.php
  src/NotificationMailing.php
  src/NotificationMailingSetting.php
  tests/functionnal/Config.php
  tests/units/GLPIMailer.php
Labels: enhancement, dependencies

#12068 Fix LDAP group import options
  src/AuthLDAP.php
  src/Html.php
Labels: bug

#12070 Add pager to bottom of software installation list
  src/Item_SoftwareVersion.php
Labels: ux

#12058 avoid to return to default sort when we have only one column sorted
  js/modules/Search/Table.js
Labels: bug

#12117 Fix extra CSS fetching from TinyMCE
  src/Html.php
Labels: performance

#12133 Fix is_glpi_class check
  src/DbUtils.php
Labels: bug

#12129 Fix selected tech in ITILCategory form
  templates/dropdown_form.html.twig
Labels: bug

#12132 fix(inventory): allow network managment on create
  src/Inventory/Asset/MainAsset.php
Labels: bug

#12130 Fix auto-assign from category/item
  src/CommonITILObject.php
  tests/functionnal/Ticket.php
Labels: bug

#12144 Fix autolink
  src/RichText/RichText.php
Labels: bug

#12146 fix(inventory): format date if needed
  src/Inventory/Asset/Device.php
Labels: bug

#12150 Fix missing 'glpi_refusedequipments.autoupdatesystems_id' key
  CHANGELOG.md
  inc/define.php
  install/migrations/update_10.0.2_to_10.0.3.php
  install/migrations/update_10.0.2_to_10.0.3/schema_fixes.php
  install/migrations/update_9.5.x_to_10.0.0/native_inventory.php
  install/mysql/glpi-10.0.3-empty.sql
  src/Toolbox.php
  src/Update.php
  tests/functionnal/Update.php
Labels: bug

#12151 Ticket validation: restrict auto scroll
  src/CommonITILValidation.php
  templates/components/itilobject/timeline/form_validation.html.twig
Labels: bug

#12158 Fix Global Stats datas
  src/Stat/Data/Sglobal/StatDataTicketAverageTime.php
  src/Stat/Data/Sglobal/StatDataTicketNumber.php
Labels: bug

#12159 Adding MeshCentral capability.
  src/Item_RemoteManagement.php
Labels: enhancement

#12164 Fix missing no status column
  src/Project.php
Labels: bug

#12123 Fix impact labels in dark themes
  js/impact.js
Labels: ux

#12171 fix(search): do not display managmement port from list (NetworkPortAggregate)
  src/NetworkName.php
  src/NetworkPort.php
Labels: enhancement

#12143 Fix display of allowed statuses for new ITIL Objects
  src/CommonITILObject.php
Labels: bug

#12176 fix(search): prevent error for ambigous column
  src/NetworkPort.php
Labels: bug

#12186 Fix duplicate click handlers for Kanban team management
  js/modules/Kanban/Kanban.js
Labels: bug

#12192 Clean unwanted tags in collected email
  src/MailCollector.php
  src/Toolbox.php
  tests/emails-tests/33-html-with-unwanted-tags-inside-body.eml
  tests/imap/MailCollector.php
Labels: bug

#12191 Dashboard: fix 'myself' search criteria in generated URLs
  src/Dashboard/Provider.php
Labels: bug

#12194 feat(ui): hide global search if needed
  templates/layout/parts/page_header.html.twig
Labels: enhancement

#12198 revert(commit): revert fix for duplicate IP / MAC
  src/NetworkName.php
  src/NetworkPort.php
Labels: bug

#12183 fix(ticket): fix dropdown item ticket entity scope
  src/Item_Ticket.php
Labels: bug

#12039 fix(notif template): alert tickets not closed
  install/empty_data.php
Labels: bug

#12181 feat(inventoriable): add snmp credential and last update for NetworkEquipement and Printer
  composer.lock
  src/CommonDBTM.php
  src/Inventory/Asset/Printer.php
  templates/components/form/inventory_info.html.twig
  tests/functionnal/Glpi/Inventory/Assets/Printer.php
  tests/functionnal/Glpi/Inventory/Inventory.php
Labels: enhancement, Need unit tests

#12065 [GLPI 10.0 Bugfixes] Add Line To User & Group
  inc/define.php
Labels: enhancement

#12199 Force display of ID for all ITIL Objects in CommonDBTB without any specific message
  src/CommonDBTM.php
  src/Ticket.php
  tests/functionnal/ProjectTask.php
  tests/functionnal/TicketTask.php
Labels: ux

#12206 E-mails with no message-ids block retrieving by collector
  src/MailCollector.php
  tests/emails-tests/34-no-message-id-header.eml
  tests/imap/MailCollector.php
Labels: bug

#12208 fix(timelineitems): bypass right for canViewItem from CLI (notification)
  src/CommonITILObject.php
Labels: bug

#12223 Impact analysis: fix dirty workspace icon
  js/impact.js
Labels: bug

#12232 Ignore invalid mail headers in mail collector
  composer.json
  tests/emails-tests/35-message-with-some-invalid-headers.eml
  tests/imap/MailCollector.php
  tools/patches/laminas-mail-invalid-header-ignore.patch
Labels: bug

#12233 Fix 'Support' system user migration
  install/migrations/update_9.5.x_to_10.0.0/pendingreason.php
Labels: bug

#12236 Allow dependabot to increase version of dev dependencies
  .github/dependabot.yml
Labels: dependencies

#12238 Prevent plugin langs to be reloaded multiple time
  src/Console/Plugin/ActivateCommand.php
  src/Console/Plugin/DeactivateCommand.php
  src/Plugin.php
Labels: bug

#12237 Central views: add missing priority color on short ticket lists
  css/includes/pages/_search.scss
  src/Ticket.php
Labels: bug

#12268 fix(central): show central warnings only on first tab
  src/Central.php
  templates/central/widget_tab.html.twig
Labels: bug

#12278 Fix unwanted glpi_impactcontexts.positions diff detection on MySQL
  src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
  tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
Labels: bug

#12277 Ensure charset directive is first in compiled CSS
  src/Console/Build/CompileScssCommand.php
Labels: bug

#11737 Improve central reminder list contents
  src/Reminder.php
Labels: enhancement

#12060 Separate agent clean actions and add uninstall integration
  install/migrations/update_10.0.x_to_10.1.0/native_inventory.php
  src/Agent.php
  src/Config.php
  src/Inventory/Conf.php
  src/Plugin/Hooks.php
  tests/functionnal/Agent.php
Labels: enhancement
