Repository glpi-project/glpi, pull requests merged in 2022-03, with the labels that each got.

#10801 Fix some issues revealed by PHPStan lvl 0
  CHANGELOG.md
  src/CommonDBRelation.php
  src/CommonDBTM.php
  src/CommonITILObject.php
  src/Console/Migration/AppliancesPluginToCoreCommand.php
  src/Console/Migration/RacksPluginToCoreCommand.php
  src/Features/TreeBrowse.php
  src/Item_SoftwareLicense.php
  src/Item_SoftwareVersion.php
  src/Knowbase.php
  src/Link.php
  src/ManualLink.php
  src/Rule.php
  src/RuleCollection.php
  src/RuleRightCollection.php
  src/SavedSearch.php
  src/SavedSearch_Alert.php
  src/Search.php
  src/Socket.php
  src/Software.php
  src/State.php
  src/Ticket.php
  src/TicketValidation.php
  src/Ticket_Contract.php
  src/Ticket_Ticket.php
  src/Toolbox.php
  src/Toolbox/MarkdownBuilder.php
  src/Transfer.php
  src/Unmanaged.php
  src/User.php
  tests/units/DB.php
Labels: bug

#10840 feat(searchoption): add rack SO
  src/Computer.php
  src/Enclosure.php
  src/Monitor.php
  src/NetworkEquipment.php
  src/PDU.php
  src/PassiveDCEquipment.php
  src/Peripheral.php
  src/Rack.php
Labels: enhancement

#10858 Update scssphp/scssphp and drop specific patch
  composer.json
  composer.lock
  tools/patches/scssphp.patch
Labels: dependencies

#10859 Make SolutionTemplate translatable
  src/SolutionTemplate.php
Labels: enhancement

#10861 Fix commonitil form display
  templates/components/itilobject/layout.html.twig
Labels: bug

#10862 Highlight TTO/TTR only when exceeded
  src/CommonITILObject.php
  src/Search.php
  src/Ticket.php
Labels: bug

#10871 Number of user in the dashboard don't take the entity filter into account #10870
  inc/dashboard/provider.class.php
Labels: bug

#10867 Fix item name created from template
  src/Features/Clonable.php
  tests/functionnal/Computer.php
  tests/functionnal/Software.php
Labels: bug

#10915 feat(database/instance): add missing tab
  inc/define.php
  pics/impact/databaseinstance.png
  src/Database.php
Labels: enhancement

#10926 Prevent requiring --allow-unstable when DB current version is not stable
  src/Console/Database/UpdateCommand.php
Labels: enhancement

#10917 fix(database): add missing is_dynamic field
  install/migrations/update_9.5.x_to_10.0.0/databases.php
  install/mysql/glpi-empty.sql
  src/Database.php
  src/Inventory/Asset/DatabaseInstance.php
Labels: enhancement

#10944 Add ability to define plugin options
  src/Marketplace/Controller.php
  src/Plugin.php
  tests/functionnal/Plugin.php
Labels: enhancement, need_doc_improvement

#10975 PHP 8.2 fixes
  CHANGELOG.md
  src/Agent/Communication/Headers/Common.php
  src/Blacklist.php
  src/CommonDBTM.php
  src/DBmysqlIterator.php
  src/Html.php
  src/IPNetwork.php
  src/Inventory/Asset/InventoryAsset.php
  src/Inventory/Asset/MainAsset.php
  src/Inventory/Asset/Monitor.php
  src/Inventory/Asset/NetworkEquipment.php
  src/Inventory/Inventory.php
  src/Item_Rack.php
  src/KnowbaseItem.php
  src/MailCollector.php
  src/MassiveAction.php
  src/NetworkPort.php
  src/NotificationTarget.php
  src/Profile.php
  src/RichText/UserMention.php
  tests/imap/MailCollector.php
Labels: bug

#11003 Fix HookManager
  src/Plugin/HookManager.php
Labels: bug

#10991 Harmonize ITIL Object link notification behavior
  src/Change_Problem.php
  src/Change_Ticket.php
  src/Problem_Ticket.php
Labels: enhancement

#11075 Add getWebDir to twig "Plugin" extension
  src/Application/View/Extension/PluginExtension.php
  src/Plugin.php
Labels: enhancement

#11078 Sanitizing value property for hidden fields
  inc/itiltemplate.class.php
Labels: bug

#11073 Fix Domain inherited class
  CHANGELOG.md
  src/Domain.php
  src/Inventory/Asset/InventoryAsset.php
Labels: bug

#11108 Fix adding Socket from Location
  src/NetworkPort.php
  src/Socket.php
Labels: bug

#11121 Fix upload handler
  src/GLPIUploadHandler.php
Labels: bug

#11113 Improve searches on Mio
  src/DeviceMemory.php
  src/Search.php
  src/Toolbox.php
  tests/functionnal/Toolbox.php
Labels: enhancement

#11129 Fix auto-percent calculation when adding or deleting tasks
  src/ProjectTask.php
  tests/functionnal/Project.php
Labels: bug

#11131 add changelog icon if plugin declares any
  css/standalone/marketplace.scss
  src/Marketplace/View.php
Labels: enhancement

#11102 Fix KB comment UI
  src/KnowbaseItem_Comment.php
  tests/functionnal/KnowbaseItem_Comment.php
Labels: bug, ux

#11146 Add PassiveDCEquipment to global search types; closes #11008
  inc/define.php
Labels: enhancement

#11149 fix(massiveation): disabled categories was available
  src/MassiveAction.php
  src/Ticket.php
Labels: bug
