Repository glpi-project/glpi, pull requests merged in 2022-12, with the labels that each got.

#13438 Fix administrator targets
  src/Config.php
  src/Entity.php
  src/NotificationEventMailing.php
  src/NotificationMailingSetting.php
  tests/functionnal/NotificationEventMailing.php
Labels: bug

#13524 Fix encryption warning
  src/Item_Disk.php
Labels: bug

#13531 Show full KB article at once
  src/KnowbaseItem.php
  src/RichText/RichText.php
Labels: bug

#13529 fix(planning recall): do not recall closed ticket tasks
  src/PlanningRecall.php
Labels: bug

#13452 fix undefined array when using a custom dashboard
  inc/define.php
  src/Dashboard/Dashboard.php
  src/Html.php
Labels: bug

#13556 fix(RuleMatchLog): add missing column value
  src/Agent/Communication/AbstractRequest.php
  src/RuleMatchedLog.php
Labels: bug, inventory

#13557 fix(RuleMatchLog): add missing tab from Agent
  src/Agent.php
  tests/functionnal/Agent.php
Labels: bug, inventory

#13565 fix(software): fix history on delete (from inventory)
  src/Inventory/Asset/Software.php
Labels: bug, inventory

#13575 List VMs from trashbin also
  src/ComputerVirtualMachine.php
Labels: bug

#13574 fix(networkport): add history on add NetworkPort
  src/NetworkPort.php
  tests/functionnal/Glpi/Inventory/Inventory.php
Labels: bug

#13512 fix(licence template): template name not editable
  templates/generic_show_form.html.twig
Labels: bug

#13510 fix(clone): relation ID not updated between cloned sub items
  src/Features/Clonable.php
  tests/functionnal/Project.php
Labels: bug

#13540 Fix "Location on map" when geo.enabled is disabled on firefox
  js/common.js
  src/MapGeolocation.php
Labels: bug

#13563 Add category filter for ITIL Kanban
  js/modules/Kanban/Kanban.js
  src/CommonITILObject.php
Labels: enhancement

#13527 Hide locked fields for deleted relation
  src/Lock.php
Labels: bug

#13058 Enhance progress bars on migration commands
  composer.lock
  src/Console/AbstractCommand.php
  src/Console/Migration/DynamicRowFormatCommand.php
  src/Console/Migration/MyIsamToInnoDbCommand.php
  src/Console/Migration/TimestampsCommand.php
  src/Console/Migration/UnsignedKeysCommand.php
  src/Console/Migration/Utf8mb4Command.php
Labels: enhancement

#13413 Planning - new timeline week view
  CHANGELOG.md
  js/planning.js
  js/reservations.js
  lib/bundles/fullcalendar.js
  package-lock.json
  package.json
  src/Planning.php
  src/Reservation.php
Labels: enhancement

#12884 Feat/dashboard palettes
  css/standalone/dashboard.scss
  js/dashboard.js
  src/Dashboard/Grid.php
  src/Dashboard/Palette.php
  src/Dashboard/Widget.php
  src/Plugin/Hooks.php
  templates/components/dashboard/widget_form.html.twig
Labels: enhancement

#13594 fix(inventory): exclude 0.0.0.0 from management port
  install/migrations/update_10.0.5_to_10.0.6/blacklist.php
  src/Blacklist.php
  src/Inventory/Asset/NetworkEquipment.php
  tests/functionnal/Blacklist.php
  tests/functionnal/Glpi/Inventory/Assets/Printer.php
Labels: bug, inventory

#13598 Upgrade laminas packages to get PHP 8.2 compatibility
  composer.json
  composer.lock
  src/Config.php
  tests/functionnal/Toolbox.php
  tests/imap/MailCollector.php
Labels: dependencies

#13607 Fix undefined array key in mio size formatting
  src/Toolbox.php
  tests/functionnal/Toolbox.php
Labels: bug

#13608 Fix auth label for mail accounts
  src/Auth.php
Labels: bug

#13595 enhance the entity name when selecting all
  src/Session.php
Labels: ux

#13526 feat(knowbase): add entity on articles
  ajax/visibility.php
  install/migrations/update_10.0.x_to_10.1.0/knowbaseitem.php
  install/mysql/glpi-empty.sql
  src/CommonDBVisible.php
Labels: enhancement

#13611 Dashboards: fix reminders visibility
  src/Dashboard/Provider.php
  tests/functionnal/Glpi/Dashboard/Provider.php
Labels: bug

#13614 Update tinymce
  package-lock.json
  package.json
Labels: security, dependencies

#13406 fix(ruleimportasset): correctly handle condition for TAG criteria
  src/Inventory/Asset/MainAsset.php
  src/RuleImportAsset.php
  tests/functionnal/RuleImportAsset.php
Labels: bug, inventory

#13627 Helpdesk config: preset contract can't be deleted or template
  src/Entity.php
Labels: bug

#13610 fix(snmp): do not delete management port each time
  src/Inventory/Asset/InventoryNetworkPort.php
  src/Inventory/Asset/Printer.php
  tests/functionnal/Glpi/Inventory/Assets/Printer.php
Labels: bug, inventory

#13615 fix(task template): user missing when dropdown_max too small
  src/Dropdown.php
Labels: bug

#13637 Better handling of numeric attributes of devices
  src/DeviceBattery.php
  src/DeviceGraphicCard.php
  src/DeviceHardDrive.php
  src/DeviceMemory.php
  src/DeviceProcessor.php
  src/DeviceSimcard.php
  src/Item_DeviceGraphicCard.php
  src/Item_DeviceHardDrive.php
  src/Item_DeviceMemory.php
  src/Item_DeviceProcessor.php
  templates/components/form/item_device.html.twig
Labels: enhancement

#13631 Fix ITILSolution timeline hooks
  src/CommonITILObject.php
  src/NotificationTargetCommonITILObject.php
  templates/components/itilobject/timeline/timeline.html.twig
  tests/functionnal/Ticket.php
Labels: bug

#13644 Simplier handling of plugin replacement
  src/Plugin.php
  tests/functionnal/Plugin.php
Labels: enhancement
