Repository glpi-project/glpi, pull requests merged in 2022-09, with the labels that each got.

#12301 Ticket rules: support 'regex_result' for more actions
  src/RuleCommonITILObject.php
  tests/functionnal/RuleCommonITILObject.php
Labels: enhancement

#12317 fix(ticket): empty service levels
  templates/components/itilobject/fields_panel.html.twig
Labels: bug

#12496 add new options for deleted users : disable and remove groups
  src/AuthLDAP.php
  src/User.php
Labels: enhancement

#12449 fix(task): show status when ticket closed
  templates/components/itilobject/timeline/timeline.html.twig
Labels: bug

#12437 Ticket: fix reopen by requester group
  src/CommonITILObject.php
  tests/functionnal/Ticket.php
Labels: bug

#12426 Fix handling of search input tokens with spaces
  js/modules/SearchTokenizer/SearchInput.js
Labels: bug

#12290 CORS must allow app-token header
  src/Api/API.php
  tests/web/APIRest.php
Labels: bug

#12509 fix(ticket): hide added group when it is hiddenfield in template
  templates/components/itilobject/actors/field.html.twig
Labels: bug

#12456 Display ID in linking dropdown for Common ITIL objects
  src/Change_Problem.php
  src/Change_Ticket.php
  src/Problem_Ticket.php
Labels: enhancement

#12445 Disable contextual character replacements by default
  css/includes/_base.scss
Labels: ux

#12528 fix(inventory): update network port metrics
  src/Inventory/Asset/NetworkPort.php
  tests/functionnal/Glpi/Inventory/Assets/NetworkPort.php
Labels: bug, inventory

#12532 fix(dashboard): fix draggable item and grid-stack size
  css/standalone/dashboard.scss
  src/Search.php
Labels: bug

#12565 Enhance readability of database diff
  src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
  tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
Labels: enhancement

#12568 fix(tickettemplate): fix predefined date not working
  src/Ticket.php
Labels: bug

#12419 fix(discovery): allow networkport update from discovery only for printer
  src/Inventory/Asset/MainAsset.php
  src/Inventory/Asset/Printer.php
  tests/functionnal/Glpi/Inventory/Assets/Printer.php
Labels: enhancement, Need unit tests, inventory

#12575 fix(inventory): fix printer TU
  tests/functionnal/Glpi/Inventory/Assets/Printer.php
Labels: bug

#12567 Fix redirect from load tab when session is expired
  ajax/common.tabs.php
  src/Html.php
Labels: bug

#12579 Inventory: fix xml errors encoding
  src/Agent/Communication/AbstractRequest.php
  tests/units/Glpi/Inventory/Request.php
  tests/web/Glpi/Inventory/Request.php
Labels: bug

#12580 Add persistent cache on DbUtils::fixItemtypeCase()
  src/DbUtils.php
Labels: performance

#12302 Delegate session cookies security to sysadmin
  css/install.scss
  src/Auth.php
  src/Session.php
  src/System/Requirement/SessionsSecurityConfiguration.php
  src/System/RequirementsManager.php
  tests/units/Glpi/System/Requirement/SessionsSecurityConfiguration.php
Labels: security

#12529 Printers: fix printed pages graph for big datasets
  css/includes/_includes.scss
  css/includes/components/chartist/_chartist.scss
  src/Dashboard/Widget.php
  src/PrinterLog.php
Labels: bug

#12582 fix(inventory): UUID is empty
  src/RuleImportAsset.php
  tests/functionnal/RuleImportAsset.php
Labels: bug

#12601 fix(rule): fix rule name
  src/RuleImportAsset.php
  tests/functionnal/Glpi/Inventory/Inventory.php
  tests/functionnal/RuleImportAsset.php
Labels: enhancement

#12388 Fix default recipients for assign group in ticket notification
  install/empty_data.php
  install/migrations/update_10.0.2_to_10.0.3/notifications.php
  src/NotificationTargetCommonITILObject.php
Labels: bug

#12592 Fix database schema check bypass condition
  src/Console/Database/UpdateCommand.php
Labels: bug

#12596 Fix ITIL Kanban under read-only profile
  js/modules/Kanban/Kanban.js
  src/CommonITILObject.php
Labels: bug

#12586 PHP 8.2 compatibility
  .composer-require-checker.config.json
  .github/workflows/ci.yml
  composer.json
  composer.lock
  inc/define.php
  src/Agent/Communication/AbstractRequest.php
  src/CommonITILObject.php
  src/Config.php
  src/Item_Devices.php
  src/System/Requirement/PhpVersion.php
  src/Toolbox.php
  src/User.php
  tests/units/Glpi/System/Requirement/ExtensionFunction.php
  tests/units/Glpi/System/Requirement/PhpVersion.php
  tools/patches/atoum-php-8.2.patch
Labels: bug, enhancement

#12459 fix(timeline): the img display size in timeline is not correct.
  src/NotificationEventMailing.php
  src/RichText/RichText.php
Labels: bug

#12602 Display last inventoried value for locked fields
  src/CommonDBTM.php
  src/Inventory/Asset/MainAsset.php
  src/Lockedfield.php
  templates/components/form/fields_macros.html.twig
  tests/functionnal/Lockedfield.php
Labels: bug, enhancement

#12076 Allow forcing closure when adding solution via rules
  src/ITILSolution.php
  tests/functionnal/ITILSolution.php
Labels: bug

#12572 Use rules to add computers as virtual machines
  src/Inventory/Asset/VirtualMachine.php
  tests/functionnal/Glpi/Inventory/Assets/VirtualMachine.php
  tests/functionnal/Glpi/Inventory/Inventory.php
Labels: enhancement

#12612 ITIL Timeline: restore rich-text-container class
  templates/components/itilobject/timeline/form_followup.html.twig
  templates/components/itilobject/timeline/form_solution.html.twig
  templates/components/itilobject/timeline/form_task.html.twig
  templates/components/itilobject/timeline/form_validation.html.twig
  templates/components/itilobject/timeline/main_description.html.twig
Labels: bug

#12615 give itemtype the ability to modify their data before add
  CHANGELOG.md
  src/CommonDBTM.php
Labels: enhancement

#12608 fix width of timeline item when displayed within todo layout
  css/includes/components/itilobject/_timeline.scss
Labels: bug

#12616 Richtext: open links in new tab by default
  css/includes/components/_richtext.scss
  src/Html.php
  src/RichText/RichText.php
  stylelint.config.js
  tests/units/Glpi/RichText/RichText.php
Labels: enhancement

#12628 fix(change): undefine index is_change
  src/CommonITILObject.php
Labels: bug

#12633 feat(escalation level): increase execution time
  src/LevelAgreementLevel.php
Labels: enhancement

#12523 Use dropdown limit option for actor fields
  src/Dropdown.php
  templates/components/itilobject/actors/field.html.twig
Labels: performance

#12634 Fix softwarecategories import update
  src/Inventory/Asset/Software.php
  tests/functionnal/Glpi/Inventory/Assets/Software.php
  tests/functionnal/Glpi/Inventory/Inventory.php
Labels: bug

#9827 Add PHPStan level 0 checks
  .github/actions/lint_php-lint.sh
  composer.json
  composer.lock
  inc/based_config.php
  phpstan.neon
  src/Agent/Communication/AbstractRequest.php
  src/Application/ErrorHandler.php
  src/Application/View/TemplateRenderer.php
  src/AuthLDAP.php
  src/Cartridge.php
  src/Certificate_Item.php
  src/CommonDBTM.php
  src/CommonDBVisible.php
  src/CommonDevice.php
  src/CommonGLPI.php
  src/CommonITILTask.php
  src/CommonTreeDropdown.php
  src/Console/AbstractCommand.php
  src/Console/Application.php
  src/Console/Migration/UnsignedKeysCommand.php
  src/Consumable.php
  src/Contact.php
  src/Contract.php
  src/CronTask.php
  src/DBmysql.php
  src/DBmysqlIterator.php
  src/DCRoom.php
  src/DatabaseInstance.php
  src/DbUtils.php
  src/Document_Item.php
  src/Domain.php
  src/Domain_Item.php
  src/Dropdown.php
  src/DropdownTranslation.php
  src/Entity.php
  src/Features/PlanningEvent.php
  src/FieldUnicity.php
  src/GLPIMailer.php
  src/GLPIPDF.php
  src/HTMLTableCell.php
  src/HTMLTableGroup.php
  src/HTMLTableMain.php
  src/Html.php
  src/KnowbaseItem.php
  src/NotificationSettingConfig.php
  src/RSSFeed.php
  src/Reminder.php
Labels: bug

#12637 Tabs in modals
  src/CommonGLPI.php
Labels: enhancement

#12640 User tooltip: add phone2 if exist
  src/DbUtils.php
  templates/components/user/info_card.html.twig
Labels: enhancement

#12644 fix(tinymce): disable text_patterns
  src/Html.php
Labels: bug

#11709 Re-organize Search Code
  src/Search.php
  src/Search/Input/QueryBuilder.php
  src/Search/Input/SearchInputInterface.php
  src/Search/Output/AbstractSearchOutput.php
  src/Search/Output/CSVSearchOutput.php
  src/Search/Output/ExportSearchOutput.php
  src/Search/Output/GlobalSearchOutput.php
  src/Search/Output/HTMLSearchOutput.php
  src/Search/Output/MapSearchOutput.php
  src/Search/Output/NamesListSearchOutput.php
  src/Search/Output/PDFLandscapeSearchOutput.php
  src/Search/Output/PDFPortraitSearchOutput.php
  src/Search/Output/PDFSearchOutput.php
  src/Search/Output/SYLKSearchOutput.php
  src/Search/Output/TableSearchOutput.php
  src/Search/Provider/SQLProvider.php
  src/Search/Provider/SearchProviderInterface.php
  src/Search/SearchEngine.php
  src/Search/SearchOption.php
  tests/functionnal/Search.php
Labels: enhancement

#12652 Fix simplified ticket template preview
  src/Ticket.php
Labels: bug

#12675 Hide NetworkPort list button
  src/NetworkPort.php
Labels: bug

#12673 move breaking points of itil object layout
  css/includes/components/itilobject/_layout.scss
  templates/components/itilobject/fields_panel.html.twig
  templates/components/itilobject/footer.html.twig
  templates/components/itilobject/layout.html.twig
  templates/components/itilobject/timeline/filter_timeline.html.twig
Labels: ux

#12685 Fix uploaded files names
  js/common.js
Labels: bug

#12688 Force ID to be visible for CommonITILObjects in dropdownAllItems
  ajax/dropdownAllItems.php
Labels: enhancement

#12695 Handle removal of install directory in db:check command
  src/Console/Database/CheckSchemaIntegrityCommand.php
  src/Console/Database/UpdateCommand.php
  src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
  tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
Labels: bug

#12697 Ignore KEY comments during database integrity checks
  src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
  tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
Labels: bug

#12699 Fix login error display
  front/login.php
  src/Api/API.php
  src/Auth.php
  templates/pages/login_error.html.twig
Labels: bug

#12280 Use of native PHP function for escaping user_dn
  src/User.php
Labels: bug

#11968 Move main asset header back to the nav header
  css/includes/_base.scss
  css/includes/components/_asset-form.scss
  js/common.js
  src/CommonDBTM.php
  src/CommonGLPI.php
  src/User.php
  templates/components/form/header.html.twig
  templates/components/form/header_content.html.twig
  templates/generic_show_form.html.twig
Labels: enhancement

#12721 Drop useless inventory_format lib files from release archive
  tools/build_glpi.sh
Labels: dependencies

#12710 API: fix update input and warnings
  src/Api/API.php
  tests/web/APIRest.php
Labels: bug

#12696 Fix array value handling in GLPI constants display
  src/Config.php
Labels: bug

#12722 feat(core): use twig for item_disk
  src/Item_Disk.php
  templates/components/form/item_disk.html.twig
  templates/generic_show_form.html.twig
Labels: enhancement

#12726 Twig computer antivirus
  src/ComputerAntivirus.php
  templates/components/form/computerantivirus.html.twig
  templates/generic_show_form.html.twig
Labels: enhancement

#12744 Fix phone import
  src/RuleImportAsset.php
  tests/functionnal/Glpi/Inventory/Inventory.php
Labels: bug

#12684 feat(ticket): remove pending status from follow-up/task
  src/CommonITILTask.php
  src/Features/ParentStatus.php
  src/ITILFollowup.php
  templates/components/itilobject/timeline/form_followup.html.twig
  templates/components/itilobject/timeline/form_task.html.twig
Labels: ux

#12717 Fix Entity dropdown using "multiple" option
  src/Dropdown.php
Labels: bug

#12734 fix(timeline content): enlarge to avoid truncating the date
  css/includes/components/itilobject/_timeline.scss
Labels: ux

#12763 Fix session related warnings on plugin activation from cli
  src/Plugin.php
Labels: bug

#12770 Events: search by itemtype
  src/Event.php
Labels: bug

#12775 fix(schema): add missing is_deleted column
  install/migrations/update_10.0.3_to_10.0.4/inventory.php
  install/mysql/glpi-10.0.4-empty.sql
  tests/functionnal/Glpi/Inventory/Inventory.php
Labels: bug

#12735 Twig itemdevice
  src/Item_Devices.php
  templates/components/form/item_device.html.twig
Labels: enhancement

#12776 Events: search by itemtype 2
  src/Event.php
Labels: bug

#12774 feat(core): check is_deleted column if table have is_dynamic
  src/System/Diagnostic/DatabaseSchemaConsistencyChecker.php
Labels: enhancement

#12788 feat(cartridge): better display
  src/Printer_CartridgeInfo.php
Labels: enhancement

#12792 feat(inventory): add dedicated right for locked field
  install/empty_data.php
  install/migrations/update_10.0.3_to_10.0.4/inventory.php
  src/Lockedfield.php
  src/Profile.php
Labels: enhancement

#12782 fix(itemdevice): fix twig template
  templates/components/form/item_device.html.twig
Labels: bug

#12798 dix(location): check entity assign
  src/Location.php
Labels: bug

#12743 feat(core): use twig for Networkname
  src/CommonDBChild.php
  src/NetworkName.php
  src/RegisteredID.php
  src/UserEmail.php
  templates/components/form/networkname.html.twig
Labels: enhancement

#12809 feat(inventory): move snmpcredentials_id to main form
  src/NetworkEquipment.php
  src/Printer.php
  src/SNMPCredential.php
  templates/components/form/inventory_info.html.twig
  templates/generic_show_form.html.twig
Labels: enhancement

#12783 Twig ComputerVirtualMachine
  src/ComputerVirtualMachine.php
  templates/components/form/computervirtualmachine.html.twig
Labels: enhancement
