Repository glpi-project/glpi, pull requests merged in 2023-04, with the labels that each got.

#14388 Fix parsing of `x-www-form-urlencoded` input in API
  src/Api/APIRest.php
  tests/web/APIRest.php
Labels: bug

#14427 Fix OLA escalation date calculation
  install/migrations/update_10.0.6_to_10.0.7/ticket_fix_internal_tto_escalation.php
  install/mysql/glpi-empty.sql
  src/LevelAgreement.php
  src/Ticket.php
  tests/functional/SLM.php
Labels: bug

#14426 Fix user dropdown filtering on helpdesk interface
  src/User.php
Labels: bug

#14471 build(deps): bump @tabler/icons-webfont from 2.8.0 to 2.13.1
  package-lock.json
  package.json
Labels: dependencies, javascript

#14474 Fix bad named foreign key
  inc/relation.constant.php
  install/migrations/update_10.0.6_to_10.0.7/wrong_fkey.php
  install/mysql/glpi-empty.sql
  src/Inventory/Asset/Camera.php
  src/Item_DeviceCamera_ImageFormat.php
  src/Item_DeviceCamera_ImageResolution.php
Labels: bug

#14433 fix: actorinformation checks
  ajax/actorinformation.php
Labels: security

#14421 Enhance unmet prerequisites message in `migration:timestamps` command
  src/Console/Migration/TimestampsCommand.php
Labels: ux

#14493 fix(inventory): fix restore / purge lock for Domain_Item
  inc/define.php
Labels: bug

#14499 fix(ticket): improve KB display
  css/legacy/includes/_styles.scss
  src/CommonDropdown.php
Labels: ux

#14494 fix(Inventory): search Domain with asset entities_id
  src/Inventory/Asset/MainAsset.php
Labels: bug

#14503 Fix shared hosting support in PHP router (using `.htaccess`)
  public/index.php
Labels: bug

#14507 fix(database): blank page
  src/CommonGLPI.php
Labels: bug

#14504 fix(search): query search with backslash
  src/Search.php
  tests/functional/Search.php
Labels: bug

#14513 Fix forcetab parameter for namespaces
  src/Toolbox/Sanitizer.php
  tests/units/Glpi/Toolbox/Sanitizer.php
Labels: bug

#14520 Fix JS toast style
  js/glpi_dialog.js
Labels: bug

#14510 Fix promote button state/visibility
  src/CommonITILObject.php
  templates/components/itilobject/timeline/timeline.html.twig
  templates/components/itilobject/timeline/timeline_item_header.html.twig
Labels: bug

#14521 Prevent SMTP OAuth config to be lost on config save
  src/Config.php
Labels: bug

#14528 Fix SQL escaping
  src/AuthLDAP.php
Labels: bug

#14532 Handle missing itemtype on log display
  src/Log.php
Labels: bug

#14534 Fix DB creation at install on PHP 8.1+
  install/install.php
  src/Console/Database/InstallCommand.php
Labels: bug

#14383 fix(Widget): prevent undefined array key from 'multipleNumber'
  src/Dashboard/Widget.php
  tests/units/Glpi/Dashboard/Widget.php
Labels: bug, Dashboard

#14538 fix contract account num field for notification
  src/NotificationTargetContract.php
Labels: bug

#14382 feat: add deleted status on items header
  src/CommonGLPI.php
  templates/components/form/header_content.html.twig
Labels: enhancement, ux

#14553 Add 'tag' and 'otherserial' to RuleAsset
  src/CommonDBTM.php
  src/RuleAsset.php
  tests/functional/Glpi/Inventory/Inventory.php
Labels: enhancement, inventory

#14565 fix(rule ticket): criterion Unavailable
  install/migrations/update_10.0.7_to_10.0.8/rule_tickets.php
  resources/Rules/RuleTicket.xml
Labels: bug

#14568 fix(notification): town not city
  src/NotificationTargetTicket.php
Labels: bug

#14552 Fix missing ticket actors in content templates
  src/CommonITILObject.php
  tests/functional/Glpi/ContentTemplates/TemplateManager.php
Labels: bug

#14566 Fix getItemTypeForTable when using namespace + item_xxx
  src/DbUtils.php
  tests/fixtures/another_test.php
  tests/fixtures/pluginfoo_search_a_b_c_d_e_f_g_bar.php
  tests/fixtures/pluginfoo_search_item_filter.php
  tests/fixtures/test_a_b.php
  tests/functional/DbUtils.php
Labels: bug

#14525 Improve Kanban performances when loading user pictures
  js/modules/Kanban/Kanban.js
Labels: bug

#14547 Fix showing closed column ITIL kanban
  src/CommonITILObject.php
Labels: bug

#14548 Reapply filters after showing Kanban column
  js/modules/Kanban/Kanban.js
Labels: bug

#14562 feat(entity): move few settings from general settings
  install/empty_data.php
  install/migrations/update_10.0.x_to_10.1.0/entity.php
  install/mysql/glpi-empty.sql
  src/Computer.php
  src/Computer_Item.php
  src/Config.php
  src/Entity.php
  src/Item_Devices.php
  src/State.php
  tests/functional/Agent.php
  tests/functional/Computer.php
  tests/functional/Glpi/Inventory/Assets/NetworkEquipment.php
  tests/functional/Unmanaged.php
Labels: enhancement

#14549 fix(ola): missing value in dropdown
  src/OlaLevel.php
Labels: enhancement

#14573 feat(Cost): increase action time from CommonITILCost
  src/CommonITILCost.php
Labels: enhancement

#14572 fix(notification template): missing tag
  src/NotificationTargetTicket.php
Labels: bug

#14519 feat(saved search): restore the ability to order the list
  ajax/savedsearch.php
  css/includes/components/_saved-searches.scss
  src/SavedSearch.php
  templates/layout/parts/saved_searches_list.html.twig
Labels: bug, enhancement

#14121 feat(ticket): assign me since followup, solution
  inc/define.php
  install/empty_data.php
  install/migrations/update_10.0.x_to_10.1.0/configs.php
  install/mysql/glpi-empty.sql
  src/Config.php
  src/ITILFollowup.php
  src/ITILSolution.php
  src/Ticket.php
  tests/functional/Ticket.php
Labels: enhancement

#14588 API: Do not render progress bars when executing massive actions
  src/MassiveAction.php
Labels: bug
