Repository glpi-project/glpi, pull requests merged in 2023-07, with the labels that each got.

#15084 prevent sub documents to break timeline layout
  css/includes/components/itilobject/_timeline.scss
  templates/components/itilobject/timeline/sub_documents.html.twig
Labels: bug

#15054 fix(export): preserve line breaks and > from completename
  src/RichText/RichText.php
  src/Search.php
  tests/units/Glpi/RichText/RichText.php
Labels: bug

#15052 Debug bar formating + Use datagrid instead of html tables
  css/includes/components/_debug-toolbar.scss
  js/modules/Debug/Debug.js
Labels: ux

#15090 fix(inventory): TAG searchOption on computer
  src/Agent.php
Labels: enhancement

#15087 fix(inventory): prevent 'Missing Entity ID' warning
  src/CommonDBTM.php
  tests/functional/Glpi/Inventory/Assets/Computer.php
Labels: bug, inventory

#15106 Fix plugin search options display
  src/DisplayPreference.php
  src/Search.php
Labels: bug

#15101 fix(CommonITILObject): clone actors
  src/CommonITILObject.php
  tests/functional/Ticket.php
Labels: bug

#15115 Add Amazon Linux name support in Operating System rules
  resources/Rules/RuleDictionnaryOperatingSystem.xml
  tests/functional/Glpi/Inventory/Assets/OperatingSystem.php
Labels: enhancement, inventory

#15020 Use user-friendly permission labels in access-errors log
  src/CommonDBTM.php
  src/Profile.php
  src/Session.php
  tests/functional/Session.php
Labels: enhancement

#15126 Log mails/browsers notifications config changes
  front/notificationajaxsetting.form.php
  front/notificationmailingsetting.form.php
Labels: enhancement

#15127 Fix `ram` field migration on MySQL 5.7
  install/migrations/update_10.0.7_to_10.0.8/ram_field.php
Labels: bug

#15164 fix(inventory): fix missing rule ID From RuleEntity when add as RefeEquipement
  src/Inventory/Asset/MainAsset.php
Labels: bug, inventory

#15179 Add drop method to DB
  src/DBmysql.php
  src/Migration.php
  src/NetworkPortMigration.php
  tests/units/DB.php
Labels: enhancement

#15178 fix(core): use non sensitive case to find user
  src/User.php
Labels: enhancement

#15160 Make CI test fails on migration errors
  .github/actions/test_update-from-9.5.sh
  .github/actions/test_update-from-older-version.sh
  install/migrations/update_0.90.1_to_0.90.5.php
  install/migrations/update_0.90.x_to_9.1.0.php
  install/migrations/update_10.0.0_to_10.0.1.php
  install/migrations/update_10.0.1_to_10.0.2.php
  install/migrations/update_10.0.2_to_10.0.3.php
  install/migrations/update_10.0.3_to_10.0.4.php
  install/migrations/update_10.0.4_to_10.0.5.php
  install/migrations/update_10.0.5_to_10.0.6/inventory.php
  install/migrations/update_10.0.6_to_10.0.7/unmanageds.php
  install/migrations/update_9.2.x_to_9.3.0.php
  install/migrations/update_9.3.1_to_9.3.2.php
  install/migrations/update_9.3.x_to_9.4.0.php
  install/migrations/update_9.4.0_to_9.4.1.php
  install/migrations/update_9.4.1_to_9.4.2.php
  install/migrations/update_9.4.2_to_9.4.3.php
  install/migrations/update_9.4.x_to_9.5.0.php
  install/migrations/update_9.5.3_to_9.5.4.php
  install/migrations/update_9.5.x_to_10.0.0.php
  install/migrations/update_9.5.x_to_10.0.0/cache.php
  install/migrations/update_9.5.x_to_10.0.0/knowbaseitem_knowbaseitemcategory.php
  install/migrations/update_9.5.x_to_10.0.0/native_inventory.php
  install/migrations/update_9.5.x_to_10.0.0/pendingreason.php
Labels: bug

#15104 Prevent user to be marked as deleted when LDAP connection failed
  src/Auth.php
  src/AuthLDAP.php
  tests/LDAP/AuthLdap.php
Labels: bug

#15177 Filter reservable itemtype dropdowns
  src/Reservation.php
  src/ReservationItem.php
  tests/functional/Reservation.php
Labels: enhancement

#15184 Fix tabs borders
  css/includes/components/_tabs.scss
Labels: ux

#15187 fix(export): preserve line breaks for 'old' HTML format
  src/Search.php
Labels: bug

#15193 Exit with an error when schema is not consistent after update
  install/update.php
  src/Console/Database/UpdateCommand.php
  src/Update.php
Labels: bug

#15199 Remove/upgrade unsecure dev dependencies
  package-lock.json
Labels: dependencies, javascript

#15209 Fix suffixes on nuumber dashboard cards
  js/dashboard.js
Labels: bug

#15204 Fix issue with phpCAS 1.3.6-1 debian package
  front/logout.php
  phpstan.neon
  src/Auth.php
Labels: bug

#15214 Adapt PHP log level to environment type
  src/GLPI.php
Labels: enhancement

#15191 Fix access check to caldav debug UI
  src/CalDAV/Plugin/Browser.php
Labels: enhancement

#15105 Ticket external ID
  install/migrations/update_10.0.x_to_10.1.0/ticket.php
  install/mysql/glpi-empty.sql
  src/Api/HL/Controller/ITILController.php
  templates/components/itilobject/fields_panel.html.twig
Labels: enhancement

#15228 Fix parent ID assignation in REST API
  src/Api/API.php
Labels: bug

#15180 Deprecate `DBmysql::truncate()` and `DBmysql::truncateOrDie()` methods
  CHANGELOG.md
  src/Console/Migration/AppliancesPluginToCoreCommand.php
  src/Console/Migration/RacksPluginToCoreCommand.php
  src/DBmysql.php
  src/NotImportedEmail.php
  tests/functional/Profile_User.php
Labels: iterator

#15226 fix(knowbase): load category from URL
  src/Knowbase.php
Labels: bug

#15235 Add missing hidden input for global_validation field
  src/Ticket.php
  tests/DbTestCase.php
  tests/RuleBuilder.php
  tests/bootstrap.php
  tests/functional/RuleTicket.php
Labels: bug

#15118 fix(kanban): preserve order by name
  src/Project.php
Labels: enhancement

#15194 fix(purge): better check
  src/CommonDBTM.php
Labels: bug, Need unit tests

#15172 Fix LDAP `use_bind` option label
  src/AuthLDAP.php
Labels: bug

#15239 fix(knowbase): tree persistence
  src/Knowbase.php
Labels: bug

#14974 feat(notifications): new document event
  install/empty_data.php
  src/Document.php
  src/NotificationTargetCommonITILObject.php
Labels: enhancement

#14789 feat(search): additional default filter
  ajax/search.php
  front/defaultfilter.form.php
  front/defaultfilter.php
  install/migrations/update_10.0.x_to_10.1.0/criteriafilter.php
  install/mysql/glpi-empty.sql
  src/DefaultFilter.php
  src/Dropdown.php
  src/Profile.php
  src/Search/CriteriaFilter.php
  src/Search/Input/QueryBuilder.php
  templates/components/search/controls.html.twig
  templates/components/search/query_builder/main.html.twig
  templates/generic_show_form.html.twig
Labels: enhancement

#15251 Add missing default delete domain rights
  install/empty_data.php
Labels: bug

#15263 Fix invalid search options datatypes
  src/CommonDBTM.php
  src/CommonITILTask.php
  src/DeviceCamera.php
  src/Infocom.php
  src/NetworkName.php
  src/NetworkPort.php
  src/ProjectTaskTemplate.php
  src/QueuedNotification.php
  src/TaskTemplate.php
  tests/functional/Search.php
Labels: bug

#15261 Search engine: use AJAX for toolips
  ajax/get_item_content.php
  src/CommonITILObject.php
  src/Html.php
  src/Search.php
Labels: bug

#15237 Ensure cache is clear when a plugin is activated/deactivated
  src/Dashboard/Grid.php
  src/Plugin.php
Labels: bug

#15234 fix(budget): Total remaining on the budget
  src/Budget.php
Labels: enhancement

#15275 Fix handling of `integer` search option datatype
  src/Search.php
  tests/functional/Search.php
Labels: bug

#15277 Enhance numeric search
  src/Search.php
  tests/functional/Search.php
Labels: enhancement

#15279 Fix and enhance date search
  src/Search.php
  tests/functional/Search.php
Labels: bug, enhancement

#15273 fix(saved search): 404 error
  src/SavedSearch.php
Labels: bug

#15283 Add link for RustDesk
  src/Item_RemoteManagement.php
Labels: enhancement

#15286 Fix "AND NOT null" search criteria
  src/Search.php
  tests/functional/Search.php
Labels: bug

#15282 fix(calendar input): week number not visible
  css/includes/components/_flatpickr.scss
Labels: bug

#15300 fix(ticket): FAQ article sliders
  css/includes/components/_richtext.scss
Labels: bug
