Repository glpi-project/glpi, pull requests merged in 2023-05, with the labels that each got.

#14639 build(deps): bump @tabler/icons-webfont from 2.13.1 to 2.17.0
  package-lock.json
  package.json
Labels: dependencies, javascript

#14640 Do not force download of HTML files
  src/Http/ProxyRouter.php
  tests/units/Glpi/Http/ProxyRouter.php
Labels: bug

#14649 Fix count and content of KB items tab
  src/KnowbaseItem_Item.php
Labels: bug

#14599 Improve kanban performances 2
  ajax/getUserPicture.php
  js/modules/Kanban/Kanban.js
Labels: bug

#14653 feat(VirtualMachine): display deleted link when needed
  src/ComputerVirtualMachine.php
Labels: enhancement, inventory

#14511 Improve plugins init performances
  src/Plugin.php
Labels: performance

#14643 fix(inventory): fix search / link between stacked switch and relateports
  src/Inventory/Asset/NetworkEquipment.php
  src/Inventory/Asset/NetworkPort.php
  tests/fixtures/inventories/dell_n3048p.xml
  tests/functional/Glpi/Inventory/Assets/NetworkEquipment.php
Labels: bug, inventory

#14660 Fix pending reason wrapping
  templates/components/itilobject/timeline/form_followup.html.twig
  templates/components/itilobject/timeline/form_task.html.twig
  templates/components/itilobject/timeline/pending_reasons.html.twig
Labels: bug

#14663 feat(core): pretty print json file
  src/Inventory/Inventory.php
Labels: enhancement, inventory

#14667 fix(network devices): add UUID in search
  src/NetworkEquipment.php
Labels: enhancement

#14669 Do not show create button for entities if no recursion
  src/Entity.php
Labels: bug

#14670 Fix project states colors
  templates/components/search/table.html.twig
  tests/DbTestCase.php
  tests/functional/Project.php
Labels: bug

#14685 fix(core): display checkbox for allasset view
  templates/components/search/table.html.twig
Labels: bug

#14681 Display expected sign option in DB diff
  src/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
  tests/units/Glpi/System/Diagnostic/DatabaseSchemaIntegrityChecker.php
Labels: enhancement

#14686 permit to query Lockedfield with api
  src/Lockedfield.php
Labels: bug

#14693 Remove code/usages deprecated in GLPI 10.0.x
  CHANGELOG.md
  front/ruleimportcomputer.form.php
  front/ruleimportcomputer.php
  inc/autoload.function.php
  inc/define.php
  phpstan.neon
  src/CommonDropdown.php
  src/GLPI.php
  src/Inventory/Conf.php
  src/MailCollector.php
  src/Netpoint.php
  src/RSSFeed.php
  src/RuleImportComputer.php
  src/RuleImportComputerCollection.php
  src/SLM.php
  src/System/Status/StatusChecker.php
  src/Toolbox.php
  tests/DbTestCase.php
  tests/functional/Glpi/System/Status/StatusChecker.php
  tests/functional/Transfer.php
  tests/imap/MailCollector.php
Labels: task

#14472 feat(Core): add new option to display name or completename for CommonTreeDropdown object
  inc/define.php
  install/empty_data.php
  install/migrations/update_10.0.7_to_10.0.8/configs.php
  install/mysql/glpi-empty.sql
  src/Config.php
  src/Entity.php
  src/Search.php
Labels: enhancement

#14700 Fix pending reasons wrap 2
  templates/components/itilobject/timeline/form_followup.html.twig
  templates/components/itilobject/timeline/form_task.html.twig
Labels: bug

#14497 fix(rule ticket): triggering action on actor update
  src/Ticket.php
  tests/functional/RuleTicket.php
Labels: bug

#14601 fix: missing category when change created from ticket
  src/CommonITILObject.php
Labels: bug

#14702 completly hide headings field in self-service interface when adding a doc to an existing ticket
  templates/components/itilobject/timeline/form_document_item.html.twig
Labels: ux

#13304 OAuth Server
  .gitignore
  .webpack.config.js
  composer.json
  composer.lock
  front/oauthclient.form.php
  front/oauthclient.php
  install/empty_data.php
  install/migrations/update_10.0.x_to_10.1.0/oauth.php
  install/mysql/glpi-empty.sql
  src/Api/HL/Controller/CoreController.php
  src/Api/HL/OpenAPIGenerator.php
  src/Api/HL/Router.php
  src/Auth.php
  src/Config.php
  src/GLPIKey.php
  src/Html.php
  src/Http/Request.php
  src/OAuth/AccessToken.php
  src/OAuth/AccessTokenRepository.php
  src/OAuth/AuthCode.php
  src/OAuth/AuthCodeRepository.php
  src/OAuth/Client.php
  src/OAuth/ClientRepository.php
  src/OAuth/RefreshToken.php
  src/OAuth/RefreshTokenRepository.php
  src/OAuth/Scope.php
  src/OAuth/ScopeRepository.php
  src/OAuth/Server.php
  src/OAuth/User.php
  src/OAuth/UserRepository.php
  src/OAuthClient.php
  src/Profile.php
  src/System/RequirementsManager.php
  src/Toolbox.php
  src/Update.php
  templates/pages/oauth/authorize.html.twig
  templates/pages/setup/oauthclient.html.twig
  tests/functional/Auth.php
  tests/functional/GLPIKey.php
  tests/functional/Glpi/Api/HL/Controller/CoreController.php
  tests/units/DB.php
  tests/units/Html.php
Labels: enhancement

#14709 Fix null handling for docs without files
  src/Document.php
Labels: bug

#14708 fix(Computer): fix antivirus not propagate from template
  src/Computer.php
  tests/functional/Computer.php
Labels: bug

#14487 Add some new API endpoints needed for Webhook feature
  src/Api/HL/Controller/AbstractController.php
  src/Api/HL/Controller/AssetController.php
  src/Api/HL/Controller/ComponentController.php
  src/Api/HL/Controller/ITILController.php
  src/Api/HL/Controller/ManagementController.php
  src/Api/HL/Controller/ProjectController.php
  src/Api/HL/Doc/Schema.php
  src/Api/HL/OpenAPIGenerator.php
  src/Api/HL/Router.php
  src/Api/HL/Search.php
  tests/functional/Glpi/Api/HL/Controller/AssetController.php
  tests/functional/Glpi/Api/HL/Controller/ComponentController.php
  tests/functional/Glpi/Api/HL/Controller/ITILController.php
  tests/functional/Glpi/Api/HL/Controller/ProjectController.php
Labels: enhancement

#14719 Fix select2 placeholder escaping
  src/Html.php
Labels: bug

#14717 added hook for dashboard filter front
  src/Dashboard/Filter.php
  src/Dashboard/Filters/AbstractFilter.php
  src/Dashboard/Filters/DatesFilter.php
  src/Dashboard/Filters/DatesModFilter.php
  src/Dashboard/Filters/GroupTechFilter.php
  src/Dashboard/Filters/ItilCategoryFilter.php
  src/Dashboard/Filters/LocationFilter.php
  src/Dashboard/Filters/ManufacturerFilter.php
  src/Dashboard/Filters/RequestTypeFilter.php
  src/Dashboard/Filters/StateFilter.php
  src/Dashboard/Filters/TicketTypeFilter.php
  src/Dashboard/Filters/UserTechFilter.php
  src/Dashboard/Grid.php
  src/Dashboard/Provider.php
Labels: enhancement

#14679 feat(core): Add user option to explicitly refuse all notifications
  inc/define.php
  install/empty_data.php
  install/migrations/update_10.0.x_to_10.1.0/user.php
  install/mysql/glpi-empty.sql
  src/CommonITILObject.php
  src/Config.php
  src/NotificationTarget.php
  src/NotificationTargetCommonITILObject.php
  src/NotificationTargetUser.php
  src/Ticket.php
  src/User.php
  templates/components/itilobject/actors/main.html.twig
  tests/functional/NotificationMailing.php
  tests/functional/Ticket.php
Labels: enhancement

#14606 Allow End of month/year for future date selections
  src/Html.php
Labels: enhancement

#14721 Add type for generic devices in components tab
  src/DeviceGeneric.php
Labels: enhancement

#14730 Update list of required extensions
  .composer-require-checker.config.json
  composer.json
  composer.lock
  src/System/RequirementsManager.php
Labels: bug, need_doc_improvement

#14756 Notifications: avoid divide by zero exception
  src/NotificationEventMailing.php
Labels: bug

#14752 Fix export link
  templates/components/search/controls.html.twig
Labels: bug

#14765 Clone reminders
  src/Reminder.php
Labels: enhancement

#14773 Fix SMTP OAuth callback on PHP 7.4
  front/smtp_oauth2_callback.php
Labels: bug

#14728 Update DevicePowerSupply.php
  src/DevicePowerSupply.php
Labels: enhancement

#14776 fix(search): &nbsp; visible in dropdown values
  src/Ticket.php
  tests/functional/ITILTemplate.php
Labels: bug

#14764 Improve kanban performances 3
  ajax/kanban.php
  src/CommonITILObject.php
Labels: bug, performance

#14777 Catch `\Throwable` instead of `\Exception`
  ajax/massiveaction.php
  front/inventory.php
  front/massiveaction.php
  src/Agent.php
  src/Auth.php
  src/AuthLDAP.php
  src/Dashboard/Grid.php
  src/Html.php
  src/Infocom.php
  src/Inventory/Asset/Software.php
  src/Inventory/Conf.php
  src/Inventory/Inventory.php
  src/MailCollector.php
  src/NotificationEventMailing.php
  src/SavedSearch.php
  src/SavedSearch_Alert.php
  src/System/Status/StatusChecker.php
  src/Toolbox.php
  src/Transfer.php
  tests/web/APIRest.php
  tests/web/APIXmlrpc.php
Labels: bug

#14746 Confirmation before uninstalling a plugin
  src/Marketplace/View.php
  src/Plugin.php
  templates/components/plugin_uninstall_modal.html.twig
Labels: enhancement

#14759 Document::canViewItem(): validate itemtype
  src/Document.php
  tests/functional/Document.php
Labels: bug

#14757 Do not login to STMP for each mail
  src/GLPIMailer.php
  src/MailCollector.php
  src/NotificationEventMailing.php
  tests/units/GLPIMailer.php
Labels: bug

#14785 Kanban: add missing join
  src/CommonITILObject.php
  src/DBmysqlIterator.php
  tests/units/DBmysqlIterator.php
Labels: bug

#14790 Add Business criticity search option
  src/Infocom.php
Labels: enhancement

#14793 fix(Dropdown): retrieve item recursivly
  src/ReservationItem.php
Labels: bug

#14799 fix(ComputerVM): recovers old behaviour when inventory handle a missing VM
  src/Inventory/Asset/VirtualMachine.php
  tests/functional/Glpi/Inventory/Assets/VirtualMachine.php
  tests/functional/Glpi/Inventory/Inventory.php
Labels: enhancement, inventory

#14747 Add "View new tickets" right
  install/empty_data.php
  install/migrations/update_10.0.x_to_10.1.0/ticket.php
  src/Search/Provider/SQLProvider.php
  src/Ticket.php
  tests/functional/Search.php
  tests/functional/Ticket.php
Labels: enhancement
