Repository glpi-project/glpi, pull requests merged in 2023-03, with the labels that each got.

#14182 IITLTimeline: hide "answer" button if not allowed to add followups
  templates/components/itilobject/footer.html.twig
Labels: bug

#14225 fix(Notification): harmonize date format from timeline item
  src/NotificationTargetCommonITILObject.php
  tests/functionnal/NotificationTargetTicket.php
Labels: bug

#14235 fix(UI): fix impact toolbar z-index
  css/legacy/includes/_impact.scss
Labels: bug

#14234 fix(UI): Display missing object header from template
  src/CommonGLPI.php
  templates/components/form/header_content.html.twig
Labels: bug

#14241 fix link for notes in logs
  front/notepad.form.php
Labels: bug

#14176 don't limit iframe when embedding dashboards
  css/includes/_base.scss
  front/central.php
  src/Html.php
Labels: bug

#14246 fix(template): wrong tab after page reloading
  src/Ajax.php
  src/Toolbox.php
Labels: bug

#14232 feat(global search): sort items by number of results
  front/search.php
Labels: enhancement

#14005 Normalize console command namespaces
  CHANGELOG.md
  src/Console/Application.php
  src/Console/CommandLoader.php
  src/Console/Plugin/ListCommand.php
  tests/units/Glpi/Console/CommandLoader.php
Labels: enhancement

#14258 fix(report): fix default report
  src/Report.php
Labels: bug

#14254 fix(inventory): revert old entities_id for agent too
  src/Inventory/Asset/MainAsset.php
  tests/functionnal/Glpi/Inventory/Assets/Computer.php
Labels: bug, inventory

#14256 fix(Approval): ##object.urlvalidation## return bad redirect
  src/NotificationTargetChange.php
  src/NotificationTargetTicket.php
Labels: bug

#14262 fix(inventory): add virtual networkcard IP if needed
  src/Inventory/Asset/MainAsset.php
  tests/functionnal/Glpi/Inventory/Inventory.php
Labels: bug

#13197 PHP router to expose only public directory
  public/index.php
  src/Central.php
  src/Console/System/CheckRequirementsCommand.php
  src/Http/ProxyRouter.php
  src/System/Requirement/DataDirectoriesProtectedPath.php
  src/System/Requirement/SafeDocumentRoot.php
  src/System/RequirementsManager.php
  tests/units/Glpi/Http/ProxyRouter.php
  tests/units/Glpi/System/Requirement/DataDirectoriesProtectedPath.php
Labels: security

#14077 add key on level column for CommonTreeDropdowns
  install/migrations/update_10.0.6_to_10.0.7/indexes.php
  install/mysql/glpi-empty.sql
  src/System/Diagnostic/DatabaseKeysChecker.php
Labels: performance

#14227 feat(Ruleticket): add Project assign to RuleTicket action
  src/RuleTicket.php
  src/SlaLevel_Ticket.php
  src/Ticket.php
  tests/functionnal/Rule.php
  tests/functionnal/RuleTicket.php
  tests/functionnal/SlaLevel_Ticket.php
Labels: enhancement

#14230 fix(ticket): check user exist before link
  src/CommonITILActor.php
  tests/bootstrap.php
  tests/functionnal/Project.php
  tests/functionnal/ProjectTask.php
  tests/functionnal/Ticket.php
Labels: bug

#14244 feat(notification template): add missing location tags
  src/NotificationTargetTicket.php
Labels: bug

#14271 build(deps): bump @tabler/icons-webfont from 2.4.0 to 2.8.0
  package-lock.json
  package.json
Labels: dependencies

#14204 fix(core): globally prohibit massive action if necessary
  src/CommonDBTM.php
  src/User.php
  templates/components/form/single-action.html.twig
  templates/components/search/table.html.twig
Labels: bug

#14268 fix(ticket): approving solution
  src/ITILFollowup.php
  tests/functionnal/ITILSolution.php
Labels: bug

#13684 Search engine: fix negative conditions on linked children
  src/CommonITILObject.php
  src/Search.php
  tests/functionnal/Search.php
Labels: bug

#14181 feat(inventory): ability to import multiple inventory files
  CHANGELOG.md
  composer.lock
  front/inventory.conf.php
  src/Inventory/Conf.php
  src/Marketplace/Controller.php
  templates/pages/admin/inventory/upload_form.html.twig
  templates/pages/admin/inventory/upload_result.html.twig
  tests/functionnal/Glpi/Inventory/Inventory.php
Labels: enhancement

#14272 Upgrade `monolog/monolog` to 3.3
  CHANGELOG.md
  composer.json
  composer.lock
  src/GLPI.php
  src/Toolbox.php
  tests/GLPITestCase.php
  tests/src/Log/TestHandler.php
  tests/units/Glpi/Application/ErrorHandler.php
Labels: dependencies

#14291 Fix getAllDasboardCards cache
  src/Dashboard/Grid.php
  src/Session.php
Labels: bug

#14287 fix(Transfer): fix entities_id not update for SoftwareVersion
  src/Transfer.php
  tests/functionnal/Transfer.php
Labels: bug

#14284 fix(inventory): software are still transfer even if not allowwed
  src/Inventory/Asset/MainAsset.php
  tests/functionnal/Glpi/Inventory/Assets/Computer.php
Labels: bug

#14294 ITIL Kanban: Fix error for empties columns
  src/CommonITILObject.php
Labels: bug

#14297 feat(SoftwareLicense): add missing 'Number of installations' SO
  src/SoftwareLicense.php
Labels: enhancement

#14238 Improve form for the "Add new task" massive action
  css/legacy/includes/_styles.scss
  src/CommonITILObject.php
  src/CommonITILTask.php
  src/Html.php
  templates/components/form/fields_macros.html.twig
  templates/components/itilobject/timeline/form_task.html.twig
  templates/components/itilobject/timeline/form_task_main_form.html.twig
  templates/components/massive_action/add_task.html.twig
Labels: enhancement

#13018 Fix database relations handling
  CHANGELOG.md
  inc/define.php
  inc/relation.constant.php
  src/CommonDBTM.php
  src/CommonDropdown.php
  src/CommonITILTask.php
  src/Computer.php
  src/Consumable.php
  src/Dashboard/Item.php
  src/Dashboard/Right.php
  src/DbUtils.php
  src/ImageFormat.php
  src/ImageResolution.php
  src/Infocom.php
  src/Item_Cluster.php
  src/Item_DeviceCamera.php
  src/Item_Enclosure.php
  src/Item_Rack.php
  src/KnowbaseItemCategory.php
  src/Monitor.php
  src/NetworkEquipment.php
  src/NetworkPort.php
  src/NetworkPortConnectionLog.php
  src/OperatingSystem.php
  src/PendingReason.php
  src/Peripheral.php
  src/Phone.php
  src/PlanningExternalEvent.php
  src/Printer.php
  src/ProjectTask.php
  src/Reminder.php
  src/Software.php
  src/SoftwareLicense.php
  src/Ticket.php
  src/Unmanaged.php
  src/User.php
  tests/functionnal/CommonDBTM.php
  tests/functionnal/DbUtils.php
Labels: bug

#12221 High-level API
  .composer-require-checker.config.json
  api.php
  composer.json
  composer.lock
  inc/autoload.function.php
  lib/bundles/swagger-ui.js
  package.json
  src/Agent/Communication/AbstractRequest.php
  src/Api/APIRest.php
  src/Api/HL/Controller/AbstractController.php
  src/Api/HL/Controller/AdministrationController.php
  src/Api/HL/Controller/AssetController.php
  src/Api/HL/Controller/CRUDControllerTrait.php
  src/Api/HL/Controller/CoreController.php
  src/Api/HL/Controller/ITILController.php
  src/Api/HL/Controller/ManagementController.php
  src/Api/HL/Doc/Parameter.php
  src/Api/HL/Doc/Response.php
  src/Api/HL/Doc/Route.php
  src/Api/HL/Doc/Schema.php
  src/Api/HL/Doc/SchemaReference.php
  src/Api/HL/Middleware/AbstractMiddleware.php
  src/Api/HL/Middleware/CRUDRequestMiddleware.php
  src/Api/HL/Middleware/DebugRequestMiddleware.php
  src/Api/HL/Middleware/DebugResponseMiddleware.php
  src/Api/HL/Middleware/MiddlewareInput.php
  src/Api/HL/Middleware/RSQLRequestMiddleware.php
  src/Api/HL/Middleware/RequestMiddlewareInterface.php
  src/Api/HL/Middleware/ResponseMiddlewareInterface.php
  src/Api/HL/Middleware/SecurityResponseMiddleware.php
  src/Api/HL/OpenAPIGenerator.php
  src/Api/HL/RSQLInput.php
  src/Api/HL/Route.php
  src/Api/HL/RoutePath.php
  src/Api/HL/Router.php
  src/Config.php
  src/Http/JSONResponse.php
  src/Http/ProxyRouter.php
  src/Http/Request.php
  src/Http/Response.php
  src/Plugin/Hooks.php
  src/System/Status/StatusChecker.php
  tests/HLAPITestCase.php
  tests/bootstrap.php
  tests/functionnal/Glpi/Api/HL/Controller/AdministrationController.php
  tests/functionnal/Glpi/Api/HL/Controller/AssetController.php
  tests/functionnal/Glpi/Api/HL/Controller/CoreController.php
  tests/functionnal/Glpi/Api/HL/Controller/ITILController.php
  tests/functionnal/Glpi/Api/HL/Controller/ManagementController.php
  tests/functionnal/Glpi/Api/HL/Doc/Schema.php
  tests/functionnal/Glpi/Api/HL/Router.php
  webpack.config.js
Labels: enhancement

#14322 Remove useless polyfills
  composer.json
  composer.lock
  src/Config.php
Labels: dependencies, php

#14301 fix(KnowbaseItem): fix a regression on boolean operators removal
  src/KnowbaseItem.php
  tests/bootstrap.php
  tests/functionnal/KnowbaseItem.php
Labels: bug

#14330 Update `webpack` to get security fixes
  package-lock.json
Labels: security, dependencies, javascript

#14338 Fix missing rateit lib for stats
  inc/define.php
Labels: bug

#14346 fix(ticket): wrong content when create from project task
  src/Ticket.php
Labels: bug

#14352 add missing softwarelicense cache fields
  install/migrations/update_10.0.6_to_10.0.7/softwarelicense.php
  install/mysql/glpi-empty.sql
  src/System/Diagnostic/DatabaseSchemaConsistencyChecker.php
Labels: bug

#14344 Handle domains on inventory
  install/migrations/update_10.0.6_to_10.0.7/domains_items.php
  install/mysql/glpi-empty.sql
  src/Domain_Item.php
  src/Inventory/Asset/MainAsset.php
  src/Lock.php
  tests/functionnal/Glpi/Inventory/Assets/Computer.php
Labels: enhancement

#14347 Fix invalid cache after moving entity under root
  src/CommonTreeDropdown.php
Labels: bug

#14368 fix(NetworkPort): remove comments on NetworkPort dropdown
  ajax/cable.php
Labels: bug

#14365 Use filters for new dashboard cards
  js/dashboard.js
Labels: bug

#14374 Fix SNMP credentials encoding issues
  front/snmpcredential.form.php
  src/GLPIKey.php
  tests/FrontBaseClass.php
  tests/functionnal/GLPIKey.php
  tests/web/SNMPCredential.php
Labels: bug

#14387 Fix: Cannot export item_devicetype (item_devicesimcard, etc...)
  front/report.dynamic.php
Labels: bug

#14395 Add `Phar` extension in marketplace optional requirements
  src/System/RequirementsManager.php
Labels: enhancement

#14401 Suggest to use an officially supported PHP version
  src/System/Requirement/PhpSupportedVersion.php
  src/System/RequirementsManager.php
  tests/units/Glpi/System/Requirement/PhpSupportedVersion.php
Labels: security

#14406 feat(Notification): add missing solution author tag
  src/NotificationTargetCommonITILObject.php
Labels: enhancement

#14404 Fix missing history entry when adding a user to a group
  src/Group_User.php
Labels: bug

#14418 drop global var for uploads indexation
  js/fileupload.js
Labels: bug

#14413 fix(massive action): check all
  js/common.js
  src/Html.php
  templates/components/search/table.html.twig
Labels: bug

#14419 Fix PHP 8.1 warning on floating numbers dropdown
  src/Dropdown.php
Labels: bug

#14415 Update `glpi-project/inventory_format`
  composer.lock
  tests/functional/Glpi/Inventory/Inventory.php
Labels: inventory

#14432 Fix dashboard fitler css conflict
  css/standalone/dashboard.scss
Labels: bug

#14434 fix: check agent rights to trigger status/inventory
  ajax/agent.php
Labels: bug
