Repository glpi-project/glpi, pull requests merged in 2023-10, with the labels that each got.

#15654 Add `sub_type` search option to rules
  src/Rule.php
  tests/functional/Rule.php
Labels: enhancement, feature suggestion

#15640 fix(ui): fix long content overflow
  css/includes/components/_richtext.scss
Labels: bug, ux

#15643 feat(Transfer): add new option for location field
  install/migrations/update_10.0.10_to_10.0.11/transfer.php
  install/mysql/glpi-empty.sql
  src/Transfer.php
  tests/functional/Transfer.php
Labels: enhancement

#15683 feat(SLA / OLA): increase maximum time
  src/LevelAgreement.php
Labels: enhancement

#15687 fix(fuzzy): main entries before subentries and dashboards
  src/Html.php
Labels: bug

#15696 Display pending reason in tickets details
  templates/components/itilobject/fields/status.html.twig
  templates/components/itilobject/timeline/pending_reasons_messages.html.twig
Labels: ux

#15697 fix(LockedField): do not save value for global lockedfield
  install/migrations/update_10.0.10_to_10.0.11/lockedfield.php
  src/CommonDBTM.php
  src/Lockedfield.php
  tests/functional/Lockedfield.php
Labels: bug, inventory

#15635 Fix LDAP delete/restore conditions
  src/AuthLDAP.php
  src/User.php
Labels: bug

#15701 fix group formats in API listSearchOptions
  src/Api/API.php
  src/Search.php
Labels: api

#15176 Modularize and test dashboards JS
  .eslintrc.json
  CHANGELOG.md
  js/dashboard.js
  js/modules/Dashboard/Dashboard.js
  src/Dashboard/Filter.php
  src/Dashboard/Filters/AbstractFilter.php
  src/Dashboard/Filters/DatesFilter.php
  src/Dashboard/Filters/DatesModFilter.php
  src/Dashboard/Widget.php
  tests/js/bootstrap.mjs
  tests/js/modules/Dashboard/Dashboard.test.js
Labels: javascript

#15705 Display pending reason in tickets details 2
  templates/components/itilobject/timeline/pending_reasons_messages.html.twig
Labels: ux

#15704 feat(ticket rules): add requester's manager
  src/CommonITILObject.php
  src/DbUtils.php
  src/RuleAction.php
  src/RuleCommonITILObject.php
  tests/functional/RuleTicket.php
Labels: enhancement

#15703 Fix LDAP unlimited timeout value
  src/AuthLDAP.php
Labels: bug

#15715 Allow pending reason edition from new fup/task form
  src/CommonITILTask.php
  src/ITILFollowup.php
  src/PendingReason_Item.php
  templates/components/itilobject/timeline/form_followup.html.twig
  templates/components/itilobject/timeline/pending_reasons.html.twig
  tests/functional/PendingReason.class.php
Labels: bug

#15720 Fix handling of null values during updates
  src/CommonDBTM.php
  src/Log.php
  tests/functional/CommonDBTM.php
Labels: bug

#15722 fix(planning): error with change tasks
  src/CommonITILTask.php
Labels: bug

#15726 fix(Change): handle HTML from searchoption
  src/Change.php
Labels: bug, ux

#15733 fix(migration 10.0.9 to 10.0.10): PHP Error Allowed memory size
  install/migrations/update_10.0.9_to_10.0.10/ldap_fields.php
Labels: bug

#15735 Trigger a warning when an updatable field does not exist
  src/CommonDBTM.php
  tests/functional/CommonDBTM.php
Labels: bug

#15743 fix(Inventory): add ruleMatchedLog on update too
  src/Inventory/Asset/NetworkPort.php
  tests/functional/Glpi/Inventory/Assets/NetworkEquipment.php
Labels: bug, inventory

#15745 fix(Inventory): purge useless Domain instead of delete it
  src/Inventory/Asset/MainAsset.php
  tests/functional/Glpi/Inventory/Assets/Computer.php
Labels: bug, inventory

#15746 fix(Inventory): prevent SQL warning on load lockedfields
  src/Inventory/Asset/InventoryAsset.php
  tests/functional/Glpi/Inventory/Assets/Firmware.php
Labels: bug, inventory

#15757 fix: Adds a "disabled" option to the dashboard preferences for tickets
  src/Config.php
  src/Dashboard/Grid.php
Labels: enhancement

#15754 fix(dashboard): Data error on "tickets by agreement status and technician group" graph
  src/Dashboard/Provider.php
  tests/units/Glpi/Dashboard/Provider.php
Labels: bug

#15739 Fix header not displaying root entity name
  templates/components/form/header_content.html.twig
Labels: bug

#15771 Fix invalid PHPdoc
  src/Html.php
Labels: bug

#15768 use internal auth for webhook api access
  src/Api/HL/Middleware/InternalAuthMiddleware.php
  src/Webhook.php
Labels: api

#15783 Add missing 'timeline_position' index to Document_Item
  install/migrations/update_10.0.10_to_10.0.11/fix_document_item_index.php
  install/mysql/glpi-empty.sql
Labels: bug

#15794 Split entity selector cache entries
  ajax/entitytreesons.php
Labels: performance

#15803 don't break header layout when global search is disabled
  templates/layout/parts/global_search_form.html.twig
  templates/layout/parts/page_header.html.twig
Labels: ux

#15809 Fix error on 10.0.2 -> 10.0.3 migration
  install/migrations/update_10.0.2_to_10.0.3/notifications.php
Labels: bug

#15814 Added Note field for reservation notification template
  src/NotificationTargetReservation.php
Labels: enhancement

#15811 fix(inventory): restoring fields
  install/migrations/update_10.0.10_to_10.0.11/item_operatingsystem.php
  install/mysql/glpi-empty.sql
  src/Inventory/Asset/MainAsset.php
  src/Inventory/Asset/OperatingSystem.php
  templates/pages/assets/operatingsystem.html.twig
  tests/functional/Glpi/Inventory/Assets/OperatingSystem.php
Labels: inventory

#15779 Create massive action to add and remove a domain to a computer
  src/Computer.php
  src/Domain.php
  tests/functional/MassiveAction.php
  tests/web/APIRest.php
Labels: enhancement

#15782 keep filename when updating document
  src/CommonDBTM.php
  tests/functional/CommonDBTM.php
Labels: bug

#15827 Fix dashboards overwriting session search criteria
  src/Dashboard/Widget.php
Labels: bug

#15785 feat: Refactor SMTP test email functionality and add debug logs modal
  CHANGELOG.md
  ajax/notificationmailingsettings.php
  front/notificationmailingsetting.form.php
  src/GLPIMailer.php
  src/MailCollector.php
  src/NotificationEventMailing.php
  src/NotificationMailing.php
  templates/pages/setup/notification/mailing_setting.html.twig
Labels: enhancement

#15830 Do not trust session cookie configuration on CLI context
  src/System/Requirement/SessionsSecurityConfiguration.php
  tests/units/Glpi/System/Requirement/SessionsSecurityConfiguration.php
Labels: security

#15748 fix(Rule): do not import as refused equipement if rule denied with no log
  src/Inventory/Asset/MainAsset.php
  src/RuleImportAsset.php
  templates/pages/admin/inventory/upload_result.html.twig
  tests/functional/Glpi/Inventory/Inventory.php
Labels: bug, inventory

#15456 feat(reservation): comment display
  src/Reservation.php
  src/ReservationItem.php
  templates/components/form/reservation.html.twig
  templates/components/form/reservationitem_comment.html.twig
Labels: enhancement

#15793 Fix data directories safeness check
  src/System/Requirement/DataDirectoriesProtectedPath.php
  tests/units/Glpi/System/Requirement/DataDirectoriesProtectedPath.php
Labels: bug

#15482 Feature : rewriting satisfaction form in twig
  src/CommonITILSatisfaction.php
  templates/components/itilobject/itilsatisfaction.html.twig
Labels: ux

#15847 Fix MFA performances
  src/Security/PermissionManager.php
Labels: bug

#15849 fix(RuleTicket): ticket category code criterion
  src/RuleTicket.php
  src/RuleTicketCollection.php
  tests/functional/RuleTicket.php
Labels: bug

#15850 Add inventory disable message if it disable
  src/Inventory/Conf.php
Labels: enhancement

#15566 Notifications url base
  install/migrations/update_10.0.x_to_10.1.0/entity.php
  install/mysql/glpi-empty.sql
  src/Entity.php
  src/NotificationTarget.php
  src/NotificationTargetUser.php
  src/User.php
  templates/pages/admin/entity/notifications.html.twig
  tests/functional/NotificationTarget.php
  tests/functional/NotificationTargetTicket.php
Labels: enhancement

#15840 Prevent TinyMCE to remove styles when content is pasted from a template
  js/fileupload.js
Labels: javascript

#15887 Prevent cache dir to be filled by temporary files
  composer.lock
Labels: bug

#15852 Fix Task Duration Update Behavior in CommonITILTask
  src/CommonITILTask.php
  tests/functional/TicketTask.php
Labels: bug

#15874 `getTableForItemType()` must support `CommonDBTM::getTable()` overrides
  src/CommonDBTM.php
  src/DbUtils.php
  tests/functional/DbUtils.php
Labels: bug

#15723 feat(Notification): no resize for email attachment
  CHANGELOG.md
  front/document.send.php
  src/Api/HL/Controller/ManagementController.php
  src/Document.php
  src/NotificationEventMailing.php
Labels: enhancement
