Repository glpi-project/glpi, pull requests merged in 2023-08, with the labels that each got.

#15294 fix(group): restore cloning
  src/Group.php
Labels: enhancement

#15288 Prevent last super admin profile from changing interface
  src/Profile.php
  tests/functional/Profile.php
Labels: enhancement

#15339 feat(user): add clean LDAP fields massive action
  src/User.php
Labels: enhancement

#15342 fix(reservation): itemtype list empty
  src/ReservationItem.php
Labels: bug

#15298 fix(user): used items list
  src/User.php
Labels: bug

#14925 PHP 8.3 support
  .github/workflows/ci.yml
  composer.json
  inc/define.php
  index.php
  tools/patches/atoum-4.1.0...4.2.0.patch
Labels: enhancement

#15356 MySQL 8.1 support
  .github/workflows/ci.yml
  tests/run_tests.sh
Labels: enhancement

#15343 Avoid costly calls to Toolbox::getAvailableTabs()
  ajax/common.tabs.php
  ajax/updatecurrenttab.php
  src/Ajax.php
Labels: performance

#15337 feat(projecttask): Adding massives actions: update, clone, trashbin
  front/projecttask.form.php
  install/empty_data.php
  install/migrations/update_10.0.x_to_10.1.0/projecttask.php
  install/mysql/glpi-empty.sql
  src/ProjectTask.php
  tests/functional/Glpi/Api/HL/Controller/ProjectController.php
Labels: enhancement

#15276 Add vuejs support
  .eslintrc.json
  .vue.webpack.config.js
  composer.lock
  js/src/vue/app.js
  package-lock.json
  package.json
  src/Html.php
Labels: dependencies, javascript

#15297 Fix private followups/tasks filtering in notifications
  src/CommonITILObject.php
  tests/functional/Ticket.php
Labels: bug

#14964 feat(notifications): attached documents
  CHANGELOG.md
  ajax/dropdownNotificationEvent.php
  install/migrations/update_10.0.x_to_10.1.0/notifications.php
  install/mysql/glpi-empty.sql
  js/common.js
  src/CommonITILSatisfaction.php
  src/CommonITILTask.php
  src/CommonITILValidation.php
  src/CommonITILValidationCron.php
  src/ITILFollowup.php
  src/Notification.php
  src/NotificationEvent.php
  src/NotificationEventAbstract.php
  src/NotificationEventInterface.php
  src/NotificationEventMailing.php
  src/NotificationMailing.php
  src/NotificationMailingSetting.php
  src/NotificationSetting.php
  src/PlanningRecall.php
  src/RichText/UserMention.php
  templates/components/form/basic_inputs_macros.html.twig
  templates/components/form/fields_macros.html.twig
  templates/pages/setup/notification/mailing_setting.html.twig
  templates/pages/setup/notification/notification.html.twig
  tests/functional/Notification.php
  tests/functional/NotificationEventAjax.php
  tests/functional/NotificationMailing.php
Labels: enhancement

#15382 Fix default dashboard computation
  src/Dashboard/Grid.php
Labels: performance

#14875 feat(search): check field pattern
  css/includes/components/_search_input.scss
  src/Search/Input/QueryBuilder.php
  src/Search/Provider/SQLProvider.php
  tests/functional/Search.php
  tests/units/Glpi/Search/Input/QueryBuilder.php
Labels: enhancement

#15383 fix(user): error message in debug mode
  src/Dropdown.php
Labels: bug

#15385 Fix LDAP connection using certificate files
  src/AuthLDAP.php
Labels: bug

#15285 fix(dropdown): sort by entity
  src/Dropdown.php
Labels: enhancement

#15287 fix(document): recursivity when added from knowbase
  src/CommonDBTM.php
Labels: bug

#15348 Reduce timeline SQL requests
  src/CommonITILObject.php
  src/ITILFollowup.php
  src/ITILSolution.php
  templates/components/itilobject/timeline/timeline.html.twig
Labels: performance

#15384 fix(user): authorization cloning
  src/Features/Clonable.php
  tests/functional/User.php
Labels: bug

#15357 Fix escalation levels computation
  src/Calendar.php
  src/CalendarSegment.php
  src/LevelAgreement.php
  src/LevelAgreementLevel.php
  tests/functional/Calendar.php
  tests/functional/CommonITILRecurrent.php
  tests/functional/SLM.php
Labels: bug

#15391 Fix ITIL actors count
  src/CommonITILObject.php
  tests/functional/Ticket.php
Labels: bug

#15394 Fix cartridge icon
  src/Cartridge.php
Labels: bug

#15399 fix(user): clean input for cloning
  src/User.php
Labels: bug

#15292 Migrate transfer forms to Twig
  src/RuleCollection.php
  src/Transfer.php
  templates/generic_show_form.html.twig
  templates/pages/admin/transfer.html.twig
  templates/pages/admin/transfer_list.html.twig
Labels: enhancement

#15388 Lazy load actors
  src/CommonITILObject.php
  tests/functional/Ticket.php
Labels: bug, performance

#15293 Migrate group and group LDAP forms to Twig
  src/Group.php
  templates/pages/admin/group.html.twig
  templates/pages/admin/group_ldap.html.twig
Labels: enhancement

#15376 Export printer graph data
  front/printerlogcsv.php
  src/Csv/PrinterLogCsvExport.php
  src/PrinterLog.php
  templates/components/printer_graph_buttons.html.twig
Labels: enhancement

#15386 Fix multiple validation with uploaded files
  src/Document.php
Labels: bug

#15280 Use search engine to display consumables
  CHANGELOG.md
  css/includes/pages/_search.scss
  install/empty_data.php
  install/migrations/update_10.0.x_to_10.1.0/consumable.php
  src/Consumable.php
  src/MassiveAction.php
  src/Search/Input/QueryBuilder.php
  src/Search/Output/HTMLSearchOutput.php
  src/Search/Provider/SQLProvider.php
  src/Search/SearchEngine.php
  templates/components/search/controls.html.twig
  templates/components/search/display_data.html.twig
  templates/components/search/query_builder/main.html.twig
  templates/components/search/table.html.twig
  templates/pages/assets/consumable_list.html.twig
Labels: enhancement

#15451 fix(RuleCriteria): unsanitize field when try to match
  src/RuleCriteria.php
  tests/functional/Rule.php
Labels: bug

#15457 login can be an email (+ char accepted)
  src/Auth.php
  tests/functional/Auth.php
Labels: bug, Need unit tests

#15448 Equipment collision in rack due to model modification
  src/CommonDCModelDropdown.php
  tests/functional/Item_Rack.php
Labels: bug
