Repository glpi-project/glpi, pull requests merged in 2023-12, with the labels that each got.

#16142 Fix recurrent ticket computation when start_date is outside of calendar
  src/Calendar.php
  src/CommonITILRecurrent.php
  tests/functional/CommonITILRecurrent.php
Labels: bug

#16138 Fix associated items not found in DB instances
  src/DatabaseInstance.php
Labels: bug

#16146 enhance db create msg during install
  install/install.php
Labels: enhancement

#16141 fix(pending-reasons): make notifications recursive and escape fields
  install/empty_data.php
  install/migrations/update_10.0.x_to_10.1.0/notifications.php
Labels: bug

#16084 Fix category filter in tickets Kanban
  src/CommonITILObject.php
Labels: bug

#16061 Monaco editors for webhook url and headers
  js/modules/Monaco/MonacoEditor.js
  src/Webhook.php
  templates/components/form/fields_macros.html.twig
  templates/pages/setup/webhook/webhook.html.twig
  templates/pages/setup/webhook/webhook_headers.html.twig
Labels: javascript

#16034 Add the possibility to see the result of satisfaction survey once expired
  src/CommonITILObject.php
  src/CommonITILSatisfaction.php
  templates/components/itilobject/itilsatisfaction.html.twig
Labels: enhancement, ux

#16054 feat(search-option): add lock status search option
  src/Application/View/TemplateRenderer.php
  src/ObjectLock.php
Labels: enhancement

#16033 Association of a technician with a ticket if he is assigned a ticket task
  src/CommonITILTask.php
  tests/functional/CommonITILTask.php
  tests/functional/Ticket.php
Labels: enhancement

#16026 Fix notification entity restriction
  src/NotificationTarget.php
  tests/functional/Notification.php
Labels: bug

#16159 Fix(ticket kanban): Add column do nothing
  js/modules/Kanban/Kanban.js
Labels: bug

#16182 fix(SearchOption): change type for IP and MAC
  src/RefusedEquipment.php
Labels: bug, inventory

#16176 fix(Unmanaged): do not empty status of the converted asset, when it's brought up from discovery
  src/Inventory/Asset/Unmanaged.php
  tests/functional/Glpi/Inventory/Assets/Unmanaged.php
Labels: inventory

#16185 Allow LDAP sync command to sync emails
  src/User.php
Labels: bug

#16190 make timeline private state more clear
  css/includes/components/itilobject/_timeline.scss
  templates/components/form/fields_macros.html.twig
  templates/components/itilobject/answer.html.twig
  templates/components/itilobject/timeline/form_followup.html.twig
  templates/components/itilobject/timeline/form_task_main_form.html.twig
  templates/components/itilobject/timeline/timeline.html.twig
  templates/components/itilobject/timeline/timeline_item_header.html.twig
Labels: enhancement, ux

#16193 fix(inventory): prevent warning message
  src/HTMLTableEntity.php
Labels: bug

#16194 fix(ldap): do not check TLS files if empty
  src/AuthLDAP.php
Labels: bug

#15861 Feat/search ux
  ajax/search.php
  css/includes/_base.scss
  css/includes/pages/_search.scss
  css/legacy/includes/_styles.scss
  inc/define.php
  install/empty_data.php
  install/migrations/update_10.0.x_to_10.1.0/user.php
  install/mysql/glpi-empty.sql
  js/modules/Search/Table.js
  src/Html.php
  src/Search.php
  src/Search/CriteriaFilter.php
  src/Search/Input/QueryBuilder.php
  src/Search/Output/HTMLSearchOutput.php
  src/Search/Output/MapSearchOutput.php
  src/Search/SearchEngine.php
  src/Ticket.php
  templates/components/search/controls.html.twig
  templates/components/search/display_data.html.twig
  templates/components/search/query_builder/criteria.html.twig
  templates/components/search/query_builder/criteria_group.html.twig
  templates/components/search/query_builder/main.html.twig
  templates/components/search/query_builder/metacriteria.html.twig
  templates/components/search/query_builder/sort/criteria.html.twig
  templates/components/search/query_builder/sort/main.html.twig
  templates/components/search/table.html.twig
  templates/layout/parts/context_links.html.twig
  templates/pages/admin/log_viewer.html.twig
  templates/pages/setup/general/preferences_setup.html.twig
  templates/pages/tools/savedsearch/save_button.html.twig
  tests/js/modules/Search/Table.test.js
Labels: enhancement, ux

#16204 fix:(search): division by zero
  src/Search.php
Labels: bug

#16209 Do not add duplicate hidden field input in rule test mode
  src/Rule.php
Labels: bug

#16173 Fix to use getPendings on QueueNotification
  src/QueuedNotification.php
Labels: bug

#16197 fix(object lock): duplicate keys in search options
  install/migrations/update_10.0.11_to_10.0.12.php
  install/migrations/update_10.0.11_to_10.0.12/duplicate_searchopt_fixes.php
  src/ObjectLock.php
  tests/functional/Search.php
Labels: bug

#16214 Prevent useless optional/out of context requirement checks
  src/System/Requirement/AbstractRequirement.php
  src/System/Requirement/DataDirectoriesProtectedPath.php
  src/System/Requirement/DbConfiguration.php
  src/System/Requirement/DbEngine.php
  src/System/Requirement/DbTimezones.php
  src/System/Requirement/DirectoriesWriteAccess.php
  src/System/Requirement/DirectoryWriteAccess.php
  src/System/Requirement/Extension.php
  src/System/Requirement/ExtensionConstant.php
  src/System/Requirement/ExtensionGroup.php
  src/System/Requirement/InstallationNotOverriden.php
  src/System/Requirement/IntegerSize.php
  src/System/Requirement/LogsWriteAccess.php
  src/System/Requirement/MemoryLimit.php
  src/System/Requirement/PhpSupportedVersion.php
  src/System/Requirement/PhpVersion.php
  src/System/Requirement/ProtectedWebAccess.php
  src/System/Requirement/SafeDocumentRoot.php
  src/System/Requirement/SeLinux.php
  src/System/Requirement/SessionsConfiguration.php
  src/System/Requirement/SessionsSecurityConfiguration.php
  src/System/RequirementsList.php
Labels: bug

#16222 Fix(inventory): add history on Computer_Item add when Mainasset already exist
  src/Inventory/Asset/InventoryAsset.php
  tests/functional/Glpi/Inventory/Assets/Monitor.php
Labels: bug, inventory

#15729 Generic assets with basic features
  CHANGELOG.md
  front/asset/asset.form.php
  front/asset/asset.php
  front/asset/assetdefinition.form.php
  front/asset/assetdefinition.php
  front/report.infocom.conso.php
  front/report.infocom.php
  inc/includes.php
  inc/relation.constant.php
  install/migrations/update_10.0.x_to_10.1.0/assets.php
  install/mysql/glpi-empty.sql
  src/Asset/Asset.php
  src/Asset/AssetDefinition.php
  src/Asset/AssetDefinitionManager.php
  src/Asset/Capacity/AbstractCapacity.php
  src/Asset/Capacity/CapacityInterface.php
  src/Asset/Capacity/HasDocumentsCapacity.php
  src/Asset/Capacity/HasHistoryCapacity.php
  src/Asset/Capacity/HasInfocomCapacity.php
  src/Asset/Capacity/HasNotepadCapacity.php
  src/CommonDBRelation.php
  src/CommonDBTM.php
  src/CommonGLPI.php
  src/CommonItilObject_Item.php
  src/ContentTemplates/Parameters/UserParameters.php
  src/Dashboard/Provider.php
  src/DbUtils.php
  src/Dropdown.php
  src/Group.php
  src/Html.php
  src/Location.php
  src/ProfileRight.php
  src/Report.php
  src/RuleImportAsset.php
  src/Search/Input/QueryBuilder.php
  src/Search/Provider/SQLProvider.php
  src/Search/SearchOption.php
  src/User.php
  templates/components/checkbox_matrix.html.twig
  templates/components/form/basic_inputs_macros.html.twig
  templates/components/search/map.html.twig
  templates/components/search/query_builder/main.html.twig
  templates/layout/parts/saved_searches.html.twig
  templates/pages/admin/assetdefinition/capacities.html.twig
  templates/pages/admin/assetdefinition/main.html.twig
  templates/pages/admin/assetdefinition/profiles.html.twig
  templates/pages/assets/asset.html.twig
  tests/DbTestCase.php
  tests/GLPITestCase.php
  tests/functional/Glpi/Asset/Asset.php
  tests/functional/Glpi/Asset/AssetDefinition.php
  tests/functional/Glpi/Asset/AssetDefinitionManager.php
  tests/functional/Glpi/Asset/Capacity/HasDocumentsCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasHistoryCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasInfocomCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasNotepadCapacity.php
  tests/functional/Notification.php
  tests/functional/Search.php
  tests/units/DB.php
  tests/units/Html.php
Labels: enhancement

#16239 fix(NetworkPort): update 'ifalias' if needed
  src/Inventory/Asset/InventoryNetworkPort.php
  src/NetworkPort.php
  tests/functional/Glpi/Inventory/Assets/NetworkPort.php
Labels: bug, inventory

#16241 feat(Pluginimage): handle subfolder
  front/pluginimage.send.php
Labels: enhancement

#16096 feat: Add user_dn_hash field to improve User::getFromDBbyDn performance
  install/migrations/update_10.0.11_to_10.0.12/user.php
  install/mysql/glpi-empty.sql
  src/User.php
  tests/LDAP/AuthLdap.php
  tests/functional/User.php
Labels: performance

#16240 Set the color of a rack's weight and consumption
  src/Html.php
Labels: bug

#16100 Feature : HardDrive Type field added to Hard Drive info page
  inc/relation.constant.php
  install/migrations/update_10.0.x_to_10.1.0/deviceharddrivetypes.php
  install/mysql/glpi-empty.sql
  src/DeviceHardDrive.php
  src/DeviceHardDriveType.php
  src/Inventory/Asset/HardDrive.php
  tests/functional/DeviceHardDrive.php
  tests/functional/DeviceHardDriveType.php
  tests/functional/Glpi/Inventory/Assets/Drive.php
Labels: enhancement

#16068 feat(search-option): add ticket age search option
  src/Ticket.php
  tests/functional/Ticket.php
Labels: enhancement
