Repository glpi-project/glpi, pull requests merged in 2023-11, with the labels that each got.

#15858 feat(Approval): use anchor to point directly to the form in the timeline
  src/NotificationTarget.php
  src/NotificationTargetChange.php
  src/NotificationTargetTicket.php
  src/Toolbox.php
  tests/functional/NotificationTargetTicket.php
Labels: enhancement

#15942 Fix display preference list JS
  templates/components/search/displaypreference_config.html.twig
Labels: javascript

#15943 Fix 0 being read as missing rsql value
  src/Api/HL/RSQL/Lexer.php
Labels: api

#15947 Fix readonly dropdown with defined width
  src/Dropdown.php
Labels: bug

#15405 Implement Kanban as Vue components
  .eslintrc.json
  .vue.webpack.config.js
  CHANGELOG.md
  ajax/kanban.php
  css/includes/_includes.scss
  inc/define.php
  js/glpi_dialog.js
  js/modules/Kanban/Kanban.js
  js/src/vue/Kanban/AddItemForm.vue
  js/src/vue/Kanban/Card.vue
  js/src/vue/Kanban/Column.vue
  js/src/vue/Kanban/Kanban.vue
  js/src/vue/Kanban/Rights.js
  js/src/vue/Kanban/TeamBadgeProvider.js
  js/src/vue/app.js
  package-lock.json
  package.json
  src/CommonITILObject.php
  src/Html.php
  src/Item_Kanban.php
  src/Project.php
  templates/components/kanban/item_panels/default_panel.html.twig
  templates/components/kanban/kanban.html.twig
Labels: javascript

#15895 Discourage usage of PHP 8.0
  src/System/Requirement/PhpSupportedVersion.php
  tests/units/Glpi/System/Requirement/PhpSupportedVersion.php
Labels: security

#15759 fix(Inventory): correctly handle Cisco stacked switch
  src/Inventory/Asset/NetworkPort.php
  tests/fixtures/inventories/cisco-C9300.xml
  tests/functional/Glpi/Inventory/Assets/NetworkEquipment.php
Labels: bug, Need feedback, inventory

#15952 Add parent meta options for timeline types
  src/Search/SearchEngine.php
  tests/functional/ITILFollowup.php
  tests/functional/TicketTask.php
Labels: Need unit tests

#15957 Do not use jquery.ready when rendering actors
  templates/components/itilobject/actors/field.html.twig
Labels: performance

#15345 Files integrity check
  src/Console/Build/GenerateCodeManifestCommand.php
  src/Console/Diagnostic/CheckSourceCodeIntegrityCommand.php
  src/System/Diagnostic/SourceCodeIntegrityChecker.php
  tests/functional/Glpi/System/Diagnostic/SourceCodeIntegrityChecker.php
  tools/build_glpi.sh
Labels: enhancement

#15963 fix(search): limit dropdown
  templates/components/dropdown/limit.html.twig
Labels: bug

#15900 fix incorrect decimal sql warning on new ticket form
  src/CommonITILActor.php
  src/CommonITILObject.php
Labels: bug

#15962 fix(UserMention): fix fatal error on null
  src/RichText/UserMention.php
  tests/functional/Glpi/RichText/UserMention.php
Labels: bug

#15985 feat: move read more setting
  inc/based_config.php
  src/RichText/RichText.php
  stubs/glpi_constants.php
Labels: enhancement

#15993 Add aliases for plugin CLI commands
  src/Console/Plugin/ActivateCommand.php
  src/Console/Plugin/DeactivateCommand.php
Labels: enhancement

#15988 Search engine: use "UNION ALL" for union_search_type
  src/Search.php
Labels: performance

#15938 fix: incorrect check right entity inventory tab
  src/Entity.php
Labels: bug

#15989 fix(Inventory): use the right field for 'interface'
  src/Inventory/Asset/Drive.php
  tests/functional/Glpi/Inventory/Assets/Drive.php
Labels: inventory

#15996 Do not call front/cron.php if no web tasks are enabled
  src/CronTask.php
Labels: performance

#16000 Revert "fix(Inventory): use the right field for 'interface' (#15989)"
  src/Inventory/Asset/Drive.php
  tests/functional/Glpi/Inventory/Assets/Drive.php
Labels: inventory

#15876 Fix getReplyTo when not allow response
  src/NotificationTarget.php
  tests/functional/NotificationTarget.php
Labels: bug

#15877 Add Log Right To getTabNameForItem
  src/Log.php
  tests/LDAP/AuthLdap.php
  tests/functional/Agent.php
  tests/functional/Appliance.php
  tests/functional/Config.php
  tests/functional/Document.php
  tests/functional/OperatingSystem.php
  tests/functional/OperatingSystemArchitecture.php
  tests/functional/OperatingSystemEdition.php
  tests/functional/OperatingSystemKernel.php
  tests/functional/OperatingSystemKernelVersion.php
Labels: bug

#16004 fix(central): warning displayed on all profiles
  src/Central.php
Labels: bug

#15997 Enhance CI results when updated DB is not consistent
  .github/actions/test_update-from-9.5.sh
  .github/actions/test_update-from-older-version.sh
  src/Console/Database/UpdateCommand.php
Labels: enhancement

#16013 Highlight security requirements
  css/install.scss
  css/legacy/includes/_styles.scss
  src/Central.php
  src/Console/System/CheckRequirementsCommand.php
  src/System/Requirement/AbstractRequirement.php
  src/System/Requirement/DataDirectoriesProtectedPath.php
  src/System/Requirement/PhpSupportedVersion.php
  src/System/Requirement/RequirementInterface.php
  src/System/Requirement/SafeDocumentRoot.php
  src/System/Requirement/SessionsSecurityConfiguration.php
  templates/install/blocks/requirements_table.html.twig
Labels: security

#16016 add 'Peripheral' to $CFG_GLPI["itemdevicepowersupply_types"]
  inc/define.php
Labels: enhancement

#16019 Fix default rights on Problem for tech user
  install/empty_data.php
  tests/functional/RuleCommonITILObject.php
Labels: bug

#16025 Fix associate items to ticket permission mistake
  src/Ticket.php
Labels: bug

#15948 fix(ticket): percentage of resolution time
  src/Search.php
Labels: bug, Need feedback

#16055 [HLAPI] Expand paths with multiple placeholders
  src/Api/HL/OpenAPIGenerator.php
Labels: api

#16044 Fix change status after refused solution
  src/Change.php
  src/Features/ParentStatus.php
  tests/functional/Change.php
Labels: bug

#16050 fix(Inventory): add missing RuleMatchedLog from Discovery (on update)
  src/Inventory/Asset/MainAsset.php
Labels: bug, inventory

#16046 fix(email notification): html entity decode
  src/MailCollector.php
  src/NotificationEventMailing.php
  src/NotificationMailing.php
Labels: bug

#16053 fix(RuleImportAsset): use ignore_import instead of import denied no log from dataset
  resources/Rules/RuleImportAsset.xml
  tests/functional/Glpi/Inventory/Inventory.php
Labels: enhancement, inventory

#16040 Fix debug timeline view implementation
  js/src/vue/Debug/Toolbar.vue
  js/src/vue/Debug/Widget/HTTPRequests.vue
  js/src/vue/Debug/Widget/RequestSummary.vue
  js/src/vue/Debug/Widget/RequestTimeline.vue
Labels: javascript

#16057 Make sure Remote mgmt are removed if node is empty
  src/Inventory/Inventory.php
  tests/functional/Glpi/Inventory/Assets/RemoteManagement.php
Labels: inventory

#16051 fix(Inventory): add missing 'oscomment' value for RuleLocation
  src/Inventory/Asset/MainAsset.php
  tests/functional/Glpi/Inventory/Assets/Computer.php
Labels: bug, inventory

#16047 Reservable racks
  inc/define.php
  inc/relation.constant.php
  install/migrations/update_10.0.x_to_10.1.0/racks.php
  install/mysql/glpi-empty.sql
  src/Rack.php
Labels: enhancement

#16066 fix(network port): warning message in log
  src/NetworkPort_NetworkPort.php
Labels: bug

#16065 Fix PathInfo parsing in PHP router
  src/Http/ProxyRouter.php
  tests/units/Glpi/Http/ProxyRouter.php
Labels: bug

#16072 fix(pending-reasons): prevent false form modification alert
  templates/components/itilobject/timeline/pending_reasons.html.twig
Labels: bug

#16073 fix(inventory): fixed bad handling of Unmanaged reconciliation fromuleImportAsset (by ifdescr)
  src/Inventory/Asset/NetworkPort.php
  tests/functional/Glpi/Inventory/Assets/NetworkEquipment.php
Labels: bug, inventory

#16067 fix(IPNetwork): Don't display unicity check result from native inventory process
  src/IPNetwork.php
  src/Inventory/Asset/InventoryNetworkPort.php
Labels: enhancement, inventory

#16082 standardize updateItemOnSelectEvent
  templates/components/itilobject/timeline/form_validation.html.twig
Labels: bug

#16076 add searchoptions for pictures in assets
  src/CommonDCModelDropdown.php
  src/Computer.php
  src/Enclosure.php
  src/Monitor.php
  src/NetworkEquipment.php
  src/PDU.php
  src/PassiveDCEquipment.php
  src/Peripheral.php
Labels: enhancement

#15864 ux(Stencil): Enhance UX for stencils
  ajax/stencil.php
  front/stencil.form.php
  js/stencil-editor.js
  src/NetworkEquipmentModelStencil.php
  src/Stencil.php
  templates/stencil/editor.html.twig
Labels: ux

#16011 Fix(Inventory): fix RuleImportAsset for Phone
  resources/Rules/RuleImportAsset.xml
  src/Phone.php
  tests/functional/Glpi/Inventory/Inventory.php
Labels: inventory

#15999 Fix "Operating system name" search option
  src/Item_OperatingSystem.php
Labels: bug

#16087 fix: checkbox visibility in general settings
  templates/pages/setup/general/general_setup.html.twig
Labels: bug

#16049 Fix Pending Reason display condition for non-last timeline items
  src/PendingReason_Item.php
  templates/components/itilobject/timeline/form_followup.html.twig
  templates/components/itilobject/timeline/form_task.html.twig
  templates/components/itilobject/timeline/pending_reasons.html.twig
Labels: bug

#16086 fix(pending-reasons): additional fix to prevent false form modification on alert
  templates/components/itilobject/timeline/pending_reasons.html.twig
Labels: bug, javascript

#16071 Prevent namespaced itemtype to be falsely considered as changed
  src/CommonDBTM.php
  tests/functional/CommonDBTM.php
Labels: bug
