Repository glpi-project/glpi, pull requests merged in 2024-02, with the labels that each got.

#16439 Prevent FullCalendar failure when default view is invalid
  js/planning.js
Labels: bug, javascript

#16445 Add Server Name To LDAP Sync
  src/Console/Ldap/SynchronizeUsersCommand.php
Labels: enhancement

#16395 Review budget and cost UI
  CHANGELOG.md
  src/Budget.php
  src/CommonITILCost.php
  src/ProjectTask.php
  templates/components/datatable.html.twig
  templates/components/form/basic_inputs_macros.html.twig
  templates/pages/management/budget.html.twig
  templates/pages/management/cost.html.twig
Labels: ux

#16308 Automatically reload updated rights
  install/migrations/update_10.0.x_to_10.1.0/profiles.php
  install/mysql/glpi-empty.sql
  src/Migration.php
  src/Profile.php
  src/ProfileRight.php
  src/Session.php
  tests/functional/ProfileRight.php
  tests/functional/Search.php
  tests/functional/Session.php
  tests/units/Migration.php
Labels: enhancement

#16433 fix(search): order by actor
  src/Search.php
  tests/functional/Search.php
Labels: bug

#16432 Capacity: Can be associated to assistance objects
  src/Asset/Asset.php
  src/Asset/AssetDefinitionManager.php
  src/Asset/Capacity/AbstractCapacity.php
  src/Change.php
  src/Change_Item.php
  src/CommonItilObject_Item.php
  src/Dropdown.php
  src/Html.php
  src/Item_Problem.php
  src/Problem.php
  src/Search/SearchOption.php
  src/Ticket.php
  tests/functional/Glpi/Asset/AssetDefinitionManager.php
Labels: enhancement

#16516 Feature/ Adding matricule to user tooltip card
  src/DbUtils.php
  templates/components/user/info_card.html.twig
Labels: enhancement

#16509 fix: make the items section visible in the right-hand panel of the ticket when it is closed
  src/Item_Ticket.php
  src/Ticket.php
Labels: bug

#16353 Add screen capture feature
  CHANGELOG.md
  js/fileupload.js
  js/modules/ITIL/Timeline/DocumentForm.js
  js/modules/Screenshot/Screenshot.js
  templates/components/itilobject/timeline/form_document_item.html.twig
  tests/js/modules/Screenshot/Screenshot.test.js
Labels: enhancement, javascript

#16520 remove plain-scrollbar dependency
  css/includes/_base.scss
  lib/bundles/base.js
  package-lock.json
  package.json
  templates/layout/parts/profile_selector.html.twig
Labels: dependencies, javascript

#16453 Add databaseinstance capacity
  src/Asset/Capacity/HasDatabaseInstanceCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasDatabaseInstanceCapacity.php
Labels: enhancement

#16454 Custom asset cloning
  src/Asset/Asset.php
  src/Asset/AssetDefinitionManager.php
  src/Asset/Capacity/AbstractCapacity.php
  src/Asset/Capacity/CapacityInterface.php
  src/Asset/Capacity/HasAntivirusCapacity.php
  src/Asset/Capacity/HasContractsCapacity.php
  src/Asset/Capacity/HasDocumentsCapacity.php
  src/Asset/Capacity/HasInfocomCapacity.php
  src/Asset/Capacity/HasKnowbaseCapacity.php
  src/Asset/Capacity/HasNotepadCapacity.php
  src/Asset/Capacity/HasOperatingSystemCapacity.php
  src/Asset/Capacity/HasRemoteManagementCapacity.php
  src/Asset/Capacity/HasVolumesCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasAntivirusCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasContractsCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasDocumentsCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasInfocomCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasKnowbaseCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasNotepadCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasOperatingSystemCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasRemoteManagementCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasVolumesCapacity.php
Labels: enhancement

#16501 allow use of certificate type in notification
  src/NotificationTargetCertificate.php
Labels: enhancement

#16518 Hide ITIL tabs if empty
  src/Change_Item.php
  src/CommonItilObject_Item.php
  src/Item_Problem.php
  src/Ticket.php
Labels: enhancement

#16528 Prevent admin to use some reserved words as asset system name
  src/Asset/AssetDefinition.php
  src/Asset/AssetDefinitionManager.php
  templates/pages/admin/assetdefinition/main.html.twig
  tests/functional/Glpi/Asset/AssetDefinition.php
Labels: enhancement

#16446 Add Type To Computer_Item List
  src/Computer_Item.php
Labels: enhancement

#16547 Refresh menu when devices in menu changed
  src/Config.php
Labels: enhancement

#16311 Small improvment login page
  templates/pages/login.html.twig
Labels: enhancement, ux

#16555 Fix(RuleRight): Take db groups into account for rights rules on LDAusers
  src/User.php
  tests/DbTestCase.php
  tests/LDAP/AuthLdap.php
  tests/RuleBuilder.php
  tests/functional/RuleCommonITILObject.php
  tests/functional/SLM.php
Labels: bug, enhancement

#16585 [HLAPI] Remove expanded path parameters from OpenAPI doc
  src/Api/HL/Controller/ITILController.php
  src/Api/HL/OpenAPIGenerator.php
  src/Api/HL/RoutePath.php
  tests/functional/Glpi/Api/HL/OpenAPIGenerator.php
Labels: api

#16587 [HLAPI] Fix some parameters incorrectly shown as required
  src/Api/HL/OpenAPIGenerator.php
Labels: api

#16570 fix(document): icon in timeline
  src/Application/View/Extension/DocumentExtension.php
Labels: bug

#16533 fix(dropdown): prevent warning on add form
  src/CommonGLPI.php
Labels: bug

#15971 [HLAPI] Rules
  CHANGELOG.md
  src/Api/HL/Controller/RuleController.php
  src/Api/HL/Router.php
  src/Rule.php
  src/RuleCollection.php
  src/RuleCriteria.php
  tests/HLAPITestCase.php
  tests/functional/Glpi/Api/HL/Controller/RuleController.php
  tests/functional/Rule.php
Labels: api

#16599 feat(RuleMailColletor): add capability to manage 'ExternalID'
  src/RuleMailCollector.php
  tests/functional/RuleMailcollector.php
Labels: enhancement

#16600 Fix(NotificationTargetTicket): add missing ##ticket.externalid## TAG
  src/NotificationTargetTicket.php
  tests/bootstrap.php
  tests/functional/NotificationTargetTicket.php
Labels: enhancement

#16091 [HLAPI] Assistance Stats
  front/report.dynamic.php
  front/stat.item.php
  front/stat.location.php
  front/stat.tracking.php
  src/Api/HL/Controller/ReportController.php
  src/Api/HL/GraphQLGenerator.php
  src/Api/HL/OpenAPIGenerator.php
  src/Api/HL/Router.php
  src/Stat.php
  tests/HLAPITestCase.php
  tests/functional/Glpi/Api/HL/Controller/ReportController.php
Labels: api

#16543 Use HL API to handle status.php calls and drop plain-text output
  CHANGELOG.md
  src/Api/HL/Controller/CoreController.php
  src/Api/HL/Router.php
  src/Console/System/CheckStatusCommand.php
  src/System/Status/StatusChecker.php
  status.php
  tests/functional/Glpi/System/Status/StatusChecker.php
Labels: api, need_doc_improvement

#16608 Remove duplicated imports of jQuery UI
  .webpack.config.js
  lib/bundles/base.js
  package-lock.json
  package.json
Labels: dependencies, javascript

#16554 [HLAPI] Centralize tests and base on expectations from REST and the endpoint docs
  src/Api/HL/Controller/AdministrationController.php
  src/Api/HL/Controller/AssetController.php
  src/Api/HL/Controller/ComponentController.php
  src/Api/HL/Controller/ITILController.php
  src/Api/HL/Controller/ManagementController.php
  src/Api/HL/Controller/ProjectController.php
  src/Api/HL/Doc/Schema.php
  src/Api/HL/Doc/SchemaReference.php
  src/Api/HL/RoutePath.php
  src/Api/HL/Router.php
  src/Api/HL/Search.php
  tests/HLAPITestCase.php
  tests/functional/Glpi/Api/HL/Controller/AdministrationController.php
  tests/functional/Glpi/Api/HL/Controller/AssetController.php
  tests/functional/Glpi/Api/HL/Controller/ComponentController.php
  tests/functional/Glpi/Api/HL/Controller/ITILController.php
  tests/functional/Glpi/Api/HL/Controller/ManagementController.php
  tests/functional/Glpi/Api/HL/Controller/ProjectController.php
  tests/functional/Glpi/Api/HL/Controller/RuleController.php
Labels: api

#16305 Placeholder dashboards
  CHANGELOG.md
  ajax/dashboard.php
  install/empty_data.php
  install/migrations/update_10.0.x_to_11.0.0/configs.php
  install/migrations/update_9.4.x_to_9.5.0/dashboards.php
  js/modules/Dashboard/Dashboard.js
  src/Ajax.php
  src/Dashboard/FakeProvider.php
  src/Dashboard/Grid.php
  src/Dashboard/Provider.php
  src/Dashboard/Widget.php
  templates/components/form/fields_macros.html.twig
  templates/pages/setup/general/preferences_setup.html.twig
  tests/src/Command/TestUpdatedDataCommand.php
Labels: enhancement

#16620 fix(project): warning on null content
  src/RichText/RichText.php
Labels: bug

#16598 fix(Software): update 'date_install' if needed
  src/Inventory/Asset/Software.php
  tests/functional/Glpi/Inventory/Assets/Software.php
Labels: enhancement, inventory

#16642 fix(ticket): deleted budget
  src/CommonITILCost.php
Labels: bug

#16645 Fix ContractCost init from last
  src/ContractCost.php
Labels: bug

#16634 Fixed display of group name in simplified interface
  src/Group.php
Labels: bug
