Repository glpi-project/glpi, pull requests merged in 2024-05, with the labels that each got.

#16980 Clean UI in Stat front files
  front/stat.graph.php
  front/stat.item.php
  front/stat.location.php
  front/stat.tracking.php
  src/CommonDBTM.php
  src/DbUtils.php
  templates/pages/assistance/stats/form.html.twig
  templates/pages/assistance/stats/single_item_pager.html.twig
  templates/pages/assistance/stats/tracking_form.html.twig
  tests/units/Glpi/Features/Dcbreadcrumb.php
Labels: ui

#17068 Support Well-known change-password URI
  CHANGELOG.md
  public/index.php
  src/Http/ProxyRouter.php
Labels: enhancement

#17071 Prevent `symfony` components to be updated to 7.x version
  .github/dependabot.yml
Labels: dependencies, php

#16962 Reservation Twig UI
  js/common.js
  src/Reservation.php
  src/ReservationItem.php
  src/Toolbox.php
  src/User.php
  templates/components/datatable.html.twig
  templates/components/form/buttons.html.twig
  templates/pages/tools/find_available_reservation.html.twig
Labels: ui

#17084 Fix(AssetDefinition): prevent PHP warning about missing translation on create
  src/Asset/AssetDefinition.php
Labels: bug

#17021 Add Read and Update Owned Rights
  front/asset/asset.form.php
  front/asset/asset.php
  front/cartridgeitem.php
  front/computer.form.php
  front/computer.php
  front/consumableitem.php
  front/monitor.form.php
  front/monitor.php
  front/networkequipment.form.php
  front/networkequipment.php
  front/peripheral.form.php
  front/peripheral.php
  front/phone.form.php
  front/phone.php
  front/printer.form.php
  front/printer.php
  front/software.form.php
  front/software.php
  inc/define.php
  inc/relation.constant.php
  install/empty_data.php
  install/migrations/update_10.0.x_to_11.0.0/assets.php
  install/mysql/glpi-empty.sql
  src/Features/AssignableAsset.php
  src/Item_DeviceSimcard.php
  tests/functional/CommonDBTM.php
  tests/functional/Dropdown.php
  tests/functional/Glpi/Inventory/Inventory.php
Labels: enhancement

#17103 Test MySQL 8.4 LTS compatibility
  .github/workflows/ci.yml
Labels: enhancement

#17095 CommonDBTM, CommonITILActor, HTML class UI + Drop unused code
  CHANGELOG.md
  css/legacy/includes/_styles.scss
  front/change_supplier.form.php
  front/change_user.form.php
  front/problem_supplier.form.php
  front/problem_user.form.php
  front/supplier_ticket.form.php
  front/ticket_user.form.php
  inc/config.php
  src/CommonDBTM.php
  src/CommonDevice.php
  src/CommonITILActor.php
  src/Html.php
  tests/units/Html.php
Labels: ui

#16984 feat(forms): Adding request type category and related question type
  src/Form/QuestionType/QuestionTypeCategory.php
  src/Form/QuestionType/QuestionTypeRequestType.php
  tests/units/Glpi/Form/AnswersSet.php
  tests/units/Glpi/Form/QuestionType/QuestionTypesManager.php
Labels: enhancement

#17077 feat(forms): Adding file category and related sub question type
  src/Form/AnswersHandler/AnswersHandler.php
  src/Form/Question.php
  src/Form/QuestionType/AbstractQuestionType.php
  src/Form/QuestionType/AbstractQuestionTypeActors.php
  src/Form/QuestionType/QuestionTypeCategory.php
  src/Form/QuestionType/QuestionTypeDateTime.php
  src/Form/QuestionType/QuestionTypeFile.php
  src/Form/QuestionType/QuestionTypeInterface.php
  tests/units/Glpi/Form/AnswersSet.php
  tests/units/Glpi/Form/QuestionType/QuestionTypesManager.php
Labels: enhancement

#17028 Custom Asset Twig/Sanitization
  src/Asset/Asset_PeripheralAsset.php
  src/CommonDBRelation.php
Labels: ui

#16972 User inventory rule
  src/Inventory/Asset/InventoryAsset.php
  src/Inventory/Asset/MainAsset.php
  src/RuleAsset.php
  tests/functional/Glpi/Inventory/Inventory.php
Labels: enhancement

#17102 HTML table and Migration Twig UI
  src/HTMLTableBase.php
  src/HTMLTableCell.php
  src/HTMLTableEntity.php
  src/HTMLTableGroup.php
  src/HTMLTableHeader.php
  src/HTMLTableMain.php
  src/HTMLTableRow.php
  src/HTMLTableSubHeader.php
  src/HTMLTableSuperHeader.php
  src/Migration.php
Labels: ui

#17120 Feat(ui): display icons in peripheral list for an item
  src/Asset/Asset_PeripheralAsset.php
Labels: enhancement, ui

#17076 fix(richtext): text color pasting
  src/Html.php
Labels: enhancement, javascript

#17114 [HLAPI] Allow exporting ITIL stats to pdf, csv, xlsx, and ods
  src/Api/HL/Controller/ReportController.php
  src/Api/HL/Doc/Route.php
  src/Search/Output/Spreadsheet.php
  src/Stat.php
Labels: api

#17027 Clean Device Code + UI work
  CHANGELOG.md
  src/CommonDBRelation.php
  src/CommonDevice.php
  src/DeviceBattery.php
  src/DeviceBatteryModel.php
  src/DeviceCamera.php
  src/DeviceCase.php
  src/DeviceControl.php
  src/DeviceDrive.php
  src/DeviceFirmware.php
  src/DeviceGeneric.php
  src/DeviceGraphicCard.php
  src/DeviceHardDrive.php
  src/DeviceMemory.php
  src/DeviceMotherboard.php
  src/DeviceNetworkCard.php
  src/DevicePci.php
  src/DevicePowerSupply.php
  src/DeviceProcessor.php
  src/DeviceSensor.php
  src/DeviceSimcard.php
  src/DeviceSoundCard.php
  src/PCIVendor.php
  src/RegisteredID.php
  src/USBVendor.php
Labels: ui

#17130 Fix install styles
  css/install.scss
  install/install.php
Labels: ui

#17067 Password forms Twig UI + Misc
  CHANGELOG.md
  front/devices.php
  front/ldap.group.import.php
  front/lostpassword.php
  front/migrationcleaner.php
  front/plugin.php
  front/rule.backup.php
  front/rule.common.php
  front/rule.test.php
  front/rulesengine.test.php
  front/search.php
  front/tracking.injector.php
  front/transfer.action.php
  front/updatepassword.php
  src/Html.php
  src/Item_Devices.php
  src/Item_Rack.php
  src/MassiveAction.php
  src/Software.php
  src/User.php
  templates/forgotpassword.html.twig
  templates/password_form.html.twig
  templates/updatepassword.html.twig
Labels: ui

#17053 More Rules Twig UI
  CHANGELOG.md
  src/Rule.php
  src/RuleCollection.php
  src/RuleDictionnarySoftware.php
  tests/functional/Rule.php
Labels: ui

#17097 Cartridge and Consumable Twig UI
  CHANGELOG.md
  src/Cartridge.php
  src/CartridgeItem.php
  src/Consumable.php
  src/ConsumableItem.php
  src/Infocom.php
  src/Printer_CartridgeInfo.php
  templates/components/datatable.html.twig
  templates/components/search/controls.html.twig
  templates/pages/assets/cartridge.html.twig
  templates/pages/assets/consumable_list.html.twig
Labels: ui

#17129 Fix pager and limit for non-form pages
  templates/components/dropdown/limit.html.twig
  templates/components/pager.html.twig
  templates/pages/admin/events_list.html.twig
Labels: bug

#17139 Feat(UI): add missing icon fron Central page
  src/Central.php
  src/Dashboard/Dashboard.php
  templates/layout/parts/menu.html.twig
  templates/pages/setup/general/preferences_setup.html.twig
Labels: enhancement, ui

#17134 feat(forms): check update right to show form destination actions
  src/Form/Destination/FormDestination.php
  templates/pages/admin/form/form_destination.html.twig
Labels: enhancement

#17131 feat(forms): Allow modification of destination form name
  css/includes/components/form/_form-editor.scss
  templates/pages/admin/form/form_destination.html.twig
  tests/cypress/e2e/form/form_destination.cy.js
Labels: enhancement

#17066 Detect and block Cron and CLI running as Root user
  .composer-require-checker.config.json
  CHANGELOG.md
  bin/console
  composer.json
  front/cron.php
Labels: enhancement

#16994 Add search option for number of component items
  src/CommonDevice.php
Labels: enhancement

#17155 Fix(LogViewer): Fix CSS
  templates/pages/admin/log_viewer.html.twig
Labels: bug, ui

#17124 Fix merged ticket responses not being added to parent ticket
  src/CommonITILTask.php
  src/Document_Item.php
  src/ITILFollowup.php
  src/Ticket.php
  tests/functional/Ticket.php
Labels: enhancement

#17160 Fix(Breadcrumb): Display vertical divider only if needed
  templates/layout/parts/context_links.html.twig
Labels: enhancement, ui

#17159 Fix(Notification): Fix CSS
  templates/pages/setup/setup_notifications.html.twig
Labels: enhancement, ui

#17163 Fix(Receiver): Fix connections option UI
  templates/pages/setup/mailcollector/server_config_fields.html.twig
Labels: enhancement, ui

#17156 Allow tab content to be opened using middle click
  src/Ajax.php
Labels: bug

#17164 Fix(Central): fix RSSFeed href
  src/RSSFeed.php
Labels: enhancement, ui

#17167 Fix(Agent): fix CSS and readonly input
  templates/pages/admin/inventory/agent.html.twig
Labels: enhancement, ui

#17175 Filter forms tags
  ajax/form/form_tags.php
  js/RichText/FormTags.js
  src/Form/Tag/AnswerTagProvider.php
  src/Form/Tag/FormTagsManager.php
  tests/cypress/e2e/form_tags.cy.js
  tests/units/Glpi/Form/Tag/FormTagsManager.php
Labels: enhancement

#17166 Fix followups entities restriction
  src/Search.php
  tests/functional/ITILFollowup.php
Labels: api

#16947 Planning Twig UI
  CHANGELOG.md
  ajax/planningcheck.php
  css/legacy/includes/_planning.scss
  js/planning.js
  src/Application/View/Extension/ItemtypeExtension.php
  src/Planning.php
  src/PlanningExternalEvent.php
  src/PlanningRecall.php
  templates/components/form/fields_macros.html.twig
  templates/pages/assistance/planning/add_classic_event.html.twig
  templates/pages/assistance/planning/availability.html.twig
  templates/pages/assistance/planning/external_event.html.twig
  templates/pages/assistance/planning/filters.html.twig
  templates/pages/assistance/planning/single_filter.html.twig
Labels: ui

#17174 Fix ticket processing criterias in the personal view
  src/Ticket.php
Labels: bug

#17191 [HLAPI] Add more ITIL task properties
  src/Api/HL/Controller/ITILController.php
Labels: api

#17171 feat(forms): Add cron task to purge old form drafts
  install/empty_data.php
  install/migrations/update_10.0.x_to_11.0.0/form.php
  src/Form/Form.php
  tests/functional/DbUtils.php
  tests/units/Glpi/Form/Form.php
Labels: enhancement

#17196 fix(API): expand_dropdowns with multiselect
  src/Api/API.php
Labels: bug

#17201 Redirect user to HTTPS context when session is not allowed on HTTP
  inc/config.php
  index.php
  install/install.php
  install/update.php
  src/Auth.php
  src/Session.php
  src/System/Requirement/SessionsSecurityConfiguration.php
  templates/layout/page_card_notlogged.html.twig
  templates/pages/https_only.html.twig
  tests/units/Glpi/System/Requirement/SessionsSecurityConfiguration.php
Labels: bug

#17195 fix(queuednotifications): add index
  install/migrations/update_10.0.15_to_10.0.16/queuednotifications.php
  install/mysql/glpi-empty.sql
Labels: performance
