Repository glpi-project/glpi, pull requests merged in 2024-11, with the labels that each got.

#18205 Genericdate always shows datetime fields
  ajax/genericdate.php
Labels: bug

#18100 Add new SearchOptions Computer
  src/Computer.php
  src/ComputerVirtualMachine.php
Labels: enhancement

#18132 fix(user): default entity value = Full structure
  install/migrations/update_10.0.16_to_10.0.17/users.php
  install/mysql/glpi-empty.sql
  src/CommonDBTM.php
  src/Session.php
  src/User.php
Labels: enhancement

#18212 Fix console error on missing config table
  src/Glpi/Console/Application.php
Labels: bug

#17797 (Feat) ‘Virtualisation system’ criterion in the rules
  phpunit/functional/Glpi/Inventory/InventoryTest.php
  phpunit/functional/RuleImportAssetTest.php
  src/Glpi/Inventory/Asset/InventoryAsset.php
  src/Glpi/Inventory/Asset/VirtualMachine.php
  src/RuleImportAsset.php
Labels: enhancement

#18213 Fix key generation when database has no tables yet
  install/install.php
  src/GLPIKey.php
  src/Glpi/Console/Database/InstallCommand.php
Labels: bug

#18206 [11.0] Add support for _in_modal in forms
  front/budget.form.php
  front/cable.form.php
  src/Budget.php
  src/Cable.php
  src/Glpi/Controller/GenericFormController.php
  templates/pages/generic_in_modal.html.twig
Labels: enhancement

#18258 Update dependencies to get latest security fixes
  composer.lock
Labels: security

#18244 fix(ticket): category no longer saved when at a lower level entity
  phpunit/functional/TicketTest.php
  src/Ticket.php
Labels: bug

#18276 fix(forms): Fixed import E2E tests
  src/Glpi/Controller/Form/Import/Step2PreviewController.php
  src/Glpi/Controller/Form/Import/Step4ExecuteController.php
  templates/pages/admin/form/import/step2_preview.html.twig
  templates/pages/admin/form/import/step3_resolve_issues.html.twig
  tests/cypress/e2e/form/serializer/import.cy.js
  tests/fixtures/export-of-2-forms.json
Labels: Forms

#18274 fix(purgeticket): purge also ticket satisfaction
  phpunit/functional/TicketTest.php
  src/CommonDBTM.php
Labels: bug

#17235 Rework of LDAP group import UI
  .phpstan-baseline.php
  CHANGELOG.md
  front/ldap.group.import.php
  front/ldap.group.php
  src/AuthLDAP.php
  templates/pages/admin/ldap.choose_directory.html.twig
  templates/pages/admin/ldap.group_criteria.html.twig
  templates/pages/admin/ldap.groups.html.twig
  templates/pages/setup/ldap/filter.html.twig
Labels: ux, ui

#18226 feat(forms): Adding missing questions and destination configs for default forms
  phpunit/functional/Glpi/Helpdesk/DefaultDataManagerTest.php
  src/Glpi/Helpdesk/DefaultDataManager.php
Labels: Forms

#17270 AuthMail and AuthLdapReplicate Twig UI
  CHANGELOG.md
  src/AuthLDAP.php
  src/AuthLdapReplicate.php
  src/AuthMail.php
  src/Toolbox.php
  templates/pages/setup/authentication/ldap_replicate.html.twig
  templates/pages/setup/authentication/mail.html.twig
  templates/pages/setup/mailcollector/server_config_fields.html.twig
Labels: ui

#18227 fix(inventory): is_recursive
  phpunit/functional/Glpi/Inventory/InventoryTest.php
  src/Inventory/Asset/InventoryAsset.php
  src/Inventory/Asset/MainAsset.php
  src/Inventory/Asset/Monitor.php
  src/Inventory/Asset/Printer.php
  src/Inventory/Inventory.php
Labels: enhancement

#18265 Add VM OS and IP Inventory
  phpunit/functional/Glpi/Inventory/Assets/VirtualMachineTest.php
  src/Glpi/Inventory/Asset/VirtualMachine.php
Labels: enhancement

#18297 Adapt error response to the request context
  CHANGELOG.md
  phpunit/GLPITestCase.php
  phpunit/functional/Glpi/Controller/ErrorControllerTest.php
  src/Ajax.php
  src/Glpi/Controller/ErrorController.php
  src/Glpi/Debug/Toolbar.php
  src/Html.php
  src/Toolbox.php
  templates/error_block.html.twig
  templates/error_page.html.twig
  templates/layout/parts/page_footer.html.twig
Labels: enhancement

#18242 Do no show empty reminder/rss tabs on home page
  phpunit/functional/Glpi/Helpdesk/HomePageTabsTest.php
  src/Glpi/Controller/Helpdesk/IndexController.php
  src/Glpi/Helpdesk/HomePageTabs.php
  src/RSSFeed.php
  src/Reminder.php
Labels: enhancement

#18328 Update dependencies to get latest security fixes
  composer.lock
  package-lock.json
Labels: security, dependencies, javascript, php

#18321 feat(project): add task team column in project tasks tab
  src/ProjectTask.php
Labels: enhancement

#18349 feat(ticket): add search option = project task
  src/Ticket.php
Labels: enhancement

#18355 Progress bar Twig helper
  src/Glpi/Application/View/Extension/DataHelpersExtension.php
  src/Html.php
  templates/pages/setup/general/performance.html.twig
Labels: enhancement

#18298 Add the port ID connected to the requested port
  src/Glpi/Api/API.php
  tests/web/APIRest.php
Labels: enhancement, api

#18361 Remove duplicate ID in form header content
  src/CommonGLPI.php
  src/CommonITILObject.php
  templates/components/form/header_content.html.twig
Labels: bug

#18237 Feat(Timeline): add 'blacklist' / 'whitelist' for doc
  templates/components/itilobject/timeline/form_document_item.html.twig
  templates/components/itilobject/timeline/sub_documents.html.twig
Labels: enhancement, Need feedback

#18374 fix: return 403 when inventory is disabled
  front/inventory.php
Labels: bug

#18239 Search for forms and faq articles on home page
  css/helpdesk_home.scss
  js/modules/Helpdesk/IndexController.js
  src/Glpi/Controller/Helpdesk/SearchController.php
  templates/pages/helpdesk/index.html.twig
  templates/pages/helpdesk/search.html.twig
  tests/cypress/e2e/self-service/home.cy.js
Labels: Forms

#18268 feat(forms): Add more checks to validate answers for actor question types
  ajax/getAbstractRightDropdownValue.php
  ajax/getFormQuestionActorsDropdownValue.php
  phpunit/functional/Glpi/Form/AnswersSetTest.php
  phpunit/functional/Glpi/Form/Destination/CommonITILField/AssigneeFieldTest.php
  phpunit/functional/Glpi/Form/Destination/CommonITILField/ObserverFieldTest.php
  phpunit/functional/Glpi/Form/Destination/CommonITILField/RequesterFieldTest.php
  phpunit/functional/Glpi/Form/Destination/CommonITILField/ValidationFieldTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeAssigneeTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeObserverTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeRequesterTest.php
  phpunit/src/Glpi/Form/QuestionType/AbstractQuestionTypeActorsTest.php
  src/AbstractRightsDropdown.php
  src/Glpi/Form/AccessControl/ControlType/AllowListDropdown.php
  src/Glpi/Form/Dropdown/FormActorsDropdown.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
  src/Glpi/Form/QuestionType/QuestionTypeAssignee.php
  src/Glpi/Form/QuestionType/QuestionTypeObserver.php
  src/Glpi/Form/QuestionType/QuestionTypeRequester.php
  src/ProjectTaskTeamDropdown.php
  src/ShareDashboardDropdown.php
  tests/cypress/e2e/form/destination_config_fields/assignee.cy.js
  tests/cypress/e2e/form/question_types/actors.cy.js
  tests/src/FormTesterTrait.php
Labels: Forms

#18384 Fix(LockedField): display lock for 'sysdescr'
  templates/generic_show_form.html.twig
Labels: bug

#18389 Force some session settings to ease the server configuration
  src/Auth.php
  src/Glpi/Application/SystemConfigurator.php
  src/Glpi/System/Requirement/SessionsConfiguration.php
  src/Glpi/System/Requirement/SessionsSecurityConfiguration.php
  tests/functional/Glpi/System/Requirement/SessionsConfiguration.php
  tests/functional/Glpi/System/Requirement/SessionsSecurityConfiguration.php
Labels: enhancement

#18399 Fix HTML doctype in install page
  install/install.php
Labels: bug

#18402 Fix loadings of JS locales on install/update pages
  install/install.php
  install/update.php
  src/Html.php
  templates/layout/parts/head.html.twig
Labels: bug
