Repository glpi-project/glpi, pull requests merged in 2024-08, with the labels that each got.

#17615 feat(forms): Add tooltip for auto config field in form destinations
  templates/pages/admin/form/form_destination_commonitil_config.html.twig
Labels: enhancement

#17604 ui(forms): Improve destination content format
  css/includes/components/_richtext.scss
  src/Glpi/Form/Destination/CommonITILField/ContentField.php
  src/Html.php
  templates/components/form/basic_inputs_macros.html.twig
Labels: enhancement

#17141 New hook : enable choosing the icon of an item in impact analysis
  ajax/impact.php
  js/impact.js
  src/Glpi/Plugin/Hooks.php
  src/Impact.php
Labels: enhancement

#17575 paginate local data when displaying icons selector, fix #17522
  .webpack.config.js
  js/modules/Form/WebIconSelector.js
  lib/bundles/tablericons-definitions.js
  templates/components/form/fields_macros.html.twig
  templates/pages/setup/manuallink.html.twig
  tests/js/modules/Form/WebIconSelector.test.js
Labels: enhancement

#17659 fix(clone): no date calculation
  phpunit/functional/PrinterTest.php
  src/CommonDBTM.php
  src/Features/Clonable.php
  src/Infocom.php
Labels: bug

#17683 fix(SLA): remove 'Export' option for escalation levels
  src/LevelAgreementLevel.php
  tests/functional/SLM.php
Labels: bug

#17681 fix(SLA): escalation levels are now cloned when the related SLA is cloned
  src/CommonDBChild.php
  src/LevelAgreement.php
  src/Rule.php
  tests/bootstrap.php
  tests/functional/SLM.php
Labels: bug

#17685 fix(notif): adding 'notifications_id' field in notification_notificationtemplate form
  src/Notification_NotificationTemplate.php
  templates/pages/setup/notification/notification_notificationtemplate.html.twig
Labels: bug

#17694 Planning task editable flag based on task not parent
  src/CommonITILTask.php
Labels: bug

#17695 Improve planning time update checks
  src/Planning.php
  tests/functional/Planning.php
Labels: bug

#17676 Custom Asset Field Unicity
  src/Glpi/Asset/Asset.php
  src/Glpi/Asset/AssetDefinitionManager.php
  tests/functional/Glpi/Asset/Asset.php
  tests/functional/Glpi/Asset/AssetDefinition.php
  tests/functional/Glpi/Asset/AssetDefinitionManager.php
  tests/functional/Glpi/Asset/Capacity/HasContractsCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasHistoryCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasOperatingSystemCapacity.php
  tests/functional/Glpi/Asset/Capacity/IsRackableCapacity.php
Labels: enhancement

#17706 Fix groups input rendering error when unicity check fails
  src/Dropdown.php
Labels: bug

#17589 fix(ticket): restores group's tooltip
  ajax/comments.php
  templates/components/group/info_card.html.twig
  templates/components/itilobject/actors/field.html.twig
Labels: enhancement

#17435 feat(forms): Adding item category and related sub question type
  ajax/dropdownAllItems.php
  js/common.js
  js/modules/Forms/QuestionItem.js
  phpunit/functional/Glpi/Form/AnswersSetTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypesManagerTest.php
  src/Dropdown.php
  src/Glpi/Form/QuestionType/QuestionTypeCategory.php
  src/Glpi/Form/QuestionType/QuestionTypeItem.php
  src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php
  src/Html.php
  src/autoload/CFG_GLPI.php
  tests/cypress/e2e/form/question_types/item.cy.js
  tests/src/FormBuilder.php
  tests/src/FormTesterTrait.php
Labels: enhancement

#17534 fix(treebrowse): sorting operation
  ajax/treebrowse.php
  src/Features/TreeBrowse.php
Labels: bug

#17606 Plan HLAPI versioning
  resources/api_doc.MD
  src/Glpi/Api/HL/Controller/AbstractController.php
  src/Glpi/Api/HL/Controller/AdministrationController.php
  src/Glpi/Api/HL/Controller/AssetController.php
  src/Glpi/Api/HL/Controller/ComponentController.php
  src/Glpi/Api/HL/Controller/CoreController.php
  src/Glpi/Api/HL/Controller/DropdownController.php
  src/Glpi/Api/HL/Controller/GraphQLController.php
  src/Glpi/Api/HL/Controller/ITILController.php
  src/Glpi/Api/HL/Controller/ManagementController.php
  src/Glpi/Api/HL/Controller/ProjectController.php
  src/Glpi/Api/HL/Controller/ReportController.php
  src/Glpi/Api/HL/Controller/RuleController.php
  src/Glpi/Api/HL/Doc/Schema.php
  src/Glpi/Api/HL/Doc/SchemaReference.php
  src/Glpi/Api/HL/GraphQL.php
  src/Glpi/Api/HL/GraphQLGenerator.php
  src/Glpi/Api/HL/OpenAPIGenerator.php
  src/Glpi/Api/HL/RoutePath.php
  src/Glpi/Api/HL/RouteVersion.php
  src/Glpi/Api/HL/Router.php
  src/Glpi/Controller/ApiController.php
  src/Webhook.php
  tests/HLAPITestCase.php
  tests/functional/Glpi/Api/HL/Controller/ComponentController.php
  tests/functional/Glpi/Api/HL/OpenAPIGenerator.php
  tests/functional/Glpi/Api/HL/Router.php
Labels: api

#17515 Add user category search option (Requester, Observer, Technician)
  src/CommonITILObject.php
Labels: enhancement

#17675 Custom Asset Default Display Preferences
  src/Glpi/Asset/AssetDefinition.php
  tests/functional/Glpi/Asset/Capacity/HasContractsCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasOperatingSystemCapacity.php
Labels: enhancement

#17680 Fix tables of changes and problems
  src/Change.php
  src/CommonItilObject_Item.php
  src/Problem.php
  src/Ticket.php
Labels: enhancement

#17722 Fix(Device): harmonize location search option
  src/Item_Devices.php
Labels: bug

#17732 fix(APIRest): remove not functional massive action
  apirest.md
  src/MassiveAction.php
  tests/web/APIRest.php
Labels: bug, api
