Repository glpi-project/glpi, pull requests merged in 2024-06, with the labels that each got.

#17202 fix(user): used items list
  src/User.php
Labels: bug

#16951 Auth Twig UI (Part 1)
  CHANGELOG.md
  front/authldap.form.php
  js/common.js
  js/src/vue/Kanban/Column.vue
  src/AuthLDAP.php
  src/User.php
  templates/pages/setup/ldap/adv_info.html.twig
  templates/pages/setup/ldap/filter.html.twig
  templates/pages/setup/ldap/form.html.twig
  templates/pages/setup/ldap/group_config.html.twig
Labels: ux, ui

#17204 fix(group): delete users
  src/Group_User.php
Labels: bug

#17234 fix(API): expand_dropdowns with multiselect
  src/Api/API.php
Labels: bug

#17246 fix: add maybeDeleted to check
  src/CommonDBConnexity.php
Labels: bug

#17258 Upgrade PHP dev dependencies
  composer.json
  composer.lock
Labels: dependencies, php

#17199 Move Item_Cluster form inline with list
  front/item_cluster.form.php
  src/Item_Cluster.php
Labels: ux, ui

#17212 feat: hide duplicate action when comment and question is not focused
  templates/pages/admin/form/form_comment.html.twig
  templates/pages/admin/form/form_question.html.twig
Labels: enhancement

#15216 Adapt error output to environment
  CHANGELOG.md
  ajax/dashboard.php
  api.php
  apirest.php
  src/CronTask.php
  src/GLPI.php
  src/Glpi/Application/ErrorHandler.php
  src/Glpi/Console/Application.php
  src/Glpi/ContentTemplates/TemplateManager.php
  src/Glpi/Dashboard/Grid.php
  src/MailCollector.php
  src/Toolbox.php
  tests/GLPITestCase.php
  tests/units/Glpi/Application/ErrorHandler.php
Labels: enhancement

#17282 Add support of the `--env` option in the console
  bin/console
  src/Glpi/Console/Application.php
  tests/README.md
  tests/bootstrap.php
Labels: enhancement

#17280 Fix duplicated items for rules pages counter
  src/RuleCollection.php
Labels: bug

#17069 Reports Feature Refactor + UI
  front/report.contract.list.php
  front/report.contract.php
  front/report.default.php
  front/report.dynamic.php
  front/report.infocom.conso.php
  front/report.infocom.php
  front/report.location.list.php
  front/report.networking.php
  front/report.php
  front/report.reservation.php
  front/report.socket.list.php
  front/report.state.php
  front/report.switch.list.php
  front/report.year.list.php
  front/report.year.php
  inc/define.php
  src/Infocom.php
  src/Report.php
  src/Reservation.php
  src/State.php
  templates/components/datatable.html.twig
  templates/pages/tools/report/network_criteria.html.twig
Labels: ux, ui

#17301 Delegate global definitions to the global autoloader
  .github/workflows/bump_version_after_release.yml
  CHANGELOG.md
  bin/console
  composer.json
  front/css.php
  inc/autoload.function.php
  inc/based_config.php
  inc/includes.php
  install/install.php
  install/update.php
  src/autoload/CFG_GLPI.php
  src/autoload/constants.php
  src/autoload/dbutils-aliases.php
  src/autoload/i18n.php
  src/autoload/legacy-autoloader.php
  src/autoload/misc-functions.php
  tests/cypress/e2e/DebugMode/debug_bar.cy.js
  tests/functional/Autoload.php
  tests/functional/Glpi/Dashboard/Provider.php
  tools/bin/check-twig-templates-syntax
  tools/make_release.sh
Labels: enhancement

#17317 Drop Rule debug tab
  CHANGELOG.md
  src/Rule.php
Labels: enhancement

#17266 Fix(Rule): do not import locations in preview mode
  src/Rule.php
  src/RuleLocation.php
  tests/functional/RuleLocation.php
Labels: bug

#17297 Show user LDAP information on a dedicated tab
  CHANGELOG.md
  src/User.php
Labels: enhancement

#17023 Entity Assistance Tab UI + some AJAX
  CHANGELOG.md
  ajax/cable.php
  ajax/changesatisfaction.php
  ajax/commonitilsatisfaction.php
  ajax/dropdownAllItems.php
  ajax/dropdownItilActors.php
  ajax/dropdownMassiveAction.php
  ajax/dropdownMassiveActionAddValidator.php
  ajax/dropdownTrackingDeviceType.php
  ajax/inputtext.php
  ajax/kblink.php
  ajax/resaperiod.php
  ajax/selectUnaffectedOrNewItem_Device.php
  ajax/subvisibility.php
  ajax/ticketsatisfaction.php
  ajax/uemailUpdate.php
  ajax/viewsubitem.php
  ajax/visibility.php
  src/Contract.php
  src/Entity.php
  src/Glpi/DBAL/QueryFunction.php
  src/Infocom.php
  templates/pages/2fa/2fa_config.html.twig
  templates/pages/admin/entity/assets.html.twig
  templates/pages/admin/entity/assistance.html.twig
  templates/pages/admin/entity/survey_config.html.twig
  tests/functional/Glpi/DBAL/QueryFunction.php
Labels: ui

#17318 Drop debug tab
  CHANGELOG.md
  src/CommonGLPI.php
Labels: enhancement

#17203 More Rules UI Work
  CHANGELOG.md
  src/Rule.php
  src/RuleCommonITILObject.php
  src/RuleDictionnarySoftware.php
  src/RuleDictionnarySoftwareCollection.php
  src/RuleImportAsset.php
  src/RuleRight.php
  templates/components/form/buttons.html.twig
  templates/pages/admin/rules/form.html.twig
  templates/pages/admin/rules/preview_criteria.html.twig
  templates/pages/admin/rules/ruleright_form.html.twig
Labels: ux, ui

#17307 Add endpoints for rack items
  src/Glpi/Api/HL/Controller/AssetController.php
  tests/functional/Glpi/Api/HL/Controller/AssetController.php
Labels: api

#16727 Support client credentials oauth for inventory
  src/Glpi/Agent/Communication/AbstractRequest.php
  src/Glpi/Agent/Communication/Headers/Common.php
  src/Glpi/Api/HL/Controller/CoreController.php
  src/Glpi/Inventory/Conf.php
  src/Glpi/OAuth/AccessTokenRepository.php
  tests/functional/Glpi/Api/HL/Controller/CoreController.php
Labels: enhancement

#17329 [HLAPI] Use active entity as default during item creation
  src/Glpi/Api/HL/Search.php
  tests/functional/Glpi/Api/HL/Controller/AssetController.php
Labels: api

#17337 Display the author of each change in the ticket timeline
  src/CommonITILObject.php
Labels: enhancement

#17324 Remove the `$PLUGINS_EXCLUDED` global variable hack
  CHANGELOG.md
  ajax/marketplace.php
  inc/includes.php
  js/marketplace.js
  src/Glpi/Marketplace/Controller.php
  src/Plugin.php
Labels: enhancement

#17350 Fix CronTaskLog access in legacy API
  src/CronTaskLog.php
Labels: bug

#17360 Fix Default Tech With Task Template
  ajax/task.php
Labels: bug
