Repository glpi-project/glpi, pull requests merged in 2024-04, with the labels that each got.

#16850 add icons to capacities
  src/Asset/Capacity/CapacityInterface.php
  src/Asset/Capacity/HasAntivirusCapacity.php
  src/Asset/Capacity/HasAppliancesCapacity.php
  src/Asset/Capacity/HasCertificatesCapacity.php
  src/Asset/Capacity/HasContractsCapacity.php
  src/Asset/Capacity/HasDatabaseInstanceCapacity.php
  src/Asset/Capacity/HasDocumentsCapacity.php
  src/Asset/Capacity/HasDomainsCapacity.php
  src/Asset/Capacity/HasHistoryCapacity.php
  src/Asset/Capacity/HasInfocomCapacity.php
  src/Asset/Capacity/HasKnowbaseCapacity.php
  src/Asset/Capacity/HasLinksCapacity.php
  src/Asset/Capacity/HasNetworkPortCapacity.php
  src/Asset/Capacity/HasNotepadCapacity.php
  src/Asset/Capacity/HasOperatingSystemCapacity.php
  src/Asset/Capacity/HasRemoteManagementCapacity.php
  src/Asset/Capacity/HasVirtualMachineCapacity.php
  src/Asset/Capacity/HasVolumesCapacity.php
  src/Asset/Capacity/IsRackableCapacity.php
  src/Asset/Capacity/IsReservableCapacity.php
  src/ItemVirtualMachine.php
  src/Item_RemoteManagement.php
  src/OperatingSystem.php
  templates/pages/admin/assetdefinition/capacities.html.twig
  tests/functional/Item_OperatingSystem.php
  tests/functional/OperatingSystem.php
Labels: ui

#16830 Always store updated SMTP Oauth refresh token
  src/GLPIMailer.php
  src/Mail/SMTP/OAuthTokenProvider.php
Labels: bug

#16539 Capacity: Has connections
  CHANGELOG.md
  ajax/dropdownConnect.php
  apirest.md
  front/asset/asset_peripheralasset.form.php
  front/monitor.form.php
  front/peripheral.form.php
  front/phone.form.php
  front/printer.form.php
  front/report.infocom.php
  inc/define.php
  inc/relation.constant.php
  install/migrations/update_10.0.x_to_11.0.0/assets_peripheralassets.php
  install/mysql/glpi-empty.sql
  src/Api/API.php
  src/Api/Deprecated/Computer_Item.php
  src/Asset/Asset_PeripheralAsset.php
  src/Asset/Capacity/HasPeripheralAssetsCapacity.php
  src/CommonDBRelation.php
  src/CommonDBTM.php
  src/CommonItilObject_Item.php
  src/Computer.php
  src/Computer_Item.php
  src/Dropdown.php
  src/Features/Inventoriable.php
  src/Inventory/Asset/InventoryAsset.php
  src/Inventory/Asset/Monitor.php
  src/Inventory/Asset/Peripheral.php
  src/Inventory/Asset/Printer.php
  src/Lock.php
  src/Monitor.php
  src/Peripheral.php
  src/Phone.php
  src/Printer.php
  src/Report.php
  src/RuleDictionnaryPrinterCollection.php
  src/Search/Provider/SQLProvider.php
  src/Search/SearchEngine.php
  src/Transfer.php
  tests/deprecated-searchoptions/Computer_Item.json
  tests/functional/Computer.php
  tests/functional/Glpi/Api/HL/Controller/CoreController.php
  tests/functional/Glpi/Asset/Capacity/HasPeripheralAssetsCapacity.php
  tests/functional/Glpi/Inventory/Assets/Computer.php
  tests/functional/Glpi/Inventory/Assets/Monitor.php
  tests/functional/Glpi/Inventory/Assets/Peripheral.php
  tests/functional/Glpi/Inventory/Assets/Printer.php
  tests/functional/Glpi/Inventory/Inventory.php
  tests/functional/RuleImportEntity.php
  tests/functional/Search.php
  tests/src/Api/Deprecated/Computer_Item.php
  tests/web/APIRest.php
Labels: enhancement

#16875 Fix project search criteria and state handling in personnal and group dashboard
  src/Project.php
  src/ProjectTask.php
Labels: bug

#16887 fix: resolve issue with auto-setting real start and end dates in ProjectTask
  src/ProjectTask.php
  tests/functional/ProjectTask.php
Labels: bug

#16878 Upgrade `tinymce`
  js/RichText/ContentTemplatesParameters.js
  js/RichText/UserMention.js
  package-lock.json
  package.json
  src/Html.php
Labels: dependencies, javascript

#14205 feat: ldap tests improved
  src/Auth.php
  src/AuthLDAP.php
  templates/pages/setup/ldap/test_form.html.twig
  tests/LDAP/AuthLdap.php
  tools/HEADER
Labels: enhancement

#16902 fix(rule engine): warning message
  src/RuleMailCollectorCollection.php
Labels: bug

#16656 Document forms and lists Twig
  CHANGELOG.md
  src/Document.php
  src/Document_Item.php
  src/Dropdown.php
  templates/pages/management/document.html.twig
  templates/pages/management/document_item.html.twig
  tests/functional/Dropdown.php
Labels: ux

#16894 fix(entity): Entity for software creation
  src/Entity.php
Labels: bug

#16851 Notifications Twig UI
  src/NotificationAjaxSetting.php
  src/NotificationEventAbstract.php
  src/NotificationSetting.php
  src/NotificationTemplateTranslation.php
  src/Notification_NotificationTemplate.php
  src/QueuedNotification.php
  templates/components/form/basic_inputs_macros.html.twig
  templates/pages/setup/notification/ajax_setting.html.twig
  templates/pages/setup/notification/queued_notification.html.twig
  templates/pages/setup/notification/template_notifications.html.twig
  tests/cypress/e2e/notifications.cy.js
  tests/cypress/support/commands.js
  tests/functional/Notification_NotificationTemplate.php
Labels: ui

#16929 Only allow array for iterator queries
  CHANGELOG.md
  ajax/dropdownTypeCertificates.php
  front/commonitiltask.form.php
  front/itilfollowup.form.php
  front/itilsolution.form.php
  front/ticket.form.php
  install/migrations/update_0.90.x_to_9.1.0.php
  install/migrations/update_10.0.11_to_10.0.12/duplicate_searchopt_fixes.php
  install/migrations/update_10.0.x_to_11.0.0/states.php
  install/migrations/update_9.1.0_to_9.1.1.php
  install/migrations/update_9.1.x_to_9.2.0.php
  src/Alert.php
  src/AuthLDAP.php
  src/CommonDBTM.php
  src/CommonITILObject.php
  src/CronTask.php
  src/DBmysql.php
  src/DBmysqlIterator.php
  src/Dashboard/Dashboard.php
  src/DbUtils.php
  src/Inventory/Asset/MainAsset.php
  src/KnowbaseItem_Comment.php
  src/KnowbaseItem_Revision.php
  src/Log.php
  src/MailCollector.php
  src/Migration.php
  src/NetworkName.php
  src/NetworkPort.php
  src/NotificationTarget.php
  src/NotificationTemplateTranslation.php
  src/Profile.php
  src/RequestType.php
  src/Software.php
  src/System/Requirement/DbTimezones.php
  src/User.php
  tests/LDAP/AuthLdap.php
  tests/bootstrap.php
  tests/functional/DbUtils.php
  tests/functional/Glpi/Inventory/Assets/Software.php
  tests/functional/RuleImportEntity.php
  tests/units/DBmysqlIterator.php
  tests/units/Glpi/System/Requirement/DbTimezones.php
  tests/units/Migration.php
Labels: need_doc_improvement

#16477 Capacity: Has softwares
  src/Asset/Capacity/HasSoftwaresCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasAntivirusCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasAppliancesCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasCertificatesCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasContractsCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasDatabaseInstanceCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasDocumentsCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasDomainsCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasHistoryCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasInfocomCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasKnowbaseCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasLinksCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasNetworkPortCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasNotepadCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasOperatingSystemCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasPeripheralAssetsCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasRemoteManagementCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasSoftwaresCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasVirtualMachineCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasVolumesCapacity.php
  tests/functional/Glpi/Asset/Capacity/IsRackableCapacity.php
  tests/functional/Glpi/Asset/Capacity/IsReservableCapacity.php
  tests/src/Asset/CapacityUsageTestTrait.php
Labels: enhancement

#16911 SLM Twig UI
  CHANGELOG.md
  src/LevelAgreement.php
  src/LevelAgreementLevel.php
  src/OlaLevel.php
  src/Rule.php
  src/SLM.php
  src/SlaLevel.php
  templates/pages/setup/levelagreement_level.html.twig
Labels: ui

#16946 fix(search): order by actor without join table
  src/Search.php
  tests/functional/Search.php
Labels: bug

#16960 RSSFeed Twig UI
  src/Application/View/Extension/DataHelpersExtension.php
  src/RSSFeed.php
  templates/pages/tools/rss_form.html.twig
Labels: ui

#16977 More Stat code cleanup + UI work
  front/stat.global.php
  front/stat.graph.php
  src/Search/Output/AbstractSearchOutput.php
  src/Search/Output/HTMLSearchOutput.php
  src/Stat.php
  templates/pages/assistance/stats/title.html.twig
Labels: ui

#16927 feat(forms): Adding urgency category and related question type
  js/common.js
  js/form_editor_controller.js
  src/Dropdown.php
  src/Form/QuestionType/QuestionTypeCategory.php
  src/Form/QuestionType/QuestionTypeUrgency.php
  src/Html.php
  tests/functional/Glpi/Form/AnswersSet.php
  tests/functional/Glpi/Form/QuestionType/QuestionTypesManager.php
Labels: enhancement

#16983 feat: add subscription period dates
  src/Application/View/Extension/DataHelpersExtension.php
  templates/pages/setup/general/glpinetwork_setup.html.twig
Labels: enhancement

#16986 Prevent profile right matrix overflow
  templates/components/checkbox_matrix.html.twig
Labels: ui

#16966 fix(migration): update template fields
  src/Migration.php
  tests/units/Migration.php
Labels: bug

#17016 chore: Adding a new abstract class as base class for form question types
  src/Form/QuestionType/AbstractQuestionType.php
  src/Form/QuestionType/AbstractQuestionTypeActors.php
  src/Form/QuestionType/AbstractQuestionTypeShortAnswer.php
  src/Form/QuestionType/QuestionTypeDateTime.php
  src/Form/QuestionType/QuestionTypeLongText.php
  src/Form/QuestionType/QuestionTypeUrgency.php
Labels: enhancement

#17015 refactor(forms): centralize end user input name
  ajax/form/answer.php
  src/Form/EndUserInputNameProvider.php
  src/Form/Question.php
  src/Form/QuestionType/AbstractQuestionTypeActors.php
  src/Form/QuestionType/AbstractQuestionTypeShortAnswer.php
  src/Form/QuestionType/QuestionTypeDateTime.php
  src/Form/QuestionType/QuestionTypeLongText.php
  src/Form/QuestionType/QuestionTypeUrgency.php
  tests/functional/Glpi/Form/EndUserInputNameProvider.php
Labels: enhancement

#16913 Software Twig UI 1
  CHANGELOG.md
  src/Html.php
  src/Item_SoftwareVersion.php
  src/Software.php
  src/SoftwareLicense.php
  src/SoftwareVersion.php
  templates/components/datatable.html.twig
Labels: ui

#17012 Fix cloned entity tree cache
  src/Entity.php
  src/Features/Clonable.php
Labels: bug
