Repository glpi-project/glpi, pull requests merged in 2024-03, with the labels that each got.

#16646 Add tech/group as default planning reminder notification target
  install/empty_data.php
Labels: enhancement

#16626 Remove CSRF/IDOR tokens time based expiration logic
  CHANGELOG.md
  inc/based_config.php
  src/Html.php
  src/Session.php
  stubs/glpi_constants.php
  tests/functional/Session.php
Labels: security

#16678 Fix "save" date picker button when the input is empty
  js/flatpickr_buttons_plugin.js
Labels: bug

#16449 Improve asset definition deletion
  js/glpi_dialog.js
  src/Asset/AssetDefinition.php
  templates/pages/admin/assetdefinition/main.html.twig
Labels: enhancement

#16690 fix(clone): special character
  src/Features/Clonable.php
  tests/DbTestCase.php
  tests/functional/Calendar.php
  tests/functional/Project.php
Labels: bug

#16677 Fix(Inventory): allow to download inventory file only if is_dynamic
  src/Features/Inventoriable.php
Labels: bug, inventory

#16696 Make `mbstring` extension mandatory
  src/System/RequirementsManager.php
Labels: dependencies

#16538 ObjectLock feature/UI review
  js/modules/ObjectLock.js
  src/ObjectLock.php
  templates/layout/parts/objectlock_message.html.twig
  tests/js/modules/ObjectLock.test.js
Labels: ux, javascript

#16549 Move inline map field JS to module
  js/modules/Form/GeolocationField.js
  src/MapGeolocation.php
Labels: javascript

#16198 States "genericity"
  inc/define.php
  inc/relation.constant.php
  install/migrations/update_10.0.x_to_11.0.0/states.php
  install/mysql/glpi-empty.sql
  src/Api/HL/Controller/ComponentController.php
  src/Api/HL/Controller/DropdownController.php
  src/Api/HL/Controller/ReportController.php
  src/Api/HL/Doc/Schema.php
  src/Api/HL/GraphQL.php
  src/Api/HL/GraphQLGenerator.php
  src/Api/HL/Search.php
  src/Appliance.php
  src/Asset/Asset.php
  src/Asset/AssetDefinitionManager.php
  src/Cable.php
  src/Certificate.php
  src/Cluster.php
  src/Computer.php
  src/Contract.php
  src/DBmysqlIterator.php
  src/DatabaseInstance.php
  src/Dropdown.php
  src/DropdownVisibility.php
  src/Enclosure.php
  src/Features/State.php
  src/Inventory/Conf.php
  src/Item_Devices.php
  src/Line.php
  src/Monitor.php
  src/NetworkEquipment.php
  src/PDU.php
  src/PassiveDCEquipment.php
  src/Peripheral.php
  src/Phone.php
  src/Printer.php
  src/Rack.php
  src/SoftwareLicense.php
  src/SoftwareVersion.php
  src/State.php
  src/Unmanaged.php
  templates/components/form/item_device.html.twig
  templates/generic_show_form.html.twig
  tests/functional/Dropdown.php
  tests/functional/Glpi/Api/HL/Controller/GraphQLController.php
  tests/functional/Glpi/Inventory/Inventory.php
  tests/functional/Search.php
  tests/functional/State.php
  tests/units/DBmysqlIterator.php
Labels: enhancement

#16714 Fix ObjectLock
  src/ObjectLock.php
Labels: bug

#16715 Forms: focus input
  js/form_editor_controller.js
  templates/pages/admin/form/form_editor.html.twig
  templates/pages/admin/form/form_question.html.twig
  templates/pages/admin/form/form_section.html.twig
Labels: ux

#16621 Move messages above search to new status area in search controls header
  CHANGELOG.md
  front/crontask.php
  front/mailcollector.php
  src/CronTask.php
  src/MailCollector.php
  templates/components/search/controls.html.twig
  templates/pages/setup/mailcollector/results_title.html.twig
Labels: ux

#16703 Fix tab changes not persisting
  src/Ajax.php
Labels: bug

#16719 fix(contrat): expiration date in search
  src/Contract.php
Labels: bug

#16709 Adding dashboard for project and projecttask in personal and groups view
  ajax/central.php
  css/includes/pages/_search.scss
  src/Central.php
  src/Change.php
  src/CommonITILTask.php
  src/Problem.php
  src/Project.php
  src/ProjectTask.php
  src/Search/Provider/SQLProvider.php
  src/Ticket.php
  tests/functional/Project.php
  tests/functional/ProjectTask.php
Labels: enhancement

#16708 fix(search): contains &
  src/Search.php
  tests/functional/Search.php
Labels: bug

#16064 Fix list of users who can be assigned to a ticket from Kanban
  ajax/kanban.php
  js/modules/Kanban/Kanban.js
  src/CommonITILObject.php
  src/Features/Kanban.php
  src/Features/Teamwork.php
  templates/components/itilobject/actors/field.html.twig
  templates/components/itilobject/actors/main.html.twig
  templates/components/kanban/kanban.html.twig
  templates/components/kanban/teammember.html.twig
  tests/functional/Ticket.php
Labels: bug

#16720 Fix category metadata in itil kanban cards
  src/CommonITILObject.php
Labels: bug

#16706 FieldUnicity Twig UI
  src/FieldUnicity.php
Labels: ux

#16705 DropdownTranslation Twig UI
  ajax/updateTranslationValue.php
  src/DropdownTranslation.php
  templates/pages/setup/dropdowntranslation.html.twig
Labels: ux

#16624 OAuth Client IP Restrictions
  install/migrations/update_10.0.x_to_11.0.0/oauth.php
  install/mysql/glpi-empty.sql
  src/Api/HL/Middleware/IPRestrictionRequestMiddleware.php
  src/Api/HL/Router.php
  src/OAuthClient.php
  templates/pages/setup/oauthclient.html.twig
  tests/functional/Glpi/Api/HL/Middleware/IPRestrictionRequestMiddleware.php
  tests/functional/OAuthClient.php
Labels: api

#16742 Fix(ReservationItem): Fix SQL error when 'is_recursive' column not exist
  src/ReservationItem.php
Labels: bug

#16623 Basic OAuth scopes implementation
  src/Api/HL/Controller/AdministrationController.php
  src/Api/HL/Middleware/OAuthRequestMiddleware.php
  src/Api/HL/OpenAPIGenerator.php
  src/Api/HL/Router.php
  src/OAuth/ScopeRepository.php
  src/OAuth/Server.php
  src/OAuthClient.php
  templates/pages/oauth/authorize.html.twig
  templates/pages/setup/oauthclient.html.twig
  tests/functional/Glpi/Api/HL/Controller/AdministrationController.php
Labels: api

#16615 Remove buttons above user and group search
  CHANGELOG.md
  css/includes/_base.scss
  front/group.php
  front/user.php
  src/Group.php
  src/User.php
Labels: ux

#16747 fix(consumable item): restore cloning
  src/ConsumableItem.php
Labels: enhancement

#16710 Automatic status updates for project tasks
  install/empty_data.php
  install/migrations/update_10.0.x_to_11.0.0/projecttask.php
  install/mysql/glpi-empty.sql
  src/ProjectTask.php
  templates/pages/setup/general/general_setup.html.twig
  templates/pages/tools/project_task.html.twig
  tests/functional/ProjectTask.php
Labels: enhancement

#16738 fix(network port): items to show
  src/NetworkPort.php
Labels: bug

#16431 Feature/remove spaces around equipment names
  js/clipboard.js
Labels: enhancement

#16745 fix(search): contains &
  src/Search.php
  tests/functional/Search.php
Labels: bug

#16718 Automatic evolution of project task dates
  src/ProjectTask.php
  tests/functional/ProjectTask.php
Labels: enhancement

#16658 Forms: configure destinations from the interface
  ajax/form/answer.php
  front/form/destination/formdestination.form.php
  inc/relation.constant.php
  install/migrations/update_10.0.x_to_11.0.0/form.php
  install/mysql/glpi-empty.sql
  js/form_renderer_controller.js
  src/Form/AnswersHandler/AnswersHandler.php
  src/Form/AnswersSet.php
  src/Form/Destination/AbstractFormDestinationType.php
  src/Form/Destination/AnswersSet_FormDestinationItem.php
  src/Form/Destination/FormDestination.php
  src/Form/Destination/FormDestinationInterface.php
  src/Form/Destination/FormDestinationTicket.php
  src/Form/Form.php
  src/Html.php
  src/Ticket.php
  templates/pages/admin/form/form_destination.html.twig
  tests/functional/Glpi/Form/AnswersSet.php
  tests/functional/Glpi/Form/Destination/FormDestination.php
  tests/functional/Glpi/Form/Destination/FormDestinationTicket.php
  tests/src/Form/Destination/AbstractFormDestinationType.php
  tests/src/FormBuilder.php
  tests/src/FormTesterTrait.php
Labels: enhancement

#16650 GLPINetwork config twig
  src/GLPINetwork.php
  templates/pages/setup/general/glpinetwork_setup.html.twig
Labels: ux

#16750 Fix(Inventory) add history on Item_Devices add / update / delete when Mainasset already exist
  src/Inventory/Asset/Device.php
  tests/functional/Glpi/Inventory/Assets/Bios.php
  tests/functional/Glpi/Inventory/Inventory.php
Labels: bug, enhancement, inventory

#16307 Expand read and update permissions for assets
  CHANGELOG.md
  front/cartridge.form.php
  front/cartridgeitem.form.php
  front/cartridgeitem.php
  front/computer.form.php
  front/computer.php
  front/consumable.form.php
  front/consumableitem.form.php
  front/consumableitem.php
  front/monitor.form.php
  front/monitor.php
  front/networkequipment.form.php
  front/networkequipment.php
  front/networkname.form.php
  front/networkname.php
  front/peripheral.form.php
  front/peripheral.php
  front/phone.form.php
  front/phone.php
  front/printer.form.php
  front/printer.php
  front/software.form.php
  front/software.php
  inc/define.php
  install/empty_data.php
  install/migrations/update_10.0.x_to_11.0.0/assets.php
  src/Cartridge.php
  src/CartridgeItem.php
  src/CommonItilObject_Item.php
  src/Computer.php
  src/Consumable.php
  src/ConsumableItem.php
  src/DeviceSimcard.php
  src/Dropdown.php
  src/Features/AssignableAsset.php
  src/Monitor.php
  src/NetworkEquipment.php
  src/NetworkName.php
  src/Peripheral.php
  src/Phone.php
  src/Printer.php
  src/Search/Provider/SQLProvider.php
  src/Session.php
  src/Software.php
  tests/functional/CommonDBTM.php
  tests/functional/Dropdown.php
  tests/functional/MassiveAction.php
Labels: enhancement

#16635 feat(forms): Adding date and time category and related question type
  css/includes/components/form/_form-editor.scss
  install/migrations/update_10.0.x_to_11.0.0/form.php
  js/form_editor_controller.js
  src/Form/Question.php
  src/Form/QuestionType/AbstractQuestionTypeShortAnswer.php
  src/Form/QuestionType/QuestionTypeCategory.php
  src/Form/QuestionType/QuestionTypeDateTime.php
  src/Form/QuestionType/QuestionTypeEmail.php
  src/Form/QuestionType/QuestionTypeInterface.php
  src/Form/QuestionType/QuestionTypeLongText.php
  src/Form/QuestionType/QuestionTypeNumber.php
  src/Form/QuestionType/QuestionTypeShortText.php
  src/Form/QuestionType/QuestionTypesManager.php
  templates/pages/admin/form/form_question.html.twig
  tests/functional/Glpi/Form/AnswersHandler/AnswersHandler.php
  tests/functional/Glpi/Form/AnswersSet.php
  tests/functional/Glpi/Form/Destination/FormDestination.php
  tests/functional/Glpi/Form/Destination/FormDestinationTicket.php
  tests/functional/Glpi/Form/Form.php
  tests/functional/Glpi/Form/Question.php
  tests/functional/Glpi/Form/QuestionType/QuestionTypesManager.php
  tests/functional/Glpi/Form/Section.php
  tests/src/Form/Destination/AbstractFormDestinationType.php
Labels: enhancement

#16648 Crontask datatable twig migration
  src/Application/View/Extension/DataHelpersExtension.php
  src/CronTask.php
  templates/components/datatable.html.twig
  templates/pages/setup/crontask/crontask.html.twig
Labels: ux

#16756 Fix tinymce config conflicts in the form editor
  js/form_editor_controller.js
Labels: javascript

#16692 Domain Twig UI
  src/CommonItilObject_Item.php
  src/DomainRecord.php
  src/DomainRecordType.php
  src/Domain_Item.php
  src/Dropdown.php
  templates/pages/management/domainrecord.html.twig
  templates/pages/management/domainrecordtype_helper.html.twig
Labels: ux

#16808 Fix dropdown translations on search results
  CHANGELOG.md
  src/Search.php
  src/Search/Provider/SQLProvider.php
Labels: bug

#16588 Export as ODS, XLSX, CSV and PDF using `phpoffice/phpspreadsheet`
  CHANGELOG.md
  composer.json
  composer.lock
  src/Config.php
  src/Dropdown.php
  src/GLPIPDF.php
  src/Html.php
  src/Search.php
  src/Search/Output/AbstractSearchOutput.php
  src/Search/Output/CSVSearchOutput.php
  src/Search/Output/Csv.php
  src/Search/Output/ExportSearchOutput.php
  src/Search/Output/HTMLSearchOutput.php
  src/Search/Output/MapSearchOutput.php
  src/Search/Output/Ods.php
  src/Search/Output/Pdf.php
  src/Search/Output/SYLKSearchOutput.php
  src/Search/Output/Spreadsheet.php
  src/Search/Output/Tcpdf.php
  src/Search/Output/Xlsx.php
  src/Search/SearchEngine.php
  src/Toolbox/DataExport.php
  templates/components/search/controls.html.twig
Labels: enhancement

#16818 Add missing device camera item form
  front/item_devicecamera.form.php
Labels: bug

#16820 Fix deprecation on dropdown fields with a `null` entity restrict
  src/Dropdown.php
  src/Session.php
  tests/functional/Session.php
Labels: bug

#16817 fix(personal view): planning display
  js/planning.js
Labels: javascript

#16780 fix(network port): error message
  src/NetworkPort.php
  tests/functional/NetworkPort.php
Labels: bug

#16843 [HLAPI] Sorting
  src/Api/HL/Controller/AbstractController.php
  src/Api/HL/Controller/AdministrationController.php
  src/Api/HL/Controller/AssetController.php
  src/Api/HL/Controller/ComponentController.php
  src/Api/HL/Controller/ITILController.php
  src/Api/HL/Controller/ManagementController.php
  src/Api/HL/Controller/ProjectController.php
  src/Api/HL/Controller/RuleController.php
  src/Api/HL/Search.php
  tests/HLAPITestCase.php
  tests/functional/Glpi/Api/HL/Controller/AdministrationController.php
Labels: api

#16837 [HLAPI] Get infocom information for assets
  src/Api/HL/Controller/AssetController.php
  src/Api/HL/Controller/ManagementController.php
  tests/functional/Glpi/Api/HL/Controller/AssetController.php
Labels: api

#16748 add option to show pagination on top of search results
  inc/define.php
  install/empty_data.php
  install/migrations/update_10.0.x_to_11.0.0/user.php
  install/mysql/glpi-empty.sql
  js/modules/Search/ResultsView.js
  js/modules/Search/Table.js
  templates/components/pager.html.twig
  templates/components/search/controls.html.twig
  templates/components/search/display_data.html.twig
  templates/pages/setup/general/preferences_setup.html.twig
  tests/js/modules/Search/Table.test.js
Labels: enhancement, ux

#16721 Groups UI Twig
  CHANGELOG.md
  front/user.form.php
  src/CommonTreeDropdown.php
  src/Group.php
  src/Group_User.php
  templates/components/datatable.html.twig
  templates/pages/admin/group_user.html.twig
  tests/functional/Group_User.php
Labels: ux
