Repository glpi-project/glpi, pull requests merged in 2024-09, with the labels that each got.

#17713 Fix(Group): fix user visibilty
  src/Group_User.php
Labels: bug

#17701 fix(ticket): solvedate and closedate on creation
  phpunit/functional/TicketTest.php
  src/CommonITILObject.php
Labels: bug

#17779 Fix(Phone): add missing Agent search option
  src/Phone.php
Labels: bug, inventory

#17746 Fix project task recipients
  src/NotificationTargetProjectTask.php
Labels: bug

#17804 Fix(SlaLevel): prevent 'clone' action
  src/LevelAgreementLevel.php
  src/SlaLevel.php
Labels: bug

#17811 Fix(ticket): check category / entity validity
  src/Ticket.php
Labels: bug

#17645 Migrate allow_list_dropdown_count_users.php into a real controller
  ajax/form/allow_list_dropdown_count_users.php
  phpunit/functional/Glpi/Form/AccessControl/ControlType/AllowListDropdownTest.php
  src/Glpi/Controller/Form/AllowListDropdown/CountUsersController.php
  src/Glpi/Form/AccessControl/ControlType/AllowListDropdown.php
  templates/pages/admin/form/access_control/allow_list.html.twig
  tests/cypress/e2e/form/access_policies/access_control.cy.js
Labels: Forms

#17602 Export form basic UI
  .gitignore
  ajax/massiveaction.php
  phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
  src/CommonDBTM.php
  src/Glpi/Controller/Form/ExportController.php
  src/Glpi/Form/Export/Result/ExportResult.php
  src/Glpi/Form/Export/Serializer/FormSerializer.php
  src/Glpi/Form/Form.php
  src/Html.php
  templates/components/datatable.html.twig
  templates/components/form/single-action.html.twig
  templates/components/search/table.html.twig
  tests/cypress/e2e/form/serializer/export.cy.js
Labels: Forms

#17813 Forms: improve export filenames
  phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
  src/Glpi/Form/Export/Serializer/FormSerializer.php
  src/Session.php
  tests/cypress/e2e/form/serializer/export.cy.js
Labels: Forms

#17653 Add proper Form\RendererController
  front/form/form_renderer.php
  phpunit/functional/Glpi/Form/Renderer/FormRendererTest.php
  src/Glpi/Controller/Form/RendererController.php
  src/Glpi/Form/AccessControl/ControlType/DirectAccess.php
  src/Glpi/Form/Renderer/FormRenderer.php
  src/Glpi/Http/Firewall.php
  templates/pages/admin/form/form_editor.html.twig
  templates/pages/form_renderer.html.twig
  tests/cypress/e2e/form/access_policies/direct_access.cy.js
  tests/functional/Glpi/Http/Firewall.php
Labels: Forms

#17800 Fix transfering ITIL supplier links
  phpunit/functional/TransferTest.php
  src/Transfer.php
Labels: bug

#17612 feat(forms) : Import form basic UI
  .phpstan-baseline.php
  phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
  src/Glpi/Controller/Form/Import/Step1IndexController.php
  src/Glpi/Controller/Form/Import/Step2PreviewController.php
  src/Glpi/Controller/Form/Import/Step3ExecuteController.php
  src/Glpi/Form/Export/Context/DatabaseMapper.php
  src/Glpi/Form/Export/Result/ImportResultPreview.php
  src/Glpi/Form/Export/Serializer/FormSerializer.php
  src/Glpi/Form/Form.php
  templates/layout/parts/context_links.html.twig
  templates/pages/admin/form/import/step1_index.html.twig
  templates/pages/admin/form/import/step2_preview.html.twig
  templates/pages/admin/form/import/step3_execute.html.twig
  tests/cypress/e2e/form/serializer/import.cy.js
  tests/fixtures/export-of-2-forms.json
Labels: Forms

#17621 feat(forms): Add Template field configuration for form destination
  phpunit/functional/Glpi/Form/Destination/CommonITILField/TemplateFieldTest.php
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
  src/Glpi/Form/Destination/CommonITILField/RequestTypeField.php
  src/Glpi/Form/Destination/CommonITILField/TemplateField.php
  src/Glpi/Form/Destination/CommonITILField/TemplateFieldConfig.php
  src/Glpi/Form/Destination/CommonITILField/TemplateFieldStrategy.php
  tests/cypress/e2e/form/destination_config_fields/template.cy.js
Labels: enhancement, Forms

#17670 Form import: map only items visible in the current entity
  phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
  src/Glpi/Controller/Form/Import/Step2PreviewController.php
  src/Glpi/Controller/Form/Import/Step3ExecuteController.php
  src/Glpi/Form/Export/Context/DatabaseMapper.php
  src/Glpi/Form/Export/Serializer/FormSerializer.php
  src/Session.php
Labels: Forms

#17661 Service catalog minimal implementation
  front/central.php
  front/helpdesk.public.php
  front/ticket.form.php
  front/tracking.injector.php
  phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php
  src/Auth.php
  src/Glpi/Controller/Form/ServiceCatalogController.php
  src/Glpi/Form/ServiceCatalog/ServiceCatalogManager.php
  src/Html.php
  src/Ticket.php
  templates/layout/page_skeleton.html.twig
  templates/pages/self-service/service_catalog.html.twig
  tests/cypress/e2e/form/service_catalog.cy.js
  tests/cypress/e2e/selfservice_tickets.cy.js
  tests/cypress/support/commands.js
  tests/cypress/support/cypress-axe.js
Labels: Forms

#17650 feat(forms): use an answer formatted by the question type to handle other types than string
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeAssigneeTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeCheckboxTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeDateTimeTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeDropdownTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeEmailTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeItemDropdownTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeLongTextTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeNumberTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeObserverTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeRadioTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeRequestTypeTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeRequesterTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeShortTextTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeUrgencyTest.php
  src/Glpi/Form/Answer.php
  src/Glpi/Form/QuestionType/AbstractQuestionType.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeShortAnswer.php
  src/Glpi/Form/QuestionType/QuestionTypeDateTime.php
  src/Glpi/Form/QuestionType/QuestionTypeFile.php
  src/Glpi/Form/QuestionType/QuestionTypeInterface.php
  src/Glpi/Form/QuestionType/QuestionTypeItem.php
  src/Glpi/Form/QuestionType/QuestionTypeLongText.php
  src/Glpi/Form/QuestionType/QuestionTypeRequestType.php
  src/Glpi/Form/QuestionType/QuestionTypeUrgency.php
  src/Glpi/Form/Tag/AnswerTagProvider.php
  tests/cypress/e2e/form/question_types/selectables.cy.js
  tests/src/FormTesterTrait.php
Labels: enhancement, Forms

#17490 Fix default firewall strategies
  dependency_injection/services.php
  phpunit/functional/Glpi/Http/FirewallTest.php
  src/Glpi/Controller/Form/ServiceCatalogController.php
  src/Glpi/Controller/IndexController.php
  src/Glpi/Controller/StatusController.php
  src/Glpi/Http/Firewall.php
  src/Glpi/Http/FirewallInterface.php
  src/Glpi/Http/FirewallListener.php
  src/Glpi/Http/FirewallStrategyListener.php
  src/Glpi/Http/LegacyRouterListener.php
  src/Glpi/Http/LegacyRouterTrait.php
  tests/functional/Glpi/Http/Firewall.php
  tests/functional/Glpi/Http/LegacyRouterListener.php
Labels: security

#17726 Add description to service catalog
  install/migrations/update_10.0.x_to_11.0.0/form.php
  install/mysql/glpi-empty.sql
  templates/pages/admin/form/service_catalog_tab.html.twig
  templates/pages/self-service/service_catalog.html.twig
  tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
  tests/cypress/e2e/form/service_catalog/service_catalog_tab.cy.js
Labels: Forms

#17839 Components capacity
  CHANGELOG.md
  inc/relation.constant.php
  src/CommonDevice.php
  src/Computer.php
  src/Config.php
  src/Glpi/Asset/Capacity/HasDevicesCapacity.php
  src/Glpi/Dashboard/FakeProvider.php
  src/Glpi/Dashboard/Grid.php
  src/Item_Devices.php
  src/Plugin.php
  src/autoload/CFG_GLPI.php
  tests/functional/Glpi/Asset/Capacity/HasDevicesCapacity.php
Labels: enhancement

#17610 fix(central): satisfaction survey link criteria
  phpunit/DbTestCase.php
  phpunit/functional/SearchTest.php
  src/CommonITILSatisfaction.php
  src/Ticket.php
Labels: bug

#17819 Fix: reload session entities in case of modification
  inc/includes.php
  src/Session.php
  tests/functional/Session.php
Labels: bug

#17852 Fix(rule ticket): User_id_recipient criterion
  install/migrations/update_10.0.16_to_10.0.17/rule_tickets.php
  phpunit/functional/RuleTicketTest.php
  src/RuleTicket.php
Labels: bug

#17669 Custom Asset Type and Model Dictionaries
  .phpstan-baseline.php
  front/asset/asset.form.php
  front/asset/ruledictionarymodel.form.php
  front/asset/ruledictionarymodel.php
  front/asset/ruledictionarytype.form.php
  front/asset/ruledictionarytype.php
  front/rule.common.form.php
  phpunit/DbTestCase.php
  phpunit/functional/Glpi/Asset/DictionaryTest.php
  src/Glpi/Api/HL/Controller/RuleController.php
  src/Glpi/Asset/AssetDefinition.php
  src/Glpi/Asset/AssetDefinitionManager.php
  src/Glpi/Asset/RuleDictionaryModel.php
  src/Glpi/Asset/RuleDictionaryModelCollection.php
  src/Glpi/Asset/RuleDictionaryType.php
  src/Glpi/Asset/RuleDictionaryTypeCollection.php
  src/Rule.php
  src/RuleCollection.php
  src/RuleCommonITILObjectCollection.php
  src/RuleDictionnaryDropdownCollection.php
  tests/DbTestCase.php
Labels: enhancement

#17860 Feat(Framework): Add new hook (pre/post_item_accordion_section)
  src/Glpi/Plugin/Hooks.php
  templates/components/itilobject/fields_panel.html.twig
Labels: enhancement, feature suggestion

#17863 fix(forms): Fixed title field destination prepareInput
  src/Glpi/Form/Destination/CommonITILField/TitleField.php
Labels: Forms

#17868 Fix KnowbaseItem Clonability
  phpunit/functional/KnowbaseItemTest.php
  src/KnowbaseItem.php
Labels: enhancement

#17864 Add process and environment capacities
  phpunit/functional/Glpi/Inventory/Assets/Environment.php
  phpunit/functional/Glpi/Inventory/Assets/Process.php
  src/Glpi/Asset/Capacity/HasEnvironmentsCapacity.php
  src/Glpi/Asset/Capacity/HasProcessCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasEnvironmentsCapacity.php
  tests/functional/Glpi/Asset/Capacity/HasProcessCapacity.php
Labels: enhancement

#17858 fix(forms): Fixed retention of default value for question type actors
  src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
  src/Html.php
  tests/cypress/e2e/form/question_types/actors.cy.js
Labels: Forms

#17842 feat(forms): Take into account the fact that urgency levels can disabled
  phpunit/functional/Glpi/Form/Destination/CommonITILField/UrgencyFieldTest.php
  phpunit/functional/Glpi/Form/QuestionType/QuestionTypeUrgencyTest.php
  src/Glpi/Form/Destination/CommonITILField/UrgencyField.php
  src/Glpi/Form/QuestionType/QuestionTypeUrgency.php
Labels: Forms

#17820 Fix - RGB format for dashboard widget colours
  phpunit/functional/ToolboxTest.php
  src/Toolbox.php
Labels: bug

#17785 Filter service catalog using access policies
  phpunit/functional/Glpi/Form/AccessControl/FormAccessControlManagerTest.php
  phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php
  src/Glpi/Controller/Form/RendererController.php
  src/Glpi/Controller/Form/ServiceCatalogController.php
  src/Glpi/Controller/Form/SubmitAnswerController.php
  src/Glpi/Form/AccessControl/FormAccessControlManager.php
  src/Glpi/Form/AccessControl/FormAccessParameters.php
  src/Glpi/Form/ServiceCatalog/ServiceCatalogManager.php
  tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
  tests/cypress/support/commands/form.js
  tests/src/FormBuilder.php
  tests/src/FormTesterTrait.php
Labels: Forms

#17891 Fix(Core): prevent warning about 'legitimate' utf8mb4_bin
  src/DBmysql.php
Labels: bug

#17652 feat(forms): Add ITILCategory field configuration for form destination
  phpunit/functional/Glpi/Form/Destination/CommonITILField/ITILCategoryFieldTest.php
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
  src/Glpi/Form/Destination/CommonITILField/ITILCategoryField.php
  src/Glpi/Form/Destination/CommonITILField/ITILCategoryFieldConfig.php
  src/Glpi/Form/Destination/CommonITILField/ITILCategoryFieldStrategy.php
  templates/pages/admin/form/itil_config_fields/itilcategory.html.twig
  tests/cypress/e2e/form/destination_config_fields/itilcategory.cy.js
  tests/cypress/e2e/form/form_destination.cy.js
Labels: enhancement, Forms

#17897 Fix(planning): event min height
  css/legacy/includes/_planning.scss
  js/planning.js
Labels: bug

#17656 feat(forms): Adding comment tags for form destinations
  .phpstan-baseline.php
  phpunit/functional/Glpi/Form/Tag/CommentDescriptionTagProviderTest.php
  phpunit/functional/Glpi/Form/Tag/CommentTitleTagProviderTest.php
  phpunit/functional/Glpi/Form/Tag/FormTagsManagerTest.php
  src/Glpi/Form/Section.php
  src/Glpi/Form/Tag/CommentDescriptionTagProvider.php
  src/Glpi/Form/Tag/CommentTitleTagProvider.php
  src/Glpi/Form/Tag/FormTagsManager.php
  tests/cypress/e2e/form/form_tags.cy.js
Labels: enhancement, Forms

#17657 feat(forms): Add Location field configuration for form destination
  phpunit/functional/Glpi/Form/Destination/CommonITILField/LocationFieldTest.php
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
  src/Glpi/Form/Destination/CommonITILField/LocationField.php
  src/Glpi/Form/Destination/CommonITILField/LocationFieldConfig.php
  src/Glpi/Form/Destination/CommonITILField/LocationFieldStrategy.php
  templates/pages/admin/form/itil_config_fields/location.html.twig
  tests/cypress/e2e/form/destination_config_fields/location.cy.js
Labels: enhancement, Forms

#17792 feat(forms): Add Associated Items field configuration for form destination
  ajax/dropdownTrackingDeviceType.php
  css/includes/_includes.scss
  css/includes/components/form/_form-destination.scss
  js/modules/Forms/FieldDestinationAssociatedItem.js
  phpunit/functional/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldTest.php
  phpunit/functional/Glpi/Form/Tag/AnswerTagProviderTest.php
  src/CommonItilObject_Item.php
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
  src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
  src/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldConfig.php
  src/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldStrategy.php
  src/Glpi/Form/QuestionType/QuestionTypeItem.php
  templates/components/form/fields_macros.html.twig
  templates/pages/admin/form/itil_config_fields/associated_items.html.twig
  tests/cypress/e2e/form/destination_config_fields/associated_items.cy.js
Labels: Forms

#17904 New helpdesk home page
  css/helpdesk_home.scss
  css/includes/_base.scss
  lib/bundles/base.js
  package-lock.json
  package.json
  pics/serfservice-portal-header-1.svg
  pics/serfservice-portal-header-2.svg
  src/Glpi/Application/View/Extension/SessionExtension.php
  src/Glpi/Controller/SelfService/HomeController.php
  src/Html.php
  src/autoload/CFG_GLPI.php
  templates/layout/parts/menu.html.twig
  templates/layout/parts/page_header.html.twig
  templates/layout/parts/user_header.html.twig
  templates/pages/self-service/new_home.html.twig
  templates/pages/setup/general/preferences_setup.html.twig
Labels: Forms

#17929 Use `/plugins/` path prefix for all plugins resources
  .phpstan-baseline.php
  CHANGELOG.md
  js/modules/Screenshot/Screenshot.js
  src/Glpi/Application/ConfigurationConstants.php
  src/Glpi/Application/View/Extension/PluginExtension.php
  src/Glpi/Http/LegacyAssetsListener.php
  src/Glpi/Http/LegacyRouterListener.php
  src/Glpi/Http/LegacyRouterTrait.php
  src/Glpi/Marketplace/View.php
  src/Html.php
  src/Plugin.php
  src/Report.php
  src/Rule.php
  src/RuleCollection.php
  src/Stat.php
  stubs/glpi_constants.php
  tests/functional/Glpi/Http/LegacyAssetsListener.php
  tests/functional/Glpi/Http/LegacyRouterListener.php
Labels: enhancement, need_doc_improvement

#17925 Fix(ticket): update ticket status when planned task is updated
  phpunit/functional/TicketTaskTest.php
  src/CommonITILTask.php
  src/Features/ParentStatus.php
Labels: enhancement

#17938 Prevent Referer spoofing
  front/central.php
  front/helpdesk.public.php
  install/install.php
  phpunit/functional/HtmlTest.php
  src/Html.php
  src/MassiveAction.php
  src/Session.php
  src/Transfer.php
Labels: enhancement

#17954 Fix(Dashboard): filters not applied
  src/Dashboard/Grid.php
Labels: bug

#17956 Fix tab display in KB tooltip
  css/legacy/includes/_styles.scss
Labels: bug

#17482 Fix(Marketplace): retrieve 'changelog_url' from API
  src/Marketplace/View.php
Labels: enhancement

#17918 (Fix) Visibility of private task assign to me
  phpunit/functional/TicketTest.php
  src/CommonITILObject.php
Labels: bug

#17678 feat(forms): Add Entity field configuration for form destination
  phpunit/functional/Glpi/Form/Destination/CommonITILField/EntityFieldTest.php
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
  src/Glpi/Form/Destination/CommonITILField/EntityField.php
  src/Glpi/Form/Destination/CommonITILField/EntityFieldConfig.php
  src/Glpi/Form/Destination/CommonITILField/EntityFieldStrategy.php
  src/Glpi/Form/QuestionType/QuestionTypeItem.php
  templates/layout/parts/profile_selector.html.twig
  templates/pages/admin/form/itil_config_fields/entity.html.twig
  tests/cypress/e2e/form/destination_config_fields/entity.cy.js
Labels: enhancement, Forms

#17798 feat(forms): Add ITILFollowup field configuration for form destination
  phpunit/functional/Glpi/Form/Destination/CommonITILField/ITILFollowupFieldTest.php
  src/Dropdown.php
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
  src/Glpi/Form/Destination/CommonITILField/ITILFollowupField.php
  src/Glpi/Form/Destination/CommonITILField/ITILFollowupFieldConfig.php
  src/Glpi/Form/Destination/CommonITILField/ITILFollowupFieldStrategy.php
  templates/pages/admin/form/itil_config_fields/itilfollowuptemplate.html.twig
  tests/cypress/e2e/form/destination_config_fields/itilfollowup.cy.js
Labels: Forms

#17959 fix(forms): Fixed the E2E test by adding the default “disabled” attribute to wait for JS init
  js/modules/Forms/RendererController.js
  templates/pages/form_renderer.html.twig
Labels: Forms
