Repository glpi-project/glpi, pull requests merged in 2025-08, with the labels that each got.

#20469 Lazy load form editor dropdowns
  js/modules/Forms/EditorController.js
  templates/pages/admin/form/form_question.html.twig
Labels: performance, Forms

#20475 fix midnight theme muted color
  css/palettes/midnight.scss
Labels: ui

#20474 [HLAPI] RecordSet refactor
  src/Glpi/Api/HL/Controller/AbstractController.php
  src/Glpi/Api/HL/Doc/SearchRoute.php
  src/Glpi/Api/HL/GraphQL.php
  src/Glpi/Api/HL/GraphQLGenerator.php
  src/Glpi/Api/HL/Search.php
  src/Glpi/Api/HL/Search/RecordSet.php
  src/Glpi/Api/HL/Search/SearchContext.php
  src/Glpi/Debug/Profiler.php
Labels: api

#20500 Fix detected Psalm `TaintedHtml` issues
  ajax/asset/assetdefinition.php
  ajax/dashboard.php
  ajax/getDropdownNumber.php
  ajax/getDropdownUsers.php
  ajax/getDropdownValue.php
  psalm.xml
  src/DBConnection.php
  src/Glpi/Api/APIRest.php
  src/Glpi/Error/ErrorDisplayHandler/CliDisplayHandler.php
  src/Problem.php
Labels: security

#20503 Fix detected Psalm `TaintedInclude` issues
  psalm.xml
  src/Plugin.php
  src/autoload/legacy-autoloader.php
Labels: security

#20505 Fix detected Psalm `TaintedHeader` issues
  front/link.send.php
  front/pluginimage.send.php
  psalm.xml
  src/UploadHandler.php
Labels: security

#20567 Fix unexpected JS code output in project costs
  src/ProjectCost.php
Labels: bug

#20550 fix(forms): Delete helpdesk translations after parent item deleted
  phpunit/functional/Glpi/Helpdesk/Translation/HelpdeskTranslationTest.php
  src/Entity.php
  src/Glpi/Helpdesk/HelpdeskTranslation.php
  src/Glpi/Helpdesk/Tile/ExternalPageTile.php
  src/Glpi/Helpdesk/Tile/FormTile.php
  src/Glpi/Helpdesk/Tile/GlpiPageTile.php
  src/Glpi/Helpdesk/Tile/TileInterface.php
  templates/pages/helpdesk/index.html.twig
Labels: bug

#20573 Fix remaining legitimate Psalm issues
  psalm.xml
  src/Glpi/System/Log/LogParser.php
  src/UploadHandler.php
Labels: security

#20574 Improve search config UI
  templates/components/search/displaypreference_list.html.twig
Labels: ui

#20579 Fix breadcrumbs and type name for enclosure items
  front/item_enclosure.form.php
  src/Item_Enclosure.php
Labels: bug

#20593 Detect unused vars with Rector
  install/migrations/update_0.90.0_to_0.90.1.php
  install/migrations/update_0.90.1_to_0.90.5.php
  install/migrations/update_9.1.0_to_9.1.1.php
  install/migrations/update_9.1.1_to_9.1.3.php
  install/migrations/update_9.2.0_to_9.2.1.php
  install/migrations/update_9.2.1_to_9.2.2.php
  install/migrations/update_9.2.2_to_9.2.3.php
  install/migrations/update_9.2.x_to_9.3.0.php
  install/migrations/update_9.3.0_to_9.3.1.php
  install/migrations/update_9.3.1_to_9.3.2.php
  install/migrations/update_9.3.x_to_9.4.0.php
  install/migrations/update_9.5.5_to_9.5.6.php
  install/migrations/update_9.5.6_to_9.5.7.php
  rector.php
  src/Auth.php
  src/Change_Problem.php
  src/CommonDBVisible.php
  src/CommonItilObject_Item.php
  src/Contract_Supplier.php
  src/CronTask.php
  src/DBmysql.php
  src/Dropdown.php
  src/Entity.php
  src/Glpi/Agent/Communication/Headers/Common.php
  src/Glpi/Api/HL/RoutePath.php
  src/Glpi/Controller/ApiController.php
  src/Glpi/Dashboard/Grid.php
  src/Glpi/Dashboard/Widget.php
  src/Glpi/Features/TreeBrowse.php
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
  src/Glpi/Inventory/Asset/VirtualMachine.php
  src/Glpi/Search/Provider/SQLProvider.php
  src/Glpi/System/Requirement/IntegerSize.php
  src/Html.php
  src/IPAddress.php
  src/IPNetwork_Vlan.php
  src/Infocom.php
  src/Item_Environment.php
  src/Item_Line.php
  src/Item_Rack.php
  src/Itil_Project.php
  src/NetworkPortInstantiation.php
  src/NetworkPort_Vlan.php
  src/NotificationEvent.php
  src/NotificationTarget.php
  src/NotificationTargetSavedSearch_Alert.php
  src/NotificationTemplate.php
  src/PDU_Rack.php
  src/RuleCollection.php
  src/Search.php
  src/Software.php
  src/Ticket_Contract.php
  src/Transfer.php
  src/User.php
  src/Webhook.php
Labels: bug

#20594 Fix legacy API ignoring getSystemSQLCriteria
  phpunit/web/APIRestTest.php
  src/Glpi/Api/API.php
Labels: bug

#20596 fix dropdownTimestamp minute padding
  phpunit/functional/DropdownTest.php
  src/Dropdown.php
Labels: bug

#20603 Fix: PHP Deprecated function
  src/RichText/RichText.php
Labels: bug

#20625 Fix home search results displaying escaped html
  templates/pages/helpdesk/search.html.twig
Labels: Forms

#20628 Filter home tiles on tickets rights
  phpunit/DbTestCase.php
  phpunit/functional/Glpi/Helpdesk/Tile/TilesManagerTest.php
  src/Glpi/Helpdesk/Tile/FormTile.php
  src/Glpi/Helpdesk/Tile/GlpiPageTile.php
Labels: Forms

#20638 Delete linked tickets items when a form is deleted
  phpunit/functional/Glpi/Form/FormTest.php
  src/Glpi/Form/Form.php
Labels: Forms

#20650 [HLAPI] Add GraphQL scope and fix scope checks
  phpunit/HLAPITestCase.php
  phpunit/functional/Glpi/Api/HL/Controller/AdministrationControllerTest.php
  phpunit/functional/Glpi/Api/HL/Controller/CoreControllerTest.php
  phpunit/functional/Glpi/Api/HL/Controller/GraphQLControllerTest.php
  resources/api_doc.MD
  src/Glpi/Api/HL/Middleware/OAuthRequestMiddleware.php
  src/Glpi/OAuth/Server.php
  tests/src/autoload/functions.php
Labels: enhancement

#20639 Fix tabs text escaping and add some missing icons
  phpunit/functional/NotificationAjaxSettingTest.php
  phpunit/functional/NotificationMailingSettingTest.php
  src/AuthMail.php
  src/CommonGLPI.php
  src/CommonITILRecurrent.php
  src/Config.php
  src/DisplayPreference.php
  src/DomainRecord.php
  src/Glpi/Inventory/Conf.php
  src/Knowbase.php
  src/KnowbaseItemTranslation.php
  src/Location.php
  src/NotificationSetting.php
  src/Planning.php
  src/ReservationItem.php
  src/RuleCollection.php
  src/RuleImportAssetCollection.php
  src/Software.php
Labels: security, ui

#20519 Remove redundant itemantivirus tab ui and checks
  src/ItemAntivirus.php
  templates/components/form/item_antivirus_item.html.twig
  tests/cypress/e2e/Asset/computer.cy.js
Labels: enhancement

#20641 Fix warning on delegation form rendering
  phpunit/functional/TicketTest.php
  templates/components/itilobject/selfservice.html.twig
Labels: bug

#20659 Stateless path may concern plugin root itself
  phpunit/functional/Glpi/Http/FirewallTest.php
  phpunit/functional/Glpi/Http/RequestRouterTraitTest.php
  phpunit/functional/Glpi/Http/SessionManagerTest.php
  phpunit/web/Glpi/RoutingTest.php
  src/Glpi/Http/Firewall.php
  src/Glpi/Http/RequestRouterTrait.php
  src/Glpi/Http/SessionManager.php
  src/Glpi/Kernel/Listener/RequestListener/FrontEndAssetsListener.php
  src/Glpi/Kernel/Listener/RequestListener/LegacyRouterListener.php
  src/Glpi/Kernel/Listener/RequestListener/PluginsRouterListener.php
  src/Plugin.php
  tests/fixtures/plugins/tester/setup.php
  tests/fixtures/plugins/tester/src/Controller/TesterController.php
Labels: bug

#20595 fix ItemTranslation not limiting sql criteria
  phpunit/web/APIRestTest.php
  src/Glpi/Application/View/Extension/I18nExtension.php
  src/Glpi/Form/FormTranslation.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeShortAnswer.php
  src/Glpi/Form/QuestionType/QuestionTypeLongText.php
  src/Glpi/Helpdesk/HelpdeskTranslation.php
  src/Glpi/ItemTranslation/ItemTranslation.php
  templates/pages/form_renderer.html.twig
  templates/pages/helpdesk/index.html.twig
  tests/src/autoload/functions.php
Labels: bug

#20664 Fix unsaved form state on load
  src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
Labels: bug

#20697 Fix some escaping issues (5/x)
  src/Contact.php
  src/Glpi/Dashboard/Filters/AbstractFilter.php
  src/Glpi/Dashboard/Grid.php
  src/Glpi/Dashboard/Widget.php
  src/Glpi/Http/RedirectResponse.php
  src/MailCollector.php
  src/Toolbox.php
Labels: security

#20668 fix(forms-migration): Handle invalid DropdownItem configs
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php
Labels: bug, forms

#20688 UserDropdown can be required - fix #20425
  src/Dropdown.php
  src/Html.php
  src/User.php
Labels: enhancement

#20682 remove img usage in supplier links
  src/Dropdown.php
  src/Supplier.php
Labels: bug

#20523 Fix add/remove item MA forms
  src/CommonItilObject_Item.php
Labels: bug

#20702 GLPIKey::decrypt: Fix invalid method throws and add missing catch for base64_decode
  src/GLPIKey.php
Labels: bug

#20715 Use absolute path for console execution in tests bootstrap
  phpunit/bootstrap.php
  tests/bootstrap.php
Labels: task

#20723 fix(tests): Fixed form_translation E2E Tests by processing data-testid instead of aria-label
  templates/pages/form_renderer.html.twig
  tests/cypress/e2e/form/form_translation.cy.js
Labels: bug, forms

#20680 fix plugin join handling
  src/Glpi/Search/Provider/SQLProvider.php
Labels: bug

#20732 fix(forms): Update tab entry names to support pluralization
  phpunit/functional/Glpi/Form/AccessControl/FormAccessControlTest.php
  phpunit/functional/Glpi/Form/FormTest.php
  src/Glpi/Form/AccessControl/FormAccessControl.php
  src/Glpi/Form/Destination/FormDestination.php
  src/Glpi/Form/FormTranslation.php
Labels: bug, forms

#20735 fix(forms): Fixed locales issue with the label of the “Add” button on the form destination
  templates/pages/admin/form/form_destination.html.twig
Labels: bug, forms

#20761 Fix form editor "Enter" behavior
  templates/pages/admin/form/form_editor.html.twig
Labels: forms

#20771 fix(forms): improve TinyMCE content saving and validation handling
  js/modules/Forms/RendererController.js
  tests/cypress/e2e/form/form_rendering.cy.js
Labels: bug

#20774 Handle 2FA issuer suffix and fix 2FA display issue
  install/empty_data.php
  install/migrations/update_10.0.x_to_11.0.0/mfa.php
  phpunit/functional/Glpi/Security/TOTPManagerTest.php
  src/Glpi/Security/TOTPManager.php
  templates/pages/2fa/2fa_request.html.twig
  templates/pages/2fa/macros.html.twig
  templates/pages/setup/general/security_setup.html.twig
Labels: enhancement

#20765 fix(forms-migration): handle negative tree depth values for dropdown item questions
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php
Labels: bug

#20767 Add extra context to form import issues
  templates/pages/admin/form/import/step3_resolve_issues.html.twig
Labels: forms

#20769 fix TOC overflow on smaller screen sizes
  css/includes/components/_documentation.scss
Labels: api, ui

#20768 Fix `Plugin::getWebDir()` results with customized `GLPI_MARKETPLACE_DIR`
  phpunit/functional/PluginTest.php
  src/Glpi/Application/Environment.php
  src/Plugin.php
  tests/fixtures/marketplace/myplugin/setup.php
  tests/functional/Plugin.php
Labels: bug

#20775 Take completenames into acount in form export/import
  phpunit/functional/Glpi/Form/Export/FormSerializerAccessPoliciesTest.php
  phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
  src/Glpi/Form/AccessControl/ControlType/AllowList.php
  src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
  src/Glpi/Form/Destination/CommonITILField/EntityField.php
  src/Glpi/Form/Destination/CommonITILField/ITILActorField.php
  src/Glpi/Form/Destination/CommonITILField/ITILCategoryField.php
  src/Glpi/Form/Destination/CommonITILField/ITILFollowupField.php
  src/Glpi/Form/Destination/CommonITILField/ITILTaskField.php
  src/Glpi/Form/Destination/CommonITILField/LinkedITILObjectsField.php
  src/Glpi/Form/Destination/CommonITILField/LocationField.php
  src/Glpi/Form/Destination/CommonITILField/SLMField.php
  src/Glpi/Form/Destination/CommonITILField/TemplateField.php
  src/Glpi/Form/Destination/CommonITILField/ValidationField.php
  src/Glpi/Form/Export/Context/DatabaseMapper.php
  src/Glpi/Form/Export/Serializer/FormSerializer.php
  src/Glpi/Form/Export/Specification/DataRequirementSpecification.php
  src/Glpi/Form/Export/Specification/FormContentSpecification.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
  src/Glpi/Form/QuestionType/QuestionTypeItem.php
  tests/fixtures/export-of-2-forms.json
Labels: enhancement, forms

#20792 Fix generic asset type search pages
  src/Glpi/Asset/AssetType.php
Labels: bug

#20770 Form import: fix conflicts when resolving issues for multiple forms
  src/Glpi/Controller/Form/Import/Step3ResolveIssuesController.php
  templates/pages/admin/form/import/step3_resolve_issues.html.twig
Labels: bug, forms

#20806 Fix SLM link in level agreements forms
  src/LevelAgreement.php
Labels: bug

#20800 fix(service-catalog): Fixed search across categories in service catalog
  phpunit/functional/Glpi/Form/ServiceCatalog/Provider/CategoryProviderTest.php
  phpunit/functional/Glpi/Form/ServiceCatalog/Provider/KnowbaseItemProviderTest.php
  phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php
  src/Glpi/Controller/ServiceCatalog/ItemsController.php
  src/Glpi/Form/ServiceCatalog/Provider/CategoryProvider.php
  src/Glpi/Form/ServiceCatalog/Provider/KnowbaseItemProvider.php
  tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
Labels: bug, forms

#20809 Fix `is_recursive` forms inputs values
  src/Domain_Item.php
  templates/pages/management/document_item.html.twig
Labels: bug

#20623 fix(migration): handle unsupported value operators in form migration conditions
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Form/Migration/FormMigration.php
Labels: bug

#20820 Only call jsonDecode if used is not an array
  ajax/dropdownAllItems.php
Labels: bug

#20817 better adaptive colors icons for dark palettes
  css/includes/_palette_dark.scss
Labels: ui

#20788 Add altcha to public forms
  composer.json
  composer.lock
  css/includes/_base.scss
  lib/bundles/altcha.js
  package-lock.json
  package.json
  phpstan.neon.dist
  phpunit/functional/Glpi/Altcha/AltchaManagerTest.php
  src/Glpi/Altcha/AltchaManager.php
  src/Glpi/Altcha/AltchaMode.php
  src/Glpi/Altcha/InvalidPayloadException.php
  src/Glpi/Application/SystemConfigurator.php
  src/Glpi/Controller/Altcha/ChallengeController.php
  src/Glpi/Controller/Form/RendererController.php
  src/Glpi/Controller/Form/SubmitAnswerController.php
  src/Glpi/Toolbox/SingletonTrait.php
  src/Html.php
  templates/components/altcha/widget.html.twig
  templates/pages/form_renderer.html.twig
Labels: security, forms, need user doc

#20823 feat(forms): Implement "Is empty/Is not empty" value operator
  phpunit/functional/Glpi/Form/Condition/ConditionHandler/EmptyConditionHandlerTest.php
  phpunit/functional/Glpi/Form/Condition/EditorManagerTest.php
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Form/AnswersHandler/AnswersHandler.php
  src/Glpi/Form/Condition/ConditionHandler/EmptyConditionHandler.php
  src/Glpi/Form/Condition/ValueOperator.php
  src/Glpi/Form/Migration/FormMigration.php
  src/Glpi/Form/QuestionType/AbstractQuestionType.php
  tests/cypress/e2e/form/editor/conditions.cy.js
Labels: forms
