Repository glpi-project/glpi, pull requests merged in 2025-03, with the labels that each got.

#19081 Fix CLI database install command to support ssl
  src/Console/Database/InstallCommand.php
Labels: bug

#19116 Small enhancements on custom objects
  install/migrations/update_10.0.x_to_11.0.0/assets.php
  install/migrations/update_10.0.x_to_11.0.0/dropdowns.php
  install/mysql/glpi-empty.sql
  phpunit/functional/Glpi/Asset/AssetDefinitionTest.php
  phpunit/functional/Glpi/Asset/CustomFieldDefinitionTest.php
  phpunit/functional/Glpi/Dropdown/DropdownDefinitionTest.php
  src/Glpi/Asset/CustomFieldDefinition.php
  src/Glpi/CustomObject/AbstractDefinition.php
Labels: enhancement

#19026 Add conditions to form destinations
  install/migrations/update_10.0.x_to_11.0.0/form.php
  install/mysql/glpi-empty.sql
  js/modules/Forms/ConditionEditorController.js
  src/Glpi/Form/Comment.php
  src/Glpi/Form/Condition/ConditionnableTrait.php
  src/Glpi/Form/Condition/CreationStrategy.php
  src/Glpi/Form/Condition/FormData.php
  src/Glpi/Form/Destination/FormDestination.php
  src/Glpi/Form/Form.php
  src/Glpi/Form/Question.php
  src/Glpi/Form/Section.php
  templates/pages/admin/form/condition_configuration.html.twig
  templates/pages/admin/form/conditional_visibility_dropdown.html.twig
  templates/pages/admin/form/destination_visibility_conditions_configuration.html.twig
  templates/pages/admin/form/form_destination.html.twig
  tests/cypress/e2e/ajax_controller.cy.js
  tests/cypress/e2e/form/editor/conditions.cy.js
Labels: Forms

#19117 Enhance plugin migration framework (2)
  phpunit/functional/Glpi/Migration/AbstractPluginMigrationTest.php
  src/Glpi/Migration/AbstractPluginMigration.php
  src/Glpi/Migration/MigrationException.php
Labels: enhancement

#19127 Display form tags prefix
  phpunit/functional/Glpi/Form/Tag/TagTest.php
  src/Glpi/Form/Tag/Tag.php
  tests/cypress/e2e/form/form_tags.cy.js
Labels: Forms

#19086 Fix duplicate dashboards that replace other copies
  phpunit/functional/Glpi/Dashboard/DashboardTest.php
  src/Dashboard/Dashboard.php
Labels: bug

#19130 Compute conditional creation for form destinations
  phpunit/functional/Glpi/Form/AnswersHandler/AnswersHandlerTest.php
  phpunit/functional/Glpi/Form/ConditionalVisibility/EngineTest.php
  src/Glpi/Form/AnswersHandler/AnswersHandler.php
  src/Glpi/Form/AnswersSet.php
  src/Glpi/Form/Comment.php
  src/Glpi/Form/Condition/ConditionableCreationInterface.php
  src/Glpi/Form/Condition/ConditionableCreationTrait.php
  src/Glpi/Form/Condition/ConditionableInterface.php
  src/Glpi/Form/Condition/ConditionableTrait.php
  src/Glpi/Form/Condition/ConditionableVisibilityInterface.php
  src/Glpi/Form/Condition/ConditionableVisibilityTrait.php
  src/Glpi/Form/Condition/Engine.php
  src/Glpi/Form/Condition/EngineCreationOutput.php
  src/Glpi/Form/Condition/EngineVisibilityOutput.php
  src/Glpi/Form/Destination/FormDestination.php
  src/Glpi/Form/Question.php
  src/Glpi/Form/Section.php
  tests/src/FormBuilder.php
  tests/src/FormTesterTrait.php
Labels: Forms

#19055 fix(forms): Fix actors retrieving for end-user form rendering
  ajax/getFormQuestionActorsDropdownValue.php
  src/Glpi/Controller/Form/QuestionActorsDropdownController.php
  src/Glpi/Form/Dropdown/FormActorsDropdown.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
  src/Glpi/Form/QuestionType/QuestionTypeItem.php
  src/Glpi/Form/QuestionType/QuestionTypeUserDevice.php
  tests/cypress/e2e/form/destination_config_fields/associated_items.cy.js
  tests/cypress/e2e/form/destination_config_fields/entity.cy.js
  tests/cypress/e2e/form/destination_config_fields/validation.cy.js
  tests/cypress/e2e/form/service_catalog/default_forms.cy.js
Labels: bug, Forms

#19089 feat(forms): Implement form access type migration
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Console/Migration/AbstractPluginMigrationCommand.php
  src/Glpi/Console/Migration/FormCreatorPluginToCoreCommand.php
  src/Glpi/Form/Migration/FormMigration.php
  tests/glpi-formcreator-migration-data.sql
Labels: Forms

#19068 feat(forms): Adding KnowbaseItems in Service Catalog
  inc/relation.constant.php
  install/migrations/update_10.0.x_to_11.0.0/knowbaseitem.php
  install/mysql/glpi-empty.sql
  phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php
  src/Glpi/Form/ServiceCatalog/Provider/KnowbaseItemProvider.php
  src/Glpi/Form/ServiceCatalog/ServiceCatalog.php
  src/Glpi/Form/ServiceCatalog/ServiceCatalogManager.php
  src/KnowbaseItem.php
  templates/pages/admin/form/service_catalog_tab.html.twig
  tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
  tests/cypress/e2e/form/service_catalog/service_catalog_tab.cy.js
Labels: Forms

#19048 Allow usage of the `APPROVAL` status in tickets
  install/empty_data.php
  install/migrations/update_10.0.x_to_11.0.0/itilobject_templates.php
  install/mysql/glpi-empty.sql
  phpunit/functional/PendingReasonTest.php
  phpunit/functional/TicketTest.php
  src/Change.php
  src/CommonITILObject.php
  src/Problem.php
  src/Ticket.php
  templates/components/itilobject/fields_panel.html.twig
Labels: enhancement

#19129 Fix - Validation status when requesting a new validation after reject
  phpunit/functional/CommonITILValidationTest.php
  src/CommonITILValidation.php
Labels: bug

#19141 Purge dropdown display preferences when a dropdown definition is purged
  phpunit/functional/Glpi/Asset/AssetDefinitionTest.php
  phpunit/functional/Glpi/Dropdown/DropdownDefinitionTest.php
  src/Glpi/Asset/AssetDefinition.php
  src/Glpi/CustomObject/AbstractDefinition.php
  src/Glpi/Dropdown/DropdownDefinition.php
Labels: bug

#19155 Fine tune form editor responsive breakpoint
  templates/pages/admin/form/form_editor.html.twig
Labels: Forms

#19123 User forms UI twig and cleanup
  .phpstan-baseline.php
  CHANGELOG.md
  js/fileupload.js
  src/CommonDBChild.php
  src/User.php
  src/UserEmail.php
  templates/components/form/header.html.twig
  templates/components/user/password_security_checks.html.twig
  templates/components/user/picture.html.twig
  templates/pages/admin/user/change_other_password.html.twig
  templates/pages/admin/user/user.html.twig
  templates/pages/admin/user/user_picture_field.html.twig
  tests/cypress/e2e/Admin/user.cy.js
Labels: need_doc_improvement, ux

#19146 feat(forms): Handle default value conversions for datetime question type
  js/modules/Forms/QuestionDateTime.js
  src/Glpi/Form/QuestionType/QuestionTypeDateTime.php
  tests/cypress/e2e/form/question_types/date_and_time.cy.js
Labels: Forms

#19159 fix: infinite file upload progress bar issue with multiple textareas …
  src/Html.php
Labels: bug

#19142 Helpdesk form: store direct access token in session once validated
  js/modules/Forms/Condition/Engine.js
  phpunit/functional/Glpi/Form/AccessControl/ControlType/AllowListTest.php
  phpunit/functional/Glpi/Form/AccessControl/ControlType/DirectAccessTest.php
  src/Glpi/Controller/Form/RendererController.php
  src/Glpi/Controller/Form/Utils/CanCheckAccessPolicies.php
  src/Glpi/Form/AccessControl/ControlType/AllowList.php
  src/Glpi/Form/AccessControl/ControlType/ControlTypeInterface.php
  src/Glpi/Form/AccessControl/ControlType/DirectAccess.php
  src/Glpi/Form/AccessControl/FormAccessControlManager.php
  templates/pages/form_renderer.html.twig
Labels: Forms

#19176 fix(document): associated items link
  src/Document_Item.php
Labels: bug

#19178 Fix filtering on anonymous users in changes
  src/Search.php
Labels: bug

#19084 Kanban UI Changes
  css/includes/components/_kanban.scss
  css/includes/components/itilobject/_status.scss
  js/src/vue/Kanban/Card.vue
  js/src/vue/Kanban/Column.vue
  js/src/vue/Kanban/Kanban.vue
  js/src/vue/Kanban/TeamBadgeProvider.js
  src/CommonITILObject.php
  src/Project.php
Labels: enhancement

#19181 Fix(Planning): improve UX
  css/legacy/includes/_planning.scss
  js/planning.js
Labels: bug, ux

#19210 Update dependencies to get latests vulnerabilities fixes
  package-lock.json
Labels: dependencies, javascript

#19212 feat(forms): add a badge that displays the number of elements in a section when it is collapsed
  css/includes/components/form/_form-editor.scss
  js/modules/Forms/EditorController.js
  templates/pages/admin/form/form_section.html.twig
  tests/cypress/e2e/form/editor/editor.cy.js
Labels: Forms

#19173 fix(ITILSolution): document not visible
  src/ITILSolution.php
Labels: bug

#19154 Remove redundant user picture search option
  CHANGELOG.md
  install/migrations/update_10.0.x_to_11.0.0/user.php
  src/Migration.php
  src/User.php
  tests/functional/Migration.php
Labels: enhancement

#19177 fix: Fix rights verification for updating saved searches via massive action
  .phpstan-baseline.php
  phpunit/functional/MassiveActionTest.php
  src/SavedSearch.php
Labels: bug

#19233 Fix(Inventory): keep manual NetworkPort if non dynamic
  phpunit/functional/Glpi/Inventory/Assets/NetworkEquipmentTest.php
  src/Inventory/Asset/InventoryNetworkPort.php
Labels: bug, inventory

#18874 Upgrade Tabler to v1.0.0 Stable
  css/includes/_base.scss
  css/includes/components/_fileupload.scss
  css/includes/components/_networkport.scss
  css/includes/components/_select2.scss
  css/legacy/includes/_impact.scss
  css/palettes/_auror_dark.scss
  css/palettes/_darker.scss
  css/palettes/_midnight.scss
  js/src/vue/Debug/Toolbar.vue
  lib/bundles/tablericons-definitions.js
  package-lock.json
  package.json
  src/Impact.php
  src/Telemetry.php
  templates/components/itilobject/itilsatisfaction.html.twig
  templates/components/pager.html.twig
Labels: enhancement

#18939 Changes the style of the reasons for waiting completed
  src/PendingReason_Item.php
  templates/components/itilobject/timeline/pending_reasons_messages.html.twig
Labels: enhancement

#19171 feat: add knowlegde for followup
  src/Glpi/Controller/Knowbase/KnowbaseItemController.php
  templates/components/itilobject/timeline/form_followup.html.twig
  templates/components/itilobject/timeline/form_solution.html.twig
  templates/components/itilobject/timeline/knowledge_item.html.twig
  templates/pages/tools/search_knowbaseitem.html.twig
  tests/cypress/e2e/ITILObject/ticket_form.cy.js
Labels: enhancement

#19253 Rework home tile configuration UX
  js/modules/Helpdesk/HelpdeskConfigController.js
  src/Glpi/Controller/Config/Helpdesk/DeleteTileController.php
  src/Glpi/Helpdesk/Tile/TilesManager.php
  templates/components/form/fields_macros.html.twig
  templates/components/illustration/icon_picker_modal.html.twig
  templates/pages/admin/external_page_tile_config_fields.html.twig
  templates/pages/admin/glpi_page_tile_config_fields.html.twig
  templates/pages/admin/helpdesk_home_config.html.twig
  templates/pages/admin/helpdesk_home_config_add_tile_form.html.twig
  templates/pages/admin/helpdesk_home_config_edit_tile_form.html.twig
  templates/pages/admin/helpdesk_home_config_tiles.html.twig
  tests/cypress/e2e/self-service/home_config.cy.js
Labels: Forms

#19258 Helpdesk forms: support regex on strings conditions
  phpunit/functional/Glpi/Form/Condition/ConditionHandler/StringConditionHandlerTest.php
  phpunit/functional/Glpi/Form/Condition/EditorManagerTest.php
  src/Glpi/Form/Condition/ConditionHandler/StringConditionHandler.php
  src/Glpi/Form/Condition/ValueOperator.php
Labels: Forms

#19236 ui(forms): rework form destination UI
  css/includes/components/form/_form-destination.scss
  js/modules/Forms/DestinationConditionController.js
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
  src/Glpi/Form/Destination/CommonITILField/AssigneeField.php
  src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
  src/Glpi/Form/Destination/CommonITILField/Category.php
  src/Glpi/Form/Destination/CommonITILField/ContentField.php
  src/Glpi/Form/Destination/CommonITILField/LocationField.php
  src/Glpi/Form/Destination/CommonITILField/OLATTOField.php
  src/Glpi/Form/Destination/CommonITILField/OLATTRField.php
  src/Glpi/Form/Destination/CommonITILField/ObserverField.php
  src/Glpi/Form/Destination/CommonITILField/RequestTypeField.php
  src/Glpi/Form/Destination/CommonITILField/RequesterField.php
  src/Glpi/Form/Destination/CommonITILField/SLATTOField.php
  src/Glpi/Form/Destination/CommonITILField/SLATTRField.php
  src/Glpi/Form/Destination/CommonITILField/StatusField.php
  src/Glpi/Form/Destination/CommonITILField/TemplateField.php
  src/Glpi/Form/Destination/CommonITILField/TitleField.php
  src/Glpi/Form/Destination/FormDestinationInterface.php
  templates/components/itilobject/layout.html.twig
  templates/pages/admin/form/form_destination.html.twig
  templates/pages/admin/form/form_destination_commonitil_config.html.twig
  templates/pages/admin/form/itil_config_fields/associated_items.html.twig
  tests/cypress/e2e/form/destination_config_fields/actors.cy.js
  tests/cypress/e2e/form/destination_config_fields/assignee.cy.js
  tests/cypress/e2e/form/destination_config_fields/associated_items.cy.js
  tests/cypress/e2e/form/destination_config_fields/entity.cy.js
  tests/cypress/e2e/form/destination_config_fields/itilcategory.cy.js
  tests/cypress/e2e/form/destination_config_fields/itilfollowup.cy.js
  tests/cypress/e2e/form/destination_config_fields/itiltask.cy.js
  tests/cypress/e2e/form/destination_config_fields/location.cy.js
  tests/cypress/e2e/form/destination_config_fields/observer.cy.js
  tests/cypress/e2e/form/destination_config_fields/ola_tto.cy.js
  tests/cypress/e2e/form/destination_config_fields/ola_ttr.cy.js
  tests/cypress/e2e/form/destination_config_fields/request_source.cy.js
  tests/cypress/e2e/form/destination_config_fields/request_type.cy.js
  tests/cypress/e2e/form/destination_config_fields/requester.cy.js
  tests/cypress/e2e/form/destination_config_fields/sla_tto.cy.js
  tests/cypress/e2e/form/destination_config_fields/sla_ttr.cy.js
  tests/cypress/e2e/form/destination_config_fields/template.cy.js
  tests/cypress/e2e/form/destination_config_fields/title.cy.js
  tests/cypress/e2e/form/destination_config_fields/urgency.cy.js
  tests/cypress/e2e/form/destination_config_fields/validation.cy.js
  tests/cypress/e2e/form/editor/conditions.cy.js
  tests/cypress/e2e/form/form_destination.cy.js
  tests/cypress/e2e/form/form_tags.cy.js
  tests/cypress/support/commands.js
  tests/src/Form/Destination/AbstractFormDestinationType.php
Labels: Forms

#19272 fix(forms): Make some UI/UX fixes for destinations : accordion & remove dynamic input
  css/includes/components/form/_form-destination.scss
  templates/pages/admin/form/form_destination.html.twig
  templates/pages/admin/form/form_destination_commonitil_config.html.twig
Labels: Forms

#19271 Do not serve resources from unloaded plugins
  phpunit/functional/Glpi/Http/Listener/LegacyAssetsListenerTest.php
  phpunit/functional/Glpi/Http/Listener/LegacyRouterListenerTest.php
  src/Glpi/Http/Listener/LegacyAssetsListener.php
  src/Glpi/Http/Listener/LegacyRouterListener.php
  src/Glpi/Http/Listener/PluginsRouterListener.php
Labels: enhancement, security

#19285 fix(forms): ensure form description translation fallback returns an empty string
  src/Glpi/Form/Form.php
  tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
Labels: bug, Forms

#19280 Remove AbstractFormDestinationType
  phpunit/functional/Glpi/Form/Destination/FormDestinationChangeTest.php
  phpunit/functional/Glpi/Form/Destination/FormDestinationProblemTest.php
  phpunit/functional/Glpi/Form/Destination/FormDestinationTicketTest.php
  phpunit/functional/Glpi/Form/Destination/FormDestinationTypeManagerTest.php
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
  src/Glpi/Form/Destination/AbstractFormDestinationType.php
  src/Glpi/Form/Destination/CommonITILField/TemplateFieldConfig.php
  src/Glpi/Form/Destination/FormDestination.php
  src/Glpi/Form/Destination/FormDestinationChange.php
  src/Glpi/Form/Destination/FormDestinationInterface.php
  src/Glpi/Form/Destination/FormDestinationProblem.php
  src/Glpi/Form/Destination/FormDestinationTicket.php
  src/Glpi/Form/Destination/FormDestinationTypeManager.php
  templates/pages/admin/form/form_destination.html.twig
  tests/src/Form/Destination/AbstractCommonITILFormDestinationType.php
Labels: Forms

#19287 feat(forms): implement migration process for form translations
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Form/Migration/FormMigration.php
  tests/glpi-formcreator-migration-data.sql
Labels: Forms

#19266 feat(forms): add translation support for default values of short answer questions
  src/Glpi/Form/QuestionType/AbstractQuestionTypeShortAnswer.php
  src/Glpi/Form/QuestionType/QuestionTypeShortText.php
  tests/cypress/e2e/form/form_translation.cy.js
Labels: Forms

#19310 Form creation tweaks
  front/form/form.form.php
Labels: Forms

#19311 Autofocus icon picker search bar
  js/modules/IllustrationPicker/Controller.js
  tests/cypress/e2e/illustration_picker.cy.js
Labels: Forms

#19312 Prevent false positive "unsaved changed" warning on access control tab
  templates/pages/admin/form/access_control/allow_list.html.twig
Labels: Forms

#19306 Init form access policies on creation
  phpunit/functional/Glpi/Form/AccessControl/ControlType/AllowListTest.php
  phpunit/functional/Glpi/Form/AccessControl/ControlType/DirectAccessTest.php
  phpunit/functional/Glpi/Form/AccessControl/FormAccessControlManagerTest.php
  phpunit/functional/Glpi/Form/AccessControl/FormAccessControlTest.php
  phpunit/functional/Glpi/Form/Export/FormSerializerAccessPoliciesTest.php
  phpunit/functional/Glpi/Form/FormTest.php
  phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php
  phpunit/functional/Glpi/Helpdesk/Tile/TilesManagerTest.php
  phpunit/functional/LogTest.php
  src/Glpi/Form/Export/Serializer/FormSerializer.php
  src/Glpi/Form/Form.php
  src/Glpi/Form/Migration/FormMigration.php
  src/Glpi/Helpdesk/DefaultDataManager.php
  tests/cypress/e2e/ajax_controller.cy.js
  tests/cypress/e2e/form/access_policies/access_control.cy.js
  tests/cypress/e2e/form/access_policies/direct_access.cy.js
  tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
  tests/src/FormBuilder.php
  tests/src/FormTesterTrait.php
Labels: Forms
