Repository glpi-project/glpi, pull requests merged in 2025-04, with the labels that each got.

#19319 Add specific style for pinned forms
  css/includes/components/_utils.scss
  templates/components/helpdesk_forms/service_catalog_item.html.twig
  tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
Labels: Forms

#19318 Remove mandatory destinations; show warning instead
  install/migrations/update_10.0.x_to_11.0.0/form.php
  install/mysql/glpi-empty.sql
  phpunit/functional/Glpi/Form/Destination/FormDestinationManagerTest.php
  phpunit/functional/Glpi/Form/Destination/FormDestinationTest.php
  phpunit/functional/Glpi/Form/Export/FormSerializerDestinationTest.php
  phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
  src/Glpi/Form/AnswersHandler/AnswersHandler.php
  src/Glpi/Form/Destination/FormDestination.php
  src/Glpi/Form/Destination/FormDestinationManager.php
  src/Glpi/Form/Export/Serializer/FormSerializer.php
  src/Glpi/Form/Export/Specification/DestinationContentSpecification.php
  src/Glpi/Form/Form.php
  src/Glpi/Form/Migration/FormMigration.php
  src/Glpi/Helpdesk/DefaultDataManager.php
  templates/pages/admin/form/form_destination.html.twig
  tests/cypress/e2e/form/editor/conditions.cy.js
  tests/src/FormBuilder.php
  tests/src/FormTesterTrait.php
Labels: Forms

#19344 Small forms tweaks
  css/includes/components/_illustration-picker.scss
  css/includes/components/_utils.scss
  src/Glpi/Form/Form.php
  templates/components/form/fields_macros.html.twig
  templates/components/helpdesk_forms/service_catalog_nested_item.html.twig
  templates/layout/parts/context_links.html.twig
  templates/pages/admin/external_page_tile_config_fields.html.twig
  templates/pages/admin/form/service_catalog_tab.html.twig
  templates/pages/admin/glpi_page_tile_config_fields.html.twig
Labels: Forms

#19366 fix(business rule): first group of user without group
  phpunit/functional/RuleAssetTest.php
  src/RuleAsset.php
Labels: bug

#19374 fix(forms-migration): add error handling for orphan sections and questions during migration
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Form/Migration/FormMigration.php
Labels: bug, Forms

#19263 Forms: allow plugins to define custom access policies
  phpunit/functional/Glpi/Form/AccessControl/FormAccessControlManagerTest.php
  src/Glpi/Form/AccessControl/ControlType/AllowList.php
  src/Glpi/Form/AccessControl/ControlType/ControlTypeInterface.php
  src/Glpi/Form/AccessControl/ControlType/DirectAccess.php
  src/Glpi/Form/AccessControl/FormAccessControlManager.php
  tests/cypress/e2e/form/form_plugins.cy.js
  tests/fixtures/plugins/tester/setup.php
  tests/fixtures/plugins/tester/src/Form/DayOfTheWeekPolicy.php
  tests/fixtures/plugins/tester/src/Form/DayOfTheWeekPolicyConfig.php
  tests/fixtures/plugins/tester/templates/day_of_the_week_policy.html.twig
Labels: Forms

#18978 search option: fix negative conditions
  phpunit/functional/SearchTest.php
  src/Appliance.php
  src/Search.php
Labels: bug

#19314 fix(forms): Fixed a few php errors triggered when using forms
  phpunit/functional/Glpi/Form/Condition/EngineTest.php
  phpunit/functional/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldTest.php
  phpunit/src/Glpi/Form/QuestionType/AbstractQuestionTypeActorsTest.php
  src/Glpi/Form/Condition/Engine.php
  src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
  templates/pages/admin/form/condition_handler_templates/dropdown_multiple.html.twig
  tests/src/FormBuilder.php
Labels: bug, Forms

#19179 Feature/form item condition
  js/modules/Forms/Condition/Engine.js
  js/modules/Forms/ConditionEditorController.js
  phpunit/functional/Glpi/Form/Condition/ConditionHandler/ItemConditionHandlerTest.php
  src/Glpi/Form/Condition/ConditionHandler/ItemConditionHandler.php
  src/Glpi/Form/QuestionType/QuestionTypeItem.php
  templates/pages/admin/form/condition_configuration.html.twig
  templates/pages/admin/form/condition_handler_templates/item_dropdown.html.twig
  tests/cypress/e2e/form/editor/conditions.cy.js
  tests/cypress/support/commands/form.js
Labels: Forms

#19390 Fix(Ticket): add missing ExternalId search option
  src/Ticket.php
Labels: enhancement

#19352 fix: Adding missing CSRF tokens for users preferences page + enhance accessibility
  src/CommonDBChild.php
  src/UserEmail.php
  templates/pages/admin/user/user.html.twig
  tests/cypress/e2e/Admin/user.cy.js
Labels: bug

#19160 Add old_id and new_id col in glpi_logs table
  install/migrations/update_10.0.x_to_11.0.0/logs.php
  install/mysql/glpi-empty.sql
  phpunit/functional/ConfigTest.php
  phpunit/functional/LogTest.php
  src/Log.php
Labels: enhancement

#19405 Prevent unicity from template on update
  phpunit/functional/CommonDBTMTest.php
  src/CommonDBTM.php
Labels: bug

#19404 Fix error page display when database is corrupted
  src/Glpi/Application/View/Extension/FrontEndAssetsExtension.php
Labels: bug

#19399 Fix save and preview
  js/common.js
  js/modules/Forms/EditorController.js
  templates/components/itilobject/timeline/pending_reasons.html.twig
  templates/pages/admin/form/access_control/allow_list.html.twig
  templates/pages/admin/form/form_editor.html.twig
Labels: Forms

#19230 Fix deletion of a used asset model/type
  phpunit/functional/Glpi/Asset/AssetModelTest.php
  phpunit/functional/Glpi/Asset/AssetTypeTest.php
  src/CommonDBTM.php
  src/CommonDropdown.php
Labels: bug

#19419 Add tooltip style for rule action addition
  src/Rule.php
Labels: enhancement

#19418 Fix missing CSRF in update process
  install/update.php
Labels: bug

#19415 fix(forms): Fixed how translation handlers are retrieved to work with horizontal layout
  phpunit/functional/Glpi/Form/Translation/FormTranslationTest.php
  src/Glpi/Form/Section.php
  tests/src/FormBuilder.php
  tests/src/FormTesterTrait.php
Labels: bug, Forms

#19183 Feature/form user devices condition
  phpunit/functional/Glpi/Form/Condition/ConditionHandler/UserDevicesConditionHandlerTest.php
  src/Glpi/Form/Condition/ConditionHandler/UserDevicesConditionHandler.php
  src/Glpi/Form/Condition/ValueOperator.php
  src/Glpi/Form/QuestionType/QuestionTypeUserDevice.php
  templates/pages/admin/form/condition_handler_templates/user_devices_dropdown.html.twig
  tests/cypress/e2e/form/editor/conditions.cy.js
Labels: Forms

#19416 Prevent form destination accordion from closing when typing
  css/includes/components/form/_form-destination.scss
  js/modules/Forms/DestinationConditionController.js
  templates/pages/admin/form/form_destination.html.twig
Labels: Forms

#19437 make a default gradient for helpdesk header
  css/includes/_base.scss
Labels: enhancement

#19438 fix(forms): Improved UI for horizontal layout elements
  css/includes/components/form/_form-editor-horizontal-layout.scss
  src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
Labels: bug, Forms

#19426 Fix(Inventory): Do not handle lock on add
  phpunit/functional/LockedfieldTest.php
  src/CommonDBTM.php
Labels: bug, inventory

#19429 Fix(Ruleright): fix test engine
  src/RuleRightCollection.php
Labels: bug

#19445 fix(forms): Service Catalog "Sort by" Icon displayed outside of dropdown
  js/modules/Forms/ServiceCatalogController.js
Labels: bug, Forms

#19425 Add a proper "install required" page
  src/Glpi/Controller/InstallController.php
  src/Glpi/Kernel/Listener/RequestListener/CheckDatabaseStatusListener.php
  templates/install/install.install_required.html.twig
Labels: enhancement

#19433 fix(lockfield): replace dropdown value don't replace locked fields
  phpunit/functional/LockedfieldTest.php
  src/CommonDBTM.php
Labels: bug

#19453 fix: Missing attachments in entity notes
  src/Html.php
  templates/components/itilobject/fields_panel.html.twig
  templates/components/notepad/form.html.twig
  tests/cypress/e2e/entity_notes.cy.js
Labels: bug

#19385 fix(forms-migration): Add null handling for mapped items and update horizontal rank
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
  src/Glpi/Form/Destination/CommonITILField/EntityField.php
  src/Glpi/Form/Destination/CommonITILField/ITILActorField.php
  src/Glpi/Form/Destination/CommonITILField/ITILCategoryField.php
  src/Glpi/Form/Destination/CommonITILField/LocationField.php
  src/Glpi/Form/Destination/CommonITILField/RequestTypeField.php
  src/Glpi/Form/Destination/CommonITILField/UrgencyField.php
  src/Glpi/Form/Destination/CommonITILField/ValidationField.php
  src/Glpi/Form/Migration/FormMigration.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
  src/Glpi/Migration/AbstractPluginMigration.php
Labels: bug, Forms

#19502 Export/Import form destinations creation conditions
  phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
  src/Glpi/Form/Export/Serializer/FormSerializer.php
  src/Glpi/Form/Export/Specification/DestinationContentSpecification.php
Labels: Forms

#19465 Display plugin local logo files in the marketplace
  phpunit/functional/Glpi/Http/FirewallTest.php
  src/Glpi/Controller/Plugin/LogoController.php
  src/Glpi/Http/Firewall.php
  src/Glpi/Marketplace/View.php
Labels: enhancement, need_doc_improvement

#19483 Display a dedicated page when webserver is misconfigured
  index.html
Labels: enhancement

#19504 Client side validation for mandatory questions
  js/modules/Forms/Condition/Engine.js
  js/modules/Forms/RendererController.js
  tests/cypress/e2e/form/form_rendering.cy.js
  tests/cypress/support/commands/form.js
Labels: Forms

#19452 Fix(TicketRule): do not compute takeintoaccount if needed
  phpunit/functional/RuleTicketTest.php
  phpunit/functional/SlaLevel_TicketTest.php
  src/CommonITILObject.php
Labels: bug

#19472 Fix dropdown conditions
  js/modules/Forms/RendererController.js
  src/Glpi/Form/Condition/ConditionHandler/SingleChoiceFromValuesConditionHandler.php
  src/Glpi/Form/Condition/Engine.php
  src/Glpi/Form/QuestionType/QuestionTypeDropdown.php
  templates/pages/admin/form/condition_handler_templates/dropdown_multiple.html.twig
  templates/pages/form_renderer.html.twig
  tests/cypress/e2e/form/editor/conditions.cy.js
Labels: Forms

#19503 [HLAPI] Add descriptions for enums
  src/Glpi/Api/HL/Controller/AssetController.php
  src/Glpi/Api/HL/Controller/ITILController.php
  src/Glpi/Api/HL/Controller/ManagementController.php
  src/Glpi/Api/HL/Controller/ProjectController.php
Labels: enhancement

#19466 Feat(ITIL object): check mandatory fields for solution
  phpunit/functional/ITILTemplateTest.php
  src/CommonITILObject.php
  templates/components/itilobject/footer.html.twig
Labels: enhancement

#19484 fix(supplier): restore 'Clone' MA for supplier
  phpunit/functional/SupplierTest.php
  src/Supplier.php
Labels: Need unit tests

#19544 update illustrations to 0.5.3
  package-lock.json
  package.json
  phpunit/functional/Glpi/UI/IllustrationManagerTest.php
Labels: ui

#19533 Cron script fixes
  front/cron.php
Labels: bug

#19560 Fix relative paths
  js/modules/Forms/ConditionEditorController.js
  src/Glpi/Form/Form.php
  templates/pages/admin/form/form_destination_actions.html.twig
Labels: Forms

#17197 Move automatic email exclusion logic to mail collector rules
  CHANGELOG.md
  install/migrations/update_10.0.x_to_11.0.0/mailcollector_rules.php
  phpunit/imap/MailCollectorTest.php
  resources/Rules/RuleMailCollector.xml
  src/MailCollector.php
  src/RuleMailCollector.php
  tests/emails-tests/22.1-notification-from-glpi-old-messageid-format.eml
  tests/emails-tests/22.1-ticket-notification-from-glpi-9.x.eml
  tests/emails-tests/22.2-notification-from-glpi-new-messageid-format.eml
  tests/emails-tests/22.2-ticket-notification-from-glpi-10.0.0.eml
  tests/emails-tests/22.3-ticket-notification-from-glpi-10.0.7.eml
  tests/emails-tests/22.4-softwarelicence-notification-from-glpi-9.x.eml
  tests/emails-tests/22.5-softwarelicence-notification-from-glpi-10.0.0.eml
  tests/emails-tests/22.6-softwarelicence-notification-from-glpi-10.0.7.eml
  tests/emails-tests/22.7-itemless-notification-from-glpi-9.x.eml
  tests/emails-tests/22.8-itemless-notification-from-glpi-10.0.0.eml
  tests/emails-tests/22.9-itemless-notification-from-glpi-10.0.7.eml
  tests/emails-tests/23-uuid-from-another-glpi.eml
Labels: enhancement, need_doc_improvement

#19566 Some twig templates fixes
  templates/components/datatable.html.twig
  templates/components/form/basic_inputs_macros.html.twig
  templates/components/form/fields_macros.html.twig
  templates/components/itilobject/fields_panel.html.twig
  templates/components/itilobject/timeline/sub_documents.html.twig
  templates/components/notepad/form.html.twig
  templates/components/photoswipe.html.twig
Labels: bug

#19569 Fix(Device): add missing 'serial' and 'otherserial' for search option to add
  src/DeviceGraphicCard.php
  src/DeviceHardDrive.php
  src/DeviceMemory.php
  src/DeviceMotherboard.php
  src/DeviceNetworkCard.php
  src/DevicePci.php
  src/DevicePowerSupply.php
  src/DeviceProcessor.php
  src/DeviceSoundCard.php
Labels: enhancement

#19565 Fix(change): add missing 'to_validate' list from central personal view
  .phpstan-baseline.php
  phpunit/functional/ChangeTest.php
  src/Central.php
  src/Change.php
Labels: bug

#19543 feat(forms): Migrate form conditions
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Form/Condition/ConditionHandler/SingleChoiceFromValuesConditionHandler.php
  src/Glpi/Form/Condition/FormData.php
  src/Glpi/Form/Migration/ConditionHandlerDataConverterInterface.php
  src/Glpi/Form/Migration/FormMigration.php
  templates/pages/admin/form/destination_visibility_conditions_configuration.html.twig
  tests/glpi-formcreator-migration-data.sql
Labels: Forms

#19474 fix(forms): Refactoring migration logic to skip orphan elements messages, and improve default value handling for some question types
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Form/Migration/FormMigration.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
  src/Glpi/Form/QuestionType/QuestionTypeUrgency.php
Labels: bug, Forms

#19219 feat(forms): prevent form elements deletion when they are used by conditions
  js/modules/Forms/EditorController.js
  src/Glpi/Form/Form.php
  templates/pages/admin/form/form_editor.html.twig
  templates/pages/admin/form/item_has_conditions_modal.html.twig
  templates/pages/admin/form/move_section_modal.html.twig
  tests/cypress/e2e/form/editor/conditions.cy.js
Labels: Forms
