Repository glpi-project/glpi, pull requests merged in 2025-07, with the labels that each got.

#20154 feat: setup option view for default marketplace
  templates/pages/setup/general/glpinetwork_setup.html.twig
Labels: enhancement

#20158 Custom helpdesk title
  install/empty_data.php
  install/migrations/update_10.0.x_to_11.0.0/form.php
  install/mysql/glpi-empty.sql
  phpunit/functional/EntityTest.php
  src/Entity.php
  templates/pages/admin/helpdesk_home_config_for_entity.html.twig
  templates/pages/helpdesk/index.html.twig
  tests/cypress/e2e/self-service/home_config.cy.js
Labels: Forms

#20132 feat(forms): Allow the use of the “email” question type as an actor
  phpunit/abstracts/AbstractActorFieldTest.php
  phpunit/functional/Glpi/Form/Condition/ConditionHandler/AbstractConditionHandler.php
  phpunit/functional/Glpi/Form/Destination/CommonITILField/AssigneeFieldTest.php
  phpunit/functional/Glpi/Form/Destination/CommonITILField/ObserverFieldTest.php
  phpunit/functional/Glpi/Form/Destination/CommonITILField/RequesterFieldTest.php
  src/Glpi/Form/Condition/Engine.php
  src/Glpi/Form/Destination/CommonITILField/AssigneeField.php
  src/Glpi/Form/Destination/CommonITILField/ITILActorField.php
  src/Glpi/Form/Destination/CommonITILField/ITILActorFieldStrategy.php
  src/Glpi/Form/Destination/CommonITILField/ObserverField.php
  src/Glpi/Form/Destination/CommonITILField/RequesterField.php
  tests/cypress/e2e/form/destination_config_fields/actors.cy.js
  tests/cypress/e2e/form/destination_config_fields/assignee.cy.js
  tests/cypress/e2e/form/destination_config_fields/observer.cy.js
  tests/cypress/e2e/form/destination_config_fields/requester.cy.js
  tests/cypress/e2e/form/form_destination.cy.js
Labels: Forms

#20181 Fix(Inventory): add missing model to RuleImportAsset for Monitor
  phpunit/functional/Glpi/Inventory/Assets/MonitorTest.php
  src/Inventory/Asset/Monitor.php
Labels: bug

#20137 Fix(Inventory): fix output when actio n is RULE_ACTION_LINK_OR_NO_IMPORT
  phpunit/functional/Glpi/Inventory/InventoryTest.php
  src/RuleImportAsset.php
Labels: bug

#20218 Restrict HLAPI debug mode
  phpunit/functional/Glpi/Api/HL/Middleware/DebugRequestMiddlewareTest.php
  src/Glpi/Api/HL/Middleware/DebugRequestMiddleware.php
Labels: api

#20223 Fix opacity concerns for form access controls
  templates/pages/admin/form/access_control.html.twig
Labels: Forms

#20224 Forms: prevent unauthenticated users from pasting images
  phpunit/functional/Glpi/Form/Destination/CommonITILField/EntityFieldTest.php
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
  src/Glpi/Form/Destination/CommonITILField/EntityField.php
  src/Glpi/Form/Destination/CommonITILField/EntityFieldStrategy.php
  src/Glpi/Form/QuestionType/QuestionTypeLongText.php
Labels: Forms

#20237 Bypass rights when creating tickets from forms
  phpunit/functional/Glpi/Form/Destination/CommonITILField/SLATTOFieldTest.php
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
Labels: Forms

#20244 Cleaner error handling on console when DB is unavailable
  src/DBmysql.php
  src/Glpi/Console/AbstractCommand.php
  src/Glpi/Console/Application.php
Labels: enhancement

#20257 Do not use `CommonDBTM` hooks on GLPI boot
  src/Glpi/Event.php
  src/Plugin.php
Labels: enhancement

#20254 Fix(NetworkPort): disconnect related socket id needed
  phpunit/functional/Glpi/SocketTest.php
  src/NetworkPortInstantiation.php
Labels: bug

#17249 Fix ticket survey central list widget
  phpunit/functional/TicketTest.php
  src/Entity.php
  src/Ticket.php
  templates/pages/admin/entity/survey_config.html.twig
Labels: bug

#20176 Fix multiple issues with DC room rack view
  ajax/rack.php
  css/includes/components/_mini-tabs.scss
  src/Rack.php
  templates/pages/management/dcroom_racks.html.twig
  tests/cypress/e2e/Tools/dcroom.cy.js
Labels: help wanted

#20298 Fix sim pinpuk permission showing useless rights
  src/Profile.php
Labels: bug

#20279 Resume plugins execution after a bugfix update
  src/Update.php
Labels: enhancement

#20250 feat(forms-destination): Add support for specific approval templates in validation field
  phpunit/functional/Glpi/Form/Destination/CommonITILField/ValidationFieldTest.php
  src/Glpi/Form/Destination/CommonITILField/ValidationField.php
  src/Glpi/Form/Destination/CommonITILField/ValidationFieldConfig.php
  src/Glpi/Form/Destination/CommonITILField/ValidationFieldStrategy.php
  templates/pages/admin/form/itil_config_fields/validation.html.twig
  tests/cypress/e2e/form/destination_config_fields/validation.cy.js
Labels: Forms

#20262 Fix(Anonymisation): clarify ambiguous option label
  src/Entity.php
Labels: enhancement, ui

#20287 Fix (ImpactAnalysis) - Resolve node overlap when adding elements to shared groups
  js/impact.js
Labels: bug

#20306 Nested transactions
  phpunit/DbTestCase.php
  phpunit/functional/DBTest.php
  phpunit/functional/Glpi/Migration/AbstractPluginMigrationTest.php
  src/DBmysql.php
  src/Glpi/Form/AnswersHandler/AnswersHandler.php
  src/Glpi/Form/Export/Serializer/FormSerializer.php
  src/Glpi/Form/Form.php
  src/Glpi/Inventory/Inventory.php
  src/Glpi/Migration/AbstractPluginMigration.php
  src/Group_User.php
  src/SavedSearch.php
  src/Ticket.php
  src/Transfer.php
  tests/functional/Glpi/System/Status/StatusChecker.php
Labels: enhancement

#18579 Fix Anonymization For Requesters / Observers
  src/CommonITILObject.php
Labels: bug

#20320 feat(forms-destination): Add support for reusable strategies
  .phpstan-baseline.php
  css/includes/components/form/_form-destination.scss
  install/migrations/update_10.0.x_to_11.0.0/form.php
  js/modules/Forms/FieldDestinationMultipleConfig.js
  phpunit/functional/Glpi/Form/Destination/CommonITILField/ValidationFieldTest.php
  phpunit/functional/Glpi/Form/Export/FormSerializerDestinationTest.php
  phpunit/functional/Glpi/Form/Migration/TargetsMigrationTest.php
  src/CommonITILObject.php
  src/Glpi/Form/Destination/AbstractConfigField.php
  src/Glpi/Form/Destination/CommonITILField/ValidationField.php
  src/Glpi/Form/Destination/CommonITILField/ValidationFieldConfig.php
  src/Glpi/Form/Destination/CommonITILField/ValidationFieldStrategy.php
  src/Glpi/Form/Destination/CommonITILField/ValidationFieldStrategyConfig.php
  templates/pages/admin/form/form_destination_commonitil_config.html.twig
  templates/pages/admin/form/itil_config_fields/validation.html.twig
  tests/cypress/e2e/form/destination_config_fields/validation.cy.js
Labels: Forms

#20388 fix(forms): Fixed incorrect display for the render layout selection option
  templates/pages/admin/form/form_editor.html.twig
Labels: bug, Forms

#20386 Fix some HTML/JS escaping
  CHANGELOG.md
  ajax/actorinformation.php
  ajax/comments.php
  ajax/dashboard.php
  ajax/dropdownAllItems.php
  ajax/dropdownItilActors.php
  js/modules/Dashboard/Dashboard.js
  js/modules/Forms/FieldDestinationAssociatedItem.js
  phpunit/functional/autoload/MiscFunctionsTest.php
  src/Ajax.php
  src/CommonGLPI.php
  src/Dropdown.php
  src/autoload/misc-functions.php
Labels: need_doc_improvement, security

#20399 Fix DateTime exceptions on ticket stats tab
  src/Html.php
  src/Ticket.php
Labels: bug

#20403 feat(forms): Add linked assistance objects field
  .phpstan-baseline.php
  css/includes/components/form/_form-destination.scss
  js/modules/Forms/FieldDestinationMultipleConfig.js
  phpunit/abstracts/AbstractDestinationFieldTest.php
  phpunit/functional/Glpi/Form/Destination/CommonITILField/LinkedITILObjectsFieldTest.php
  phpunit/functional/Glpi/Form/Migration/TargetsMigrationTest.php
  src/CommonITILObject_CommonITILObject.php
  src/Glpi/Form/AnswersHandler/AnswersHandler.php
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
  src/Glpi/Form/Destination/AbstractConfigField.php
  src/Glpi/Form/Destination/CommonITILField/AssociatedItemsField.php
  src/Glpi/Form/Destination/CommonITILField/ContentField.php
  src/Glpi/Form/Destination/CommonITILField/EntityField.php
  src/Glpi/Form/Destination/CommonITILField/ITILActorField.php
  src/Glpi/Form/Destination/CommonITILField/ITILCategoryField.php
  src/Glpi/Form/Destination/CommonITILField/ITILFollowupField.php
  src/Glpi/Form/Destination/CommonITILField/ITILTaskField.php
  src/Glpi/Form/Destination/CommonITILField/LinkedITILObjectsField.php
  src/Glpi/Form/Destination/CommonITILField/LinkedITILObjectsFieldConfig.php
  src/Glpi/Form/Destination/CommonITILField/LinkedITILObjectsFieldStrategy.php
  src/Glpi/Form/Destination/CommonITILField/LinkedITILObjectsFieldStrategyConfig.php
  src/Glpi/Form/Destination/CommonITILField/LocationField.php
  src/Glpi/Form/Destination/CommonITILField/RequestSourceField.php
  src/Glpi/Form/Destination/CommonITILField/RequestTypeField.php
  src/Glpi/Form/Destination/CommonITILField/SLMField.php
  src/Glpi/Form/Destination/CommonITILField/StatusField.php
  src/Glpi/Form/Destination/CommonITILField/TemplateField.php
  src/Glpi/Form/Destination/CommonITILField/TitleField.php
  src/Glpi/Form/Destination/CommonITILField/UrgencyField.php
  src/Glpi/Form/Destination/CommonITILField/ValidationField.php
  src/Glpi/Form/Destination/DestinationFieldInterface.php
  src/Glpi/Form/Destination/FormDestinationInterface.php
  src/Glpi/Form/Migration/FormMigration.php
  templates/pages/admin/form/form_destination_commonitil_config.html.twig
  templates/pages/admin/form/itil_config_fields/associated_items.html.twig
  templates/pages/admin/form/itil_config_fields/linked_itilobjects.html.twig
  tests/cypress/e2e/form/destination_config_fields/linked_itilobjects.cy.js
  tests/fixtures/plugins/tester/src/Form/ComputerDestination.php
Labels: Forms

#20351 fix(rule): specific_groups_id actions not exporting values to XML file
  phpunit/functional/RuleRightCollectionTest.php
  src/RuleCollection.php
Labels: bug

#20458 Remove `nikic/php-parser` from dev requirements
  composer.json
  composer.lock
Labels: dependencies, php

#20383 Fix (Reservations) - Allow reservations in simplified interface with RESERVEANITEM right
  front/reservation.form.php
  phpunit/functional/ReservationTest.php
  src/Reservation.php
Labels: bug

#20427 Fix (API) - Handle array input types in Entity PUT/PATCH requests
  phpunit/web/APIRestTest.php
  src/Api/APIRest.php
Labels: bug
