Repository glpi-project/glpi, pull requests merged in 2025-02, with the labels that each got.

#18857 input to filter capacities
  templates/pages/admin/assetdefinition/capacities.html.twig
Labels: Need unit tests

#18901 Increase maximum alert delay (backport)
  src/Entity.php
Labels: enhancement

#18850 Fix missing TTO date in TTO + progress SO when status is waiting
  src/Search.php
Labels: enhancement

#18928 Fix(contrat): notice date
  templates/pages/management/contract.html.twig
Labels: bug

#18841 feat(forms): Add new strategies for ITILActorField fields
  phpunit/abstracts/AbstractActorFieldTest.php
  phpunit/functional/Glpi/Form/Destination/CommonITILField/AssigneeFieldTest.php
  phpunit/functional/Glpi/Form/Destination/CommonITILField/ObserverFieldTest.php
  phpunit/functional/Glpi/Form/Destination/CommonITILField/RequesterFieldTest.php
  src/Glpi/Form/Destination/CommonITILField/ITILActorField.php
  src/Glpi/Form/Destination/CommonITILField/ITILActorFieldStrategy.php
  templates/pages/admin/form/itil_config_fields/itilactor.html.twig
  tests/cypress/e2e/form/destination_config_fields/actors.cy.js
  tests/cypress/e2e/form/destination_config_fields/assignee.cy.js
  tests/cypress/e2e/form/destination_config_fields/observer.cy.js
  tests/cypress/e2e/form/destination_config_fields/requester.cy.js
Labels: Forms

#18920 Remove extra break on Management Port (Network Ports - Asset)
  src/NetworkPort.php
Labels: enhancement

#18934 Fix ONADD rules based on inventory agent tag
  src/CommonDBTM.php
  src/Inventory/Asset/InventoryAsset.php
Labels: bug

#18936 Remove specific AJAX handling based on manual declarations
  .phpstan-baseline.php
  CHANGELOG.md
  ajax/2fa.php
  ajax/actorinformation.php
  ajax/actors.php
  ajax/agent.php
  ajax/asset/assetdefinition.php
  ajax/asset/customfield.php
  ajax/central.php
  ajax/comments.php
  ajax/common.tabs.php
  ajax/commonitilsatisfaction.php
  ajax/displayMessageAfterRedirect.php
  ajax/dropdownConnectNetworkPort.php
  ajax/dropdownInstallVersion.php
  ajax/dropdownMassiveActionAddActor.php
  ajax/dropdownMassiveActionAddValidator.php
  ajax/dropdownMassiveActionAuthMethods.php
  ajax/dropdownRubDocument.php
  ajax/dropdownSoftwareLicense.php
  ajax/dropdownValidator.php
  ajax/entitytreesons.php
  ajax/fuzzysearch.php
  ajax/genericdate.php
  ajax/getDropdownUsers.php
  ajax/getFileTag.php
  ajax/getUserPicture.php
  ajax/impact.php
  ajax/itilfollowup.php
  ajax/itilvalidation.php
  ajax/kanban.php
  ajax/mailcollector.php
  ajax/notificationmailingsettings.php
  ajax/planningend.php
  ajax/projecttask.php
  ajax/rack.php
  ajax/resaperiod.php
  ajax/rule.php
  ajax/search.php
  ajax/solution.php
  ajax/subvisibility.php
  ajax/task.php
  ajax/ticketiteminformation.php
  ajax/uemailUpdate.php
  ajax/unlockobject.php
  ajax/visibility.php
  front/dropdown.common.form.php
  front/reservation.form.php
  inc/includes.php
  phpstan.neon.dist
  src/Glpi/Controller/LegacyFileLoadController.php
  src/Glpi/Http/Listener/LegacyPostRequestActionsListener.php
  src/Glpi/Kernel/Kernel.php
  src/Session.php
Labels: need_doc_improvement

#17248 Notification target contract add tags
  src/NotificationTargetContract.php
Labels: enhancement

#18807 Mail authentication can be set as default (works together with LDAP auth)
  CHANGELOG.md
  install/migrations/update_10.0.x_to_11.0.0/authmail.php
  install/mysql/glpi-empty.sql
  phpunit/LDAP/AuthLdapTest.php
  phpunit/functional/AuthLdapTest.php
  phpunit/functional/AuthMailTest.php
  phpunit/src/Glpi/Auth/HelpersTrait.php
  src/Auth.php
  src/AuthLDAP.php
  src/AuthMail.php
  src/Entity.php
  templates/pages/setup/authentication/mail.html.twig
Labels: enhancement

#18983 fix(forms): invalid `Go home` button on central interface
  templates/pages/form_renderer.html.twig
Labels: Forms

#18993 replace menu_toadd hook by a constant
  src/Glpi/Plugin/Hooks.php
  src/Html.php
Labels: task

#18977 Enhance the progress indicator component
  dependency_injection/services.php
  js/modules/GlpiInstall.js
  js/modules/ProgressBar.js
  js/modules/ProgressIndicator.js
  phpunit/functional/Glpi/Progress/AbstractProgressIndicatorTest.php
  phpunit/functional/Glpi/Progress/ConsoleProgressIndicatorTest.php
  phpunit/functional/Glpi/Progress/StoredProgressIndicatorTest.php
  src/Glpi/Console/Database/InstallCommand.php
  src/Glpi/Controller/InstallController.php
  src/Glpi/Controller/ProgressController.php
  src/Glpi/Progress/AbstractProgressIndicator.php
  src/Glpi/Progress/ConsoleProgressIndicator.php
  src/Glpi/Progress/ProgressMessageType.php
  src/Glpi/Progress/ProgressStorage.php
  src/Glpi/Progress/SessionProgress.php
  src/Glpi/Progress/StoredProgressIndicator.php
  src/Toolbox.php
Labels: enhancement

#18981 Can add emails on user creation
  src/UserEmail.php
Labels: bug

#19001 Apply conditions to sections
  css/includes/components/_utils.scss
  js/modules/Forms/Condition/Engine.js
  js/modules/Forms/RendererController.js
  phpunit/functional/Glpi/Form/ConditionalVisibility/EngineTest.php
  src/Glpi/Controller/Form/ConditionalVisibility/EngineController.php
  src/Glpi/Form/ConditionalVisiblity/Engine.php
  src/Glpi/Form/ConditionalVisiblity/EngineOutput.php
  templates/pages/form_renderer.html.twig
  tests/cypress/e2e/form/editor/conditions.cy.js
Labels: Forms

#18264 Add option to set default state for planned task
  install/empty_data.php
  install/migrations/update_10.0.x_to_11.0.0/configs.php
  install/mysql/glpi-empty.sql
  src/autoload/CFG_GLPI.php
  templates/components/itilobject/timeline/form_task_main_form.html.twig
  templates/pages/setup/general/preferences_setup.html.twig
Labels: enhancement

#19007 Fix mistake in conditions tests
  tests/cypress/e2e/form/editor/conditions.cy.js
Labels: Forms

#18943 Feat(rule mail collector): add criterion for quarantine released
  phpunit/functional/RuleMailCollectorTest.php
  src/RuleMailCollector.php
  src/RuleMailCollectorCollection.php
Labels: enhancement

#18986 Hide answers; show created ticket directly
  .phpstan-baseline.php
  phpunit/functional/Glpi/Form/AnswersHandler/AnswersHandlerTest.php
  phpunit/functional/Glpi/Form/AnswersSetTest.php
  phpunit/functional/Glpi/Form/Destination/CommonITILField/AssociatedItemsFieldTest.php
  phpunit/functional/Glpi/Form/FormTest.php
  phpunit/functional/Glpi/Helpdesk/DefaultDataManagerTest.php
  src/Change_Item.php
  src/Glpi/Form/AnswersHandler/AnswersHandler.php
  src/Glpi/Form/AnswersSet.php
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
  src/Glpi/Form/Destination/AbstractFormDestinationType.php
  src/Glpi/Form/Destination/FormDestination.php
  src/Glpi/Form/Destination/FormDestinationInterface.php
  src/Glpi/Form/Form.php
  src/Glpi/Form/QuestionType/AbstractQuestionType.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeActors.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
  src/Glpi/Form/QuestionType/QuestionTypeFile.php
  src/Glpi/Form/QuestionType/QuestionTypeInterface.php
  src/Glpi/Form/QuestionType/QuestionTypeItem.php
  src/Glpi/Form/QuestionType/QuestionTypeLongText.php
  src/Item_Problem.php
  src/Item_Ticket.php
  templates/pages/admin/form/display_answers.html.twig
  tests/src/Form/Destination/AbstractFormDestinationType.php
Labels: Forms

#18849 Add possibility to disable or restrict users mentions in RichText
  ajax/timeline.php
  install/empty_data.php
  install/migrations/update_10.0.x_to_11.0.0/profiles.php
  install/mysql/glpi-empty.sql
  js/RichText/UserMention.js
  src/CommonITILObject.php
  src/Glpi/RichText/UserMention.php
  src/Profile.php
  src/Ticket.php
  templates/components/form/basic_inputs_macros.html.twig
  templates/components/form/fields_macros.html.twig
  templates/components/itilobject/answer.html.twig
  templates/components/itilobject/timeline/approbation_form.html.twig
  templates/components/itilobject/timeline/form_followup.html.twig
  templates/components/itilobject/timeline/form_solution.html.twig
  templates/components/itilobject/timeline/form_task_main_form.html.twig
  templates/components/itilobject/timeline/form_validation.html.twig
  templates/components/itilobject/timeline/simple_form.html.twig
  templates/components/itilobject/timeline/timeline.html.twig
  tests/cypress/e2e/ITILObject/user_mentions.cy.js
Labels: enhancement

#18992 Mail collector server and type should be required fields
  phpunit/functional/TelemetryTest.php
  phpunit/imap/MailCollectorTest.php
  src/MailCollector.php
  src/Toolbox.php
Labels: bug

#19006 fix: Empty IN are not allowed
  phpunit/functional/DbUtilsTest.php
  src/DbUtils.php
  src/Dropdown.php
  src/Profile.php
Labels: bug

#19030 Improve allow list search link
  src/Glpi/Form/AccessControl/ControlType/AllowListDropdown.php
Labels: Forms

#19032 Fix contact vcard button
  src/Contact.php
Labels: bug

#19023 Forms: fix richtext editor margins
  css/includes/components/_content-editable-inputs.scss
Labels: Forms

#18873 Custom Field option profile restrictions
  ajax/asset/assetdefinition.php
  js/src/vue/CustomObject/FieldPreview/FieldDisplay.vue
  src/Glpi/Asset/Asset.php
  src/Glpi/Asset/AssetDefinition.php
  src/Glpi/Asset/CustomFieldOption/ProfileRestrictOption.php
  src/Glpi/Asset/CustomFieldType/AbstractType.php
  src/Glpi/Asset/CustomFieldType/TypeInterface.php
  tests/cypress/e2e/Asset/custom_fields.cy.js
Labels: enhancement

#19050 fix(forms): Fixed behavior of Date and Time question type options
  src/Glpi/Form/QuestionType/QuestionTypeDateTime.php
  tests/cypress/e2e/form/question_types/date_and_time.cy.js
Labels: Forms

#19031 feat(forms): Add pinned status to forms and update sorting logic
  install/migrations/update_10.0.x_to_11.0.0/form.php
  install/mysql/glpi-empty.sql
  phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php
  src/Glpi/Form/Category.php
  src/Glpi/Form/Form.php
  src/Glpi/Form/ServiceCatalog/ServiceCatalogItemInterface.php
  src/Glpi/Form/ServiceCatalog/ServiceCatalogManager.php
  templates/pages/admin/form/service_catalog_tab.html.twig
  tests/src/FormBuilder.php
  tests/src/FormTesterTrait.php
Labels: Forms

#19020 Add rule system to define itemtype before inventory
  .phpstan-baseline.php
  front/ruledefineitemtype.form.php
  front/ruledefineitemtype.php
  phpunit/DbTestCase.php
  phpunit/RuleBuilder.php
  phpunit/functional/RuleDefineItemtypeTest.php
  phpunit/functional/RuleImportAssetTest.php
  src/Glpi/Inventory/Asset/InventoryAsset.php
  src/Glpi/Inventory/Inventory.php
  src/Glpi/Inventory/MainAsset/Itemtype.php
  src/Glpi/Inventory/MainAsset/MainAsset.php
  src/Rule.php
  src/RuleCollection.php
  src/RuleDefineItemtype.php
  src/RuleDefineItemtypeCollection.php
  src/Toolbox.php
  src/autoload/CFG_GLPI.php
  templates/pages/admin/rules/index.html.twig
Labels: enhancement

#19053 PHP 8.4 support
  .github/workflows/ci.yml
  .github/workflows/coverage.yml
  README.md
  composer.json
  composer.lock
  inc/define.php
  index.php
  src/Application/ErrorHandler.php
  src/Console/CommandLoader.php
  tools/patches/atoum-4.1.0...4.2.0.patch
  tools/patches/atoum-atoum-4.1.0...4.2.0.patch
  tools/patches/atoum-atoum-php8.4-compat.patch
  tools/patches/atoum-stubs-php8.4-compat.patch
  tools/patches/firebase-php-jwt-php8.4-compat.patch
  tools/patches/friendsoftwig-twigcs-php8.4-compat.patch
  tools/patches/guzzlehttp-guzzle-restrict-http-methods.patch
  tools/patches/guzzlehttp-promises-php8.4-compat.patch
  tools/patches/laminas-laminas-mail-address-no-length-check.patch
  tools/patches/laminas-laminas-mail-invalid-header-ignore.patch
  tools/patches/laminas-laminas-mail-php8.4-compat.patch
  tools/patches/laminas-laminas-servicemanager-php8.4-compat.patch
  tools/patches/league-csv-php8.4-compat.patch
  tools/patches/michelf-php-markdown-php8-compat.patch
  tools/patches/psr-http-factory-php8.4-compat.patch
  tools/patches/scssphp-scssphp-php8.4-compat.patch
  tools/patches/swaggest-json-diff-php8.4-compat.patch
  tools/patches/wapmorgan-unified-archive-php-8.4-compat.patch
Labels: enhancement

#19021 Forms: add an option to close a ticket on creation
  phpunit/functional/Glpi/Form/Destination/CommonITILField/StatusFieldTest.php
  src/Glpi/Form/Destination/CommonITILField/StatusField.php
  src/Glpi/Form/Destination/FormDestinationTicket.php
Labels: Forms

#19043 Allow helpdesk forms fields to be preset using GET parameters
  js/modules/Forms/EditorController.js
  src/Glpi/Controller/Form/RendererController.php
  src/Glpi/Form/Question.php
  src/Glpi/Form/QuestionType/AbstractQuestionType.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeShortAnswer.php
  src/Glpi/Form/QuestionType/QuestionTypeInterface.php
  src/Glpi/Form/QuestionType/QuestionTypeLongText.php
  src/Glpi/Form/QuestionType/QuestionTypeRequestType.php
  src/Glpi/Form/QuestionType/QuestionTypeUrgency.php
  templates/pages/admin/form/form_question.html.twig
  templates/pages/form_renderer.html.twig
  tests/cypress/e2e/form/form_rendering.cy.js
Labels: Forms

#18998 feat(forms): Add pagination system for service catalog
  js/modules/Forms/ServiceCatalogController.js
  phpunit/functional/Glpi/Form/ServiceCatalog/ServiceCatalogManagerTest.php
  src/Glpi/Controller/Helpdesk/SearchController.php
  src/Glpi/Controller/ServiceCatalog/ItemsController.php
  src/Glpi/Form/Category.php
  src/Glpi/Form/ServiceCatalog/ItemRequest.php
  src/Glpi/Form/ServiceCatalog/ServiceCatalogManager.php
  templates/components/helpdesk_forms/service_catalog_items.html.twig
  templates/components/helpdesk_forms/service_catalog_nested_item.html.twig
  templates/pages/helpdesk/search.html.twig
  templates/pages/self-service/service_catalog.html.twig
  tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
Labels: Forms

#19039 fix(dashboard): groups lost in session
  ajax/dashboard.php
  front/central.php
  src/Dashboard/Grid.php
Labels: bug

#19072 feat: Include asset name in rule engine processing
  phpunit/functional/RuleAssetTest.php
  src/RuleAsset.php
Labels: enhancement
