Repository glpi-project/glpi, pull requests merged in 2025-09, with the labels that each got.

#20644 Adjust display of reservation repitition fields
  templates/components/form/reservation.html.twig
Labels: ui

#20831 Allow form direct access token to be refreshed
  templates/pages/admin/form/access_control/direct_access.html.twig
Labels: forms

#20824 fix(forms): Detect changes made to the `File` question type when rendering the form
  js/fileupload.js
  js/modules/Forms/Condition/Engine.js
  js/modules/Forms/RendererController.js
  tests/cypress/e2e/form/editor/conditions.cy.js
Labels: bug, forms

#20839 Make sure helpdesk scenes stick to the bottom
  css/helpdesk_home.scss
Labels: ui

#20861 fix(forms): Add validation logic to ConditionData to filter invalid conditions
  phpunit/functional/Glpi/Form/Condition/ConditionDataTest.php
  src/Glpi/Form/Condition/ConditionData.php
  src/Glpi/Form/Condition/ConditionableTrait.php
Labels: bug, forms

#20884 Fix `chr(): Providing a value not in-between 0 and 255 is deprecated`
  src/GLPIKey.php
Labels: bug

#20814 Fix 2FA with LDAP users
  src/Auth.php
  src/Glpi/Controller/IndexController.php
  src/Glpi/Controller/Security/MFAController.php
  src/Glpi/Security/TOTPManager.php
  templates/pages/2fa/2fa_backup_codes.html.twig
  templates/pages/2fa/2fa_request.html.twig
  templates/pages/2fa/2fa_status.html.twig
  templates/pages/2fa/macros.html.twig
  tests/cypress/e2e/session.cy.js
Labels: bug

#20891 Fix KB export
  front/report.dynamic.php
Labels: bug

#20826 Fix some escaping issues (10/x)
  ajax/getUserPicture.php
  front/stat.location.php
  front/stat.tracking.php
  phpunit/functional/HtmlTest.php
  phpunit/functional/ToolboxTest.php
  src/Document.php
  src/DocumentType.php
  src/Document_Item.php
  src/DomainRecordType.php
  src/Domain_Item.php
  src/Dropdown.php
  src/Entity.php
  src/FieldUnicity.php
  src/GLPINetwork.php
  src/Glpi/Application/View/Extension/HtmlExtension.php
  src/Glpi/Application/View/TemplateRenderer.php
  src/HTMLTableCell.php
  src/HTMLTableEntity.php
  src/HTMLTableGroup.php
  src/HTMLTableHeader.php
  src/HTMLTableMain.php
  src/HTMLTableRow.php
  src/Html.php
  src/KnowbaseItem.php
  src/Project.php
  src/Stat.php
  templates/components/dropdown/limit.html.twig
  templates/components/form/basic_inputs_macros.html.twig
  templates/components/form/fields_macros.html.twig
  templates/components/printer_graph_buttons.html.twig
Labels: security

#20894 Rename missed "step" occurences to sections
  phpunit/functional/Glpi/Form/Condition/EditorManagerTest.php
  src/Glpi/Form/Section.php
  tests/cypress/e2e/form/editor/conditions.cy.js
Labels: translation

#20901 neutralize a few annoying shadow (notably in healpdesk fields)
  css/includes/_base.scss
  css/includes/components/_select2.scss
Labels: ui

#20905 Fix some escaping issues (11/x)
  src/ITILFollowup.php
  src/ITILSolution.php
  src/ITILTemplate.php
  src/ITILValidationTemplate.php
  src/Impact.php
  src/Infocom.php
  src/ItemVirtualMachine.php
  src/Item_Devices.php
  src/Item_Disk.php
  src/Item_OperatingSystem.php
  src/Item_Plug.php
  src/Item_Project.php
  src/Item_Rack.php
  src/Item_SoftwareLicense.php
  src/Item_SoftwareVersion.php
  src/KnowbaseItem.php
  src/KnowbaseItem_Revision.php
  src/LevelAgreement.php
  src/LevelAgreementLevel.php
  src/Link.php
  src/Lock.php
Labels: security

#20895 fix(forms): Improve condition validation to check whether the value operator is supported by the actual element
  phpunit/functional/Glpi/Form/Condition/ConditionDataTest.php
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Form/Condition/ConditionData.php
  src/Glpi/Form/Migration/FormMigration.php
Labels: bug, forms

#20907 Fix handling of plugin SCSS files
  composer.json
  phpunit/functional/HtmlTest.php
  src/Glpi/Application/View/Extension/PluginExtension.php
  src/Html.php
  tests/fixtures/plugins/tester/public/css/_mixins.scss
  tests/fixtures/plugins/tester/public/css/styles.scss
  tools/patches/scssphp-scssphp-php-8.5-compat.patch
Labels: bug

#20984 Rename new form comment placeholder
  templates/pages/admin/form/form_comment.html.twig
Labels: forms

#20924 feat(forms): prevent the question type from being updated when it is used by conditions
  js/modules/Forms/EditorController.js
  src/Glpi/Controller/Form/Condition/EditorController.php
  src/Glpi/Form/Comment.php
  src/Glpi/Form/Condition/UsedAsCriteriaInterface.php
  src/Glpi/Form/QuestionType/AbstractQuestionType.php
  src/Glpi/Form/Section.php
  templates/pages/admin/form/form_editor.html.twig
  templates/pages/admin/form/item_has_conditions_for_deletion_modal.html.twig
  templates/pages/admin/form/item_has_conditions_for_new_question_type_modal.html.twig
  templates/pages/admin/form/item_has_conditions_modal_base.html.twig
  tests/cypress/e2e/form/editor/conditions.cy.js
  tests/cypress/e2e/form/form_convert_default_values.cy.js
  tests/cypress/e2e/form/form_preview.cy.js
  tests/cypress/e2e/form/form_translation.cy.js
  tests/cypress/support/commands/form.js
Labels: forms

#20983 Put description above form sections
  css/includes/components/form/_form-renderer.scss
  templates/pages/admin/form/form_question.html.twig
  templates/pages/form_renderer.html.twig
  tests/cypress/e2e/form/editor/conditions.cy.js
  tests/cypress/e2e/form/editor/validations.cy.js
Labels: forms

#21004 Fix "Tickets status by month" fake series order
  src/Glpi/Dashboard/FakeProvider.php
Labels: bug

#21009 Fix escaping of array dropdown matches
  js/common.js
Labels: bug

#21014 Fix save button placement
  templates/pages/admin/profile/base_tab.html.twig
Labels: ui

#21007 Replace `escapeMarkupText()` by `_.escape()`
  js/common.js
  js/modules/ObjectLock.js
  js/src/vue/Debug/Widget/ProfilerTable.vue
  js/src/vue/Debug/Widget/SQLRequests.vue
  js/src/vue/Kanban/Kanban.vue
  js/src/vue/Kanban/SearchInput.js
  templates/components/itilobject/actors/field.html.twig
  tests/js/modules/ObjectLock.test.js
Labels: security

#21016 fix(migration): Use completename as a priority to retrieve dropdown item
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Form/Condition/ConditionHandler/ItemConditionHandler.php
Labels: bug, forms

#20987 Tweak service catalog internal values
  install/empty_data.php
  install/migrations/update_10.0.x_to_11.0.0/form.php
  phpunit/functional/EntityTest.php
  tests/cypress/e2e/form/service_catalog/service_catalog_page.cy.js
  tests/cypress/support/commands.d.ts
Labels: forms

#21031 Fix SMTP Oauth2 callback compat with `samesite=strict` cookies
  src/Glpi/Http/SessionManager.php
Labels: bug

#21025 ajaxdropdownjs fix
  js/common.js
  templates/components/itilobject/validation.html.twig
  tests/cypress/e2e/dropdown.cy.js
Labels: bug

#21039 Prevent missing index in Twig file
  src/Config.php
  src/Glpi/Api/HL/Router.php
  templates/pages/setup/general/api_setup.html.twig
Labels: bug

#21030 Rework link display
  src/Appliance_Item.php
  src/Link.php
  src/NetworkPort.php
  src/ReservationItem.php
  templates/components/form/item_remotemanagement_list.html.twig
  templates/components/form/viewsubitem.html.twig
  templates/components/infocom.html.twig
  templates/components/notepad/form.html.twig
Labels: ui

#20991 use text datatype for webhook urls
  install/migrations/update_10.0.x_to_11.0.0/webhook.php
  install/mysql/glpi-empty.sql
Labels: bug

#21047 Fix API config page
  src/Config.php
  templates/pages/setup/general/api_setup.html.twig
Labels: bug

#21041 Run cypress with docker
  Makefile
  docker-compose.yaml
  tests/cypress/README.md
Labels: task

#21088 Do not catch some specific exceptions during plugins init
  src/Plugin.php
Labels: bug

#21076 Fix question type dropdown item export
  phpunit/functional/Glpi/Form/Export/FormSerializerTest.php
  src/Glpi/Form/Question.php
  src/Glpi/Form/QuestionType/AbstractQuestionType.php
  src/Glpi/Form/QuestionType/QuestionTypeInterface.php
  src/Glpi/Form/QuestionType/QuestionTypeItemDropdown.php
Labels: bug, forms

#21075 Do not submit hidden answers
  src/Glpi/Controller/Form/SubmitAnswerController.php
  src/Glpi/Form/AnswersHandler/AnswersHandler.php
  src/Glpi/Form/AnswersSet.php
  src/Glpi/Form/Destination/AbstractCommonITILFormDestination.php
  src/Glpi/Form/Destination/AbstractConfigField.php
  src/Glpi/Form/Destination/CommonITILField/ContentField.php
  src/Glpi/Form/Destination/DestinationFieldInterface.php
  tests/cypress/e2e/form/form_rendering.cy.js
  tests/cypress/support/commands/form.d.ts
  tests/cypress/support/commands/form.js
  tests/fixtures/forms/form-with-a-hidden-question-2025-09-19.json
Labels: enhancement

#21121 Fix SQL condition error
  templates/pages/admin/profile/assistance.html.twig
Labels: bug

#21126 Update some PHP dependencies and fix versions requirements
  composer.json
  composer.lock
Labels: dependencies, php

#21092 fix(core): Mandatory fields not enforced
  src/Html.php
Labels: bug

#21138 Preserve showmassiveactions on search refresh
  templates/components/search/display_data.html.twig
Labels: bug

#21176 Migrate forms as single page render layout
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Form/Migration/FormMigration.php
Labels: forms

#21167 [HLAPI] use readOnly and writeOnly
  phpunit/HLAPITestCase.php
  src/Glpi/Api/HL/Controller/AbstractController.php
  src/Glpi/Api/HL/Controller/AdministrationController.php
  src/Glpi/Api/HL/Controller/AssetController.php
  src/Glpi/Api/HL/Controller/ComponentController.php
  src/Glpi/Api/HL/Controller/CustomAssetController.php
  src/Glpi/Api/HL/Controller/DropdownController.php
  src/Glpi/Api/HL/Controller/ITILController.php
  src/Glpi/Api/HL/Controller/ManagementController.php
  src/Glpi/Api/HL/Controller/ProjectController.php
  src/Glpi/Api/HL/Controller/RuleController.php
  src/Glpi/Api/HL/Controller/SetupController.php
  src/Glpi/Api/HL/Doc/Schema.php
  src/Glpi/Api/HL/OpenAPIGenerator.php
  src/Glpi/Api/HL/ResourceAccessor.php
  src/Glpi/Api/HL/Search.php
  src/Glpi/Api/HL/Search/RecordSet.php
Labels: api

#21171 fix dc breadcrumb for side pdus
  src/Glpi/Features/DCBreadcrumb.php
Labels: bug

#21145 Fix(ticket): missing requestor
  front/tracking.injector.php
Labels: bug

#21183 Fix entity badge rendering
  src/Glpi/Search/Provider/SQLProvider.php
Labels: bug

#21188 Fix PHP 8.5 deprecations
  composer.json
  src/CommonITILObject.php
  src/Dropdown.php
  src/Search.php
  templates/generic_show_form.html.twig
  tools/patches/symfony-string-php8.5-compat.patch
Labels: bug

#21149 fix(forms-migration): Limit the import of form categories when the import is restricted to certain forms
  phpunit/functional/Glpi/Form/Migration/FormMigrationTest.php
  src/Glpi/Form/Migration/FormMigration.php
Labels: bug, forms

#21108 Migrate plugin test to phpunit
  phpunit/functional/CommonDBRelationTest.php
  phpunit/functional/PluginTest.php
  src/DbUtils.php
  src/Plugin.php
  tests/functional/Plugin.php
Labels: task

#21154 Migrate session test to phpunit
  phpunit/functional/SessionTest.php
  phpunit/local_en_GB.mo
  phpunit/local_en_GB.po
Labels: task

#21197 fix custom icons adapting to tile's description
  templates/components/illustration/custom_icon.html.twig
Labels: bug

#21179 Fix form editor performances
  css/includes/components/form/_form-editor-horizontal-layout.scss
  css/includes/components/form/_form-editor.scss
  css/includes/components/form/_item-translations.scss
  js/common.js
  js/modules/Forms/EditorController.js
  js/modules/Forms/QuestionDropdown.js
  js/modules/Forms/QuestionSelectable.js
  src/CommonDBTM.php
  src/Entity.php
  src/Glpi/Form/Comment.php
  src/Glpi/Form/Form.php
  src/Glpi/Form/Question.php
  src/Glpi/Form/QuestionType/AbstractQuestionTypeSelectable.php
  src/Glpi/Form/QuestionType/QuestionTypeDropdown.php
  src/Glpi/Form/QuestionType/QuestionTypeLongText.php
  src/Glpi/Form/Section.php
  src/Glpi/Helpdesk/Tile/ExternalPageTile.php
  src/Glpi/Helpdesk/Tile/GlpiPageTile.php
  src/Glpi/ItemTranslation/Context/TranslationHandler.php
  src/Glpi/Toolbox/UuidStore.php
  src/Html.php
  templates/components/form/basic_inputs_macros.html.twig
  templates/pages/admin/form/form_comment.html.twig
  templates/pages/admin/form/form_editor.html.twig
  templates/pages/admin/form/form_question.html.twig
  templates/pages/admin/form/form_section.html.twig
  templates/pages/admin/form/form_translation.html.twig
  templates/pages/admin/helpdesk_home_translation.html.twig
  tests/cypress/e2e/ITILObject/ticket_form.cy.js
  tests/cypress/e2e/form/editor/editor.cy.js
  tests/cypress/support/commands.js
Labels: performance, forms

#21201 fix sizing of icons on service-catalog
  templates/components/illustration/custom_icon.html.twig
Labels: ui
